# AP Biology image manifest.
# Maps a clean filename (used in Supabase Storage) to the original screenshot
# and a list of topic keywords Claude uses to match images to sections.
#
# Storage path convention: textbooks/images/ap-biology/{filename}
# Public URL base is injected at runtime from SUPABASE_URL.

AP_BIO_IMAGES = [
    {
        "filename": "glucose-carbohydrates.png",
        "original": "Screenshot 2026-05-03 at 8.07.17 PM.png",
        "title": "Glucose and Carbohydrates",
        "keywords": ["glucose", "monosaccharide", "disaccharide", "glycogen", "carbohydrate", "sucrose", "maltose", "lactose", "GLUT4", "polysaccharide"],
        "caption": "Glucose (C₆H₁₂O₆) is the primary monosaccharide fuel for cellular respiration. Monosaccharides join via glycosidic bonds to form disaccharides and polysaccharides such as starch and glycogen.",
    },
    {
        "filename": "plant-cell-wall-structure.png",
        "original": "Screenshot 2026-05-03 at 8.10.43 PM.png",
        "title": "Plant Cell Wall Structure",
        "keywords": ["cell wall", "cellulose", "microfibrils", "middle lamella", "pectin", "cellulose synthase", "plant cell"],
        "caption": "Plant cell walls are built from cellulose microfibrils embedded in a pectin-rich matrix. The primary wall allows cell expansion during growth; the secondary wall adds structural rigidity after maturation.",
    },
    {
        "filename": "phospholipid-chemical-structure.png",
        "original": "Screenshot 2026-05-03 at 8.11.47 PM.png",
        "title": "Phospholipid Chemical Structure",
        "keywords": ["phospholipid", "polar head", "nonpolar tail", "fatty acid", "lipid", "amphipathic"],
        "caption": "A phospholipid has a polar phosphate head and two nonpolar fatty acid tails, making it amphipathic. This dual nature drives spontaneous bilayer formation in aqueous environments.",
    },
    {
        "filename": "phospholipid-bilayer-membrane.png",
        "original": "Screenshot 2026-05-03 at 8.12.20 PM.png",
        "title": "Phospholipid Bilayer Membrane",
        "keywords": ["phospholipid bilayer", "cell membrane", "glycolipid", "glycoprotein", "cholesterol", "integral protein", "peripheral protein", "fluid mosaic model"],
        "caption": "The fluid mosaic model describes the cell membrane as a dynamic phospholipid bilayer studded with proteins and cholesterol. Integral proteins span the bilayer; peripheral proteins associate with its surface.",
    },
    {
        "filename": "protein-structure-levels.png",
        "original": "Screenshot 2026-05-03 at 8.13.58 PM.png",
        "title": "Protein Structure: Primary to Quaternary",
        "keywords": ["protein structure", "primary structure", "secondary structure", "tertiary structure", "quaternary structure", "alpha helix", "beta-pleated sheet", "polypeptide chain", "disulfide bond"],
        "caption": "Primary structure is the amino acid sequence; secondary structure includes alpha helices and beta-pleated sheets. Tertiary folding produces the functional 3D shape, and quaternary structure assembles multiple polypeptide subunits.",
    },
    {
        "filename": "enzyme-noncompetitive-inhibition.png",
        "original": "Screenshot 2026-05-03 at 8.14.39 PM.png",
        "title": "Non-competitive Enzyme Inhibition",
        "keywords": ["enzyme", "enzyme inhibition", "non-competitive inhibition", "allosteric site", "enzyme-substrate complex", "inhibitor", "enzyme kinetics", "active site", "activation energy", "substrate", "catalyst"],
        "caption": "A noncompetitive inhibitor binds the allosteric site rather than the active site, changing the enzyme’s shape and reducing catalytic activity. Unlike competitive inhibition, increasing substrate concentration cannot overcome this effect.",
    },
    {
        "filename": "dna-base-sequencing.png",
        "original": "Screenshot 2026-05-03 at 8.15.17 PM.png",
        "title": "DNA Base Sequencing",
        "keywords": ["DNA sequencing", "base pairs", "nucleotides", "DNA sequence"],
        "caption": "DNA sequencing reads the order of nucleotide bases (A, T, G, C) along a strand. This sequence encodes genetic information and is used to identify mutations, ancestry, and gene function.",
    },
    {
        "filename": "dna-molecular-structure.png",
        "original": "Screenshot 2026-05-03 at 8.15.47 PM.png",
        "title": "Molecular Structure of DNA",
        "keywords": ["DNA structure", "double helix", "sugar-phosphate backbone", "base pairs", "adenine", "thymine", "guanine", "cytosine", "Watson-Crick"],
        "caption": "DNA consists of two antiparallel strands wound into a double helix, held together by hydrogen bonds between complementary base pairs (A–T and G–C). The sugar-phosphate backbone forms the outer rails of the ladder.",
    },
    {
        "filename": "dna-nucleotide-detail.png",
        "original": "Screenshot 2026-05-03 at 8.15.53 PM.png",
        "title": "DNA Nucleotide and Base Pairing",
        "keywords": ["nucleotide", "deoxyribose", "nitrogenous base", "purine", "pyrimidine", "adenine", "guanine", "thymine", "cytosine", "complementary base pairing"],
        "caption": "Each DNA nucleotide contains a phosphate group, a deoxyribose sugar, and one nitrogenous base. Purines (adenine, guanine) pair with pyrimidines (thymine, cytosine) via two or three hydrogen bonds.",
    },
    {
        "filename": "atp-overview.png",
        "original": "Screenshot 2026-05-03 at 8.16.37 PM.png",
        "title": "ATP Structure and Function Overview",
        "keywords": ["ATP", "ADP", "ATP hydrolysis", "phosphorylation", "ATP synthase", "ATP-ADP cycle", "energy currency"],
        "caption": "ATP (adenosine triphosphate) stores chemical energy in its high-energy phosphoanhydride bonds. Hydrolysis of the terminal phosphate releases approximately 7.3 kcal/mol, powering active transport, muscle contraction, and biosynthesis.",
    },
    {
        "filename": "chromosome-nucleobases.png",
        "original": "Screenshot 2026-05-03 at 8.16.59 PM.png",
        "title": "Chromosome and Nucleobases",
        "keywords": ["chromosome", "nucleobase", "purine", "pyrimidine", "adenine", "guanine", "thymine", "cytosine", "complementary base pairing", "chromatin"],
        "caption": "Chromosomes are highly condensed chromatin structures containing DNA wrapped around histone proteins. The four nitrogenous bases—adenine, guanine, thymine, and cytosine—encode genetic information through their sequence.",
    },
    {
        "filename": "allosteric-enzyme-kinetics.png",
        "original": "Screenshot 2026-05-03 at 8.18.15 PM.png",
        "title": "Allosteric Enzyme Kinetics",
        "keywords": ["allosteric", "enzyme", "enzyme kinetics", "R state", "T state", "sigmoidal curve", "activator", "inhibitor", "cooperativity", "active site", "activation energy", "substrate"],
        "caption": "Allosteric enzymes switch between an active R state and an inactive T state in response to activators or inhibitors binding non-active-site regions. This produces sigmoidal kinetics rather than the hyperbolic curve seen in Michaelis-Menten enzymes.",
    },
    {
        "filename": "cell-membrane-3d.png",
        "original": "Screenshot 2026-05-03 at 8.18.52 PM.png",
        "title": "Cell Membrane (3D View)",
        "keywords": ["cell membrane", "phospholipid bilayer", "membrane protein", "glycoprotein", "cholesterol", "integral protein", "fluid mosaic"],
        "caption": "The cell membrane is a selectively permeable phospholipid bilayer embedded with cholesterol, glycoproteins, and integral proteins. It regulates the movement of ions, nutrients, and signaling molecules across the cell boundary.",
    },
    {
        "filename": "sodium-potassium-pump.png",
        "original": "Screenshot 2026-05-03 at 8.19.51 PM.png",
        "title": "Na+/K+ Pump (Sodium-Potassium Pump)",
        "keywords": ["sodium-potassium pump", "Na+/K+ ATPase", "active transport", "ATP", "phosphorylation", "sodium", "potassium", "membrane pump"],
        "caption": "The Na⁺/K⁺-ATPase pumps 3 sodium ions out and 2 potassium ions in per ATP hydrolyzed, creating an electrochemical gradient. This gradient powers secondary active transport and maintains resting membrane potential in neurons.",
    },
    {
        "filename": "secondary-active-transporters.png",
        "original": "Screenshot 2026-05-03 at 8.20.14 PM.png",
        "title": "Secondary Active Transporters",
        "keywords": ["secondary active transport", "symporter", "antiporter", "co-transporter", "Na+/K+/Cl-", "dopamine transporter", "GABA transporter"],
        "caption": "Secondary active transporters harness the Na⁺ gradient established by the Na⁺/K⁺ pump to move other solutes against their concentration gradient. Symporters move both solutes in the same direction; antiporters move them in opposite directions.",
    },
    {
        "filename": "intracellular-transport.png",
        "original": "Screenshot 2026-05-03 at 8.20.50 PM.png",
        "title": "Intracellular Transport",
        "keywords": ["intracellular transport", "Golgi apparatus", "lysosome", "endosome", "endoplasmic reticulum", "secretory vesicle", "exocytosis", "endocytosis", "vesicle trafficking"],
        "caption": "Vesicles bud from the ER, mature through the Golgi apparatus, and are directed to the lysosome, plasma membrane, or extracellular space. This vesicular trafficking pathway is essential for protein sorting and secretion.",
    },
    {
        "filename": "extracellular-vesicles-exosomes.png",
        "original": "Screenshot 2026-05-03 at 8.21.49 PM.png",
        "title": "Extracellular Vesicles and Exosomes",
        "keywords": ["exosome", "microvesicle", "extracellular vesicle", "exocytosis", "endocytosis", "multivesicular endosome"],
        "caption": "Exosomes form when multivesicular endosomes fuse with the plasma membrane and release their internal vesicles into the extracellular space. They carry proteins, lipids, and nucleic acids between cells as a form of intercellular communication.",
    },
    {
        "filename": "eukaryotic-cells-animal-plant.png",
        "original": "Screenshot 2026-05-03 at 8.22.54 PM.png",
        "title": "Eukaryotic Cells: Animal vs Plant",
        "keywords": ["eukaryotic cell", "animal cell", "plant cell", "organelle", "mitochondria", "nucleus", "chloroplast", "endoplasmic reticulum", "Golgi apparatus", "ribosome", "vacuole", "cell wall", "peroxisome", "lysosome"],
        "caption": "Animal and plant cells both contain a nucleus, mitochondria, ER, and Golgi apparatus. Plant cells additionally have a cell wall, chloroplasts, and a large central vacuole; animal cells have lysosomes and centrioles.",
    },
    {
        "filename": "bacterial-cell-structure.png",
        "original": "Screenshot 2026-05-03 at 8.23.27 PM.png",
        "title": "Bacterial Cell Structure",
        "keywords": ["prokaryote", "bacteria", "bacterial cell", "capsule", "cell wall", "plasma membrane", "nucleoid", "flagellum", "pilus", "plasmid", "ribosome"],
        "caption": "Prokaryotic cells lack a membrane-bound nucleus; genetic material resides in the nucleoid region. Bacteria may possess a capsule, flagella, pili, and plasmids in addition to their cell wall and plasma membrane.",
    },
    {
        "filename": "mitochondria-structure.png",
        "original": "Screenshot 2026-05-03 at 8.23.59 PM.png",
        "title": "Mitochondria Structure",
        "keywords": ["mitochondria", "outer membrane", "inner membrane", "cristae", "matrix", "intermembrane space"],
        "caption": "The inner mitochondrial membrane folds into cristae, dramatically increasing surface area for ATP synthase complexes. The matrix contains Krebs cycle enzymes; the intermembrane space stores the proton gradient that drives oxidative phosphorylation.",
    },
    {
        "filename": "vesicular-traffic-golgi-er.png",
        "original": "Screenshot 2026-05-03 at 8.24.44 PM.png",
        "title": "Vesicular Traffic: Golgi and ER",
        "keywords": ["vesicular traffic", "Golgi apparatus", "endoplasmic reticulum", "secretion", "endocytosis", "retrograde transport", "cis-Golgi", "trans-Golgi", "lysosome sorting"],
        "caption": "Proteins synthesized in the rough ER are packaged into COPII vesicles and transported to the cis-Golgi for modification and sorting. The Golgi acts as the cell’s dispatch center, directing cargo to lysosomes, the plasma membrane, or secretion.",
    },
    {
        "filename": "chloroplast-structure.png",
        "original": "Screenshot 2026-05-03 at 8.25.52 PM.png",
        "title": "Chloroplast Structure",
        "keywords": ["chloroplast", "stroma", "thylakoid", "granum", "stroma lamellae", "lumen", "photosynthesis", "inner membrane", "outer membrane"],
        "caption": "Chloroplasts have outer and inner membranes enclosing the stroma, which contains stacked thylakoid discs called grana. Light-dependent reactions occur in the thylakoid membranes; the Calvin cycle (light-independent reactions) runs in the stroma.",
    },
    {
        "filename": "cytoskeleton.png",
        "original": "Screenshot 2026-05-03 at 8.27.06 PM.png",
        "title": "Cytoskeleton",
        "keywords": ["cytoskeleton", "actin filament", "intermediate filament", "microtubule", "cell structure", "cytoplasm"],
        "caption": "The cytoskeleton consists of microfilaments (actin), intermediate filaments, and microtubules. These structural fibers maintain cell shape, enable cell movement, and serve as tracks for intracellular vesicle transport.",
    },
    {
        "filename": "motor-proteins-kinesin-dynein.png",
        "original": "Screenshot 2026-05-03 at 8.27.43 PM.png",
        "title": "Motor Proteins: Kinesin and Dynein",
        "keywords": ["kinesin", "dynein", "motor protein", "microtubule", "axonal transport", "anterograde transport", "retrograde transport", "neuron"],
        "caption": "Kinesin moves cargo toward the microtubule plus end (anterograde), while dynein moves toward the minus end (retrograde). Both motor proteins use ATP hydrolysis to transport organelles and vesicles along cytoskeletal tracks.",
    },
    {
        "filename": "gpcr-effector-pathways.png",
        "original": "Screenshot 2026-05-03 at 8.28.48 PM.png",
        "title": "GPCR Effector Pathways",
        "keywords": ["GPCR", "G-protein", "adenylate cyclase", "cAMP", "phospholipase C", "DAG", "IP3", "protein kinase A", "protein kinase C", "signal transduction", "second messenger"],
        "caption": "G protein-coupled receptors activate either adenylate cyclase (producing cAMP) or phospholipase C (producing DAG and IP3), depending on the G protein subtype. These second messengers amplify the signal through downstream kinase cascades.",
    },
    {
        "filename": "cell-junctions.png",
        "original": "Screenshot 2026-05-03 at 8.29.56 PM.png",
        "title": "Cell Junctions: Gap, Adherens, Tight",
        "keywords": ["cell junction", "gap junction", "adherens junction", "tight junction", "connexin", "E-cadherin", "occludin", "claudin", "intercellular communication"],
        "caption": "Tight junctions seal adjacent epithelial cells to prevent paracellular leakage. Gap junctions allow direct cytoplasmic communication via connexin channels; adherens junctions link actin cytoskeletons using E-cadherin.",
    },
    {
        "filename": "atp-adp-cycle.png",
        "original": "Screenshot 2026-05-03 at 8.31.40 PM.png",
        "title": "ATP-ADP Cycle",
        "keywords": ["ATP", "ADP", "ATP-ADP cycle", "phosphorylation", "hydrolysis", "energy", "adenine", "triphosphate", "diphosphate"],
        "caption": "The ATP-ADP cycle is the cell’s energy currency exchange. Energy from catabolism is stored by adding a phosphate to ADP to form ATP; that energy is released when ATP is hydrolyzed back to ADP + inorganic phosphate.",
    },
    {
        "filename": "tca-cycle-overview.png",
        "original": "Screenshot 2026-05-03 at 8.33.06 PM.png",
        "title": "TCA Cycle Overview",
        "keywords": ["TCA cycle", "Krebs cycle", "citric acid cycle", "pyruvate", "acetyl-CoA", "oxaloacetate", "citrate", "mitochondria"],
        "caption": "The TCA (Krebs) cycle oxidizes acetyl-CoA to CO₂, producing 3 NADH, 1 FADH₂, and 1 GTP per turn. These electron carriers feed the electron transport chain, where most of the cell’s ATP is synthesized.",
    },
    {
        "filename": "lactic-acid-fermentation.png",
        "original": "Screenshot 2026-05-03 at 8.33.31 PM.png",
        "title": "Lactic Acid Fermentation",
        "keywords": ["lactic acid fermentation", "anaerobic", "pyruvate", "lactate", "NADH", "NAD+", "fermentation"],
        "caption": "Lactic acid fermentation regenerates NAD⁺ by reducing pyruvate to lactate, allowing glycolysis to continue without oxygen. This occurs in muscle cells during intense exercise when oxygen delivery is insufficient.",
    },
    {
        "filename": "glycolysis-enzymes.png",
        "original": "Screenshot 2026-05-03 at 8.34.09 PM.png",
        "title": "Glycolysis and Glycolytic Enzymes",
        "keywords": ["glycolysis", "glycolytic enzymes", "hexokinase", "phosphofructokinase", "pyruvate kinase", "glucose", "pyruvate", "ATP", "NADH", "10 steps"],
        "caption": "Glycolysis converts one glucose molecule into two pyruvate molecules through 10 enzyme-catalyzed steps. The pathway requires an initial investment of 2 ATP and yields 4 ATP and 2 NADH, for a net gain of 2 ATP.",
    },
    {
        "filename": "glycolysis-simplified.png",
        "original": "Screenshot 2026-05-03 at 8.34.44 PM.png",
        "title": "Glycolysis (Simplified)",
        "keywords": ["glycolysis", "glucose", "fructose-6-phosphate", "pyruvate", "net ATP yield", "NADH"],
        "caption": "The simplified glycolysis pathway highlights two phases: an energy-investment phase (2 ATP consumed) and an energy-payoff phase (4 ATP produced). The net yield is 2 ATP and 2 NADH per glucose molecule.",
    },
    {
        "filename": "cellular-respiration-overview.png",
        "original": "Screenshot 2026-05-03 at 8.35.01 PM.png",
        "title": "Cellular Respiration Overview",
        "keywords": ["cellular respiration", "aerobic respiration", "anaerobic respiration", "glycolysis", "TCA cycle", "electron transport", "ATP yield", "fermentation", "mitochondria", "glucose oxidation"],
        "caption": "Aerobic cellular respiration oxidizes glucose through glycolysis, the TCA cycle, and oxidative phosphorylation to yield approximately 30–32 ATP per glucose molecule. CO₂ and water are released as byproducts.",
    },
    {
        "filename": "electron-transport-chain-simple.png",
        "original": "Screenshot 2026-05-03 at 8.35.38 PM.png",
        "title": "Electron Transport Chain (Simple)",
        "keywords": ["electron transport chain", "ETC", "ATP synthase", "mitochondria", "oxidative phosphorylation"],
        "caption": "The electron transport chain transfers electrons from NADH and FADH₂ through membrane protein complexes to oxygen, pumping protons across the inner mitochondrial membrane. The resulting proton gradient drives ATP synthase.",
    },
    {
        "filename": "electron-transport-chain-detail.png",
        "original": "Screenshot 2026-05-03 at 8.36.18 PM.png",
        "title": "Electron Transport Chain (Detailed)",
        "keywords": ["electron transport chain", "Complex I", "Complex II", "Complex III", "Complex IV", "NADH", "FADH2", "coenzyme Q", "cytochrome c", "ATP synthase", "proton gradient", "oxidative phosphorylation"],
        "caption": "Complexes I–IV transfer electrons in sequential redox reactions, using released energy to pump H⁺ into the intermembrane space. Complex IV reduces O₂ to water; the resulting proton gradient powers ATP synthase (Complex V).",
    },
    {
        "filename": "nad-nadh-redox-reaction.png",
        "original": "Screenshot 2026-05-03 at 8.36.46 PM.png",
        "title": "NAD+ to NADH Redox Reaction",
        "keywords": ["NAD+", "NADH", "redox", "reduction", "oxidation", "electron carrier", "nicotinamide"],
        "caption": "NAD⁺ accepts two electrons and one proton during substrate oxidation, becoming NADH. NADH then donates its electrons to Complex I of the electron transport chain, releasing energy to pump protons across the mitochondrial membrane.",
    },
    {
        "filename": "alcohol-fermentation.png",
        "original": "Screenshot 2026-05-03 at 8.37.39 PM.png",
        "title": "Alcohol Fermentation",
        "keywords": ["alcohol fermentation", "ethanol fermentation", "anaerobic", "pyruvate", "acetaldehyde", "ethanol", "NADH", "yeast"],
        "caption": "Alcohol fermentation in yeast converts pyruvate to acetaldehyde and then to ethanol, regenerating NAD⁺ so glycolysis can continue without oxygen. This anaerobic pathway cannot produce ATP beyond the glycolytic yield.",
    },
    {
        "filename": "light-reactions-z-scheme.png",
        "original": "Screenshot 2026-05-03 at 8.38.15 PM.png",
        "title": "Light Reactions / Z-Scheme",
        "keywords": ["light reactions", "Z-scheme", "photosystem I", "photosystem II", "PSI", "PSII", "thylakoid membrane", "NADPH", "ATP synthase", "water splitting", "oxygen evolution", "plastoquinone", "cytochrome b6f", "plastocyanin"],
        "caption": "The Z-scheme shows how light energizes electrons in Photosystem II and Photosystem I to ultimately reduce NADP⁺ to NADPH. Water is split at PSII to replace lost electrons, releasing O₂ as a byproduct.",
    },
    {
        "filename": "photosynthesis-oxygen-exchange.png",
        "original": "Screenshot 2026-05-03 at 8.39.15 PM.png",
        "title": "Photosynthesis Oxygen Exchange (Chloroplast/Mitochondria)",
        "keywords": ["photosynthesis", "Rubisco", "PCR cycle", "photorespiration", "chloroplast", "mitochondria", "peroxisome", "oxygen production", "NADPH"],
        "caption": "Rubisco catalyzes carbon fixation but can also bind O₂, triggering photorespiration that wastes energy. C4 and CAM plants use CO₂ concentration mechanisms to suppress photorespiration under hot, dry conditions.",
    },
    {
        "filename": "photosynthometer.png",
        "original": "Screenshot 2026-05-03 at 8.39.37 PM.png",
        "title": "Photosynthesis Measurement (Photosynthometer)",
        "keywords": ["photosynthesis measurement", "Elodea", "photosynthometer", "oxygen collection", "capillary tube", "water bath", "light intensity"],
        "caption": "A photosynthometer measures the rate of photosynthesis by collecting oxygen gas produced by aquatic plants such as Elodea. Changing light intensity, temperature, or CO₂ concentration alters the measured rate.",
    },
    {
        "filename": "c3-c4-cam-plants.png",
        "original": "Screenshot 2026-05-03 at 8.40.09 PM.png",
        "title": "C3, C4, and CAM Plants",
        "keywords": ["C3 plant", "C4 plant", "CAM plant", "Calvin cycle", "mesophyll", "bundle sheath", "CO2 fixation", "photorespiration", "RuBisCO"],
        "caption": "C3 plants fix CO₂ directly via Rubisco; C4 plants preconcentrate CO₂ in bundle sheath cells to minimize photorespiration; CAM plants open stomata only at night. Each strategy is an adaptation to different climatic conditions.",
    },
    {
        "filename": "calvin-cycle.png",
        "original": "Screenshot 2026-05-03 at 8.40.27 PM.png",
        "title": "Calvin Cycle",
        "keywords": ["Calvin cycle", "dark reactions", "RuBisCO", "carbon fixation", "3-phosphoglycerate", "3-PGA", "G3P", "glyceraldehyde 3-phosphate", "RuBP", "ribulose bisphosphate", "ATP", "NADPH", "carbon dioxide fixation"],
        "caption": "The Calvin cycle uses ATP and NADPH from the light reactions to fix CO₂ into G3P, a three-carbon precursor for glucose synthesis. Three turns of the cycle are required to produce one net G3P molecule.",
    },
    {
        "filename": "neurotransmitter-receptors.png",
        "original": "Screenshot 2026-05-03 at 8.41.58 PM.png",
        "title": "Neurotransmitter Receptors",
        "keywords": ["neurotransmitter receptor", "ligand-gated ion channel", "GPCR", "G-protein-coupled receptor", "ionotropic", "metabotropic", "signal transduction"],
        "caption": "Ionotropic receptors open ion channels directly upon ligand binding, producing fast synaptic responses. Metabotropic (GPCR) receptors act through second messengers for slower, longer-lasting effects on the postsynaptic cell.",
    },
    {
        "filename": "types-of-chemical-signaling.png",
        "original": "Screenshot 2026-05-03 at 8.42.24 PM.png",
        "title": "Types of Chemical Signaling",
        "keywords": ["chemical signaling", "synaptic signaling", "paracrine signaling", "endocrine signaling", "autocrine", "signal transduction", "receptor", "effector molecule"],
        "caption": "Chemical signals can act locally (paracrine, autocrine) or systemically (endocrine via the bloodstream) or across synapses. The type of signaling determines the speed, specificity, and duration of the cellular response.",
    },
    {
        "filename": "apoptosis-cell-death.png",
        "original": "Screenshot 2026-05-03 at 8.42.56 PM.png",
        "title": "Apoptotic Cell Death",
        "keywords": ["apoptosis", "programmed cell death", "membrane blebbing", "apoptotic bodies", "caspase", "cell shrinkage"],
        "caption": "Apoptosis is programmed cell death executed by caspase proteases, resulting in cell shrinkage, membrane blebbing, and fragmentation into apoptotic bodies. It removes damaged or unnecessary cells without triggering inflammation.",
    },
    {
        "filename": "mitosis-cell-division.png",
        "original": "Screenshot 2026-05-03 at 8.43.54 PM.png",
        "title": "Mitosis",
        "keywords": ["mitosis", "prophase", "metaphase", "anaphase", "telophase", "interphase", "cytokinesis", "spindle", "cell cycle", "chromosomes", "sister chromatids"],
        "caption": "Mitosis produces two genetically identical daughter cells through four stages: prophase (chromosomes condense), metaphase (align at the plate), anaphase (chromatids separate), and telophase (nuclear envelopes reform). Cytokinesis then divides the cytoplasm.",
    },
    {
        "filename": "meiosis-spermatogenesis.png",
        "original": "Screenshot 2026-05-03 at 8.44.27 PM.png",
        "title": "Meiosis: Spermatogenesis",
        "keywords": ["meiosis", "spermatogenesis", "sperm", "meiosis I", "meiosis II", "prophase I", "metaphase I", "anaphase I", "differentiation", "haploid"],
        "caption": "Meiosis in spermatogenesis produces four haploid sperm cells from one diploid primary spermatocyte. Meiosis I separates homologous chromosomes; meiosis II separates sister chromatids, generating genetic diversity through crossing over.",
    },
    {
        "filename": "meiosis-plant-meiocyte.png",
        "original": "Screenshot 2026-05-03 at 8.44.56 PM.png",
        "title": "Meiosis: Plant Meiocyte",
        "keywords": ["meiosis", "meiocyte", "spores", "plant reproduction", "meiosis I", "meiosis II", "leptotene", "zygotene", "pachytene", "diplotene"],
        "caption": "In plants, meiosis in the meiocyte produces four haploid spores rather than gametes. These spores develop into the gametophyte generation, which subsequently produces the actual eggs and sperm.",
    },
    {
        "filename": "meiosis-oogenesis.png",
        "original": "Screenshot 2026-05-03 at 8.45.22 PM.png",
        "title": "Meiosis: Oogenesis",
        "keywords": ["meiosis", "oogenesis", "oocyte", "polar body", "zygote", "fertilization", "meiosis I", "meiosis II"],
        "caption": "Oogenesis produces one large egg cell and three small polar bodies through unequal cytoplasmic division. The asymmetry concentrates nutrients in the oocyte; polar bodies typically degenerate without being fertilized.",
    },
    {
        "filename": "plant-cell-mitosis.png",
        "original": "Screenshot 2026-05-03 at 8.46.00 PM.png",
        "title": "Plant Cell Mitosis",
        "keywords": ["mitosis", "plant cell division", "preprophase band", "phragmoplast", "cell plate", "spindle fiber", "prophase", "metaphase", "anaphase", "telophase"],
        "caption": "Plant cell mitosis lacks centrioles and forms a phragmoplast and cell plate during cytokinesis rather than a cleavage furrow. The cell plate grows outward from the center and ultimately becomes the new cell wall between daughter cells.",
    },
    {
        "filename": "cell-cycle-cyclins.png",
        "original": "Screenshot 2026-05-03 at 8.47.17 PM.png",
        "title": "Cell Cycle and Cyclins",
        "keywords": ["cell cycle", "cyclin", "CDK", "G1 phase", "S phase", "G2 phase", "M phase", "G0", "checkpoint", "cyclin A", "cyclin B", "cyclin D", "cyclin E"],
        "caption": "Cyclin-CDK complexes drive cell cycle progression at key checkpoints: cyclin D/CDK4 initiates the G1–S transition; cyclin B/CDK1 triggers mitosis. Checkpoint proteins halt the cycle if DNA is damaged or replication is incomplete.",
    },
    {
        "filename": "normal-vs-malignant-cell-division.png",
        "original": "Screenshot 2026-05-03 at 8.48.02 PM.png",
        "title": "Normal vs Malignant Cell Division",
        "keywords": ["cancer", "oncogene", "tumor suppressor gene", "proto-oncogene", "malignant cell division", "uncontrolled cell growth", "cell cycle regulation"],
        "caption": "Cancer results from mutations in proto-oncogenes (which promote growth) and tumor suppressor genes (which restrain it). When these regulatory systems fail, cells divide uncontrollably and may metastasize to distant tissues.",
    },
    {
        "filename": "mendels-pea-traits.png",
        "original": "Screenshot 2026-05-03 at 8.49.29 PM.png",
        "title": "Mendel's Pea Traits",
        "keywords": ["Mendel", "genetics", "dominant", "recessive", "F2 generation", "3:1 ratio", "seed shape", "seed color", "flower color", "pea plant", "Mendelian genetics"],
        "caption": "Mendel’s pea plant experiments revealed dominant and recessive inheritance patterns. The 3:1 phenotypic ratio in F2 offspring demonstrated that alleles segregate independently during gamete formation (Law of Segregation).",
    },
    {
        "filename": "punnett-square-monohybrid.png",
        "original": "Screenshot 2026-05-03 at 8.51.22 PM.png",
        "title": "Punnett Square: Monohybrid Cross",
        "keywords": ["Punnett square", "monohybrid cross", "dominant", "recessive", "genotype", "phenotype", "flower color", "Mendelian genetics"],
        "caption": "A Punnett square predicts the genotype and phenotype ratios of offspring from a given cross. For a monohybrid cross of two heterozygotes (Aa × Aa), the expected ratio is 1 AA : 2 Aa : 1 aa.",
    },
    {
        "filename": "abo-blood-types.png",
        "original": "Screenshot 2026-05-03 at 8.52.52 PM.png",
        "title": "ABO Blood Types",
        "keywords": ["ABO blood type", "blood group", "type A", "type B", "type AB", "type O", "antigen", "antibody", "erythrocyte", "codominance", "multiple alleles"],
        "caption": "ABO blood type is determined by three alleles (Iᴬ, Iᴮ, i) at a single locus; Iᴬ and Iᴮ are codominant while i is recessive. Surface antigens and plasma antibodies determine compatibility for transfusions.",
    },
    {
        "filename": "x-linked-dominant-inheritance.png",
        "original": "Screenshot 2026-05-03 at 8.53.50 PM.png",
        "title": "X-linked Dominant Inheritance",
        "keywords": ["X-linked dominant", "sex-linked", "X chromosome", "inheritance pattern", "pedigree"],
        "caption": "X-linked dominant conditions affect individuals who carry the allele on their X chromosome. Affected fathers pass the trait to all daughters but no sons; affected mothers have a 50% chance of passing it to each child.",
    },
    {
        "filename": "x-linked-recessive-inheritance.png",
        "original": "Screenshot 2026-05-03 at 8.54.14 PM.png",
        "title": "X-linked Recessive Inheritance",
        "keywords": ["X-linked recessive", "carrier", "sex-linked", "X chromosome", "inheritance pattern", "hemophilia", "color blindness"],
        "caption": "X-linked recessive traits such as hemophilia and red-green color blindness appear more frequently in males because they have only one X chromosome. Females with one recessive allele are typically unaffected carriers.",
    },
    {
        "filename": "pedigree-chart.png",
        "original": "Screenshot 2026-05-03 at 8.55.04 PM.png",
        "title": "Pedigree Chart",
        "keywords": ["pedigree", "inheritance", "autosomal", "affected", "carrier", "unaffected", "family tree", "trait inheritance"],
        "caption": "A pedigree chart traces a trait’s inheritance across generations using standardized symbols for affected, unaffected, and carrier individuals. The pattern reveals whether inheritance is autosomal or sex-linked, and dominant or recessive.",
    },
    {
        "filename": "dna-replication.png",
        "original": "Screenshot 2026-05-03 at 8.56.07 PM.png",
        "title": "DNA Replication (Eukaryotic)",
        "keywords": ["DNA replication", "origin of replication", "primase", "RNA primer", "DNA polymerase", "leading strand", "lagging strand", "Okazaki fragments", "ligase", "helicase", "semiconservative replication"],
        "caption": "DNA replication is semiconservative: each parental strand serves as a template for a new complementary strand. Helicase unwinds the helix, primase adds RNA primers, and DNA polymerase synthesizes the new strand exclusively 5′→3′.",
    },
    {
        "filename": "telomere-repeats.png",
        "original": "Screenshot 2026-05-03 at 8.56.33 PM.png",
        "title": "Telomere Repeats",
        "keywords": ["telomere", "TTAGGG", "telomerase", "chromosome end", "aging", "cancer", "replication problem"],
        "caption": "Telomeres are repetitive sequences (TTAGGG) that cap chromosome ends, preventing degradation and end-to-end fusion. They shorten with each cell division; telomerase in germ cells and cancer cells rebuilds these protective caps.",
    },
    {
        "filename": "genetic-codon-table.png",
        "original": "Screenshot 2026-05-03 at 8.57.14 PM.png",
        "title": "Genetic Codon Table",
        "keywords": ["codon table", "genetic code", "mRNA codon", "start codon", "stop codon", "AUG", "UAA", "UAG", "UGA", "translation"],
        "caption": "The genetic code is nearly universal: each three-nucleotide mRNA codon specifies one of 20 amino acids or a stop signal. The code is redundant—most amino acids are encoded by multiple synonymous codons.",
    },
    {
        "filename": "transcription-translation-overview.png",
        "original": "Screenshot 2026-05-03 at 8.57.53 PM.png",
        "title": "Transcription and Translation Overview",
        "keywords": ["transcription", "translation", "central dogma", "DNA to mRNA", "mRNA to protein", "codon", "gene expression"],
        "caption": "The central dogma describes information flow from DNA to mRNA (transcription) to protein (translation). Transcription occurs in the nucleus; the processed mRNA is exported to the cytoplasm where ribosomes carry out translation.",
    },
    {
        "filename": "codon-wheel.png",
        "original": "Screenshot 2026-05-03 at 8.58.13 PM.png",
        "title": "Codon Wheel",
        "keywords": ["codon wheel", "genetic code", "codon", "start codon", "stop codon"],
        "caption": "The codon wheel maps all 64 possible mRNA triplets to their corresponding amino acids. Reading from the center outward gives the first, second, and third codon positions, allowing rapid identification of the encoded amino acid.",
    },
    {
        "filename": "eukaryotic-transcription.png",
        "original": "Screenshot 2026-05-03 at 8.58.54 PM.png",
        "title": "Eukaryotic Transcription",
        "keywords": ["transcription", "RNA polymerase II", "promoter", "initiation", "elongation", "termination", "mRNA synthesis", "gene expression"],
        "caption": "Eukaryotic transcription requires RNA polymerase II and general transcription factors that assemble at the promoter. The pre-mRNA is processed by adding a 5′ cap, poly-A tail, and removing introns before export to the cytoplasm.",
    },
    {
        "filename": "point-mutations.png",
        "original": "Screenshot 2026-05-03 at 8.59.30 PM.png",
        "title": "Point Mutations",
        "keywords": ["point mutation", "silent mutation", "nonsense mutation", "missense mutation", "conservative mutation", "non-conservative mutation", "DNA mutation", "codon change"],
        "caption": "A point mutation changes a single nucleotide. Silent mutations leave the amino acid unchanged; missense mutations substitute a different amino acid; nonsense mutations introduce a premature stop codon, truncating the protein.",
    },
    {
        "filename": "ribosome-translation-3d.png",
        "original": "Screenshot 2026-05-03 at 9.00.03 PM.png",
        "title": "Translating Ribosome (3D)",
        "keywords": ["ribosome", "translation", "tRNA", "mRNA", "anticodon", "codon", "amino acid chain", "large subunit", "small subunit", "protein synthesis"],
        "caption": "The ribosome has three tRNA binding sites: A (aminoacyl), P (peptidyl), and E (exit). During translation, each incoming tRNA anticodon pairs with the mRNA codon, and the growing polypeptide is transferred to the new amino acid.",
    },
    {
        "filename": "crispr-cas9-gene-editing.png",
        "original": "Screenshot 2026-05-03 at 9.00.30 PM.png",
        "title": "CRISPR/Cas9 Gene Editing",
        "keywords": ["CRISPR", "Cas9", "gene editing", "sgRNA", "guide RNA", "PAM sequence", "double-strand break", "NHEJ", "HDR", "homology-directed repair", "biotechnology"],
        "caption": "CRISPR/Cas9 uses a guide RNA to direct the Cas9 nuclease to a specific DNA sequence, where it creates a double-strand break. The cell repairs the break via NHEJ (causing mutations) or HDR (inserting a new sequence).",
    },
    {
        "filename": "rt-pcr-two-step.png",
        "original": "Screenshot 2026-05-03 at 9.01.04 PM.png",
        "title": "Two-step RT-PCR",
        "keywords": ["RT-PCR", "PCR", "reverse transcription", "cDNA", "RNA template", "gene expression", "reverse transcriptase", "DNA polymerase", "biotechnology"],
        "caption": "RT-PCR first uses reverse transcriptase to convert RNA into complementary DNA (cDNA), then amplifies a specific sequence by PCR. It is widely used to measure gene expression levels and detect RNA viruses.",
    },
    {
        "filename": "gel-electrophoresis.png",
        "original": "Screenshot 2026-05-03 at 9.02.00 PM.png",
        "title": "Gel Electrophoresis",
        "keywords": ["gel electrophoresis", "agarose gel", "DNA separation", "DNA fragment", "electric current", "biotechnology", "DNA analysis"],
        "caption": "Gel electrophoresis separates DNA fragments by size as they migrate through an agarose gel under an electric current. Smaller fragments travel farther; bands are compared against a DNA ladder to determine fragment sizes.",
    },
    {
        "filename": "epistasis-coat-color.png",
        "original": "Screenshot 2026-05-03 at 9.02.40 PM.png",
        "title": "Epistasis: Mouse Coat Color",
        "keywords": ["epistasis", "gene interaction", "phenotypic ratio", "coat color", "dominant epistasis", "recessive epistasis", "9:3:4", "dihybrid", "genetics"],
        "caption": "Epistasis occurs when one gene masks the expression of another at a different locus. In Labrador coat color, a homozygous recessive ee genotype prevents pigment deposition regardless of the B/b locus, producing a 9:3:4 ratio.",
    },
    {
        "filename": "food-web-decomposition.png",
        "original": "Screenshot 2026-05-03 at 9.04.48 PM.png",
        "title": "Food Web and Decomposition Chain",
        "keywords": ["food web", "decomposition", "nutrient cycle", "primary consumer", "secondary consumer", "bacteria", "fungi", "soil food web", "trophic level", "energy flow"],
        "caption": "A food web maps energy transfer through an ecosystem via feeding relationships at successive trophic levels. Decomposers (bacteria and fungi) break down dead organic matter, returning nutrients to the soil and completing biogeochemical cycles.",
    },
    {
        "filename": "nitrogen-cycle.png",
        "original": "Screenshot 2026-05-03 at 9.05.52 PM.png",
        "title": "The Nitrogen Cycle",
        "keywords": ["nitrogen cycle", "denitrification", "nitrification", "nitrogen fixation", "ammonification", "ammonia", "nitrate", "nitrite", "atmospheric nitrogen", "decomposer", "bacteria"],
        "caption": "The nitrogen cycle converts atmospheric N₂ into biologically available forms through nitrogen fixation, nitrification, and ammonification by bacteria. All organisms require nitrogen for amino acids and nucleic acids, but cannot use N₂ directly.",
    },
    {
        "filename": "carbon-cycle.png",
        "original": "Screenshot 2026-05-03 at 9.06.22 PM.png",
        "title": "The Carbon Cycle",
        "keywords": ["carbon cycle", "carbon fixation", "decomposition", "fossil fuel", "greenhouse gas", "biosphere", "atmosphere", "carbon reservoir", "carbon flux"],
        "caption": "Carbon cycles between the atmosphere, biosphere, hydrosphere, and lithosphere through photosynthesis, respiration, decomposition, and combustion. Rising CO₂ from fossil fuel burning intensifies the greenhouse effect and drives climate change.",
    },
    {
        "filename": "carbon-cycle-geological.png",
        "original": "Screenshot 2026-05-03 at 9.06.44 PM.png",
        "title": "The Carbon Cycle (Geological)",
        "keywords": ["carbon cycle", "geological carbon cycle", "volcanism", "sedimentation", "burial", "chemical precipitation", "biological activity", "fossil fuel", "deep carbon cycle"],
        "caption": "The geological carbon cycle operates over millions of years through volcanism, rock weathering, and sedimentation. Long-term carbon sequestration in rock and fossil fuels represents a slow but critical buffer for atmospheric CO₂ levels.",
    },
]


def get_image_url(filename: str, supabase_url: str) -> str:
    """Build the public Supabase Storage URL for an AP Bio image."""
    return f"{supabase_url}/storage/v1/object/public/textbooks/images/ap-biology/{filename}"


def find_images_for_section(section_title: str, section_body: str, max_images: int = 1) -> list[dict]:
    """
    Title-weighted keyword matching. Section title matches score 3×; body matches score 1×.
    Threshold 3 means: at least one title-level match, or an unusually keyword-dense body.
    This prevents images from being assigned to chapters where their keywords only appear
    in passing body text (e.g., carbon-cycle diagram in a carbon-bonding chemistry section).
    """
    title_text = section_title.lower()
    body_text = section_body.lower()
    scored = []
    for img in AP_BIO_IMAGES:
        title_score = sum(3 for kw in img["keywords"] if kw.lower() in title_text)
        body_score = sum(1 for kw in img["keywords"] if kw.lower() in body_text)
        score = title_score + body_score
        if score >= 3:
            scored.append((score, img))
    scored.sort(key=lambda x: x[0], reverse=True)
    return [img for _, img in scored[:max_images]]
