// Second fact-bank for AP content subjects (authored by Claude, no API).
// New terms not in content-gen.mjs. Forward + reverse MCQs. upload.mjs dedupes.
import fs from "node:fs";
const OUT = new URL(".", import.meta.url).pathname;
function mulberry32(a){return function(){a|=0;a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296;};}
const seed=Number(process.argv[2]||1);const rnd=mulberry32(seed*5381+29);
const shuffle=(arr)=>{const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const sample=(arr,n,not)=>shuffle(arr.filter(x=>x!==not)).slice(0,n);
function build(entries){const qs=[];const defs=entries.map(e=>e.def);const terms=entries.map(e=>e.term);
 for(const e of entries){const fd=sample(defs,3,e.def);if(fd.length===3)qs.push(opt(e.u,e.t,`In AP terms, ${e.term} is best defined as:`,e.def,fd,`${e.term}: ${e.def}`));
  const rt=sample(terms,3,e.term);if(rt.length===3)qs.push(opt(e.u,e.t,`Which term is defined as: "${e.def}"?`,e.term,rt,`${e.term} — ${e.def}`));}
 return uniq(qs);}
function opt(unit,topic,question_text,correct,distractors,explanation){const chosen=[String(correct)];for(const d of distractors){const s=String(d);if(!chosen.includes(s))chosen.push(s);if(chosen.length===4)break;}if(chosen.length<4)return null;
 const arr=shuffle(chosen.map((v,i)=>({v,ok:i===0})));const L=["A","B","C","D"];const q={unit,topic,difficulty:"medium",question_text};let ca="A";arr.forEach((o,i)=>{q["option_"+L[i].toLowerCase()]=o.v;if(o.ok)ca=L[i];});q.correct_answer=ca;q.explanation=explanation;return q;}
const uniq=(qs)=>{const seen=new Set();return qs.filter(q=>{if(!q)return false;if(seen.has(q.question_text))return false;seen.add(q.question_text);return true;});};

const banks={
"ap-us-government":[
 {u:1,t:"Foundations",term:"the Three-Fifths Compromise",def:"the agreement counting each enslaved person as three-fifths for representation and taxation"},
 {u:1,t:"Foundations",term:"the Great Compromise",def:"the agreement creating a bicameral Congress with proportional and equal representation"},
 {u:1,t:"Foundations",term:"enumerated powers",def:"powers specifically granted to the federal government in the Constitution"},
 {u:1,t:"Foundations",term:"the full faith and credit clause",def:"the requirement that states honor the public acts and records of other states"},
 {u:1,t:"Foundations",term:"dual federalism",def:"a system with distinct, separate spheres of national and state power"},
 {u:1,t:"Foundations",term:"cooperative federalism",def:"a system with intermingled national and state responsibilities"},
 {u:1,t:"Foundations",term:"an unfunded mandate",def:"a federal requirement imposed on states without providing money to fulfill it"},
 {u:2,t:"Branches",term:"the War Powers Resolution",def:"the law limiting the president's ability to commit troops without congressional approval"},
 {u:2,t:"Branches",term:"a signing statement",def:"a presidential statement on how the executive interprets a law being signed"},
 {u:2,t:"Branches",term:"the franking privilege",def:"the right of members of Congress to send official mail free of charge"},
 {u:2,t:"Branches",term:"a discharge petition",def:"a procedure to force a bill out of committee to the House floor"},
 {u:2,t:"Branches",term:"the Rules Committee",def:"the House committee that controls debate terms and which bills reach the floor"},
 {u:2,t:"Branches",term:"a conference committee",def:"a temporary committee that reconciles differing House and Senate versions of a bill"},
 {u:2,t:"Branches",term:"a writ of certiorari",def:"an order by which the Supreme Court agrees to review a lower court case"},
 {u:2,t:"Branches",term:"a precedent",def:"a prior court decision that guides future rulings (stare decisis)"},
 {u:2,t:"Branches",term:"judicial restraint",def:"a philosophy that courts should defer to elected branches and precedent"},
 {u:2,t:"Branches",term:"judicial activism",def:"a philosophy that courts should actively shape policy through broad rulings"},
 {u:2,t:"Branches",term:"patronage",def:"giving government jobs to political supporters"},
 {u:2,t:"Branches",term:"the merit system",def:"hiring government workers based on qualifications rather than connections"},
 {u:3,t:"Civil Liberties",term:"the clear and present danger test",def:"the standard allowing limits on speech that poses an immediate threat"},
 {u:3,t:"Civil Rights",term:"de jure segregation",def:"segregation created and enforced by law"},
 {u:3,t:"Civil Rights",term:"de facto segregation",def:"segregation that exists in practice rather than by law"},
 {u:3,t:"Civil Rights",term:"affirmative action",def:"policies that consider group membership to remedy past discrimination"},
 {u:3,t:"Civil Rights",term:"strict scrutiny",def:"the highest standard of judicial review applied to race-based classifications"},
 {u:3,t:"Civil Liberties",term:"the right to privacy",def:"an implied constitutional right inferred from several amendments"},
 {u:4,t:"Ideologies",term:"a tracking poll",def:"a poll repeated over time to measure changes in opinion"},
 {u:4,t:"Ideologies",term:"a push poll",def:"a deceptive technique disguising persuasion as a survey"},
 {u:4,t:"Ideologies",term:"the gender gap",def:"the difference in political attitudes and voting between men and women"},
 {u:4,t:"Ideologies",term:"libertarianism",def:"an ideology favoring minimal government in both economic and social matters"},
 {u:4,t:"Ideologies",term:"a margin of error",def:"the range that quantifies a poll's sampling uncertainty"},
 {u:5,t:"Participation",term:"a closed primary",def:"a primary in which only registered party members may vote"},
 {u:5,t:"Participation",term:"the Electoral College",def:"the body that formally elects the president based on state outcomes"},
 {u:5,t:"Participation",term:"a poll tax",def:"a now-banned fee once required to vote, used to disenfranchise voters"},
 {u:5,t:"Participation",term:"a political action committee",def:"an organization that raises and donates money to candidates within limits"},
 {u:5,t:"Participation",term:"grassroots mobilization",def:"organizing ordinary citizens to influence policy or elections"},
 {u:5,t:"Participation",term:"divided government",def:"when different parties control the presidency and at least one chamber of Congress"},
 {u:5,t:"Participation",term:"a midterm election",def:"a congressional election held between presidential elections"},
 {u:5,t:"Participation",term:"rational choice voting",def:"voting based on what is seen as in the voter's individual self-interest"},
 {u:5,t:"Participation",term:"retrospective voting",def:"voting based on an incumbent's or party's past performance"},
],
"ap-psychology":[
 {u:1,t:"Biological Bases",term:"the cerebellum",def:"the brain structure coordinating balance and fine motor movement"},
 {u:1,t:"Biological Bases",term:"the thalamus",def:"the brain's sensory relay station directing input to the cortex"},
 {u:1,t:"Biological Bases",term:"serotonin",def:"the neurotransmitter linked to mood, sleep, and appetite"},
 {u:1,t:"Biological Bases",term:"acetylcholine",def:"the neurotransmitter involved in muscle movement and memory"},
 {u:1,t:"Biological Bases",term:"GABA",def:"the brain's main inhibitory neurotransmitter"},
 {u:1,t:"Biological Bases",term:"an agonist",def:"a drug that mimics or enhances a neurotransmitter's effect"},
 {u:1,t:"Biological Bases",term:"an antagonist",def:"a drug that blocks a neurotransmitter's effect"},
 {u:1,t:"Biological Bases",term:"the endocrine system",def:"the system of glands communicating via hormones in the bloodstream"},
 {u:1,t:"Biological Bases",term:"an EEG",def:"a tool measuring the brain's electrical activity through scalp electrodes"},
 {u:1,t:"Biological Bases",term:"the all-or-none principle",def:"the rule that a neuron fires completely or not at all once threshold is reached"},
 {u:2,t:"Cognition",term:"proactive interference",def:"when old learning disrupts recall of new information"},
 {u:2,t:"Cognition",term:"retroactive interference",def:"when new learning disrupts recall of old information"},
 {u:2,t:"Cognition",term:"the framing effect",def:"the influence of how choices are worded on the decisions people make"},
 {u:2,t:"Cognition",term:"an algorithm",def:"a step-by-step procedure that guarantees a solution"},
 {u:2,t:"Cognition",term:"a heuristic",def:"a mental shortcut that allows quick judgments but can cause errors"},
 {u:2,t:"Cognition",term:"belief perseverance",def:"clinging to beliefs even after the evidence supporting them is discredited"},
 {u:2,t:"Cognition",term:"the spacing effect",def:"better long-term memory from study distributed over time"},
 {u:2,t:"Cognition",term:"priming",def:"when exposure to one stimulus influences the response to a later one"},
 {u:3,t:"Development & Learning",term:"latent learning",def:"learning that occurs without reinforcement and stays hidden until needed"},
 {u:3,t:"Development & Learning",term:"spontaneous recovery",def:"the reappearance of an extinguished conditioned response after a rest"},
 {u:3,t:"Development & Learning",term:"a fixed-ratio schedule",def:"reinforcement given after a set number of responses"},
 {u:3,t:"Development & Learning",term:"a variable-ratio schedule",def:"reinforcement given after an unpredictable number of responses"},
 {u:3,t:"Development & Learning",term:"stimulus discrimination",def:"responding differently to similar but distinct stimuli"},
 {u:3,t:"Development & Learning",term:"imprinting",def:"a rapid early attachment to the first moving object an animal sees"},
 {u:3,t:"Development & Learning",term:"the zone of proximal development",def:"the gap between what a learner can do alone and with guidance"},
 {u:4,t:"Social & Personality",term:"deindividuation",def:"the loss of self-awareness and restraint in group situations"},
 {u:4,t:"Social & Personality",term:"social facilitation",def:"improved performance on easy tasks when others are present"},
 {u:4,t:"Social & Personality",term:"social loafing",def:"exerting less effort when working in a group than alone"},
 {u:4,t:"Social & Personality",term:"the self-serving bias",def:"attributing successes to oneself and failures to external factors"},
 {u:4,t:"Social & Personality",term:"the foot-in-the-door phenomenon",def:"the tendency to agree to a large request after agreeing to a small one"},
 {u:4,t:"Social & Personality",term:"the halo effect",def:"letting one positive trait shape an overall positive impression"},
 {u:4,t:"Social & Personality",term:"reciprocal determinism",def:"the interaction among behavior, personal factors, and environment"},
 {u:4,t:"Social & Personality",term:"the Big Five",def:"the five-trait model: openness, conscientiousness, extraversion, agreeableness, neuroticism"},
 {u:5,t:"Mental Health",term:"obsessive-compulsive disorder",def:"a disorder of intrusive obsessions and repetitive compulsions"},
 {u:5,t:"Mental Health",term:"bipolar disorder",def:"a mood disorder alternating between mania and depression"},
 {u:5,t:"Mental Health",term:"PTSD",def:"a disorder following trauma, marked by flashbacks and hypervigilance"},
 {u:5,t:"Mental Health",term:"schizophrenia",def:"a disorder featuring hallucinations, delusions, and disorganized thought"},
 {u:5,t:"Mental Health",term:"a panic attack",def:"a sudden episode of intense fear with strong physical symptoms"},
],
"ap-human-geography":[
 {u:1,t:"Thinking Geographically",term:"a choropleth map",def:"a map using shading or color to show data values by area"},
 {u:1,t:"Thinking Geographically",term:"the Mercator projection",def:"a map projection preserving direction but distorting area near the poles"},
 {u:1,t:"Thinking Geographically",term:"sequent occupance",def:"the layered cultural imprints left by successive groups in a place"},
 {u:1,t:"Thinking Geographically",term:"GIS",def:"a system that captures and analyzes spatial and geographic data"},
 {u:2,t:"Population",term:"the dependency ratio",def:"the ratio of dependents to the working-age population"},
 {u:2,t:"Population",term:"natural increase rate",def:"the crude birth rate minus the crude death rate"},
 {u:2,t:"Population",term:"a push factor",def:"a condition that drives people to leave a place"},
 {u:2,t:"Population",term:"a pull factor",def:"a condition that attracts people to a destination"},
 {u:2,t:"Population",term:"an intervening obstacle",def:"a barrier that hinders migration between origin and destination"},
 {u:2,t:"Population",term:"a pronatalist policy",def:"a government policy aimed at encouraging higher birth rates"},
 {u:2,t:"Population",term:"carrying capacity",def:"the population an environment can support given its resources"},
 {u:3,t:"Culture",term:"contagious diffusion",def:"the rapid, widespread spread of a trait through a population"},
 {u:3,t:"Culture",term:"hierarchical diffusion",def:"the spread of a trait from larger or more powerful places to smaller ones"},
 {u:3,t:"Culture",term:"a creole language",def:"a stable language that develops when a pidgin becomes a native tongue"},
 {u:3,t:"Culture",term:"cultural relativism",def:"understanding a culture on its own terms rather than judging by another"},
 {u:3,t:"Culture",term:"a syncretic religion",def:"a religion blending elements of two or more traditions"},
 {u:4,t:"Political",term:"a nation-state",def:"a state whose territory corresponds to a single national identity"},
 {u:4,t:"Political",term:"a federal state",def:"a state dividing power between national and regional governments"},
 {u:4,t:"Political",term:"a centripetal force",def:"a factor that unifies a state"},
 {u:4,t:"Political",term:"a centrifugal force",def:"a factor that divides a state"},
 {u:4,t:"Political",term:"a fragmented state",def:"a state divided into several discontinuous pieces"},
 {u:4,t:"Political",term:"a choke point",def:"a narrow passage controlling the flow of trade or military movement"},
 {u:4,t:"Political",term:"gerrymandering",def:"drawing electoral boundaries to favor a group"},
 {u:4,t:"Political",term:"supranationalism",def:"states pooling sovereignty in a larger organization like the EU"},
 {u:5,t:"Agriculture",term:"the Green Revolution",def:"the spread of high-yield seeds and technology that raised crop production"},
 {u:5,t:"Agriculture",term:"shifting cultivation",def:"farming that moves to new plots as soil fertility declines"},
 {u:5,t:"Agriculture",term:"intensive agriculture",def:"farming using high inputs on small plots for high yield per area"},
 {u:5,t:"Agriculture",term:"truck farming",def:"the commercial gardening of fruits and vegetables for market"},
 {u:5,t:"Agriculture",term:"a commodity chain",def:"the linked steps from production to consumption of a good"},
 {u:6,t:"Cities",term:"the rank-size rule",def:"the pattern where a city's size is inversely proportional to its rank"},
 {u:6,t:"Cities",term:"suburbanization",def:"the movement of people from cities to surrounding suburbs"},
 {u:6,t:"Cities",term:"redlining",def:"denying loans or services to residents of certain neighborhoods"},
 {u:6,t:"Cities",term:"a world city",def:"a city with command-and-control influence over the global economy"},
 {u:6,t:"Cities",term:"urban sprawl",def:"the low-density, car-dependent spread of development at a city's edge"},
 {u:7,t:"Development",term:"the Rostow model",def:"a model of development through five linear stages of growth"},
 {u:7,t:"Development",term:"the Gini coefficient",def:"a measure of income inequality within a country"},
 {u:7,t:"Development",term:"a newly industrialized country",def:"a country rapidly shifting from agriculture to manufacturing"},
 {u:7,t:"Development",term:"foreign direct investment",def:"investment by a firm in business interests in another country"},
],
"ap-environmental-science":[
 {u:1,t:"Ecosystems",term:"denitrification",def:"the bacterial conversion of nitrates back into nitrogen gas"},
 {u:1,t:"Ecosystems",term:"a trophic level",def:"a feeding position in a food chain"},
 {u:1,t:"Ecosystems",term:"parasitism",def:"a symbiotic relationship in which one organism benefits and the other is harmed"},
 {u:1,t:"Ecosystems",term:"commensalism",def:"a relationship in which one benefits and the other is unaffected"},
 {u:1,t:"Ecosystems",term:"secondary succession",def:"succession occurring where soil already exists after a disturbance"},
 {u:1,t:"Ecosystems",term:"a biome",def:"a large region characterized by its climate, plants, and animals"},
 {u:2,t:"Biodiversity",term:"a pioneer species",def:"an early colonizer like lichen that begins soil formation"},
 {u:2,t:"Biodiversity",term:"ecotourism",def:"tourism that funds conservation while minimizing environmental impact"},
 {u:2,t:"Biodiversity",term:"a wildlife corridor",def:"a strip of habitat connecting fragmented areas to allow movement"},
 {u:3,t:"Populations",term:"a K-selected species",def:"a species with few offspring and much parental care"},
 {u:3,t:"Populations",term:"biotic potential",def:"the maximum rate a population could grow under ideal conditions"},
 {u:3,t:"Populations",term:"a density-independent factor",def:"a limiting factor like weather that affects a population regardless of size"},
 {u:4,t:"Earth Systems",term:"the rock cycle",def:"the transformation of rock types through heat, pressure, and weathering"},
 {u:4,t:"Earth Systems",term:"a watershed",def:"an area that drains precipitation into a common body of water"},
 {u:4,t:"Earth Systems",term:"soil texture",def:"the proportions of sand, silt, and clay in soil"},
 {u:4,t:"Earth Systems",term:"a subduction zone",def:"a convergent boundary where one plate sinks beneath another"},
 {u:4,t:"Earth Systems",term:"La Niña",def:"the cool phase of ENSO that strengthens Pacific upwelling"},
 {u:5,t:"Land & Water",term:"terracing",def:"creating level steps on slopes to reduce erosion and retain water"},
 {u:5,t:"Land & Water",term:"drip irrigation",def:"delivering water directly to roots to reduce waste"},
 {u:5,t:"Land & Water",term:"clear-cutting",def:"removing all trees in an area, causing erosion and habitat loss"},
 {u:5,t:"Land & Water",term:"a CAFO",def:"a concentrated animal feeding operation producing large amounts of waste"},
 {u:6,t:"Energy",term:"a fossil fuel",def:"a fuel formed from ancient organic matter over millions of years"},
 {u:6,t:"Energy",term:"hydroelectric power",def:"electricity generated from flowing or falling water"},
 {u:6,t:"Energy",term:"pumped-storage hydroelectricity",def:"storing energy by pumping water uphill to release at peak demand"},
 {u:6,t:"Energy",term:"energy efficiency",def:"providing the same service with less energy input"},
 {u:7,t:"Atmospheric Pollution",term:"a scrubber",def:"a device removing pollutants like sulfur dioxide from smokestack gases"},
 {u:7,t:"Atmospheric Pollution",term:"carbon monoxide",def:"a gas from incomplete combustion that reduces oxygen delivery in blood"},
 {u:7,t:"Atmospheric Pollution",term:"particulate matter",def:"fine particles that penetrate deep into the lungs"},
 {u:7,t:"Atmospheric Pollution",term:"the ozone hole",def:"stratospheric ozone depletion caused by CFCs, worst over Antarctica"},
 {u:8,t:"Aquatic Pollution",term:"a persistent organic pollutant",def:"a toxin that resists degradation and bioaccumulates in food chains"},
 {u:8,t:"Aquatic Pollution",term:"nonpoint-source pollution",def:"diffuse pollution from many sources like agricultural runoff"},
 {u:8,t:"Aquatic Pollution",term:"a sanitary landfill",def:"a lined, covered waste site that contains leachate and gas"},
 {u:8,t:"Aquatic Pollution",term:"composting",def:"decomposing organic waste into nutrient-rich material"},
 {u:9,t:"Global Change",term:"permafrost thaw",def:"the melting of frozen soil that releases stored methane and CO2"},
 {u:9,t:"Global Change",term:"a negative feedback loop",def:"a process that counteracts a change and stabilizes a system"},
 {u:9,t:"Global Change",term:"climate adaptation",def:"adjusting to climate impacts, such as building sea walls"},
 {u:9,t:"Global Change",term:"sustainable development",def:"meeting present needs without compromising future generations"},
],
"ap-english-language":[
 {u:1,t:"Rhetorical Situation",term:"the rhetorical situation",def:"the relationship among speaker, audience, purpose, context, and message"},
 {u:1,t:"Rhetorical Situation",term:"audience",def:"the intended readers or listeners a text aims to reach"},
 {u:1,t:"Rhetorical Situation",term:"purpose",def:"the goal a writer aims to achieve with a text"},
 {u:1,t:"Rhetorical Situation",term:"context",def:"the circumstances surrounding a text's creation and reception"},
 {u:3,t:"Claims & Evidence",term:"a claim",def:"an arguable assertion a writer supports with evidence"},
 {u:3,t:"Claims & Evidence",term:"a thesis",def:"the central arguable claim a text develops"},
 {u:3,t:"Claims & Evidence",term:"testimony",def:"firsthand or expert statements used as evidence"},
 {u:3,t:"Claims & Evidence",term:"commentary",def:"analysis explaining how evidence supports a claim"},
 {u:5,t:"Reasoning",term:"a line of reasoning",def:"the logical sequence connecting claims, evidence, and conclusions"},
 {u:5,t:"Reasoning",term:"chronological organization",def:"arranging ideas by time sequence"},
 {u:5,t:"Reasoning",term:"climactic order",def:"arranging points from least to most important"},
 {u:5,t:"Reasoning",term:"a transition",def:"a word or phrase that signals how ideas relate"},
 {u:7,t:"Style",term:"diction",def:"a writer's word choice"},
 {u:7,t:"Style",term:"syntax",def:"the arrangement of words and phrases in sentences"},
 {u:7,t:"Style",term:"tone",def:"the writer's attitude toward the subject or audience"},
 {u:7,t:"Style",term:"a metaphor",def:"a direct comparison stating one thing is another"},
 {u:7,t:"Style",term:"a simile",def:"a comparison using 'like' or 'as'"},
 {u:7,t:"Style",term:"imagery",def:"descriptive language appealing to the senses"},
 {u:7,t:"Style",term:"epistrophe",def:"the repetition of a word at the end of successive clauses"},
 {u:7,t:"Style",term:"active voice",def:"a construction in which the subject performs the action"},
 {u:7,t:"Style",term:"passive voice",def:"a construction in which the subject receives the action"},
 {u:7,t:"Style",term:"connotation",def:"the emotional or cultural associations of a word"},
 {u:7,t:"Style",term:"denotation",def:"the literal dictionary meaning of a word"},
 {u:7,t:"Style",term:"satire",def:"the use of humor and irony to criticize folly or vice"},
 {u:7,t:"Style",term:"irony",def:"a contrast between expectation and reality"},
 {u:9,t:"Fallacies",term:"a red herring",def:"introducing an irrelevant topic to divert from the argument"},
 {u:9,t:"Fallacies",term:"the genetic fallacy",def:"judging a claim by its origin rather than its merits"},
 {u:9,t:"Fallacies",term:"an appeal to authority",def:"citing an authority who may lack relevant expertise"},
 {u:9,t:"Fallacies",term:"circular reasoning",def:"an argument whose conclusion is assumed in its premises"},
 {u:9,t:"Fallacies",term:"an appeal to fear",def:"using fear instead of evidence to persuade"},
],
"ap-world-history":[
 {u:1,t:"Global Tapestry",term:"the Mali Empire",def:"a wealthy West African empire built on the gold-salt trade"},
 {u:1,t:"Global Tapestry",term:"Confucianism",def:"a Chinese philosophy emphasizing hierarchy, filial piety, and education"},
 {u:1,t:"Global Tapestry",term:"the Delhi Sultanate",def:"a series of Muslim dynasties ruling much of northern India"},
 {u:1,t:"Global Tapestry",term:"chinampas",def:"Aztec floating gardens used for intensive agriculture"},
 {u:1,t:"Global Tapestry",term:"serfdom",def:"a system binding peasants to the land and their lord"},
 {u:2,t:"Networks",term:"the Indian Ocean trade",def:"a maritime network relying on monsoon winds across Afro-Eurasia"},
 {u:2,t:"Networks",term:"the Hanseatic League",def:"a commercial alliance of northern European trading cities"},
 {u:2,t:"Networks",term:"the Black Death",def:"the plague that spread along trade routes, killing much of Eurasia's population"},
 {u:2,t:"Networks",term:"Swahili",def:"a syncretic East African coastal culture and language blending African and Arab influences"},
 {u:3,t:"Land-Based Empires",term:"the Janissaries",def:"elite Ottoman infantry recruited through the devshirme"},
 {u:3,t:"Land-Based Empires",term:"the Safavid Empire",def:"a Shi'a Persian gunpowder empire centered in Isfahan"},
 {u:3,t:"Land-Based Empires",term:"the jizya",def:"a tax historically levied on non-Muslims in Islamic empires"},
 {u:3,t:"Land-Based Empires",term:"tax farming",def:"granting private individuals the right to collect taxes for a profit"},
 {u:4,t:"Transoceanic",term:"the triangular trade",def:"the Atlantic exchange of goods and enslaved people among Europe, Africa, and the Americas"},
 {u:4,t:"Transoceanic",term:"indentured servitude",def:"labor bound for a fixed term in exchange for passage, then freedom"},
 {u:4,t:"Transoceanic",term:"the mit'a",def:"the Inca and later Spanish system of compulsory labor"},
 {u:4,t:"Transoceanic",term:"a syncretic religion",def:"a faith blending traditions, such as Vodou combining African beliefs and Catholicism"},
 {u:5,t:"Revolutions",term:"the Congress of Vienna",def:"the 1815 settlement restoring conservative order in Europe after Napoleon"},
 {u:5,t:"Revolutions",term:"abolitionism",def:"the movement to end slavery"},
 {u:5,t:"Revolutions",term:"Marxism",def:"a theory framing history as class struggle and calling for proletarian revolution"},
 {u:5,t:"Revolutions",term:"romanticism",def:"a movement emphasizing emotion and nature in reaction to Enlightenment reason"},
 {u:6,t:"Industrialization",term:"the assembly line",def:"manufacturing broken into sequential specialized steps to boost efficiency"},
 {u:6,t:"Industrialization",term:"the Opium Wars",def:"conflicts that forced China to open ports and cede Hong Kong to Britain"},
 {u:6,t:"Industrialization",term:"the Meiji Restoration",def:"Japan's rapid top-down modernization beginning in 1868"},
 {u:6,t:"Industrialization",term:"a labor union",def:"a worker organization that bargains collectively for better conditions"},
 {u:7,t:"Global Conflict",term:"trench warfare",def:"WWI's entrenched defensive fighting that produced stalemate and mass casualties"},
 {u:7,t:"Global Conflict",term:"the Holocaust",def:"the Nazi genocide of six million Jews and millions of others"},
 {u:7,t:"Global Conflict",term:"the League of Nations",def:"the post-WWI organization that failed to prevent WWII"},
 {u:8,t:"Cold War",term:"the Marshall Plan",def:"U.S. aid to rebuild Western Europe after WWII"},
 {u:8,t:"Cold War",term:"the domino theory",def:"the belief that one nation falling to communism would cause neighbors to follow"},
 {u:8,t:"Cold War",term:"the Berlin Wall",def:"the barrier dividing communist East from capitalist West Berlin"},
 {u:9,t:"Globalization",term:"the World Trade Organization",def:"the body regulating international trade and resolving disputes"},
 {u:9,t:"Globalization",term:"the United Nations",def:"the post-WWII organization promoting international cooperation and peace"},
],
};
let total=0;
for(const [subject,entries] of Object.entries(banks)){const qs=shuffle(build(entries));fs.writeFileSync(`${OUT}${subject}-fact2-${seed}.json`,JSON.stringify({subject,questions:qs},null,1));console.log(`${subject}: ${entries.length} facts -> ${qs.length} q`);total+=qs.length;}
console.log("total:",total);
