// Fourth fact-bank (authored by Claude, no API). New terms for the 5 term-rich content subjects.
import fs from "node:fs";
const OUT = new URL(".", import.meta.url).pathname;
function mulberry32(a){return function(){a|=0;a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296;};}
const seed=Number(process.argv[2]||1);const rnd=mulberry32(seed*1299721+53);
const shuffle=(arr)=>{const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const sample=(arr,n,not)=>shuffle(arr.filter(x=>x!==not)).slice(0,n);
function build(entries){const qs=[];const defs=entries.map(e=>e.def);const terms=entries.map(e=>e.term);
 for(const e of entries){const fd=sample(defs,3,e.def);if(fd.length===3)qs.push(opt(e.u,e.t,`In AP terms, ${e.term} is best defined as:`,e.def,fd,`${e.term}: ${e.def}`));
  const rt=sample(terms,3,e.term);if(rt.length===3)qs.push(opt(e.u,e.t,`Which term is defined as: "${e.def}"?`,e.term,rt,`${e.term} — ${e.def}`));}
 return uniq(qs);}
function opt(unit,topic,question_text,correct,distractors,explanation){const chosen=[String(correct)];for(const d of distractors){const s=String(d);if(!chosen.includes(s))chosen.push(s);if(chosen.length===4)break;}if(chosen.length<4)return null;
 const arr=shuffle(chosen.map((v,i)=>({v,ok:i===0})));const L=["A","B","C","D"];const q={unit,topic,difficulty:"medium",question_text};let ca="A";arr.forEach((o,i)=>{q["option_"+L[i].toLowerCase()]=o.v;if(o.ok)ca=L[i];});q.correct_answer=ca;q.explanation=explanation;return q;}
const uniq=(qs)=>{const seen=new Set();return qs.filter(q=>{if(!q)return false;if(seen.has(q.question_text))return false;seen.add(q.question_text);return true;});};

const banks={
"ap-us-government":[
 {u:2,t:"Branches",term:"a continuing resolution",def:"a temporary measure funding government when a budget is not passed"},
 {u:2,t:"Branches",term:"a rider",def:"an unrelated provision attached to a bill to gain passage"},
 {u:2,t:"Branches",term:"the seniority system",def:"the practice of granting power based on length of congressional service"},
 {u:2,t:"Branches",term:"a standing committee",def:"a permanent congressional committee handling bills in a policy area"},
 {u:2,t:"Branches",term:"a select committee",def:"a temporary committee created for a specific investigation or purpose"},
 {u:2,t:"Branches",term:"trustee representation",def:"a legislator voting based on personal judgment of the common good"},
 {u:2,t:"Branches",term:"delegate representation",def:"a legislator voting according to constituents' wishes"},
 {u:2,t:"Branches",term:"politico representation",def:"a legislator blending trustee and delegate roles depending on the issue"},
 {u:2,t:"Branches",term:"recess appointment",def:"a presidential appointment made while the Senate is not in session"},
 {u:2,t:"Branches",term:"an executive agreement",def:"a pact with a foreign leader that does not require Senate ratification"},
 {u:2,t:"Branches",term:"executive order",def:"a presidential directive that manages the federal government with the force of law"},
 {u:2,t:"Branches",term:"the spoils system",def:"rewarding political supporters with government jobs"},
 {u:2,t:"Branches",term:"the Pendleton Act",def:"the law establishing merit-based federal hiring"},
 {u:2,t:"Branches",term:"the Office of Management and Budget",def:"the agency that prepares the president's budget"},
 {u:2,t:"Branches",term:"discretionary authority",def:"the bureaucracy's power to decide how to implement laws"},
 {u:2,t:"Branches",term:"rule-making authority",def:"the bureaucracy's power to create regulations with the force of law"},
 {u:3,t:"Civil Liberties",term:"the Miranda warning",def:"the notice of rights police must give before custodial interrogation"},
 {u:3,t:"Civil Liberties",term:"double jeopardy",def:"being tried twice for the same offense, barred by the Fifth Amendment"},
 {u:3,t:"Civil Liberties",term:"the right to bear arms",def:"the Second Amendment protection of gun ownership"},
 {u:3,t:"Civil Liberties",term:"cruel and unusual punishment",def:"penalties barred by the Eighth Amendment"},
 {u:3,t:"Civil Rights",term:"the Nineteenth Amendment",def:"the amendment guaranteeing women the right to vote"},
 {u:3,t:"Civil Rights",term:"the Fifteenth Amendment",def:"the amendment barring denial of the vote based on race"},
 {u:3,t:"Civil Rights",term:"the Twenty-Sixth Amendment",def:"the amendment lowering the voting age to eighteen"},
 {u:4,t:"Ideologies",term:"the free-rider problem",def:"when people benefit from a good without paying for it"},
 {u:4,t:"Ideologies",term:"deregulation",def:"reducing government restrictions on industry"},
 {u:4,t:"Ideologies",term:"the social safety net",def:"government programs protecting against poverty and hardship"},
 {u:5,t:"Participation",term:"motor voter law",def:"a law easing voter registration at motor vehicle offices"},
 {u:5,t:"Participation",term:"a winner-take-all system",def:"a system awarding all of a state's electoral votes to the popular-vote winner"},
 {u:5,t:"Participation",term:"soft money",def:"unregulated funds once given to parties for party-building"},
 {u:5,t:"Participation",term:"hard money",def:"regulated, limited contributions given directly to candidates"},
],
"ap-psychology":[
 {u:1,t:"Biological Bases",term:"the limbic system",def:"the brain network governing emotion and memory"},
 {u:1,t:"Biological Bases",term:"the hypothalamus",def:"the structure regulating drives like hunger, thirst, and body temperature"},
 {u:1,t:"Biological Bases",term:"the parietal lobe",def:"the brain region processing touch and spatial awareness"},
 {u:1,t:"Biological Bases",term:"the temporal lobe",def:"the brain region processing hearing and language"},
 {u:1,t:"Biological Bases",term:"the myelin sheath",def:"the fatty layer that speeds neural transmission"},
 {u:1,t:"Biological Bases",term:"a refractory period",def:"the brief pause after firing before a neuron can fire again"},
 {u:1,t:"Biological Bases",term:"norepinephrine",def:"a neurotransmitter involved in arousal and alertness"},
 {u:2,t:"Cognition",term:"the anchoring effect",def:"relying too heavily on the first piece of information when deciding"},
 {u:2,t:"Cognition",term:"overconfidence",def:"overestimating the accuracy of one's knowledge or judgments"},
 {u:2,t:"Cognition",term:"the peak-end rule",def:"judging an experience by its most intense point and its ending"},
 {u:2,t:"Cognition",term:"mental set",def:"the tendency to approach problems using past successful methods"},
 {u:2,t:"Cognition",term:"working memory",def:"the active system holding and manipulating information briefly"},
 {u:2,t:"Cognition",term:"the testing effect",def:"the finding that retrieval practice strengthens memory"},
 {u:3,t:"Development & Learning",term:"the formal operational stage",def:"Piaget's stage marked by abstract and hypothetical reasoning"},
 {u:3,t:"Development & Learning",term:"the concrete operational stage",def:"Piaget's stage marked by logical thought about concrete events"},
 {u:3,t:"Development & Learning",term:"an avoidant attachment",def:"an attachment style showing little distress at separation and avoidance at reunion"},
 {u:3,t:"Development & Learning",term:"generativity vs. stagnation",def:"Erikson's middle-adulthood crisis of contributing versus feeling unproductive"},
 {u:3,t:"Development & Learning",term:"identity vs. role confusion",def:"Erikson's adolescent crisis of forming a sense of self"},
 {u:3,t:"Development & Learning",term:"a continuous reinforcement schedule",def:"reinforcing every correct response, producing fast but fragile learning"},
 {u:4,t:"Social & Personality",term:"attribution theory",def:"the study of how people explain the causes of behavior"},
 {u:4,t:"Social & Personality",term:"the actor-observer bias",def:"attributing one's own actions to the situation but others' to disposition"},
 {u:4,t:"Social & Personality",term:"prejudice",def:"an unjustified attitude, usually negative, toward a group"},
 {u:4,t:"Social & Personality",term:"discrimination",def:"unjust behavior directed at members of a group"},
 {u:4,t:"Social & Personality",term:"a locus of control",def:"the degree to which people believe they control their own fate"},
 {u:5,t:"Mental Health",term:"a compulsion",def:"a repetitive behavior performed to reduce anxiety in OCD"},
 {u:5,t:"Mental Health",term:"an obsession",def:"a persistent unwanted thought characteristic of OCD"},
 {u:5,t:"Mental Health",term:"a delusion",def:"a false belief held despite contrary evidence"},
 {u:5,t:"Mental Health",term:"a hallucination",def:"a sensory experience without an external stimulus"},
 {u:5,t:"Mental Health",term:"the DSM",def:"the standard manual for classifying mental disorders"},
 {u:5,t:"Mental Health",term:"humanistic therapy",def:"a client-centered approach emphasizing growth and self-acceptance"},
],
"ap-human-geography":[
 {u:1,t:"Thinking Geographically",term:"map scale",def:"the ratio of distance on a map to distance on the ground"},
 {u:1,t:"Thinking Geographically",term:"a thematic map",def:"a map displaying a particular theme or data variable"},
 {u:1,t:"Thinking Geographically",term:"a reference map",def:"a map showing locations of features like borders and cities"},
 {u:1,t:"Thinking Geographically",term:"environmental determinism",def:"the discredited view that environment dictates cultural development"},
 {u:1,t:"Thinking Geographically",term:"possibilism",def:"the view that environment sets limits but people adapt and choose"},
 {u:2,t:"Population",term:"the J-curve",def:"the shape of exponential population growth"},
 {u:2,t:"Population",term:"the S-curve",def:"the shape of population growth leveling at carrying capacity"},
 {u:2,t:"Population",term:"zero population growth",def:"a stable population where births equal deaths"},
 {u:2,t:"Population",term:"forced migration",def:"migration compelled by external pressure such as conflict or slavery"},
 {u:2,t:"Population",term:"voluntary migration",def:"migration chosen by the migrant, often for opportunity"},
 {u:2,t:"Population",term:"transhumance",def:"the seasonal movement of livestock between pastures"},
 {u:3,t:"Culture",term:"material culture",def:"the physical objects a culture produces"},
 {u:3,t:"Culture",term:"nonmaterial culture",def:"a culture's beliefs, values, and practices"},
 {u:3,t:"Culture",term:"a folk culture",def:"a culture practiced by small, homogeneous, often rural groups"},
 {u:3,t:"Culture",term:"a popular culture",def:"a culture of large, heterogeneous societies sharing common traits"},
 {u:3,t:"Culture",term:"language family",def:"a group of related languages descended from a common ancestor"},
 {u:4,t:"Political",term:"a microstate",def:"a state with a very small land area or population"},
 {u:4,t:"Political",term:"a multinational state",def:"a state containing more than one nation"},
 {u:4,t:"Political",term:"a multistate nation",def:"a nation spread across more than one state"},
 {u:4,t:"Political",term:"a boundary dispute",def:"a conflict over the location or control of a border"},
 {u:4,t:"Political",term:"a relic boundary",def:"a former boundary that no longer functions but leaves cultural marks"},
 {u:5,t:"Agriculture",term:"agribusiness",def:"the integrated system of commercial agriculture and related industries"},
 {u:5,t:"Agriculture",term:"a commodity crop",def:"a crop grown for sale rather than the farmer's own use"},
 {u:5,t:"Agriculture",term:"mixed crop and livestock farming",def:"farming integrating crops and animals on the same land"},
 {u:5,t:"Agriculture",term:"Mediterranean agriculture",def:"farming of crops like grapes and olives in dry-summer climates"},
 {u:6,t:"Cities",term:"urbanization",def:"the increasing share of people living in cities"},
 {u:6,t:"Cities",term:"a bid-rent curve",def:"the relationship between land value and distance from the city center"},
 {u:6,t:"Cities",term:"a greenbelt",def:"a ring of protected open land limiting urban sprawl"},
 {u:6,t:"Cities",term:"infrastructure",def:"the basic physical systems supporting urban life"},
 {u:7,t:"Development",term:"the informal economy",def:"economic activity not taxed or monitored by government"},
 {u:7,t:"Development",term:"a tertiary sector",def:"the part of the economy providing services"},
],
"ap-environmental-science":[
 {u:1,t:"Ecosystems",term:"a biogeochemical cycle",def:"the movement of an element through living and nonliving parts of an ecosystem"},
 {u:1,t:"Ecosystems",term:"the hydrologic cycle",def:"the continuous movement of water through the environment"},
 {u:1,t:"Ecosystems",term:"a limiting factor",def:"a resource or condition that restricts a population's growth"},
 {u:1,t:"Ecosystems",term:"a niche",def:"the role and position a species has in its environment"},
 {u:1,t:"Ecosystems",term:"a habitat",def:"the physical place where an organism lives"},
 {u:1,t:"Ecosystems",term:"a primary consumer",def:"an organism that eats producers"},
 {u:1,t:"Ecosystems",term:"a secondary consumer",def:"an organism that eats primary consumers"},
 {u:2,t:"Biodiversity",term:"a generalist species",def:"a species that can thrive in many conditions"},
 {u:2,t:"Biodiversity",term:"a specialist species",def:"a species adapted to a narrow range of conditions"},
 {u:2,t:"Biodiversity",term:"resilience",def:"an ecosystem's ability to recover after disturbance"},
 {u:2,t:"Biodiversity",term:"resistance",def:"an ecosystem's ability to withstand disturbance"},
 {u:3,t:"Populations",term:"a type I survivorship curve",def:"a pattern with high survival early and death concentrated in old age"},
 {u:3,t:"Populations",term:"a type III survivorship curve",def:"a pattern with high early mortality and few reaching old age"},
 {u:3,t:"Populations",term:"population density",def:"the number of individuals per unit area"},
 {u:4,t:"Earth Systems",term:"a warm front",def:"the leading edge of a warm air mass rising over cooler air"},
 {u:4,t:"Earth Systems",term:"a temperate grassland",def:"a biome of grasses, moderate rainfall, and fertile soil"},
 {u:4,t:"Earth Systems",term:"the tundra",def:"a cold biome with permafrost and low-growing vegetation"},
 {u:4,t:"Earth Systems",term:"a tropical savanna",def:"a biome of grassland with scattered trees and a wet-dry climate"},
 {u:4,t:"Earth Systems",term:"weathering",def:"the breakdown of rock at or near Earth's surface"},
 {u:5,t:"Land & Water",term:"slash-and-burn agriculture",def:"clearing land by cutting and burning vegetation"},
 {u:5,t:"Land & Water",term:"crop rotation",def:"alternating crops to maintain soil fertility"},
 {u:5,t:"Land & Water",term:"no-till farming",def:"planting without plowing to reduce erosion"},
 {u:5,t:"Land & Water",term:"the Green Revolution",def:"the spread of high-yield seeds and inputs that raised food output"},
 {u:6,t:"Energy",term:"peak oil",def:"the point of maximum global oil production before decline"},
 {u:6,t:"Energy",term:"a smart grid",def:"an electricity network using digital technology to balance supply and demand"},
 {u:6,t:"Energy",term:"tidal energy",def:"renewable energy harnessed from the rise and fall of tides"},
 {u:7,t:"Atmospheric Pollution",term:"the Montreal Protocol",def:"the treaty phasing out ozone-depleting substances"},
 {u:7,t:"Atmospheric Pollution",term:"a catalytic converter",def:"a device reducing harmful emissions from vehicle exhaust"},
 {u:8,t:"Aquatic Pollution",term:"bioaccumulation",def:"the buildup of a toxin within a single organism over time"},
 {u:8,t:"Aquatic Pollution",term:"groundwater",def:"water stored in soil and rock beneath the surface"},
 {u:9,t:"Global Change",term:"a greenhouse gas",def:"a gas like CO2 or methane that traps heat in the atmosphere"},
],
"ap-world-history":[
 {u:1,t:"Global Tapestry",term:"Angkor Wat",def:"a Khmer temple complex reflecting Hindu and Buddhist influence"},
 {u:1,t:"Global Tapestry",term:"the Swahili city-states",def:"East African coastal trading centers blending Bantu and Arab culture"},
 {u:1,t:"Global Tapestry",term:"Great Zimbabwe",def:"a powerful southern African trading kingdom"},
 {u:1,t:"Global Tapestry",term:"the Aztec Empire",def:"a Mesoamerican empire centered on Tenochtitlan"},
 {u:1,t:"Global Tapestry",term:"the Inca Empire",def:"an Andean empire administered by roads and the quipu"},
 {u:2,t:"Networks",term:"the astrolabe",def:"a navigational instrument that aided long-distance sea travel"},
 {u:2,t:"Networks",term:"the lateen sail",def:"a triangular sail allowing ships to sail against the wind"},
 {u:2,t:"Networks",term:"Mansa Musa",def:"the Mali ruler whose hajj displayed the empire's wealth"},
 {u:2,t:"Networks",term:"the Champa rice",def:"a fast-ripening rice that boosted Chinese population growth"},
 {u:3,t:"Land-Based Empires",term:"Suleiman the Magnificent",def:"the Ottoman sultan under whom the empire reached its height"},
 {u:3,t:"Land-Based Empires",term:"Shah Abbas",def:"the Safavid ruler who modernized the army and promoted trade"},
 {u:3,t:"Land-Based Empires",term:"Akbar",def:"the tolerant Mughal emperor who integrated Hindus into government"},
 {u:3,t:"Land-Based Empires",term:"the Songhai Empire",def:"a large West African empire that succeeded Mali"},
 {u:4,t:"Transoceanic",term:"Vasco da Gama",def:"the explorer who reached India by sea around Africa"},
 {u:4,t:"Transoceanic",term:"the conquistadors",def:"Spanish soldiers who conquered American empires"},
 {u:4,t:"Transoceanic",term:"the Manila galleons",def:"ships linking Asian and American trade across the Pacific"},
 {u:4,t:"Transoceanic",term:"smallpox",def:"a disease that devastated indigenous American populations"},
 {u:5,t:"Revolutions",term:"Toussaint Louverture",def:"the leader of the Haitian Revolution"},
 {u:5,t:"Revolutions",term:"Simón Bolívar",def:"a creole leader of South American independence"},
 {u:5,t:"Revolutions",term:"Napoleon Bonaparte",def:"the French general and emperor who spread revolutionary ideals by conquest"},
 {u:5,t:"Revolutions",term:"the Declaration of the Rights of Man",def:"the French document proclaiming liberty and equality"},
 {u:6,t:"Industrialization",term:"the spinning jenny",def:"an early machine that mechanized textile production"},
 {u:6,t:"Industrialization",term:"the steam engine",def:"a machine that powered railroads, ships, and factories"},
 {u:6,t:"Industrialization",term:"the White Man's Burden",def:"a racist justification for imperialism as a civilizing duty"},
 {u:6,t:"Industrialization",term:"the Suez Canal",def:"a waterway linking the Mediterranean and Red Seas, vital to trade"},
 {u:7,t:"Global Conflict",term:"the Bolsheviks",def:"the communist party that seized power in Russia in 1917"},
 {u:7,t:"Global Conflict",term:"the Manhattan Project",def:"the U.S. program that developed the atomic bomb"},
 {u:7,t:"Global Conflict",term:"appeasement",def:"the policy of conceding to aggression to avoid war"},
 {u:8,t:"Cold War",term:"NATO",def:"the Western military alliance formed during the Cold War"},
 {u:8,t:"Cold War",term:"the Warsaw Pact",def:"the Soviet-led military alliance of Eastern Bloc states"},
 {u:8,t:"Cold War",term:"glasnost",def:"Gorbachev's policy of openness in the Soviet Union"},
 {u:8,t:"Cold War",term:"perestroika",def:"Gorbachev's policy of economic restructuring"},
],
};
let total=0;
for(const [subject,entries] of Object.entries(banks)){const qs=shuffle(build(entries));fs.writeFileSync(`${OUT}${subject}-fact4-${seed}.json`,JSON.stringify({subject,questions:qs},null,1));console.log(`${subject}: ${entries.length} facts -> ${qs.length} q`);total+=qs.length;}
console.log("total:",total);
