// Third fact-bank for AP content subjects (authored by Claude, no API).
// New terms not in content-gen / content-gen2. Forward + reverse MCQs.
import fs from "node:fs";
const OUT = new URL(".", import.meta.url).pathname;
function mulberry32(a){return function(){a|=0;a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296;};}
const seed=Number(process.argv[2]||1);const rnd=mulberry32(seed*2654435761+97);
const shuffle=(arr)=>{const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const sample=(arr,n,not)=>shuffle(arr.filter(x=>x!==not)).slice(0,n);
function build(entries){const qs=[];const defs=entries.map(e=>e.def);const terms=entries.map(e=>e.term);
 for(const e of entries){const fd=sample(defs,3,e.def);if(fd.length===3)qs.push(opt(e.u,e.t,`In AP terms, ${e.term} is best defined as:`,e.def,fd,`${e.term}: ${e.def}`));
  const rt=sample(terms,3,e.term);if(rt.length===3)qs.push(opt(e.u,e.t,`Which term is defined as: "${e.def}"?`,e.term,rt,`${e.term} — ${e.def}`));}
 return uniq(qs);}
function opt(unit,topic,question_text,correct,distractors,explanation){const chosen=[String(correct)];for(const d of distractors){const s=String(d);if(!chosen.includes(s))chosen.push(s);if(chosen.length===4)break;}if(chosen.length<4)return null;
 const arr=shuffle(chosen.map((v,i)=>({v,ok:i===0})));const L=["A","B","C","D"];const q={unit,topic,difficulty:"medium",question_text};let ca="A";arr.forEach((o,i)=>{q["option_"+L[i].toLowerCase()]=o.v;if(o.ok)ca=L[i];});q.correct_answer=ca;q.explanation=explanation;return q;}
const uniq=(qs)=>{const seen=new Set();return qs.filter(q=>{if(!q)return false;if(seen.has(q.question_text))return false;seen.add(q.question_text);return true;});};

const banks={
"ap-us-government":[
 {u:1,t:"Foundations",term:"Brutus No. 1",def:"an Anti-Federalist paper arguing a large republic would threaten liberty"},
 {u:1,t:"Foundations",term:"Federalist No. 51",def:"the essay arguing separation of powers and checks let ambition counteract ambition"},
 {u:1,t:"Foundations",term:"Federalist No. 70",def:"the essay arguing for a single energetic executive"},
 {u:1,t:"Foundations",term:"Federalist No. 78",def:"the essay defending an independent judiciary and judicial review"},
 {u:1,t:"Foundations",term:"the Declaration of Independence",def:"the 1776 document asserting natural rights and justifying separation from Britain"},
 {u:1,t:"Foundations",term:"participatory democracy",def:"a model emphasizing broad citizen participation in politics"},
 {u:1,t:"Foundations",term:"pluralist democracy",def:"a model where group competition shapes policy"},
 {u:1,t:"Foundations",term:"elite democracy",def:"a model where a small number of influential people make most decisions"},
 {u:2,t:"Branches",term:"McCulloch v. Maryland",def:"the case upholding implied powers and federal supremacy"},
 {u:2,t:"Branches",term:"United States v. Lopez",def:"the case limiting Congress's commerce-clause power"},
 {u:2,t:"Branches",term:"Marbury v. Madison",def:"the case establishing judicial review"},
 {u:2,t:"Branches",term:"the State of the Union",def:"the president's annual address to Congress on national priorities"},
 {u:2,t:"Branches",term:"a veto",def:"the president's formal rejection of a bill passed by Congress"},
 {u:2,t:"Branches",term:"appropriations",def:"the congressional process of setting government spending"},
 {u:2,t:"Branches",term:"entitlement spending",def:"mandatory spending determined by eligibility rules, like Social Security"},
 {u:2,t:"Branches",term:"the bureaucracy",def:"the agencies and civil servants that implement and enforce laws"},
 {u:3,t:"Civil Liberties",term:"Schenck v. United States",def:"the case allowing speech limits posing a clear and present danger"},
 {u:3,t:"Civil Liberties",term:"Tinker v. Des Moines",def:"the case protecting students' symbolic speech in schools"},
 {u:3,t:"Civil Liberties",term:"Gideon v. Wainwright",def:"the case guaranteeing the right to an attorney in criminal cases"},
 {u:3,t:"Civil Liberties",term:"Engel v. Vitale",def:"the case barring state-sponsored prayer in public schools"},
 {u:3,t:"Civil Liberties",term:"New York Times v. United States",def:"the case limiting prior restraint on the press"},
 {u:3,t:"Civil Rights",term:"Brown v. Board of Education",def:"the case ending segregation in public schools"},
 {u:3,t:"Civil Liberties",term:"McDonald v. Chicago",def:"the case incorporating the Second Amendment to the states"},
 {u:3,t:"Civil Liberties",term:"Wisconsin v. Yoder",def:"the case protecting free exercise of religion over compulsory schooling"},
 {u:3,t:"Civil Rights",term:"the Equal Protection Clause",def:"the Fourteenth Amendment guarantee against unequal treatment by states"},
 {u:3,t:"Civil Rights",term:"the Civil Rights Act of 1964",def:"the law banning discrimination in public accommodations and employment"},
 {u:3,t:"Civil Rights",term:"the Voting Rights Act of 1965",def:"the law banning racial discrimination in voting"},
 {u:3,t:"Civil Rights",term:"Title IX",def:"the law barring sex discrimination in federally funded education"},
 {u:4,t:"Ideologies",term:"Keynesian economics",def:"the view that government spending can stabilize the economy"},
 {u:4,t:"Ideologies",term:"supply-side economics",def:"the view that tax cuts spur growth by boosting production"},
 {u:4,t:"Ideologies",term:"monetary policy",def:"the Fed's control of money supply and interest rates"},
 {u:4,t:"Ideologies",term:"fiscal policy",def:"the government's use of taxing and spending to influence the economy"},
 {u:5,t:"Participation",term:"an open primary",def:"a primary in which any registered voter may participate"},
 {u:5,t:"Participation",term:"a caucus",def:"a local meeting where party members select candidates"},
 {u:5,t:"Participation",term:"prospective voting",def:"voting based on what a candidate promises to do"},
 {u:5,t:"Participation",term:"party realignment",def:"a lasting shift in the coalitions supporting the parties"},
 {u:5,t:"Participation",term:"a single-member district",def:"an electoral district that elects one representative, favoring two parties"},
],
"ap-psychology":[
 {u:1,t:"Biological Bases",term:"the somatic nervous system",def:"the division controlling voluntary skeletal muscle movement"},
 {u:1,t:"Biological Bases",term:"the parasympathetic nervous system",def:"the division that calms the body after arousal"},
 {u:1,t:"Biological Bases",term:"an fMRI",def:"a tool showing brain activity by tracking blood-oxygen flow"},
 {u:1,t:"Biological Bases",term:"the frontal lobe",def:"the brain region governing planning, judgment, and voluntary movement"},
 {u:1,t:"Biological Bases",term:"the occipital lobe",def:"the brain region primarily processing vision"},
 {u:1,t:"Biological Bases",term:"reuptake",def:"the reabsorption of neurotransmitters by the sending neuron"},
 {u:1,t:"Biological Bases",term:"neurogenesis",def:"the formation of new neurons, possible in the adult hippocampus"},
 {u:1,t:"Biological Bases",term:"endorphins",def:"neurotransmitters that relieve pain and produce pleasure"},
 {u:2,t:"Cognition",term:"flashbulb memory",def:"a vivid, emotionally charged memory of a significant event"},
 {u:2,t:"Cognition",term:"source amnesia",def:"recalling information but misremembering where it came from"},
 {u:2,t:"Cognition",term:"the serial position effect",def:"the tendency to best recall the first and last items in a list"},
 {u:2,t:"Cognition",term:"convergent thinking",def:"narrowing options to find the single best solution"},
 {u:2,t:"Cognition",term:"divergent thinking",def:"generating many possible solutions, associated with creativity"},
 {u:2,t:"Cognition",term:"the gambler's fallacy",def:"the false belief that past independent events affect future probabilities"},
 {u:2,t:"Cognition",term:"sensory memory",def:"the brief initial recording of sensory information"},
 {u:3,t:"Development & Learning",term:"the preoperational stage",def:"Piaget's stage marked by egocentrism and lack of conservation"},
 {u:3,t:"Development & Learning",term:"conservation",def:"understanding that quantity stays the same despite changes in shape"},
 {u:3,t:"Development & Learning",term:"scaffolding",def:"providing temporary support that is gradually removed as a learner gains skill"},
 {u:3,t:"Development & Learning",term:"a secure attachment",def:"a bond in which an infant uses a caregiver as a safe base"},
 {u:3,t:"Development & Learning",term:"authoritative parenting",def:"a style combining high demands with warmth and responsiveness"},
 {u:3,t:"Development & Learning",term:"a variable-interval schedule",def:"reinforcement after unpredictable time periods, yielding steady responding"},
 {u:3,t:"Development & Learning",term:"positive punishment",def:"adding an unpleasant stimulus to decrease a behavior"},
 {u:4,t:"Social & Personality",term:"normative social influence",def:"conforming to gain approval and avoid rejection"},
 {u:4,t:"Social & Personality",term:"informational social influence",def:"conforming because others are believed to be correct"},
 {u:4,t:"Social & Personality",term:"the just-world hypothesis",def:"the belief that people get what they deserve"},
 {u:4,t:"Social & Personality",term:"stereotype threat",def:"impaired performance from fear of confirming a negative group stereotype"},
 {u:4,t:"Social & Personality",term:"an out-group",def:"a group one does not identify with or belong to"},
 {u:4,t:"Social & Personality",term:"companionate love",def:"deep affection, trust, and commitment in a lasting relationship"},
 {u:5,t:"Mental Health",term:"generalized anxiety disorder",def:"a disorder of persistent, free-floating worry"},
 {u:5,t:"Mental Health",term:"major depressive disorder",def:"a mood disorder of prolonged sadness and loss of interest"},
 {u:5,t:"Mental Health",term:"dissociative identity disorder",def:"a disorder featuring two or more distinct identity states"},
 {u:5,t:"Mental Health",term:"anorexia nervosa",def:"an eating disorder of self-starvation and distorted body image"},
 {u:5,t:"Mental Health",term:"psychoanalysis",def:"a therapy aiming to bring unconscious conflicts into awareness"},
 {u:5,t:"Mental Health",term:"a negative symptom",def:"a schizophrenia symptom involving absence of normal function, like flat affect"},
 {u:5,t:"Mental Health",term:"electroconvulsive therapy",def:"a treatment using brief electrical stimulation for severe depression"},
],
"ap-human-geography":[
 {u:1,t:"Thinking Geographically",term:"distance decay",def:"the weakening of a phenomenon's effect as distance from its origin increases"},
 {u:1,t:"Thinking Geographically",term:"a vernacular region",def:"a region defined by people's informal perceptions, like 'the South'"},
 {u:1,t:"Thinking Geographically",term:"spatial association",def:"the degree to which two phenomena occur together in space"},
 {u:1,t:"Thinking Geographically",term:"remote sensing",def:"collecting data about Earth's surface from satellites or aircraft"},
 {u:2,t:"Population",term:"the demographic momentum",def:"continued population growth from a youthful age structure"},
 {u:2,t:"Population",term:"crude birth rate",def:"the number of live births per 1,000 people per year"},
 {u:2,t:"Population",term:"infant mortality rate",def:"the number of deaths of infants under one year per 1,000 births"},
 {u:2,t:"Population",term:"step migration",def:"migration in a series of smaller moves toward a final destination"},
 {u:2,t:"Population",term:"an ethnic enclave",def:"a neighborhood with a high concentration of one ethnic group"},
 {u:2,t:"Population",term:"the epidemiological transition",def:"the shift in leading causes of death as a society develops"},
 {u:3,t:"Culture",term:"stimulus diffusion",def:"the spread of an underlying idea that is then adapted locally"},
 {u:3,t:"Culture",term:"acculturation",def:"adopting some traits of another culture while keeping one's own"},
 {u:3,t:"Culture",term:"assimilation",def:"the full adoption of another culture, losing the original"},
 {u:3,t:"Culture",term:"a cultural hearth",def:"the place where a cultural trait originates and spreads from"},
 {u:3,t:"Culture",term:"toponym",def:"a place name that can reveal cultural history"},
 {u:4,t:"Political",term:"a stateless nation",def:"a national group without its own sovereign state"},
 {u:4,t:"Political",term:"an enclave",def:"a territory entirely surrounded by another state"},
 {u:4,t:"Political",term:"an exclave",def:"part of a state separated from the main territory"},
 {u:4,t:"Political",term:"irredentism",def:"a state's claim to territory in another state on cultural grounds"},
 {u:4,t:"Political",term:"a compact state",def:"a state whose territory is roughly circular, easing administration"},
 {u:4,t:"Political",term:"an elongated state",def:"a state with a long, narrow shape that complicates governance"},
 {u:5,t:"Agriculture",term:"the First Agricultural Revolution",def:"the Neolithic domestication of plants and animals"},
 {u:5,t:"Agriculture",term:"the Second Agricultural Revolution",def:"the mechanization and improved methods accompanying industrialization"},
 {u:5,t:"Agriculture",term:"pastoral nomadism",def:"extensive herding of animals across grazing lands"},
 {u:5,t:"Agriculture",term:"plantation agriculture",def:"large-scale commercial farming of a single cash crop"},
 {u:5,t:"Agriculture",term:"a feedlot",def:"a confined operation fattening livestock for market"},
 {u:6,t:"Cities",term:"the concentric zone model",def:"a model of a city as rings expanding outward from the CBD"},
 {u:6,t:"Cities",term:"the sector model",def:"a model of urban growth along wedges from the center"},
 {u:6,t:"Cities",term:"the multiple nuclei model",def:"a model of a city developing around several specialized centers"},
 {u:6,t:"Cities",term:"a edge city",def:"a suburban node of business and services outside the old downtown"},
 {u:6,t:"Cities",term:"filtering",def:"the process by which older housing passes to lower-income groups"},
 {u:6,t:"Cities",term:"a squatter settlement",def:"informal housing on land the occupants do not own"},
 {u:7,t:"Development",term:"world-systems theory",def:"a model dividing the world into core, periphery, and semi-periphery"},
 {u:7,t:"Development",term:"the periphery",def:"less-developed regions supplying raw materials and labor"},
 {u:7,t:"Development",term:"the quaternary sector",def:"knowledge-based services like research and information processing"},
 {u:7,t:"Development",term:"sustainable development",def:"meeting present needs without compromising future generations"},
],
"ap-environmental-science":[
 {u:1,t:"Ecosystems",term:"the carbon cycle",def:"the movement of carbon among the atmosphere, organisms, oceans, and rocks"},
 {u:1,t:"Ecosystems",term:"the phosphorus cycle",def:"the movement of phosphorus through rock, soil, water, and organisms with no gas phase"},
 {u:1,t:"Ecosystems",term:"gross primary productivity",def:"the total rate at which producers capture energy"},
 {u:1,t:"Ecosystems",term:"net primary productivity",def:"the energy producers store after their own respiration"},
 {u:1,t:"Ecosystems",term:"a food web",def:"the interconnected feeding relationships in an ecosystem"},
 {u:1,t:"Ecosystems",term:"a decomposer",def:"an organism that breaks down dead matter, recycling nutrients"},
 {u:2,t:"Biodiversity",term:"an indicator species",def:"a species whose health reflects the condition of its ecosystem"},
 {u:2,t:"Biodiversity",term:"an invasive species",def:"a non-native species that spreads and harms an ecosystem"},
 {u:2,t:"Biodiversity",term:"island biogeography",def:"the study of species richness on isolated habitats"},
 {u:2,t:"Biodiversity",term:"ecological tolerance",def:"the range of conditions an organism can survive"},
 {u:3,t:"Populations",term:"a survivorship curve",def:"a graph showing the proportion of individuals surviving at each age"},
 {u:3,t:"Populations",term:"exponential growth",def:"J-shaped growth occurring without limiting factors"},
 {u:3,t:"Populations",term:"logistic growth",def:"S-shaped growth that levels off at carrying capacity"},
 {u:3,t:"Populations",term:"the replacement-level fertility",def:"the fertility rate at which a population exactly replaces itself"},
 {u:4,t:"Earth Systems",term:"a cold front",def:"the leading edge of a cold air mass displacing warmer air"},
 {u:4,t:"Earth Systems",term:"the Coriolis effect",def:"the deflection of moving air and water due to Earth's rotation"},
 {u:4,t:"Earth Systems",term:"a tropical rainforest",def:"a biome of high rainfall, warmth, and great biodiversity"},
 {u:4,t:"Earth Systems",term:"a desert biome",def:"a biome defined by very low precipitation"},
 {u:4,t:"Earth Systems",term:"horizon A",def:"the topsoil layer rich in organic matter"},
 {u:5,t:"Land & Water",term:"overgrazing",def:"excessive grazing that degrades land and promotes desertification"},
 {u:5,t:"Land & Water",term:"desertification",def:"the degradation of once-fertile land into desert"},
 {u:5,t:"Land & Water",term:"aquaculture",def:"the farming of aquatic organisms like fish and shellfish"},
 {u:5,t:"Land & Water",term:"the tragedy of the commons",def:"the overuse of a shared resource by individuals acting in self-interest"},
 {u:5,t:"Land & Water",term:"monoculture",def:"growing a single crop over a large area"},
 {u:6,t:"Energy",term:"cogeneration",def:"capturing waste heat from electricity generation for additional use"},
 {u:6,t:"Energy",term:"a passive solar design",def:"using building design to capture solar heat without mechanical systems"},
 {u:6,t:"Energy",term:"biomass energy",def:"energy from burning organic material like wood or crops"},
 {u:6,t:"Energy",term:"a fuel cell",def:"a device generating electricity from a chemical reaction, often hydrogen"},
 {u:7,t:"Atmospheric Pollution",term:"a primary pollutant",def:"a pollutant emitted directly into the air"},
 {u:7,t:"Atmospheric Pollution",term:"a secondary pollutant",def:"a pollutant formed by reactions in the atmosphere"},
 {u:7,t:"Atmospheric Pollution",term:"the Clean Air Act",def:"the U.S. law regulating air pollutant emissions"},
 {u:8,t:"Aquatic Pollution",term:"a dead zone",def:"an oxygen-depleted area of water where most life cannot survive"},
 {u:8,t:"Aquatic Pollution",term:"thermal pollution",def:"the harmful warming of water by industrial discharge"},
 {u:8,t:"Aquatic Pollution",term:"the Clean Water Act",def:"the U.S. law regulating discharges into surface waters"},
 {u:9,t:"Global Change",term:"the carbon footprint",def:"the total greenhouse gases produced by an activity or entity"},
 {u:9,t:"Global Change",term:"carbon sequestration",def:"capturing and storing atmospheric carbon dioxide"},
],
"ap-english-language":[
 {u:7,t:"Style",term:"alliteration",def:"the repetition of initial consonant sounds in nearby words"},
 {u:7,t:"Style",term:"an allusion",def:"a brief reference to a well-known person, event, or work"},
 {u:7,t:"Style",term:"a rhetorical question",def:"a question asked for effect rather than an answer"},
 {u:7,t:"Style",term:"personification",def:"giving human qualities to non-human things"},
 {u:7,t:"Style",term:"asyndeton",def:"omitting conjunctions between words or clauses for effect"},
 {u:7,t:"Style",term:"polysyndeton",def:"using many conjunctions in close succession for effect"},
 {u:7,t:"Style",term:"a paradox",def:"a seemingly contradictory statement that reveals a truth"},
 {u:7,t:"Style",term:"an oxymoron",def:"a phrase combining contradictory terms"},
 {u:7,t:"Style",term:"a metonymy",def:"substituting a related term for the thing meant, like 'the crown' for monarchy"},
 {u:7,t:"Style",term:"synecdoche",def:"using a part to represent the whole, like 'hands' for workers"},
 {u:7,t:"Style",term:"verbal irony",def:"saying the opposite of what is meant"},
 {u:7,t:"Style",term:"situational irony",def:"a contrast between what is expected and what occurs"},
 {u:7,t:"Style",term:"dramatic irony",def:"when the audience knows something the characters do not"},
 {u:7,t:"Style",term:"a motif",def:"a recurring element that develops a theme"},
 {u:7,t:"Style",term:"juxtaposition",def:"placing contrasting ideas close together for effect"},
 {u:7,t:"Style",term:"parallel structure",def:"using matching grammatical forms for related ideas"},
 {u:7,t:"Style",term:"a periodic structure",def:"withholding the main clause until the sentence's end"},
 {u:7,t:"Style",term:"anecdote",def:"a brief story used to illustrate a point"},
 {u:1,t:"Rhetorical Situation",term:"the occasion",def:"the time and place or event prompting a text"},
 {u:1,t:"Rhetorical Situation",term:"the speaker",def:"the voice or persona presenting a text"},
 {u:1,t:"Rhetorical Situation",term:"a constraint",def:"a factor limiting how a writer can respond to a situation"},
 {u:3,t:"Claims & Evidence",term:"a rebuttal",def:"a response refuting an opposing argument"},
 {u:3,t:"Claims & Evidence",term:"empirical evidence",def:"support based on observation or experiment"},
 {u:3,t:"Claims & Evidence",term:"anecdotal evidence",def:"support based on personal accounts rather than data"},
 {u:5,t:"Reasoning",term:"inductive reasoning",def:"drawing general conclusions from specific examples"},
 {u:5,t:"Reasoning",term:"deductive reasoning",def:"applying a general principle to reach a specific conclusion"},
 {u:5,t:"Reasoning",term:"a syllogism",def:"a deductive argument with two premises and a conclusion"},
 {u:5,t:"Reasoning",term:"cause and effect organization",def:"structuring an argument by showing how one thing leads to another"},
 {u:5,t:"Reasoning",term:"compare and contrast organization",def:"structuring writing by examining similarities and differences"},
 {u:9,t:"Fallacies",term:"equivocation",def:"using a word with two meanings to mislead"},
 {u:9,t:"Fallacies",term:"a non sequitur",def:"a conclusion that does not follow from its premises"},
 {u:9,t:"Fallacies",term:"a tu quoque",def:"dismissing criticism by accusing the critic of hypocrisy"},
],
"ap-world-history":[
 {u:1,t:"Global Tapestry",term:"the Khmer Empire",def:"a Southeast Asian state known for Angkor Wat"},
 {u:1,t:"Global Tapestry",term:"the Song dynasty",def:"a Chinese dynasty noted for commercial growth and innovation"},
 {u:1,t:"Global Tapestry",term:"the Mamluk Sultanate",def:"a state ruled by former enslaved soldiers in Egypt"},
 {u:1,t:"Global Tapestry",term:"the Holy Roman Empire",def:"a fragmented political entity in central Europe"},
 {u:1,t:"Global Tapestry",term:"the caste system",def:"the hereditary social hierarchy of South Asia"},
 {u:2,t:"Networks",term:"the Trans-Saharan trade",def:"caravan routes carrying gold and salt across the Sahara"},
 {u:2,t:"Networks",term:"a diaspora community",def:"a group of merchants settled far from their homeland along trade routes"},
 {u:2,t:"Networks",term:"the dhow",def:"an Arab sailing vessel used in Indian Ocean trade"},
 {u:2,t:"Networks",term:"the compass",def:"a Chinese navigational invention that spread along trade routes"},
 {u:3,t:"Land-Based Empires",term:"the Mughal Empire",def:"a Muslim empire ruling much of South Asia"},
 {u:3,t:"Land-Based Empires",term:"the Ottoman Empire",def:"a long-lived Turkish Muslim empire centered on Anatolia"},
 {u:3,t:"Land-Based Empires",term:"the Qing dynasty",def:"the last imperial dynasty of China, founded by the Manchus"},
 {u:3,t:"Land-Based Empires",term:"divine right",def:"the doctrine that a monarch's authority comes directly from God"},
 {u:4,t:"Transoceanic",term:"the Atlantic slave trade",def:"the forced transport of millions of Africans to the Americas"},
 {u:4,t:"Transoceanic",term:"the casta system",def:"the racial hierarchy of colonial Spanish America"},
 {u:4,t:"Transoceanic",term:"the Spanish Armada",def:"the fleet whose 1588 defeat marked Spain's naval decline"},
 {u:4,t:"Transoceanic",term:"the Atlantic system",def:"the interconnected trade linking Europe, Africa, and the Americas"},
 {u:5,t:"Revolutions",term:"the American Revolution",def:"the colonial revolt that created the United States"},
 {u:5,t:"Revolutions",term:"the French Revolution",def:"the upheaval that overthrew the French monarchy"},
 {u:5,t:"Revolutions",term:"the Latin American revolutions",def:"the independence movements led largely by creole elites"},
 {u:5,t:"Revolutions",term:"the Industrial Revolution",def:"the shift to mechanized factory production beginning in Britain"},
 {u:5,t:"Revolutions",term:"socialism",def:"an ideology favoring collective or state ownership of production"},
 {u:6,t:"Industrialization",term:"imperialism",def:"the policy of extending control over foreign territories"},
 {u:6,t:"Industrialization",term:"the Berlin Conference",def:"the 1884–85 meeting that formalized the European partition of Africa"},
 {u:6,t:"Industrialization",term:"the Sepoy Rebellion",def:"the 1857 Indian uprising against British rule"},
 {u:6,t:"Industrialization",term:"the Taiping Rebellion",def:"a massive mid-1800s civil war in Qing China"},
 {u:7,t:"Global Conflict",term:"World War I",def:"the 1914–18 global conflict marked by trench warfare"},
 {u:7,t:"Global Conflict",term:"the Russian Revolution",def:"the 1917 upheaval that brought the Bolsheviks to power"},
 {u:7,t:"Global Conflict",term:"the Great Depression",def:"the severe global economic downturn of the 1930s"},
 {u:7,t:"Global Conflict",term:"World War II",def:"the 1939–45 global conflict against the Axis powers"},
 {u:8,t:"Cold War",term:"the Cuban Missile Crisis",def:"the 1962 Cold War standoff over Soviet missiles in Cuba"},
 {u:8,t:"Cold War",term:"the Cultural Revolution",def:"Mao's campaign to reassert communist ideology in China"},
 {u:8,t:"Cold War",term:"the breakup of the Soviet Union",def:"the 1991 dissolution that ended the Cold War"},
 {u:8,t:"Cold War",term:"apartheid",def:"South Africa's system of legalized racial segregation"},
 {u:9,t:"Globalization",term:"the European Union",def:"a supranational organization integrating European economies and politics"},
 {u:9,t:"Globalization",term:"the Green Revolution",def:"the spread of high-yield agriculture to feed growing populations"},
],
};
let total=0;
for(const [subject,entries] of Object.entries(banks)){const qs=shuffle(build(entries));fs.writeFileSync(`${OUT}${subject}-fact3-${seed}.json`,JSON.stringify({subject,questions:qs},null,1));console.log(`${subject}: ${entries.length} facts -> ${qs.length} q`);total+=qs.length;}
console.log("total:",total);
