// Fact-bank generator for AP content subjects (authored by Claude, no API).
// Each entry {u: unit, t: topic, term, def} yields a forward (term->def) and a
// reverse (def->term) MCQ, with distractors drawn from sibling entries.
// Usage: node content-gen.mjs <seed>. Output ap-<subject>-fact<seed>.json (upload.mjs dedupes).

import fs from "node:fs";
const OUT = new URL(".", import.meta.url).pathname;
function mulberry32(a){return function(){a|=0;a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296;};}
const seed=Number(process.argv[2]||1);const rnd=mulberry32(seed*7919+13);
const shuffle=(arr)=>{const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const sample=(arr,n,not)=>shuffle(arr.filter(x=>x!==not)).slice(0,n);

function build(entries){
  const qs=[];
  const defs=entries.map(e=>e.def);
  const terms=entries.map(e=>e.term);
  for(const e of entries){
    // forward: term -> definition
    const fd=sample(defs,3,e.def);
    if(fd.length===3) qs.push(opt(e.u,e.t,`In AP terms, ${e.term} is best defined as:`,e.def,fd,`${e.term}: ${e.def}`));
    // reverse: definition -> term
    const rt=sample(terms,3,e.term);
    if(rt.length===3) qs.push(opt(e.u,e.t,`Which term is defined as: "${e.def}"?`,e.term,rt,`${e.term} — ${e.def}`));
  }
  return uniq(qs);
}
function opt(unit,topic,question_text,correct,distractors,explanation){
  const chosen=[String(correct)];for(const d of distractors){const s=String(d);if(!chosen.includes(s))chosen.push(s);if(chosen.length===4)break;}
  if(chosen.length<4)return null;
  const arr=shuffle(chosen.map((v,i)=>({v,ok:i===0})));const L=["A","B","C","D"];const q={unit,topic,difficulty:"medium",question_text};let ca="A";
  arr.forEach((o,i)=>{q["option_"+L[i].toLowerCase()]=o.v;if(o.ok)ca=L[i];});q.correct_answer=ca;q.explanation=explanation;return q;
}
const uniq=(qs)=>{const seen=new Set();return qs.filter(q=>{if(!q)return false;if(seen.has(q.question_text))return false;seen.add(q.question_text);return true;});};

const banks={
"ap-us-government":[
 {u:1,t:"Foundations",term:"federalism",def:"the division of power between a national government and state governments"},
 {u:1,t:"Foundations",term:"popular sovereignty",def:"the principle that government authority derives from the consent of the people"},
 {u:1,t:"Foundations",term:"separation of powers",def:"the division of government into legislative, executive, and judicial branches"},
 {u:1,t:"Foundations",term:"checks and balances",def:"the system by which each branch can limit the powers of the others"},
 {u:1,t:"Foundations",term:"judicial review",def:"the power of courts to declare laws or actions unconstitutional"},
 {u:1,t:"Foundations",term:"a faction",def:"a group united by a common interest that may threaten the rights of others (per Federalist 10)"},
 {u:1,t:"Foundations",term:"the supremacy clause",def:"the constitutional provision making federal law the supreme law of the land"},
 {u:1,t:"Foundations",term:"the necessary and proper clause",def:"the elastic clause allowing Congress to make laws to carry out its enumerated powers"},
 {u:1,t:"Foundations",term:"a block grant",def:"federal money given to states with broad discretion within a general policy area"},
 {u:1,t:"Foundations",term:"a categorical grant",def:"federal money given to states for a specific purpose with strict conditions"},
 {u:1,t:"Foundations",term:"reserved powers",def:"powers kept by the states under the Tenth Amendment"},
 {u:1,t:"Foundations",term:"concurrent powers",def:"powers shared by both national and state governments, such as taxation"},
 {u:1,t:"Foundations",term:"a confederation",def:"a system in which states hold most power and the central government is weak"},
 {u:2,t:"Branches",term:"a filibuster",def:"a Senate tactic of prolonged debate used to delay or block a vote"},
 {u:2,t:"Branches",term:"cloture",def:"a Senate procedure to end a filibuster, requiring 60 votes"},
 {u:2,t:"Branches",term:"logrolling",def:"the trading of votes among legislators to support each other's bills"},
 {u:2,t:"Branches",term:"a pocket veto",def:"the indirect rejection of a bill by the president taking no action while Congress is adjourned"},
 {u:2,t:"Branches",term:"executive privilege",def:"the president's claimed right to withhold certain communications from Congress and courts"},
 {u:2,t:"Branches",term:"an iron triangle",def:"the stable relationship among an agency, a committee, and an interest group in policymaking"},
 {u:2,t:"Branches",term:"gerrymandering",def:"drawing district boundaries to favor a party or group"},
 {u:2,t:"Branches",term:"impeachment",def:"the formal charging of an official with misconduct by the House of Representatives"},
 {u:2,t:"Branches",term:"a bully pulpit",def:"the president's use of public visibility to promote an agenda"},
 {u:2,t:"Branches",term:"oversight",def:"Congress's review and monitoring of the executive branch and agencies"},
 {u:3,t:"Civil Liberties",term:"selective incorporation",def:"applying Bill of Rights protections to the states through the Fourteenth Amendment"},
 {u:3,t:"Civil Liberties",term:"the establishment clause",def:"the First Amendment provision barring government endorsement of religion"},
 {u:3,t:"Civil Liberties",term:"the free exercise clause",def:"the First Amendment protection of the right to practice one's religion"},
 {u:3,t:"Civil Liberties",term:"prior restraint",def:"government censorship of material before it is published"},
 {u:3,t:"Civil Liberties",term:"due process",def:"the constitutional requirement that government act fairly and follow legal procedures"},
 {u:3,t:"Civil Liberties",term:"the exclusionary rule",def:"the rule barring illegally obtained evidence from being used in court"},
 {u:3,t:"Civil Liberties",term:"symbolic speech",def:"nonverbal expression, such as wearing armbands, protected by the First Amendment"},
 {u:4,t:"Ideologies",term:"political socialization",def:"the process by which people develop their political beliefs and values"},
 {u:4,t:"Ideologies",term:"party identification",def:"a person's psychological attachment to a political party"},
 {u:4,t:"Ideologies",term:"a random sample",def:"a poll sample in which every member of the population has an equal chance of selection"},
 {u:4,t:"Ideologies",term:"sampling error",def:"the natural variability between a sample's result and the true population value"},
 {u:4,t:"Ideologies",term:"liberalism",def:"an ideology generally favoring government action to promote equality and social welfare"},
 {u:4,t:"Ideologies",term:"conservatism",def:"an ideology generally favoring limited government, free markets, and tradition"},
 {u:5,t:"Participation",term:"the incumbency advantage",def:"the tendency of current officeholders to win reelection at high rates"},
 {u:5,t:"Participation",term:"a swing state",def:"a state that could be won by either major party and attracts heavy campaigning"},
 {u:5,t:"Participation",term:"a super PAC",def:"a group that may raise and spend unlimited money independently of campaigns"},
 {u:5,t:"Participation",term:"a linkage institution",def:"a channel such as parties or media that connects citizens to government"},
 {u:5,t:"Participation",term:"lobbying",def:"attempting to influence policymakers on behalf of an interest"},
 {u:5,t:"Participation",term:"voter turnout",def:"the proportion of eligible citizens who actually vote in an election"},
],
"ap-psychology":[
 {u:1,t:"Biological Bases",term:"a neuron",def:"a nerve cell that transmits information through electrical and chemical signals"},
 {u:1,t:"Biological Bases",term:"a synapse",def:"the gap between neurons across which neurotransmitters carry signals"},
 {u:1,t:"Biological Bases",term:"the hippocampus",def:"the brain structure central to forming new long-term explicit memories"},
 {u:1,t:"Biological Bases",term:"the amygdala",def:"the limbic structure that processes fear and other strong emotions"},
 {u:1,t:"Biological Bases",term:"dopamine",def:"the neurotransmitter associated with reward, motivation, and movement"},
 {u:1,t:"Biological Bases",term:"the medulla",def:"the brainstem structure controlling vital functions like breathing and heartbeat"},
 {u:1,t:"Biological Bases",term:"plasticity",def:"the brain's ability to change and reorganize, greatest in early life"},
 {u:1,t:"Biological Bases",term:"the sympathetic nervous system",def:"the division that arouses the body for fight-or-flight responses"},
 {u:1,t:"Biological Bases",term:"the corpus callosum",def:"the band of fibers connecting the brain's two hemispheres"},
 {u:2,t:"Cognition",term:"the availability heuristic",def:"judging likelihood by how easily examples come to mind"},
 {u:2,t:"Cognition",term:"the representativeness heuristic",def:"judging probability by similarity to a prototype, often ignoring base rates"},
 {u:2,t:"Cognition",term:"confirmation bias",def:"the tendency to seek information that supports existing beliefs"},
 {u:2,t:"Cognition",term:"a schema",def:"a mental framework that organizes and interprets information"},
 {u:2,t:"Cognition",term:"chunking",def:"grouping items into meaningful units to expand short-term memory"},
 {u:2,t:"Cognition",term:"the misinformation effect",def:"the distortion of memory by misleading post-event information"},
 {u:2,t:"Cognition",term:"functional fixedness",def:"the inability to see an object used in a way other than its usual function"},
 {u:2,t:"Cognition",term:"semantic memory",def:"memory for general knowledge and facts"},
 {u:3,t:"Development & Learning",term:"assimilation",def:"fitting new information into an existing schema"},
 {u:3,t:"Development & Learning",term:"accommodation",def:"modifying a schema to incorporate new information"},
 {u:3,t:"Development & Learning",term:"object permanence",def:"understanding that objects continue to exist when out of sight"},
 {u:3,t:"Development & Learning",term:"negative reinforcement",def:"removing an unpleasant stimulus to increase a behavior"},
 {u:3,t:"Development & Learning",term:"shaping",def:"reinforcing successive approximations toward a target behavior"},
 {u:3,t:"Development & Learning",term:"observational learning",def:"learning by watching and imitating others"},
 {u:3,t:"Development & Learning",term:"a critical period",def:"a window when an organism is especially primed to acquire a skill"},
 {u:4,t:"Social & Personality",term:"the fundamental attribution error",def:"overemphasizing personality and underestimating situation in explaining others' behavior"},
 {u:4,t:"Social & Personality",term:"cognitive dissonance",def:"the discomfort from holding conflicting attitudes, motivating attitude change"},
 {u:4,t:"Social & Personality",term:"groupthink",def:"poor decision-making from a group's desire for harmony over critical evaluation"},
 {u:4,t:"Social & Personality",term:"the bystander effect",def:"the reduced likelihood of helping when others are present"},
 {u:4,t:"Social & Personality",term:"conformity",def:"adjusting one's behavior or thinking to match group norms"},
 {u:4,t:"Social & Personality",term:"the mere exposure effect",def:"increased liking for stimuli from repeated exposure"},
 {u:4,t:"Social & Personality",term:"an internal locus of control",def:"the belief that one controls one's own outcomes through one's actions"},
 {u:5,t:"Mental Health",term:"a phobia",def:"an intense, irrational fear of a specific object or situation"},
 {u:5,t:"Mental Health",term:"the diathesis-stress model",def:"the view that disorders arise from a predisposition activated by stress"},
 {u:5,t:"Mental Health",term:"systematic desensitization",def:"a therapy pairing gradual exposure to a fear with relaxation"},
 {u:5,t:"Mental Health",term:"comorbidity",def:"the presence of two or more disorders in the same person"},
 {u:5,t:"Mental Health",term:"cognitive-behavioral therapy",def:"a treatment that changes maladaptive thoughts and behaviors"},
 {u:5,t:"Mental Health",term:"the biopsychosocial approach",def:"explaining behavior through biological, psychological, and social factors together"},
],
"ap-human-geography":[
 {u:1,t:"Thinking Geographically",term:"a formal region",def:"an area defined by a shared uniform characteristic"},
 {u:1,t:"Thinking Geographically",term:"a functional region",def:"an area organized around a central node with connections decreasing outward"},
 {u:1,t:"Thinking Geographically",term:"a perceptual region",def:"an area defined by people's shared feelings or perceptions"},
 {u:1,t:"Thinking Geographically",term:"absolute location",def:"a place's exact position given by coordinates"},
 {u:1,t:"Thinking Geographically",term:"relative location",def:"a place's position described in relation to other places"},
 {u:1,t:"Thinking Geographically",term:"time-space compression",def:"the reduction in time it takes to connect distant places due to technology"},
 {u:1,t:"Thinking Geographically",term:"a cartogram",def:"a map that distorts area to represent a data variable like population"},
 {u:2,t:"Population",term:"physiological density",def:"the number of people per unit of arable land"},
 {u:2,t:"Population",term:"the demographic transition",def:"the shift in birth and death rates as a society develops"},
 {u:2,t:"Population",term:"the total fertility rate",def:"the average number of children a woman is expected to have"},
 {u:2,t:"Population",term:"chain migration",def:"migration of people to where relatives or members of their group have settled"},
 {u:2,t:"Population",term:"a refugee",def:"a person who flees their country due to persecution or conflict"},
 {u:2,t:"Population",term:"remittances",def:"money sent by migrant workers back to their home country"},
 {u:2,t:"Population",term:"an anti-natalist policy",def:"a government policy aimed at reducing birth rates"},
 {u:3,t:"Culture",term:"relocation diffusion",def:"the spread of culture through the physical movement of people"},
 {u:3,t:"Culture",term:"a lingua franca",def:"a common language adopted for communication between different groups"},
 {u:3,t:"Culture",term:"a universalizing religion",def:"a religion that actively seeks converts across cultures"},
 {u:3,t:"Culture",term:"an ethnic religion",def:"a religion tied to a particular people and place that does not seek converts"},
 {u:3,t:"Culture",term:"ethnocentrism",def:"judging other cultures by the standards of one's own"},
 {u:3,t:"Culture",term:"cultural convergence",def:"cultures becoming more similar through increased contact"},
 {u:4,t:"Political",term:"a unitary state",def:"a state that concentrates power in a central national government"},
 {u:4,t:"Political",term:"devolution",def:"the transfer of power from a central government to regional governments"},
 {u:4,t:"Political",term:"a perforated state",def:"a state that completely surrounds another state's territory"},
 {u:4,t:"Political",term:"a buffer state",def:"a country located between two rival powers, reducing direct conflict"},
 {u:4,t:"Political",term:"balkanization",def:"the fragmentation of a region into smaller, often hostile units"},
 {u:4,t:"Political",term:"self-determination",def:"the right of peoples to govern themselves and form their own states"},
 {u:5,t:"Agriculture",term:"a food desert",def:"an area with limited access to affordable, nutritious food"},
 {u:5,t:"Agriculture",term:"double cropping",def:"harvesting two crops from the same land in a single year"},
 {u:5,t:"Agriculture",term:"the von Thünen model",def:"a model arranging agricultural land use in rings based on transport cost"},
 {u:5,t:"Agriculture",term:"extensive agriculture",def:"farming using large land areas with relatively low inputs"},
 {u:6,t:"Cities",term:"a primate city",def:"a city far larger than any other, dominating a country"},
 {u:6,t:"Cities",term:"a megalopolis",def:"a continuous chain of metropolitan areas"},
 {u:6,t:"Cities",term:"gentrification",def:"the renovation of neighborhoods that often displaces lower-income residents"},
 {u:6,t:"Cities",term:"the central business district",def:"the commercial core of a city with the highest land values"},
 {u:6,t:"Cities",term:"counter-urbanization",def:"the movement of people from urban areas to smaller towns or rural areas"},
 {u:7,t:"Development",term:"the brain drain",def:"the emigration of highly skilled or educated people from a country"},
 {u:7,t:"Development",term:"the Human Development Index",def:"a composite measure of income, life expectancy, and education"},
 {u:7,t:"Development",term:"a core region",def:"an advanced economy that dominates the global economy in world-systems theory"},
 {u:7,t:"Development",term:"microfinance",def:"small loans to low-income entrepreneurs lacking access to traditional banking"},
],
"ap-environmental-science":[
 {u:1,t:"Ecosystems",term:"a keystone species",def:"a species with a disproportionately large effect on its ecosystem"},
 {u:1,t:"Ecosystems",term:"a producer",def:"an organism that makes its own food through photosynthesis or chemosynthesis"},
 {u:1,t:"Ecosystems",term:"nitrification",def:"the bacterial conversion of ammonia into nitrites and nitrates usable by plants"},
 {u:1,t:"Ecosystems",term:"primary succession",def:"ecological succession beginning on bare rock with no soil"},
 {u:1,t:"Ecosystems",term:"the 10% rule",def:"the principle that about 10% of energy transfers between trophic levels"},
 {u:1,t:"Ecosystems",term:"mutualism",def:"a symbiotic relationship in which both organisms benefit"},
 {u:2,t:"Biodiversity",term:"genetic diversity",def:"the variety of genes within a species that aids adaptation"},
 {u:2,t:"Biodiversity",term:"habitat fragmentation",def:"the breaking of habitats into isolated patches, reducing gene flow"},
 {u:2,t:"Biodiversity",term:"species richness",def:"the number of different species in a community"},
 {u:3,t:"Populations",term:"carrying capacity",def:"the maximum population size an environment can sustainably support"},
 {u:3,t:"Populations",term:"an r-selected species",def:"a species producing many offspring with little parental care"},
 {u:3,t:"Populations",term:"a density-dependent factor",def:"a limiting factor whose effect intensifies as population density rises"},
 {u:4,t:"Earth Systems",term:"the albedo effect",def:"a surface's ability to reflect solar radiation"},
 {u:4,t:"Earth Systems",term:"a rain shadow",def:"the dry area on the leeward side of a mountain range"},
 {u:4,t:"Earth Systems",term:"El Niño",def:"the warm phase of ENSO that weakens upwelling off South America"},
 {u:4,t:"Earth Systems",term:"the greenhouse effect",def:"the trapping of heat in the atmosphere by greenhouse gases"},
 {u:5,t:"Land & Water",term:"salinization",def:"the buildup of salts in soil from evaporating irrigation water"},
 {u:5,t:"Land & Water",term:"contour plowing",def:"plowing across a slope to reduce soil erosion and runoff"},
 {u:5,t:"Land & Water",term:"integrated pest management",def:"combining biological, cultural, and limited chemical pest controls"},
 {u:5,t:"Land & Water",term:"sustainable yield",def:"harvesting at a rate that does not exceed natural replenishment"},
 {u:6,t:"Energy",term:"a capacity factor",def:"the ratio of a plant's actual energy output to its maximum possible output"},
 {u:6,t:"Energy",term:"geothermal energy",def:"energy harnessed from heat within the Earth"},
 {u:6,t:"Energy",term:"nuclear fission",def:"splitting heavy atomic nuclei to release heat for electricity"},
 {u:7,t:"Atmospheric Pollution",term:"a thermal inversion",def:"a layer of warm air over cool air that traps pollutants near the ground"},
 {u:7,t:"Atmospheric Pollution",term:"photochemical smog",def:"smog formed when VOCs and NOx react in sunlight"},
 {u:7,t:"Atmospheric Pollution",term:"acid rain",def:"precipitation acidified by sulfur and nitrogen oxide emissions"},
 {u:8,t:"Aquatic Pollution",term:"cultural eutrophication",def:"human-caused nutrient enrichment of water causing algal blooms and oxygen loss"},
 {u:8,t:"Aquatic Pollution",term:"biomagnification",def:"the increasing concentration of toxins up a food chain"},
 {u:8,t:"Aquatic Pollution",term:"point-source pollution",def:"pollution from a single, identifiable source"},
 {u:8,t:"Aquatic Pollution",term:"biochemical oxygen demand",def:"the oxygen consumed by microbes decomposing organic matter in water"},
 {u:9,t:"Global Change",term:"ocean acidification",def:"the lowering of ocean pH as it absorbs excess atmospheric CO2"},
 {u:9,t:"Global Change",term:"a positive feedback loop",def:"a process that amplifies a change, such as melting ice lowering albedo"},
 {u:9,t:"Global Change",term:"climate mitigation",def:"actions that reduce the causes of climate change, such as cutting emissions"},
 {u:9,t:"Global Change",term:"coral bleaching",def:"the loss of symbiotic algae from corals due to stress such as warming"},
],
"ap-english-language":[
 {u:1,t:"Rhetorical Situation",term:"exigence",def:"the issue or urgency that prompts a writer to respond"},
 {u:1,t:"Rhetorical Situation",term:"ethos",def:"a rhetorical appeal based on the speaker's credibility and character"},
 {u:1,t:"Rhetorical Situation",term:"pathos",def:"a rhetorical appeal to the audience's emotions"},
 {u:1,t:"Rhetorical Situation",term:"logos",def:"a rhetorical appeal based on logic and evidence"},
 {u:1,t:"Rhetorical Situation",term:"kairos",def:"the opportune timing and context of a rhetorical message"},
 {u:5,t:"Reasoning",term:"a warrant",def:"the underlying assumption connecting evidence to a claim"},
 {u:5,t:"Reasoning",term:"a concession",def:"acknowledging a valid point made by the opposing side"},
 {u:5,t:"Reasoning",term:"a rebuttal",def:"a response that refutes an opposing argument"},
 {u:5,t:"Reasoning",term:"a counterargument",def:"an opposing position that a writer presents and responds to"},
 {u:5,t:"Reasoning",term:"a qualifier",def:"a word like 'most' or 'often' that limits a claim to make it more defensible"},
 {u:7,t:"Style",term:"anaphora",def:"the repetition of a word at the beginning of successive clauses"},
 {u:7,t:"Style",term:"parallelism",def:"the use of the same grammatical form for related ideas in a series"},
 {u:7,t:"Style",term:"antithesis",def:"the juxtaposition of contrasting ideas in balanced structure"},
 {u:7,t:"Style",term:"a euphemism",def:"a mild or indirect word substituted for one considered harsh"},
 {u:7,t:"Style",term:"understatement",def:"deliberately representing something as less significant than it is"},
 {u:7,t:"Style",term:"hyperbole",def:"deliberate exaggeration for emphasis or effect"},
 {u:7,t:"Style",term:"juxtaposition",def:"placing two elements side by side to highlight contrast"},
 {u:7,t:"Style",term:"colloquial diction",def:"informal, conversational word choice"},
 {u:7,t:"Style",term:"a periodic sentence",def:"a sentence that delays its main idea until the end for emphasis"},
 {u:7,t:"Style",term:"a cumulative sentence",def:"a sentence stating its main idea first, followed by modifying details"},
 {u:9,t:"Fallacies",term:"a straw man",def:"misrepresenting an opponent's argument to make it easier to attack"},
 {u:9,t:"Fallacies",term:"a slippery slope",def:"claiming one step will inevitably lead to extreme consequences without justification"},
 {u:9,t:"Fallacies",term:"an ad hominem",def:"attacking the person rather than their argument"},
 {u:9,t:"Fallacies",term:"begging the question",def:"an argument that assumes the truth of its own conclusion"},
 {u:9,t:"Fallacies",term:"a hasty generalization",def:"drawing a broad conclusion from too few examples"},
 {u:9,t:"Fallacies",term:"a false analogy",def:"comparing two things that differ in ways crucial to the conclusion"},
 {u:9,t:"Fallacies",term:"the bandwagon fallacy",def:"claiming something is true because many people believe it"},
 {u:9,t:"Fallacies",term:"post hoc reasoning",def:"assuming that because one event followed another, the first caused the second"},
 {u:9,t:"Fallacies",term:"a false dilemma",def:"presenting only two options when more exist"},
],
"ap-world-history":[
 {u:2,t:"Networks of Exchange",term:"the Silk Roads",def:"overland trade routes connecting East Asia to the Mediterranean"},
 {u:2,t:"Networks of Exchange",term:"a caravanserai",def:"a roadside inn providing shelter for merchants along trade routes"},
 {u:2,t:"Networks of Exchange",term:"the Pax Mongolica",def:"the period of stability under the Mongols that boosted Eurasian trade"},
 {u:1,t:"Global Tapestry",term:"the bhakti movement",def:"a Hindu devotional movement emphasizing personal devotion accessible to all castes"},
 {u:1,t:"Global Tapestry",term:"the mandate of heaven",def:"the Chinese principle legitimizing a ruler's authority through divine approval"},
 {u:1,t:"Global Tapestry",term:"feudalism",def:"a system of reciprocal obligations between lords and vassals"},
 {u:3,t:"Land-Based Empires",term:"the devshirme",def:"the Ottoman system of recruiting Christian boys for state and military service"},
 {u:3,t:"Land-Based Empires",term:"the millet system",def:"the Ottoman policy granting religious communities self-governance"},
 {u:3,t:"Land-Based Empires",term:"absolutism",def:"a system in which a monarch holds total, centralized power"},
 {u:4,t:"Transoceanic",term:"the Columbian Exchange",def:"the transfer of plants, animals, and diseases between the hemispheres after 1492"},
 {u:4,t:"Transoceanic",term:"mercantilism",def:"an economic theory equating national wealth with gold and a favorable trade balance"},
 {u:4,t:"Transoceanic",term:"the Middle Passage",def:"the brutal transatlantic voyage transporting enslaved Africans to the Americas"},
 {u:4,t:"Transoceanic",term:"the encomienda",def:"a Spanish labor system granting colonists the right to demand indigenous labor"},
 {u:4,t:"Transoceanic",term:"a joint-stock company",def:"a business pooling investors' capital to fund overseas ventures and spread risk"},
 {u:5,t:"Revolutions",term:"the Enlightenment",def:"an intellectual movement emphasizing reason, natural rights, and progress"},
 {u:5,t:"Revolutions",term:"nationalism",def:"strong identification with and devotion to one's nation"},
 {u:5,t:"Revolutions",term:"liberalism",def:"a 19th-century ideology emphasizing individual rights and constitutional government"},
 {u:5,t:"Revolutions",term:"the Haitian Revolution",def:"the first successful large-scale slave revolt, creating an independent nation"},
 {u:6,t:"Industrialization",term:"the factory system",def:"a system concentrating workers under strict schedules and division of labor"},
 {u:6,t:"Industrialization",term:"social Darwinism",def:"the misapplication of natural selection to justify imperialism and racial hierarchy"},
 {u:6,t:"Industrialization",term:"the second industrial revolution",def:"late-1800s industrial growth driven by steel, chemicals, and electricity"},
 {u:7,t:"Global Conflict",term:"appeasement",def:"the policy of conceding to an aggressor's demands to avoid conflict"},
 {u:7,t:"Global Conflict",term:"total war",def:"war mobilizing a nation's entire population and economy"},
 {u:7,t:"Global Conflict",term:"fascism",def:"an ideology of extreme nationalism and authoritarian, anti-democratic rule"},
 {u:7,t:"Global Conflict",term:"the Treaty of Versailles",def:"the 1919 settlement that imposed harsh terms on Germany after WWI"},
 {u:8,t:"Cold War",term:"containment",def:"the U.S. Cold War policy of stopping the spread of communism"},
 {u:8,t:"Cold War",term:"the Non-Aligned Movement",def:"nations refusing to formally ally with either Cold War superpower"},
 {u:8,t:"Cold War",term:"decolonization",def:"the process by which colonies gained independence after WWII"},
 {u:8,t:"Cold War",term:"the Truman Doctrine",def:"the U.S. pledge to support nations resisting communism"},
 {u:9,t:"Globalization",term:"globalization",def:"the increasing interconnection of economies and cultures worldwide"},
 {u:9,t:"Globalization",term:"outsourcing",def:"relocating production to where labor and costs are lower"},
 {u:9,t:"Globalization",term:"a multinational corporation",def:"a company conducting business across multiple countries"},
],
};

let totalWritten = 0;
for(const [subject,entries] of Object.entries(banks)){
  const qs=shuffle(build(entries));
  fs.writeFileSync(`${OUT}${subject}-fact${seed}.json`,JSON.stringify({subject,questions:qs},null,1));
  console.log(`${subject}: ${entries.length} facts -> ${qs.length} questions`);
  totalWritten+=qs.length;
}
console.log("total:",totalWritten);
