// Sixth fact-bank (authored by Claude, no API). New terms for all 6 content subjects.
import fs from "node:fs";
const OUT = new URL(".", import.meta.url).pathname;
function mulberry32(a){return function(){a|=0;a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296;};}
const seed=Number(process.argv[2]||1);const rnd=mulberry32(seed*999983+41);
const shuffle=(arr)=>{const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const sample=(arr,n,not)=>shuffle(arr.filter(x=>x!==not)).slice(0,n);
function build(entries){const qs=[];const defs=entries.map(e=>e.def);const terms=entries.map(e=>e.term);
 for(const e of entries){const fd=sample(defs,3,e.def);if(fd.length===3)qs.push(opt(e.u,e.t,`In AP terms, ${e.term} is best defined as:`,e.def,fd,`${e.term}: ${e.def}`));
  const rt=sample(terms,3,e.term);if(rt.length===3)qs.push(opt(e.u,e.t,`Which term is defined as: "${e.def}"?`,e.term,rt,`${e.term} — ${e.def}`));}
 return uniq(qs);}
function opt(unit,topic,question_text,correct,distractors,explanation){const chosen=[String(correct)];for(const d of distractors){const s=String(d);if(!chosen.includes(s))chosen.push(s);if(chosen.length===4)break;}if(chosen.length<4)return null;
 const arr=shuffle(chosen.map((v,i)=>({v,ok:i===0})));const L=["A","B","C","D"];const q={unit,topic,difficulty:"medium",question_text};let ca="A";arr.forEach((o,i)=>{q["option_"+L[i].toLowerCase()]=o.v;if(o.ok)ca=L[i];});q.correct_answer=ca;q.explanation=explanation;return q;}
const uniq=(qs)=>{const seen=new Set();return qs.filter(q=>{if(!q)return false;if(seen.has(q.question_text))return false;seen.add(q.question_text);return true;});};

const banks={
"ap-us-government":[
 {u:1,t:"Foundations",term:"a unitary system",def:"a system concentrating power in a central government"},
 {u:1,t:"Foundations",term:"a bicameral legislature",def:"a lawmaking body with two chambers"},
 {u:1,t:"Foundations",term:"the elastic clause",def:"the clause giving Congress implied powers to execute its duties"},
 {u:1,t:"Foundations",term:"states' rights",def:"the doctrine emphasizing state authority against federal power"},
 {u:1,t:"Foundations",term:"a constitutional republic",def:"a government of elected representatives bound by a constitution"},
 {u:2,t:"Branches",term:"a joint committee",def:"a committee with members from both the House and Senate"},
 {u:2,t:"Branches",term:"a whip",def:"a party leader who counts and rallies votes in Congress"},
 {u:2,t:"Branches",term:"the majority leader",def:"the head of the majority party in a chamber of Congress"},
 {u:2,t:"Branches",term:"a closed rule",def:"a House rule barring amendments to a bill on the floor"},
 {u:2,t:"Branches",term:"an open rule",def:"a House rule permitting amendments to a bill on the floor"},
 {u:2,t:"Branches",term:"the power of the purse",def:"Congress's control over government spending"},
 {u:2,t:"Branches",term:"a pardon",def:"the president's power to forgive a federal crime"},
 {u:2,t:"Branches",term:"original jurisdiction",def:"a court's authority to hear a case first, before any appeal"},
 {u:2,t:"Branches",term:"appellate jurisdiction",def:"a court's authority to review decisions of lower courts"},
 {u:3,t:"Civil Liberties",term:"the incorporation doctrine",def:"applying federal Bill of Rights protections to the states"},
 {u:3,t:"Civil Liberties",term:"symbolic conduct",def:"expressive action protected as speech"},
 {u:3,t:"Civil Liberties",term:"a search warrant",def:"a court order authorizing a search, required by the Fourth Amendment"},
 {u:3,t:"Civil Rights",term:"the suffrage movement",def:"the campaign to extend the right to vote, notably to women"},
 {u:3,t:"Civil Rights",term:"civil disobedience",def:"nonviolent refusal to obey unjust laws as protest"},
 {u:4,t:"Ideologies",term:"a swing voter",def:"a voter not firmly committed to one party"},
 {u:4,t:"Ideologies",term:"political efficacy",def:"a citizen's belief that they can influence government"},
 {u:4,t:"Ideologies",term:"a mandate",def:"a perceived public endorsement of a winner's agenda"},
 {u:5,t:"Participation",term:"voter registration",def:"the requirement of enrolling before being allowed to vote"},
 {u:5,t:"Participation",term:"a general election",def:"the final election choosing among parties' nominees"},
],
"ap-psychology":[
 {u:1,t:"Biological Bases",term:"a dendrite",def:"the branching part of a neuron that receives signals"},
 {u:1,t:"Biological Bases",term:"an axon",def:"the part of a neuron that carries signals away from the cell body"},
 {u:1,t:"Biological Bases",term:"a threshold",def:"the level of stimulation needed to trigger a neural impulse"},
 {u:1,t:"Biological Bases",term:"the brainstem",def:"the brain region controlling basic survival functions"},
 {u:1,t:"Biological Bases",term:"the reticular formation",def:"the network controlling arousal and alertness"},
 {u:1,t:"Biological Bases",term:"the somatosensory cortex",def:"the region registering touch and body sensation"},
 {u:1,t:"Biological Bases",term:"the motor cortex",def:"the region controlling voluntary movement"},
 {u:2,t:"Cognition",term:"selective attention",def:"focusing conscious awareness on a particular stimulus"},
 {u:2,t:"Cognition",term:"inattentional blindness",def:"failing to see visible objects when attention is elsewhere"},
 {u:2,t:"Cognition",term:"the recency effect",def:"the tendency to best recall the most recent items"},
 {u:2,t:"Cognition",term:"the primacy effect",def:"the tendency to best recall the first items in a list"},
 {u:2,t:"Cognition",term:"mood-congruent memory",def:"recalling memories consistent with one's current mood"},
 {u:3,t:"Development & Learning",term:"a fixed-interval schedule",def:"reinforcement after a set time period"},
 {u:3,t:"Development & Learning",term:"a conditioned response",def:"a learned reaction to a previously neutral stimulus"},
 {u:3,t:"Development & Learning",term:"an unconditioned response",def:"an automatic, unlearned reaction to a stimulus"},
 {u:3,t:"Development & Learning",term:"habituation",def:"a decreased response to a repeated stimulus"},
 {u:4,t:"Social & Personality",term:"the central route to persuasion",def:"persuasion through careful consideration of arguments"},
 {u:4,t:"Social & Personality",term:"the peripheral route to persuasion",def:"persuasion through superficial cues rather than content"},
 {u:4,t:"Social & Personality",term:"altruism",def:"unselfish concern for the welfare of others"},
 {u:4,t:"Social & Personality",term:"the frustration-aggression principle",def:"the idea that blocked goals can trigger aggression"},
 {u:5,t:"Mental Health",term:"a somatic symptom disorder",def:"a disorder featuring physical symptoms with no medical cause"},
 {u:5,t:"Mental Health",term:"a personality disorder",def:"an enduring, inflexible pattern of behavior causing distress"},
 {u:5,t:"Mental Health",term:"resilience",def:"the ability to recover from stress and adversity"},
 {u:5,t:"Mental Health",term:"a token economy",def:"a behavioral therapy rewarding desired behavior with exchangeable tokens"},
],
"ap-human-geography":[
 {u:1,t:"Thinking Geographically",term:"spatial distribution",def:"the arrangement of a feature across space"},
 {u:1,t:"Thinking Geographically",term:"density",def:"the number of a feature within a given area"},
 {u:1,t:"Thinking Geographically",term:"concentration",def:"how clustered or dispersed a feature is across space"},
 {u:1,t:"Thinking Geographically",term:"pattern",def:"the geometric arrangement of objects in space"},
 {u:2,t:"Population",term:"overpopulation",def:"when population exceeds the resources available to support it"},
 {u:2,t:"Population",term:"a guest worker",def:"a migrant admitted temporarily to fill labor needs"},
 {u:2,t:"Population",term:"asylum",def:"protection granted to refugees fleeing persecution"},
 {u:2,t:"Population",term:"the Ravenstein laws",def:"early generalizations describing patterns of migration"},
 {u:3,t:"Culture",term:"cultural landscape",def:"the visible imprint of human activity on the environment"},
 {u:3,t:"Culture",term:"a centrifugal cultural force",def:"a cultural difference that divides a society"},
 {u:3,t:"Culture",term:"a centripetal cultural force",def:"a shared cultural trait that unites a society"},
 {u:3,t:"Culture",term:"indigenous religion",def:"a belief system tied to a specific group and place"},
 {u:4,t:"Political",term:"a frontier",def:"a zone where no state exercises full control"},
 {u:4,t:"Political",term:"a demilitarized zone",def:"an area where military forces are prohibited"},
 {u:4,t:"Political",term:"antecedent boundary",def:"a boundary drawn before an area was heavily settled"},
 {u:4,t:"Political",term:"subsequent boundary",def:"a boundary drawn after settlement, reflecting cultural divisions"},
 {u:4,t:"Political",term:"superimposed boundary",def:"a boundary forced onto an area by an outside power"},
 {u:5,t:"Agriculture",term:"a cash crop",def:"a crop grown primarily for sale and profit"},
 {u:5,t:"Agriculture",term:"a staple crop",def:"a basic food crop that forms the bulk of a diet"},
 {u:5,t:"Agriculture",term:"crop rotation",def:"alternating crops to preserve soil fertility"},
 {u:6,t:"Cities",term:"the range of a service",def:"the maximum distance people will travel for a service"},
 {u:6,t:"Cities",term:"agglomeration",def:"the clustering of activities to share resources and reduce costs"},
 {u:7,t:"Development",term:"deindustrialization",def:"the decline of manufacturing in an economy"},
 {u:7,t:"Development",term:"fair trade",def:"trade ensuring producers receive a fair price"},
],
"ap-environmental-science":[
 {u:1,t:"Ecosystems",term:"a food chain",def:"a linear sequence of who eats whom in an ecosystem"},
 {u:1,t:"Ecosystems",term:"an autotroph",def:"an organism that produces its own food"},
 {u:1,t:"Ecosystems",term:"a heterotroph",def:"an organism that consumes others for energy"},
 {u:1,t:"Ecosystems",term:"a nitrogen fixer",def:"an organism that converts atmospheric nitrogen into usable forms"},
 {u:1,t:"Ecosystems",term:"the ecological footprint",def:"the land and resources needed to support a population's consumption"},
 {u:2,t:"Biodiversity",term:"genetic drift",def:"random change in allele frequencies, stronger in small populations"},
 {u:2,t:"Biodiversity",term:"a corridor",def:"a habitat link allowing species to move between fragmented areas"},
 {u:2,t:"Biodiversity",term:"a mass extinction",def:"a sharp, widespread loss of species in a short time"},
 {u:3,t:"Populations",term:"age structure",def:"the distribution of individuals among age groups"},
 {u:3,t:"Populations",term:"a population bottleneck",def:"a sharp reduction in population reducing genetic diversity"},
 {u:3,t:"Populations",term:"fecundity",def:"the reproductive capacity of an organism or population"},
 {u:4,t:"Earth Systems",term:"an estuary",def:"a coastal zone where fresh and salt water mix"},
 {u:4,t:"Earth Systems",term:"upwelling",def:"the rise of cold, nutrient-rich water to the ocean surface"},
 {u:4,t:"Earth Systems",term:"a watershed divide",def:"the high ground separating adjacent watersheds"},
 {u:4,t:"Earth Systems",term:"loam",def:"a fertile soil with a balanced mix of sand, silt, and clay"},
 {u:5,t:"Land & Water",term:"a riparian zone",def:"the vegetated area along a stream or river"},
 {u:5,t:"Land & Water",term:"a wetland",def:"land saturated with water that filters pollutants and buffers floods"},
 {u:5,t:"Land & Water",term:"reforestation",def:"replanting trees in deforested areas"},
 {u:6,t:"Energy",term:"a photovoltaic cell",def:"a device converting sunlight directly into electricity"},
 {u:6,t:"Energy",term:"an electric grid",def:"the network distributing electricity from generators to users"},
 {u:7,t:"Atmospheric Pollution",term:"indoor air pollution",def:"harmful contaminants concentrated inside buildings"},
 {u:8,t:"Aquatic Pollution",term:"sewage treatment",def:"the process of removing contaminants from wastewater"},
 {u:9,t:"Global Change",term:"sea level rise",def:"the increase in ocean height from warming and melting ice"},
 {u:9,t:"Global Change",term:"a climate model",def:"a computer simulation projecting future climate conditions"},
],
"ap-english-language":[
 {u:5,t:"Reasoning",term:"a premise",def:"a statement offered as support for a conclusion"},
 {u:5,t:"Reasoning",term:"a conclusion",def:"the claim an argument's premises aim to support"},
 {u:5,t:"Reasoning",term:"an assumption",def:"an unstated belief taken for granted in an argument"},
 {u:5,t:"Reasoning",term:"an implication",def:"a conclusion suggested but not directly stated"},
 {u:5,t:"Reasoning",term:"coherence",def:"the logical flow and connection of ideas in writing"},
 {u:5,t:"Reasoning",term:"unity",def:"the quality of all parts supporting a single main idea"},
 {u:1,t:"Rhetorical Situation",term:"a persona",def:"the character or voice a writer adopts"},
 {u:1,t:"Rhetorical Situation",term:"the message",def:"the central idea a text communicates"},
 {u:3,t:"Claims & Evidence",term:"a counterclaim",def:"a claim opposing the writer's thesis"},
 {u:3,t:"Claims & Evidence",term:"relevance",def:"the degree to which evidence bears on the claim"},
 {u:3,t:"Claims & Evidence",term:"sufficiency",def:"whether evidence is enough to support a claim"},
 {u:7,t:"Style",term:"a tone shift",def:"a change in the writer's attitude within a text"},
 {u:7,t:"Style",term:"pacing",def:"the speed at which a text moves, shaped by sentence length"},
 {u:7,t:"Style",term:"a loose sentence",def:"a sentence stating its main idea first, then adding detail"},
 {u:7,t:"Style",term:"a balanced sentence",def:"a sentence with parallel parts of equal weight"},
 {u:7,t:"Style",term:"repetition",def:"the deliberate reuse of words for emphasis"},
 {u:7,t:"Style",term:"sentence variety",def:"using different sentence lengths and structures for effect"},
 {u:9,t:"Fallacies",term:"a circular argument",def:"an argument that assumes what it tries to prove"},
 {u:9,t:"Fallacies",term:"a sweeping generalization",def:"applying a general rule to a case it does not fit"},
 {u:9,t:"Fallacies",term:"an appeal to tradition",def:"arguing something is right because it has always been done"},
 {u:9,t:"Fallacies",term:"an appeal to ignorance",def:"claiming something is true because it has not been proven false"},
 {u:9,t:"Fallacies",term:"moral equivalence",def:"treating minor faults as equal to serious wrongs"},
 {u:9,t:"Fallacies",term:"loaded language",def:"wording with strong connotations used to sway emotion"},
],
"ap-world-history":[
 {u:1,t:"Global Tapestry",term:"the Mississippian culture",def:"a mound-building society in North America"},
 {u:1,t:"Global Tapestry",term:"the Maya",def:"a Mesoamerican civilization known for writing and astronomy"},
 {u:1,t:"Global Tapestry",term:"the Srivijaya Empire",def:"a maritime Southeast Asian trading state"},
 {u:1,t:"Global Tapestry",term:"Kievan Rus",def:"an early East Slavic state that adopted Orthodox Christianity"},
 {u:2,t:"Networks",term:"the monsoon winds",def:"seasonal winds that structured Indian Ocean trade"},
 {u:2,t:"Networks",term:"the Mongol postal system",def:"the relay network that sped communication across the empire"},
 {u:2,t:"Networks",term:"the spread of Islam",def:"the diffusion of a faith along trade routes across Afro-Eurasia"},
 {u:3,t:"Land-Based Empires",term:"the Tokugawa Shogunate",def:"the military government that unified and isolated early modern Japan"},
 {u:3,t:"Land-Based Empires",term:"the Ming dynasty",def:"the Chinese dynasty that sponsored Zheng He's voyages"},
 {u:3,t:"Land-Based Empires",term:"divine kingship",def:"the idea that a ruler is divine or chosen by the divine"},
 {u:4,t:"Transoceanic",term:"the Reconquista",def:"the Christian reconquest of Iberia from Muslim rule"},
 {u:4,t:"Transoceanic",term:"the Counter-Reformation",def:"the Catholic Church's response to the Protestant Reformation"},
 {u:4,t:"Transoceanic",term:"the Spanish silver fleet",def:"ships carrying American silver that fueled global trade"},
 {u:5,t:"Revolutions",term:"the steam-powered railroad",def:"a transport innovation that integrated markets and sped travel"},
 {u:5,t:"Revolutions",term:"the Tanzimat reforms",def:"Ottoman modernization efforts in the 19th century"},
 {u:5,t:"Revolutions",term:"the Meiji oligarchs",def:"the leaders who drove Japan's rapid modernization"},
 {u:6,t:"Industrialization",term:"the gold standard",def:"a monetary system tying currency value to gold"},
 {u:6,t:"Industrialization",term:"the Panama Canal",def:"a waterway linking the Atlantic and Pacific oceans"},
 {u:6,t:"Industrialization",term:"settler colonialism",def:"colonization that replaces native populations with settlers"},
 {u:7,t:"Global Conflict",term:"the New Deal",def:"U.S. programs responding to the Great Depression"},
 {u:7,t:"Global Conflict",term:"the Nuremberg Trials",def:"the post-WWII trials of Nazi war criminals"},
 {u:8,t:"Cold War",term:"the Iron Curtain",def:"the political divide between communist East and democratic West"},
 {u:8,t:"Cold War",term:"the Great Leap Forward",def:"Mao's failed campaign to rapidly industrialize China"},
 {u:9,t:"Globalization",term:"the information revolution",def:"the rapid spread of digital communication technology"},
],
};
let total=0;
for(const [subject,entries] of Object.entries(banks)){const qs=shuffle(build(entries));fs.writeFileSync(`${OUT}${subject}-fact6-${seed}.json`,JSON.stringify({subject,questions:qs},null,1));console.log(`${subject}: ${entries.length} facts -> ${qs.length} q`);total+=qs.length;}
console.log("total:",total);
