// Seventh fact-bank (authored by Claude, no API). New terms for all 6 content subjects.
import fs from "node:fs";
const OUT = new URL(".", import.meta.url).pathname;
function mulberry32(a){return function(){a|=0;a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296;};}
const seed=Number(process.argv[2]||1);const rnd=mulberry32(seed*2246822519+83);
const shuffle=(arr)=>{const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const sample=(arr,n,not)=>shuffle(arr.filter(x=>x!==not)).slice(0,n);
function build(entries){const qs=[];const defs=entries.map(e=>e.def);const terms=entries.map(e=>e.term);
 for(const e of entries){const fd=sample(defs,3,e.def);if(fd.length===3)qs.push(opt(e.u,e.t,`In AP terms, ${e.term} is best defined as:`,e.def,fd,`${e.term}: ${e.def}`));
  const rt=sample(terms,3,e.term);if(rt.length===3)qs.push(opt(e.u,e.t,`Which term is defined as: "${e.def}"?`,e.term,rt,`${e.term} — ${e.def}`));}
 return uniq(qs);}
function opt(unit,topic,question_text,correct,distractors,explanation){const chosen=[String(correct)];for(const d of distractors){const s=String(d);if(!chosen.includes(s))chosen.push(s);if(chosen.length===4)break;}if(chosen.length<4)return null;
 const arr=shuffle(chosen.map((v,i)=>({v,ok:i===0})));const L=["A","B","C","D"];const q={unit,topic,difficulty:"medium",question_text};let ca="A";arr.forEach((o,i)=>{q["option_"+L[i].toLowerCase()]=o.v;if(o.ok)ca=L[i];});q.correct_answer=ca;q.explanation=explanation;return q;}
const uniq=(qs)=>{const seen=new Set();return qs.filter(q=>{if(!q)return false;if(seen.has(q.question_text))return false;seen.add(q.question_text);return true;});};

const banks={
"ap-us-government":[
 {u:1,t:"Foundations",term:"a constitutional amendment",def:"a formal change to the Constitution, ratified by three-fourths of states"},
 {u:1,t:"Foundations",term:"the amendment process",def:"the method of proposing and ratifying constitutional changes"},
 {u:1,t:"Foundations",term:"checks on the judiciary",def:"powers like appointment and amendment that limit the courts"},
 {u:1,t:"Foundations",term:"a grant-in-aid",def:"federal funds given to states for specified purposes"},
 {u:1,t:"Foundations",term:"revenue sharing",def:"federal distribution of tax money to states with few restrictions"},
 {u:2,t:"Branches",term:"the necessary and proper powers",def:"implied powers letting Congress carry out its enumerated duties"},
 {u:2,t:"Branches",term:"a continuing committee",def:"a permanent committee that exists across congressional sessions"},
 {u:2,t:"Branches",term:"the speaker pro tempore",def:"the member presiding over a chamber in the leader's absence"},
 {u:2,t:"Branches",term:"a roll-call vote",def:"a recorded vote of each member by name"},
 {u:2,t:"Branches",term:"a voice vote",def:"a vote decided by the volume of spoken ayes and noes"},
 {u:2,t:"Branches",term:"executive agreements",def:"international pacts made without Senate ratification"},
 {u:2,t:"Branches",term:"the bully pulpit",def:"the president's platform to shape public opinion"},
 {u:3,t:"Civil Liberties",term:"selective exclusion",def:"limiting some speech categories like obscenity from protection"},
 {u:3,t:"Civil Liberties",term:"freedom of assembly",def:"the First Amendment right to gather peacefully"},
 {u:3,t:"Civil Liberties",term:"the right to petition",def:"the First Amendment right to ask government to address grievances"},
 {u:3,t:"Civil Rights",term:"intermediate scrutiny",def:"the review standard applied to gender-based classifications"},
 {u:3,t:"Civil Rights",term:"rational basis review",def:"the most lenient standard of judicial review"},
 {u:4,t:"Ideologies",term:"a single-issue voter",def:"a voter who decides based on one policy area"},
 {u:4,t:"Ideologies",term:"a party platform",def:"the set of positions a party adopts for an election"},
 {u:5,t:"Participation",term:"absentee voting",def:"casting a ballot remotely before election day"},
],
"ap-psychology":[
 {u:1,t:"Biological Bases",term:"the synaptic gap",def:"the space between neurons where neurotransmitters are released"},
 {u:1,t:"Biological Bases",term:"depolarization",def:"the change in charge that triggers a neural impulse"},
 {u:1,t:"Biological Bases",term:"the adrenal glands",def:"glands that release adrenaline during stress"},
 {u:1,t:"Biological Bases",term:"the autonomic nervous system",def:"the system controlling involuntary bodily functions"},
 {u:1,t:"Biological Bases",term:"Broca's area",def:"the frontal-lobe region controlling speech production"},
 {u:1,t:"Biological Bases",term:"Wernicke's area",def:"the region governing language comprehension"},
 {u:2,t:"Cognition",term:"semantic encoding",def:"processing information by its meaning"},
 {u:2,t:"Cognition",term:"acoustic encoding",def:"processing information by its sound"},
 {u:2,t:"Cognition",term:"the method of loci",def:"a mnemonic linking items to familiar locations"},
 {u:2,t:"Cognition",term:"déjà vu",def:"the eerie sense that a new situation has been experienced before"},
 {u:2,t:"Cognition",term:"the availability bias",def:"overestimating events that come easily to mind"},
 {u:3,t:"Development & Learning",term:"the sensorimotor stage",def:"Piaget's infancy stage of learning through senses and action"},
 {u:3,t:"Development & Learning",term:"egocentrism",def:"the inability to see another's perspective in early childhood"},
 {u:3,t:"Development & Learning",term:"a schema (Piaget)",def:"a mental framework for organizing knowledge"},
 {u:3,t:"Development & Learning",term:"insecure attachment",def:"an anxious or avoidant caregiver bond"},
 {u:4,t:"Social & Personality",term:"the bystander effect",def:"reduced helping when others are present"},
 {u:4,t:"Social & Personality",term:"diffusion of responsibility",def:"feeling less accountable when others share a task"},
 {u:4,t:"Social & Personality",term:"the trait perspective",def:"describing personality by stable characteristics"},
 {u:5,t:"Mental Health",term:"the medical model",def:"viewing disorders as illnesses with physical causes and treatments"},
 {u:5,t:"Mental Health",term:"a phobic disorder",def:"a disorder of intense, specific irrational fear"},
],
"ap-human-geography":[
 {u:1,t:"Thinking Geographically",term:"absolute distance",def:"the exact physical measurement between two points"},
 {u:1,t:"Thinking Geographically",term:"relative distance",def:"distance measured in terms of time, cost, or effort"},
 {u:1,t:"Thinking Geographically",term:"a mental map",def:"an individual's internal representation of space"},
 {u:1,t:"Thinking Geographically",term:"globalization",def:"the increasing interconnection of places worldwide"},
 {u:2,t:"Population",term:"a baby boom",def:"a sharp temporary rise in birth rates"},
 {u:2,t:"Population",term:"a baby bust",def:"a sharp decline in birth rates"},
 {u:2,t:"Population",term:"carrying capacity (population)",def:"the population an area's resources can sustain"},
 {u:2,t:"Population",term:"internal migration",def:"movement within a country's borders"},
 {u:3,t:"Culture",term:"a taboo",def:"a culturally forbidden behavior"},
 {u:3,t:"Culture",term:"a custom",def:"a repeated practice of a group"},
 {u:3,t:"Culture",term:"a habit",def:"a repeated action of an individual"},
 {u:3,t:"Culture",term:"placelessness",def:"the loss of unique character as places grow alike"},
 {u:4,t:"Political",term:"a city-state",def:"a sovereign state consisting of a city and surroundings"},
 {u:4,t:"Political",term:"an empire",def:"a group of territories under a single supreme authority"},
 {u:4,t:"Political",term:"ethnic cleansing",def:"the forced removal of an ethnic group from an area"},
 {u:4,t:"Political",term:"genocide",def:"the deliberate destruction of a national or ethnic group"},
 {u:5,t:"Agriculture",term:"horticulture",def:"the small-scale growing of fruits, vegetables, and flowers"},
 {u:5,t:"Agriculture",term:"dairy farming",def:"raising cattle for milk production"},
 {u:6,t:"Cities",term:"exurbs",def:"prosperous communities beyond the suburbs"},
 {u:7,t:"Development",term:"economic restructuring",def:"a shift in the dominant sectors of an economy"},
],
"ap-environmental-science":[
 {u:1,t:"Ecosystems",term:"a biome shift",def:"a change in a region's dominant ecosystem due to climate change"},
 {u:1,t:"Ecosystems",term:"nutrient cycling",def:"the movement of nutrients through an ecosystem"},
 {u:1,t:"Ecosystems",term:"a quaternary consumer",def:"a predator that eats tertiary consumers"},
 {u:1,t:"Ecosystems",term:"net productivity",def:"the energy available to consumers after producer respiration"},
 {u:2,t:"Biodiversity",term:"alpha diversity",def:"the species diversity within a single ecosystem"},
 {u:2,t:"Biodiversity",term:"beta diversity",def:"the change in species diversity between ecosystems"},
 {u:2,t:"Biodiversity",term:"a flagship species",def:"a charismatic species used to promote conservation"},
 {u:3,t:"Populations",term:"intrinsic growth rate",def:"a population's maximum growth rate under ideal conditions"},
 {u:3,t:"Populations",term:"a metapopulation",def:"a group of separated populations that interact"},
 {u:4,t:"Earth Systems",term:"a hot spot",def:"a volcanic area from a mantle plume, not a plate boundary"},
 {u:4,t:"Earth Systems",term:"a transform boundary",def:"a plate boundary where plates slide past each other"},
 {u:4,t:"Earth Systems",term:"a temperate deciduous forest",def:"a biome of trees that drop leaves seasonally"},
 {u:5,t:"Land & Water",term:"soil compaction",def:"the loss of pore space that harms root growth and drainage"},
 {u:5,t:"Land & Water",term:"a cover crop",def:"a crop planted to protect and enrich soil between harvests"},
 {u:6,t:"Energy",term:"concentrated solar power",def:"using mirrors to focus sunlight and generate heat for electricity"},
 {u:6,t:"Energy",term:"energy return on investment",def:"the ratio of energy obtained to energy spent obtaining it"},
 {u:7,t:"Atmospheric Pollution",term:"ground-level ozone",def:"a harmful secondary pollutant in smog"},
 {u:7,t:"Atmospheric Pollution",term:"stratospheric ozone",def:"the protective ozone layer that absorbs UV radiation"},
 {u:8,t:"Aquatic Pollution",term:"an oil spill",def:"the release of petroleum that harms marine ecosystems"},
 {u:9,t:"Global Change",term:"a climate refugee",def:"a person displaced by climate-related environmental change"},
],
"ap-english-language":[
 {u:1,t:"Rhetorical Situation",term:"rhetoric",def:"the art of effective or persuasive communication"},
 {u:1,t:"Rhetorical Situation",term:"a rhetorical appeal",def:"a strategy (ethos, pathos, logos) used to persuade"},
 {u:1,t:"Rhetorical Situation",term:"a stance",def:"the position a writer takes toward a subject"},
 {u:3,t:"Claims & Evidence",term:"a defensible thesis",def:"an arguable claim that can be supported with evidence"},
 {u:3,t:"Claims & Evidence",term:"a concession and refutation",def:"acknowledging an opposing point then countering it"},
 {u:3,t:"Claims & Evidence",term:"corroborating evidence",def:"additional support that confirms a claim"},
 {u:5,t:"Reasoning",term:"a logical progression",def:"the ordered development of ideas toward a conclusion"},
 {u:5,t:"Reasoning",term:"a topic sentence",def:"a sentence stating a paragraph's main point"},
 {u:5,t:"Reasoning",term:"a transitional phrase",def:"words that link ideas and guide the reader"},
 {u:7,t:"Style",term:"sentence fragment",def:"an incomplete sentence sometimes used for effect"},
 {u:7,t:"Style",term:"a run-on sentence",def:"two independent clauses joined incorrectly"},
 {u:7,t:"Style",term:"subordination",def:"placing a less important idea in a dependent clause"},
 {u:7,t:"Style",term:"coordination",def:"joining ideas of equal weight with conjunctions"},
 {u:7,t:"Style",term:"concision",def:"expressing ideas in as few words as needed"},
 {u:7,t:"Style",term:"a qualifier",def:"a word that limits or softens a claim"},
 {u:9,t:"Fallacies",term:"a faulty causality",def:"wrongly assuming one event caused another"},
 {u:9,t:"Fallacies",term:"a false equivalence",def:"treating two unlike things as if comparable"},
 {u:9,t:"Fallacies",term:"cherry-picking",def:"citing only evidence that supports a claim"},
 {u:9,t:"Fallacies",term:"a scare tactic",def:"using fear rather than reason to persuade"},
 {u:9,t:"Fallacies",term:"an overgeneralization",def:"a claim that goes beyond what the evidence supports"},
],
"ap-world-history":[
 {u:1,t:"Global Tapestry",term:"the Chola dynasty",def:"a South Indian maritime empire active in Indian Ocean trade"},
 {u:1,t:"Global Tapestry",term:"the Swahili coast",def:"East African city-states trading across the Indian Ocean"},
 {u:1,t:"Global Tapestry",term:"the Ghana Empire",def:"an early West African empire built on the gold-salt trade"},
 {u:1,t:"Global Tapestry",term:"the Crusader states",def:"European-ruled territories established in the Levant"},
 {u:2,t:"Networks",term:"the camel saddle",def:"a technology that expanded trans-Saharan caravan trade"},
 {u:2,t:"Networks",term:"the junk",def:"a large Chinese ship used in maritime trade"},
 {u:2,t:"Networks",term:"banking houses",def:"institutions that financed long-distance medieval trade"},
 {u:3,t:"Land-Based Empires",term:"the Habsburg Empire",def:"a powerful European dynasty ruling Austria and Spain"},
 {u:3,t:"Land-Based Empires",term:"the Romanov dynasty",def:"the ruling family that expanded the Russian Empire"},
 {u:3,t:"Land-Based Empires",term:"Peter the Great",def:"the tsar who westernized and modernized Russia"},
 {u:4,t:"Transoceanic",term:"the Dutch East India Company",def:"a joint-stock company that dominated Asian trade"},
 {u:4,t:"Transoceanic",term:"the British East India Company",def:"a company that came to rule much of India"},
 {u:4,t:"Transoceanic",term:"the plantation system",def:"large estates using coerced labor to grow cash crops"},
 {u:5,t:"Revolutions",term:"the Glorious Revolution",def:"the 1688 English shift toward constitutional monarchy"},
 {u:5,t:"Revolutions",term:"the Bill of Rights (English)",def:"the 1689 document limiting the English monarchy"},
 {u:5,t:"Revolutions",term:"the cult of domesticity",def:"the 19th-century ideal confining women to the home"},
 {u:6,t:"Industrialization",term:"the Berlin Conference",def:"the meeting that partitioned Africa among European powers"},
 {u:6,t:"Industrialization",term:"economic imperialism",def:"controlling a region through economic rather than direct rule"},
 {u:7,t:"Global Conflict",term:"the Zimmermann Telegram",def:"a German message that helped bring the U.S. into WWI"},
 {u:7,t:"Global Conflict",term:"Pearl Harbor",def:"the 1941 attack that brought the U.S. into WWII"},
],
};
let total=0;
for(const [subject,entries] of Object.entries(banks)){const qs=shuffle(build(entries));fs.writeFileSync(`${OUT}${subject}-fact7-${seed}.json`,JSON.stringify({subject,questions:qs},null,1));console.log(`${subject}: ${entries.length} facts -> ${qs.length} q`);total+=qs.length;}
console.log("total:",total);
