// Fifth fact-bank (authored by Claude, no API). New terms for the 5 term-rich content subjects.
import fs from "node:fs";
const OUT = new URL(".", import.meta.url).pathname;
function mulberry32(a){return function(){a|=0;a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t=(t+Math.imul(t^(t>>>7),61|t))^t;return((t^(t>>>14))>>>0)/4294967296;};}
const seed=Number(process.argv[2]||1);const rnd=mulberry32(seed*16777619+71);
const shuffle=(arr)=>{const a=arr.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const sample=(arr,n,not)=>shuffle(arr.filter(x=>x!==not)).slice(0,n);
function build(entries){const qs=[];const defs=entries.map(e=>e.def);const terms=entries.map(e=>e.term);
 for(const e of entries){const fd=sample(defs,3,e.def);if(fd.length===3)qs.push(opt(e.u,e.t,`In AP terms, ${e.term} is best defined as:`,e.def,fd,`${e.term}: ${e.def}`));
  const rt=sample(terms,3,e.term);if(rt.length===3)qs.push(opt(e.u,e.t,`Which term is defined as: "${e.def}"?`,e.term,rt,`${e.term} — ${e.def}`));}
 return uniq(qs);}
function opt(unit,topic,question_text,correct,distractors,explanation){const chosen=[String(correct)];for(const d of distractors){const s=String(d);if(!chosen.includes(s))chosen.push(s);if(chosen.length===4)break;}if(chosen.length<4)return null;
 const arr=shuffle(chosen.map((v,i)=>({v,ok:i===0})));const L=["A","B","C","D"];const q={unit,topic,difficulty:"medium",question_text};let ca="A";arr.forEach((o,i)=>{q["option_"+L[i].toLowerCase()]=o.v;if(o.ok)ca=L[i];});q.correct_answer=ca;q.explanation=explanation;return q;}
const uniq=(qs)=>{const seen=new Set();return qs.filter(q=>{if(!q)return false;if(seen.has(q.question_text))return false;seen.add(q.question_text);return true;});};

const banks={
"ap-us-government":[
 {u:1,t:"Foundations",term:"limited government",def:"the principle that government power is restricted by law"},
 {u:1,t:"Foundations",term:"natural rights",def:"rights such as life, liberty, and property that exist prior to government"},
 {u:1,t:"Foundations",term:"the social contract",def:"the idea that people consent to government in exchange for protection of rights"},
 {u:1,t:"Foundations",term:"a republic",def:"a government in which citizens elect representatives to rule for them"},
 {u:1,t:"Foundations",term:"fiscal federalism",def:"the use of federal grants and taxes to influence state policy"},
 {u:1,t:"Foundations",term:"the commerce clause",def:"the constitutional grant of power to Congress to regulate interstate commerce"},
 {u:2,t:"Branches",term:"gridlock",def:"the inability to pass legislation due to political division"},
 {u:2,t:"Branches",term:"a quorum",def:"the minimum number of members needed to conduct business"},
 {u:2,t:"Branches",term:"casework",def:"the help members of Congress provide to constituents with the bureaucracy"},
 {u:2,t:"Branches",term:"pork barrel spending",def:"funds directed to a legislator's district to gain favor"},
 {u:2,t:"Branches",term:"a markup",def:"the committee stage of revising and amending a bill"},
 {u:2,t:"Branches",term:"the Twenty-Fifth Amendment",def:"the amendment establishing presidential succession and disability procedures"},
 {u:2,t:"Branches",term:"the cabinet",def:"the heads of executive departments advising the president"},
 {u:2,t:"Branches",term:"the line-item veto",def:"a struck-down power to reject parts of a spending bill"},
 {u:2,t:"Branches",term:"an amicus curiae brief",def:"a 'friend of the court' document filed by a non-party to influence a case"},
 {u:2,t:"Branches",term:"the solicitor general",def:"the official who represents the federal government before the Supreme Court"},
 {u:2,t:"Branches",term:"a concurring opinion",def:"a written opinion agreeing with the majority's result for different reasons"},
 {u:2,t:"Branches",term:"a dissenting opinion",def:"a written opinion disagreeing with the majority decision"},
 {u:3,t:"Civil Liberties",term:"the Patriot Act",def:"a law expanding surveillance powers after September 11"},
 {u:3,t:"Civil Liberties",term:"libel",def:"a false written statement that damages a reputation, not protected speech"},
 {u:3,t:"Civil Liberties",term:"obscenity",def:"a category of expression not protected by the First Amendment"},
 {u:3,t:"Civil Liberties",term:"the time, place, and manner test",def:"the rule allowing reasonable, content-neutral limits on expression"},
 {u:3,t:"Civil Rights",term:"the Americans with Disabilities Act",def:"the law barring discrimination based on disability"},
 {u:3,t:"Civil Rights",term:"the Thirteenth Amendment",def:"the amendment abolishing slavery"},
 {u:4,t:"Ideologies",term:"a political ideology",def:"a coherent set of beliefs about government's role and goals"},
 {u:4,t:"Ideologies",term:"the generational effect",def:"the lasting impact of major events on a generation's political views"},
 {u:4,t:"Ideologies",term:"a benchmark poll",def:"an initial poll establishing a baseline of opinion"},
 {u:4,t:"Ideologies",term:"an exit poll",def:"a poll of voters as they leave the polling place"},
 {u:5,t:"Participation",term:"rational ignorance",def:"choosing not to learn about politics because the cost outweighs the benefit"},
 {u:5,t:"Participation",term:"a third party",def:"a minor party outside the two dominant parties"},
],
"ap-psychology":[
 {u:1,t:"Biological Bases",term:"an action potential",def:"the electrical impulse that travels down a neuron's axon"},
 {u:1,t:"Biological Bases",term:"the resting potential",def:"the stable negative charge of a neuron before it fires"},
 {u:1,t:"Biological Bases",term:"the central nervous system",def:"the brain and spinal cord"},
 {u:1,t:"Biological Bases",term:"the peripheral nervous system",def:"the nerves outside the brain and spinal cord"},
 {u:1,t:"Biological Bases",term:"glutamate",def:"the brain's main excitatory neurotransmitter"},
 {u:1,t:"Biological Bases",term:"the pituitary gland",def:"the master endocrine gland controlling other glands"},
 {u:1,t:"Biological Bases",term:"a lesion",def:"tissue destruction used to study brain function"},
 {u:2,t:"Cognition",term:"prototype",def:"a mental best example of a category"},
 {u:2,t:"Cognition",term:"a concept",def:"a mental grouping of similar objects, events, or ideas"},
 {u:2,t:"Cognition",term:"insight",def:"a sudden realization of a problem's solution"},
 {u:2,t:"Cognition",term:"encoding",def:"the process of getting information into memory"},
 {u:2,t:"Cognition",term:"retrieval",def:"the process of getting information out of memory"},
 {u:2,t:"Cognition",term:"a retrieval cue",def:"an association that helps trigger a memory"},
 {u:2,t:"Cognition",term:"long-term potentiation",def:"the strengthening of neural connections underlying memory"},
 {u:3,t:"Development & Learning",term:"a teratogen",def:"an agent that can harm a developing embryo or fetus"},
 {u:3,t:"Development & Learning",term:"temperament",def:"a person's characteristic emotional reactivity present early in life"},
 {u:3,t:"Development & Learning",term:"the unconditioned stimulus",def:"a stimulus that naturally triggers a response"},
 {u:3,t:"Development & Learning",term:"the conditioned stimulus",def:"a once-neutral stimulus that triggers a response after pairing"},
 {u:3,t:"Development & Learning",term:"generalization",def:"responding to stimuli similar to the conditioned stimulus"},
 {u:3,t:"Development & Learning",term:"a primary reinforcer",def:"a reinforcer satisfying a biological need"},
 {u:3,t:"Development & Learning",term:"a secondary reinforcer",def:"a reinforcer that gains value through association"},
 {u:4,t:"Social & Personality",term:"an attitude",def:"an evaluation or feeling toward a person, object, or idea"},
 {u:4,t:"Social & Personality",term:"social comparison",def:"evaluating oneself relative to others"},
 {u:4,t:"Social & Personality",term:"the door-in-the-face technique",def:"making a large request first so a smaller one seems reasonable"},
 {u:4,t:"Social & Personality",term:"a self-fulfilling prophecy",def:"a belief that leads to its own fulfillment through behavior"},
 {u:4,t:"Social & Personality",term:"in-group bias",def:"favoring members of one's own group"},
 {u:5,t:"Mental Health",term:"agoraphobia",def:"fear of situations where escape might be difficult"},
 {u:5,t:"Mental Health",term:"a mood disorder",def:"a category of disorders marked by disturbed emotional states"},
 {u:5,t:"Mental Health",term:"tardive dyskinesia",def:"involuntary movements that can result from long-term antipsychotic use"},
 {u:5,t:"Mental Health",term:"lithium",def:"a medication used to stabilize mood in bipolar disorder"},
],
"ap-human-geography":[
 {u:1,t:"Thinking Geographically",term:"a dot distribution map",def:"a map using dots to show the location and density of a feature"},
 {u:1,t:"Thinking Geographically",term:"an isoline map",def:"a map connecting points of equal value with lines"},
 {u:1,t:"Thinking Geographically",term:"a graduated symbol map",def:"a map using symbols sized to represent data values"},
 {u:1,t:"Thinking Geographically",term:"place",def:"the physical and human characteristics that make a location unique"},
 {u:1,t:"Thinking Geographically",term:"a site",def:"the physical characteristics of a location"},
 {u:1,t:"Thinking Geographically",term:"a situation",def:"a location's position relative to other places"},
 {u:2,t:"Population",term:"the crude death rate",def:"the number of deaths per 1,000 people per year"},
 {u:2,t:"Population",term:"life expectancy",def:"the average number of years a person is expected to live"},
 {u:2,t:"Population",term:"a population pyramid",def:"a graph showing a population's age and sex structure"},
 {u:2,t:"Population",term:"Malthusian theory",def:"the idea that population growth would outpace food supply"},
 {u:2,t:"Population",term:"net migration",def:"the difference between immigration and emigration"},
 {u:3,t:"Culture",term:"a dialect",def:"a regional variation of a language"},
 {u:3,t:"Culture",term:"an isogloss",def:"a boundary line marking where a linguistic feature changes"},
 {u:3,t:"Culture",term:"a monotheistic religion",def:"a religion believing in one god"},
 {u:3,t:"Culture",term:"a polytheistic religion",def:"a religion believing in multiple gods"},
 {u:3,t:"Culture",term:"a built environment",def:"the human-made surroundings of a place"},
 {u:4,t:"Political",term:"sovereignty",def:"a state's supreme authority over its territory"},
 {u:4,t:"Political",term:"a colony",def:"a territory under the political control of another state"},
 {u:4,t:"Political",term:"neocolonialism",def:"continued economic control over former colonies"},
 {u:4,t:"Political",term:"a confederation",def:"a loose union of states with a weak central authority"},
 {u:4,t:"Political",term:"the heartland theory",def:"the idea that controlling Eurasia's interior leads to world power"},
 {u:5,t:"Agriculture",term:"subsistence agriculture",def:"farming to feed the farmer's own family"},
 {u:5,t:"Agriculture",term:"market gardening",def:"intensive production of fruits and vegetables for nearby markets"},
 {u:5,t:"Agriculture",term:"the long lot survey",def:"a land division of narrow plots stretching back from a river"},
 {u:5,t:"Agriculture",term:"the township and range system",def:"a rectangular U.S. land survey dividing land into grids"},
 {u:6,t:"Cities",term:"a site factor",def:"a physical feature influencing where a settlement develops"},
 {u:6,t:"Cities",term:"a primate city distribution",def:"an urban pattern dominated by one very large city"},
 {u:6,t:"Cities",term:"the central place theory",def:"a theory explaining the size and spacing of settlements by services"},
 {u:6,t:"Cities",term:"a threshold",def:"the minimum market needed to support a service"},
 {u:7,t:"Development",term:"the gender inequality index",def:"a measure of disparity between men and women in development"},
 {u:7,t:"Development",term:"comparative advantage",def:"the ability to produce a good at lower opportunity cost"},
],
"ap-environmental-science":[
 {u:1,t:"Ecosystems",term:"chemosynthesis",def:"producing food using chemical energy instead of sunlight"},
 {u:1,t:"Ecosystems",term:"a tertiary consumer",def:"an organism that eats secondary consumers"},
 {u:1,t:"Ecosystems",term:"an apex predator",def:"a predator at the top of a food chain with no natural predators"},
 {u:1,t:"Ecosystems",term:"symbiosis",def:"a close, long-term interaction between two species"},
 {u:1,t:"Ecosystems",term:"the nitrogen cycle",def:"the movement of nitrogen among air, soil, and organisms"},
 {u:2,t:"Biodiversity",term:"biodiversity",def:"the variety of life in an area or on Earth"},
 {u:2,t:"Biodiversity",term:"a biodiversity hotspot",def:"a region with exceptional species richness under threat"},
 {u:2,t:"Biodiversity",term:"endemic species",def:"species found only in one geographic location"},
 {u:2,t:"Biodiversity",term:"ecosystem services",def:"the benefits humans receive from natural ecosystems"},
 {u:3,t:"Populations",term:"emigration",def:"individuals leaving a population"},
 {u:3,t:"Populations",term:"immigration",def:"individuals entering a population"},
 {u:3,t:"Populations",term:"a doubling time",def:"the time it takes a population to double in size"},
 {u:3,t:"Populations",term:"the rule of 70",def:"a method estimating doubling time by dividing 70 by the growth rate"},
 {u:4,t:"Earth Systems",term:"the lithosphere",def:"the rigid outer layer of Earth including the crust"},
 {u:4,t:"Earth Systems",term:"a tectonic plate",def:"a large slab of lithosphere that moves over the mantle"},
 {u:4,t:"Earth Systems",term:"a divergent boundary",def:"a plate boundary where plates move apart and new crust forms"},
 {u:4,t:"Earth Systems",term:"the boreal forest",def:"a cold northern coniferous forest biome, also called taiga"},
 {u:4,t:"Earth Systems",term:"soil horizons",def:"the distinct layers of a soil profile"},
 {u:5,t:"Land & Water",term:"a confined aquifer",def:"groundwater trapped between impermeable layers"},
 {u:5,t:"Land & Water",term:"the Ogallala Aquifer",def:"a major U.S. aquifer being depleted by irrigation"},
 {u:5,t:"Land & Water",term:"furrow irrigation",def:"directing water along channels between crop rows"},
 {u:5,t:"Land & Water",term:"selective cutting",def:"harvesting only some trees to reduce forest damage"},
 {u:6,t:"Energy",term:"a kilowatt-hour",def:"a unit of energy equal to one kilowatt used for one hour"},
 {u:6,t:"Energy",term:"net metering",def:"crediting solar owners for electricity they send to the grid"},
 {u:6,t:"Energy",term:"fracking",def:"injecting fluid to fracture rock and release oil or gas"},
 {u:6,t:"Energy",term:"a wind farm",def:"a group of turbines generating electricity from wind"},
 {u:7,t:"Atmospheric Pollution",term:"the Air Quality Index",def:"a scale reporting daily air pollution levels"},
 {u:7,t:"Atmospheric Pollution",term:"radon",def:"a naturally occurring radioactive indoor air pollutant"},
 {u:8,t:"Aquatic Pollution",term:"leachate",def:"liquid that drains from a landfill and can pollute groundwater"},
 {u:8,t:"Aquatic Pollution",term:"the LD50",def:"the dose of a substance that kills half of a test population"},
 {u:9,t:"Global Change",term:"the carbon tax",def:"a fee on carbon emissions to discourage fossil-fuel use"},
 {u:9,t:"Global Change",term:"cap and trade",def:"a system setting an emissions limit and allowing permit trading"},
],
"ap-world-history":[
 {u:1,t:"Global Tapestry",term:"the Mongol Empire",def:"the largest contiguous land empire, founded by Genghis Khan"},
 {u:1,t:"Global Tapestry",term:"the Yuan dynasty",def:"the Mongol-ruled dynasty of China under Kublai Khan"},
 {u:1,t:"Global Tapestry",term:"the Abbasid Caliphate",def:"an Islamic empire known for a golden age of learning"},
 {u:1,t:"Global Tapestry",term:"the Byzantine Empire",def:"the eastern Roman empire centered on Constantinople"},
 {u:1,t:"Global Tapestry",term:"manorialism",def:"the economic system of self-sufficient feudal estates"},
 {u:2,t:"Networks",term:"the Grand Canal",def:"a Chinese waterway linking north and south for internal trade"},
 {u:2,t:"Networks",term:"the Crusades",def:"religious wars that increased European contact with the East"},
 {u:2,t:"Networks",term:"flying cash",def:"an early Chinese form of paper credit aiding trade"},
 {u:2,t:"Networks",term:"the hajj",def:"the Islamic pilgrimage to Mecca that linked the Muslim world"},
 {u:3,t:"Land-Based Empires",term:"gunpowder empires",def:"empires like the Ottoman, Safavid, and Mughal that used firearms to expand"},
 {u:3,t:"Land-Based Empires",term:"the Edict of Nantes",def:"the French decree granting limited religious toleration"},
 {u:3,t:"Land-Based Empires",term:"the Thirty Years' War",def:"a devastating European religious and political conflict"},
 {u:3,t:"Land-Based Empires",term:"boyars",def:"the Russian nobility that tsars sought to control"},
 {u:4,t:"Transoceanic",term:"the Treaty of Tordesillas",def:"the agreement dividing the New World between Spain and Portugal"},
 {u:4,t:"Transoceanic",term:"the Protestant Reformation",def:"the movement that split Western Christianity"},
 {u:4,t:"Transoceanic",term:"the Scientific Revolution",def:"the transformation in understanding nature through observation and reason"},
 {u:4,t:"Transoceanic",term:"the price revolution",def:"the inflation in Europe caused by an influx of American silver"},
 {u:5,t:"Revolutions",term:"laissez-faire",def:"the doctrine of minimal government interference in the economy"},
 {u:5,t:"Revolutions",term:"the Reign of Terror",def:"the radical, violent phase of the French Revolution"},
 {u:5,t:"Revolutions",term:"utilitarianism",def:"the ethical view favoring the greatest good for the greatest number"},
 {u:5,t:"Revolutions",term:"abolition of serfdom",def:"the 1861 emancipation of Russian serfs"},
 {u:6,t:"Industrialization",term:"the Sepoy Mutiny",def:"the 1857 revolt that led to direct British rule of India"},
 {u:6,t:"Industrialization",term:"the Boxer Rebellion",def:"an anti-foreign uprising in Qing China"},
 {u:6,t:"Industrialization",term:"the Monroe Doctrine",def:"the U.S. policy opposing European intervention in the Americas"},
 {u:6,t:"Industrialization",term:"the Scramble for Africa",def:"the rapid European colonization of Africa in the late 1800s"},
 {u:7,t:"Global Conflict",term:"the Fourteen Points",def:"Wilson's plan for peace after World War I"},
 {u:7,t:"Global Conflict",term:"the Armenian genocide",def:"the WWI-era mass killing of Armenians by the Ottomans"},
 {u:7,t:"Global Conflict",term:"blitzkrieg",def:"the fast, mechanized German warfare of World War II"},
 {u:7,t:"Global Conflict",term:"the Long March",def:"the Communist retreat that built Mao's power in China"},
 {u:8,t:"Cold War",term:"the Korean War",def:"a Cold War conflict that divided Korea at the 38th parallel"},
 {u:8,t:"Cold War",term:"the Vietnam War",def:"a Cold War conflict ending in communist victory in Vietnam"},
 {u:8,t:"Cold War",term:"the Suez Crisis",def:"the 1956 conflict signaling the decline of British and French power"},
],
};
let total=0;
for(const [subject,entries] of Object.entries(banks)){const qs=shuffle(build(entries));fs.writeFileSync(`${OUT}${subject}-fact5-${seed}.json`,JSON.stringify({subject,questions:qs},null,1));console.log(`${subject}: ${entries.length} facts -> ${qs.length} q`);total+=qs.length;}
console.log("total:",total);
