/**
 * GET /api/question-bank/subjects — per-subject exam counts, served from a
 * build-time precomputed snapshot (lib/data/precomputed/questionBankSubjects.json).
 *
 * The full bank (~170k computed MCQs) takes ~12s+ to build; doing that on a
 * cold start left the exam page's subject grid empty for seconds. The list only
 * changes on deploy (regenerated by scripts/precompute-subject-lists.ts, wired
 * into prebuild), so we ship the counts and return them INSTANTLY — no runtime
 * dataset build. examPool / examReady (>= 30 real MCQs) are baked in.
 */
import { NextResponse } from "next/server";
import precomputed from "@/lib/data/precomputed/questionBankSubjects.json";

export const dynamic = "force-static";

export async function GET() {
  return NextResponse.json(precomputed, {
    headers: { "Cache-Control": "public, s-maxage=900, stale-while-revalidate=86400" },
  });
}
