/**
 * Core Notes English version — IB Economics Unit 1 (Introduction to Economics & Microeconomics Foundations).
 * Faithful translation of the Korean storytelling source; all content fully preserved
 * (objectives · terms · traps · examples). Same array structure, same lessonIds.
 */
import type { CoreNote } from "@/lib/coreNotes";

export const IB_ECONOMICS_U1_EN: CoreNote[] = [
  {
    lessonId: "ib-economics-u1-l1",
    courseId: "ib-economics",
    subjectLabel: "IB Economics",
    emoji: "📈",
    unit: 1,
    lessonNum: 1,
    unitName: "Introduction & Microeconomics",
    title: "Scarcity, Choice, and the 9 Key Concepts of Economics",
    subtitle: "The root of every economic decision — the eternal tension between unlimited wants and limited resources",
    overview:
      "Economics begins with a single premise: human wants are unlimited, yet the resources available to satisfy them are always finite. This fundamental tension is called scarcity, and as long as scarcity exists, choice is unavoidable. IB DP Economics analyzes the world through the lens of nine key concepts — scarcity, choice, efficiency, equity, economic well-being, sustainability, change, interdependence, and intervention — all of which trace back to this one root problem. This lesson starts at the very beginning.",
    objectives: [
      "Explain why scarcity is the fundamental problem in economics by contrasting unlimited wants with limited resources",
      "Identify the four factors of production and link each to its corresponding factor reward",
      "List the nine key concepts of IB DP Economics and apply them to real-world economic scenarios",
      "Use the concept of opportunity cost to analyze decision-making by individuals, firms, and governments",
      "Distinguish between positive and normative statements in economics and evaluate how this distinction affects policy debates",
    ],
    sections: [
      {
        title: "Scarcity and Choice: The Foundation of Economics",
        subtitle: "Because resources are finite, every choice involves a sacrifice",
        terms: [
          {
            term: "Scarcity",
            def: "The fundamental economic problem that human wants are unlimited while the resources (land, labour, capital, entrepreneurship) available to satisfy them are finite. Because scarcity exists, every economic agent must make choices, and every choice necessarily generates an opportunity cost.",
          },
          {
            term: "Opportunity cost",
            def: "The value of the next-best alternative foregone when a choice is made. IB mark schemes require the phrasing 'the value of the next-best alternative sacrificed'; simply writing 'what was lost' will cost marks.",
          },
          {
            term: "Positive statement",
            def: "An objective, factual statement that can be verified as true or false using data. 'The unemployment rate is 5%' is an example of a positive statement.",
          },
          {
            term: "Normative statement",
            def: "A subjective statement that contains a value judgement and cannot be verified as true or false by data alone. 'The government should provide more support for the unemployed' is an example of a normative statement.",
          },
        ],
        traps: [
          "In IB exams, expressing opportunity cost purely in terms of 'money' or 'time' will cost marks. You must specifically identify the value that the next-best alternative could have provided. For example, when a government spends its budget building a hospital, the opportunity cost should be stated as 'the educational benefits that could have been generated by the school that could have been built with the same budget.' Both the concrete alternative and its value must be articulated together to earn full marks.",
          "The positive/normative distinction appears regularly on every Paper 1. Statements containing 'should' or 'ought to' are normative; statements in factual form ('is/are') that can be checked against evidence are positive. Note that future predictions ('inflation will rise') are positive statements even if they turn out to be wrong — they contain no value judgement.",
        ],
        example:
          "The textbook example of opportunity cost is the decision to attend university. If a high-school graduate chooses to invest four years in university, the opportunity cost is the sum of the salary, career development, and social experience they would have gained had they worked during those four years instead. The tuition fees themselves are an explicit cost, while the foregone income is an implicit cost. IB Economics treats both as components of opportunity cost, and this distinction becomes a core piece of logic in Production Possibility Frontier (PPF) analysis.",
      },
      {
        title: "Factors of Production",
        subtitle: "The inputs to all production and the reward each factor earns",
        terms: [
          {
            term: "Land",
            def: "All natural resources used in production — soil, minerals, water, air, etc. The factor reward for land is rent.",
          },
          {
            term: "Labour",
            def: "The physical and mental effort of human beings contributed to the production process. The factor reward for labour is wages.",
          },
          {
            term: "Capital",
            def: "Human-made resources used to produce other goods and services (factory machinery, buildings, roads, etc.). Important: in economics, capital refers to physical capital, not financial assets. The factor reward for capital is interest.",
          },
          {
            term: "Entrepreneurship",
            def: "The ability and willingness to combine the other three factors of production, bear risk, and organise the production of goods and services. The factor reward for entrepreneurship is profit.",
          },
        ],
        traps: [
          "In IB exams, the definition of 'capital' must refer specifically to physical capital — human-made goods used in production (machinery, buildings, etc.). Answering 'money' or 'financial capital' is incorrect. When an exam question asks you to give an example of capital, always write physical assets such as machines or factories. Shares and cash are not capital in the economic sense.",
        ],
        example: null,
      },
      {
        title: "The 9 Key Concepts of IB Economics",
        subtitle: "These are analytical lenses to apply throughout your arguments, not a list to memorise",
        terms: [
          {
            term: "Efficiency",
            def: "Achieving the maximum possible output from given resources, or producing a given output with the minimum possible resources. Allocative efficiency is achieved when resources are distributed in the combination society desires; productive efficiency is achieved when production occurs at the lowest possible cost.",
          },
          {
            term: "Equity",
            def: "The fair distribution of economic outcomes. Do not confuse with efficiency. An efficient outcome is not necessarily equitable, and this tension is a central justification for government intervention.",
          },
          {
            term: "Sustainability",
            def: "A pattern of development that meets the needs of the present without compromising the ability of future generations to meet their own needs. In IB DP, this concept links directly to the analysis of environmental externalities.",
          },
          {
            term: "Interdependence",
            def: "The relationship in which economic agents (individuals, firms, governments, nations) influence each other's decision-making. This is a core lens for analysing international trade, exchange rate policy, and global supply chains.",
          },
        ],
        traps: [
          "Simply listing the nine key concepts in an HL Paper 1 essay will earn a low score. You must deploy the concepts as analytical lenses to develop your argument. For example, in a minimum-wage debate, you should develop the efficiency–equity trade-off — exploring efficiency (potential distortion of market equilibrium) versus equity (protection of low-income workers' earnings) — with specific supporting evidence to earn high marks.",
        ],
        example: null,
      },
    ],
  },
  {
    lessonId: "ib-economics-u1-l2",
    courseId: "ib-economics",
    subjectLabel: "IB Economics",
    emoji: "📈",
    unit: 1,
    lessonNum: 2,
    unitName: "Introduction & Microeconomics",
    title: "Demand and Supply — The Language of Markets",
    subtitle: "How prices coordinate quantity demanded and quantity supplied to produce equilibrium",
    overview:
      "A market is a space where buyers and sellers meet and trade voluntarily. The law of demand and the law of supply define the relationship between price and quantity demanded, and between price and quantity supplied respectively; the point where the two forces meet is market equilibrium. IB exams consistently test the distinction between a movement along a curve and a shift of the curve itself — confusing these two is the single most frequent error in microeconomics. Being able to draw and correctly label a supply-and-demand diagram is the key that unlocks all further micro analysis.",
    objectives: [
      "Distinguish between the law of demand and the non-price determinants of demand, and represent the effects of price changes versus non-price changes using a diagram",
      "Distinguish between the law of supply and the non-price determinants of supply, and accurately predict the direction of supply-curve shifts",
      "Explain how market equilibrium is formed through the adjustment mechanism of excess demand and excess supply",
      "Analyse the direction of change in equilibrium price and equilibrium quantity when both demand and supply shift simultaneously",
      "Evaluate how the price mechanism resolves the scarcity problem from the perspectives of the allocative function and the signalling function",
    ],
    sections: [
      {
        title: "Demand: The Relationship Between Price and Quantity Demanded",
        subtitle: "Never confuse a movement along the demand curve with a shift of the demand curve itself",
        terms: [
          {
            term: "Law of demand",
            def: "Ceteris paribus, when the price of a good rises, the quantity demanded falls; when the price falls, the quantity demanded rises. This inverse relationship gives the demand curve its downward slope.",
          },
          {
            term: "Change in quantity demanded",
            def: "A movement along an existing demand curve caused by a change in the good's own price. In a diagram, the point on the curve moves; the curve itself does not shift.",
          },
          {
            term: "Change in demand",
            def: "A shift of the entire demand curve caused by a change in a non-price factor (income, prices of related goods, consumer tastes, expectations, population). An increase in demand shifts the curve rightward; a decrease shifts it leftward.",
          },
          {
            term: "Substitute goods",
            def: "Goods that can be consumed in place of one another. When the price of good A rises, the demand for good B (its substitute) increases. Example: a rise in the price of butter leads to an increase in the demand for margarine.",
          },
          {
            term: "Complementary goods",
            def: "Goods consumed together. When the price of good A rises, the quantity demanded of A falls, which in turn reduces the demand for good B (its complement). Example: a rise in the price of printers leads to a fall in the demand for ink cartridges.",
          },
        ],
        traps: [
          "The most common error in IB Paper 1 is confusing 'an increase in demand' with 'an increase in quantity demanded.' Buying more because the price fell is an increase in quantity demanded (a movement along the curve). Buying more because income has risen or because of advertising is an increase in demand (a rightward shift of the curve itself). When drawing a diagram, clearly distinguish between the two using arrow directions — failure to do so will cost marks.",
          "With complementary and substitute goods, always trace the causal chain step by step or you will make mistakes. Practise stating the full chain: 'rise in printer price → fall in quantity demanded of printers → therefore fall in demand for ink cartridges.' IB examiners will not accept logical leaps.",
        ],
        example:
          "Consider the laptop market as a real example of a demand-curve shift. In the early 2020s, the surge in remote work due to COVID-19 increased overall demand for laptops. This was not caused by a change in laptop prices but by a non-price factor: a change in consumer needs. In a diagram, the demand curve shifts rightward from D₀ to D₁. The intersection with the existing supply curve defines a new equilibrium E₁. Both equilibrium price (P₁ > P₀) and equilibrium quantity (Q₁ > Q₀) increase. This is the classic pattern of a rightward demand-curve shift.",
      },
      {
        title: "Supply: The Producer's Logic",
        subtitle: "How changes in production costs shift the supply curve",
        terms: [
          {
            term: "Law of supply",
            def: "Ceteris paribus, when the price of a good rises, the quantity supplied increases; when the price falls, the quantity supplied decreases. This positive relationship gives the supply curve its upward slope.",
          },
          {
            term: "Change in supply",
            def: "A shift of the entire supply curve caused by a non-price factor (production costs, technology, input prices, subsidies/taxes, number of producers, expectations). An increase in supply shifts the curve rightward (downward); a decrease shifts it leftward (upward).",
          },
          {
            term: "Improvement in technology",
            def: "Advances in technology that allow more output to be produced from the same inputs. This lowers production costs and shifts the supply curve rightward.",
          },
          {
            term: "Subsidy",
            def: "Financial support paid by the government to producers to encourage production. Subsidies lower production costs and shift the supply curve rightward (increasing supply).",
          },
        ],
        traps: [
          "The direction of a supply-curve shift can feel counterintuitive: 'rightward shift = price falls.' When supply increases, producers are willing to supply more at the same price, so the curve moves down and to the right, and the equilibrium price falls. When confused, work through the logic slowly: 'supply increases → willing to sell more at the same price → curve moves right.'",
        ],
        example: null,
      },
      {
        title: "Market Equilibrium and the Price Mechanism",
        subtitle: "The self-correcting process by which excess demand and excess supply resolve themselves",
        terms: [
          {
            term: "Market equilibrium",
            def: "The combination of price (equilibrium price, P*) and quantity (equilibrium quantity, Q*) at which quantity demanded equals quantity supplied. Shown on a diagram as the intersection E of the demand and supply curves.",
          },
          {
            term: "Excess demand",
            def: "A situation in which quantity demanded exceeds quantity supplied at the current price (a shortage). Upward pressure on price arises and the market adjusts toward equilibrium.",
          },
          {
            term: "Excess supply",
            def: "A situation in which quantity supplied exceeds quantity demanded at the current price (a surplus). Downward pressure on price arises and the market adjusts toward equilibrium.",
          },
          {
            term: "Price mechanism",
            def: "The automatic coordinating function of markets in which prices act as signals and incentives that guide the decisions of buyers and sellers, ultimately allocating resources across the economy.",
          },
        ],
        traps: [
          "An equilibrium diagram must clearly label P*, Q*, and E to earn full marks in IB. Drawing the curves without marking the intersection will cost marks. After a curve shift, the new equilibrium (E₁, P₁, Q₁) must be clearly distinguished from the original equilibrium (E₀, P₀, Q₀). Remember: a diagram with no labels can score zero no matter how accurately it is drawn.",
        ],
        example:
          "Consider the self-correcting mechanism of excess demand using the face-mask market. Shortly after the pandemic was declared in early 2020, demand for masks surged suddenly. At the existing equilibrium price, quantity demanded far exceeded quantity supplied — a large excess demand emerged. In this situation, suppliers could charge higher prices, and consumers were willing to pay them. As prices rose, quantity demanded fell and quantity supplied increased, until the market reached a new equilibrium (E₁). This episode illustrates clearly how the price mechanism can clear the market without any government intervention.",
      },
    ],
  },
  {
    lessonId: "ib-economics-u1-l3",
    courseId: "ib-economics",
    subjectLabel: "IB Economics",
    emoji: "📈",
    unit: 1,
    lessonNum: 3,
    unitName: "Introduction & Microeconomics",
    title: "Price Elasticity of Demand — How Sensitively Does Demand Respond?",
    subtitle: "How the PED coefficient and its determinants reshape firm strategy and government policy",
    overview:
      "Price elasticity of demand (PED) measures how sensitively consumers respond when a price changes. For goods like cigarettes or insulin — where there are few or no substitutes and they are essential to survival — demand barely falls even when the price rises significantly (inelastic). By contrast, for luxury goods like designer handbags, where many substitutes exist, even a small price rise causes a large drop in quantity demanded (elastic). IB exams intensively test PED calculation, interpretation, determinants, and the relationship between PED and total revenue.",
    objectives: [
      "Calculate PED using the formula and interpret the coefficient using its absolute value",
      "Link the four determinants of PED (availability of substitutes, necessity vs. luxury, proportion of income, time period) to real-world examples",
      "Analyse the implications of PED for firms' pricing strategies and governments' decisions about taxation",
      "Use the relationship between total revenue (TR) and PED to predict the effect of a price change on a firm's revenue",
    ],
    sections: [
      {
        title: "Calculating and Interpreting PED",
        subtitle: "An absolute value above or below 1 determines whether demand is elastic or inelastic",
        terms: [
          {
            term: "Price elasticity of demand (PED)",
            def: "The percentage change in quantity demanded resulting from a 1% change in price. Formula: PED = (% change in quantity demanded) ÷ (% change in price). Because of the law of demand the result is always negative, so IB interprets PED using its absolute value.",
          },
          {
            term: "Elastic demand",
            def: "The case where |PED| > 1. When price rises by 1%, quantity demanded falls by more than 1%. Represented in a diagram by a relatively flat (nearly horizontal) demand curve.",
          },
          {
            term: "Inelastic demand",
            def: "The case where |PED| < 1. When price rises by 1%, quantity demanded falls by less than 1%. Represented in a diagram by a relatively steep (nearly vertical) demand curve.",
          },
          {
            term: "Perfectly inelastic demand",
            def: "The case where |PED| = 0. Quantity demanded does not change regardless of price. The demand curve is drawn as a vertical line. Certain essential medicines (e.g. a specific form of insulin with no alternative) are a standard example.",
          },
        ],
        traps: [
          "PED calculations always yield a negative value, but IB mark schemes require interpretation using the absolute value. Write '|PED| = 2, therefore elastic.' Writing 'PED = –2, therefore elastic' is also acceptable, but writing 'PED = 2, therefore inelastic' (dropping the negative sign and then misinterpreting) is wrong. Always separate the sign and the absolute value when writing up your answer.",
          "In PED calculation questions, swapping the numerator and denominator is a very common error. The numerator is the responding variable (change in quantity demanded); the denominator is the cause (change in price). Remember: 'response on top, cause on the bottom.'",
        ],
        example:
          "Suppose the price of petrol rises from $1.50 to $1.80 per litre — a 20% increase — and monthly quantity demanded falls from 100 litres to 90 litres, a 10% decrease. PED = (–10%) ÷ (+20%) = –0.5. The absolute value |PED| = 0.5 < 1, so demand is inelastic. This result means that even though the price of petrol rose by 20%, consumers only cut back by 10% — petrol is essential for daily commuting and hard to substitute in the short run. Inelastic goods like this are attractive targets for government taxation because a tax raises substantial revenue while generating only a modest reduction in consumption, which is the theoretical rationale behind cigarette, alcohol, and fuel taxes.",
      },
      {
        title: "Determinants of PED",
        subtitle: "What conditions make demand elastic or inelastic?",
        terms: [
          {
            term: "Availability of substitutes",
            def: "The more close substitutes a good has, the more elastic demand tends to be, because consumers can easily switch away if the price rises. Conversely, a unique medicine with no alternatives will have inelastic demand.",
          },
          {
            term: "Necessity vs. luxury",
            def: "Goods essential to daily life (food, medicine) tend to have inelastic demand; goods that are desirable but non-essential luxuries (expensive watches, overseas holidays) tend to have elastic demand.",
          },
          {
            term: "Proportion of income",
            def: "Goods that account for a very small share of income (salt, matches) tend to have inelastic demand because consumers barely notice a price change. Goods that absorb a large share of income (cars, housing) tend to have more elastic demand.",
          },
          {
            term: "Time period",
            def: "In the short run, consumers find it difficult to change their habits, so demand is more inelastic. Over the long run, they can find substitutes or alter consumption patterns, making demand more elastic.",
          },
        ],
        traps: [
          "Writing only 'it is a necessity, therefore inelastic' in response to a PED determinants question will earn only partial credit. You must connect the reason to the mechanism: 'because there are few substitutes and it is difficult to reduce consumption, a price rise causes only a small change in quantity demanded.' Complete the causal logic. Also note that a good's PED is not fixed forever — it can change with time, market conditions, and income levels. Mentioning this nuance helps earn higher marks.",
        ],
        example: null,
      },
      {
        title: "PED and Total Revenue",
        subtitle: "Should you raise or lower the price? Elasticity gives you the answer",
        terms: [
          {
            term: "Total revenue (TR)",
            def: "TR = Price (P) × Quantity sold (Q). The total revenue a firm earns from selling a good. Its relationship with PED is the central logic of pricing strategy.",
          },
          {
            term: "Elastic demand and total revenue",
            def: "When |PED| > 1: a price increase → TR falls (the quantity effect dominates); a price decrease → TR rises. To increase revenue, the firm should lower its price.",
          },
          {
            term: "Inelastic demand and total revenue",
            def: "When |PED| < 1: a price increase → TR rises (the price effect dominates); a price decrease → TR falls. To increase revenue, the firm should raise its price.",
          },
          {
            term: "Unit elastic demand",
            def: "The case where |PED| = 1. The percentage change in price equals the percentage change in quantity demanded. TR remains constant regardless of how the price changes.",
          },
        ],
        traps: [
          "The most common mistake with TR and PED is memorising the relationship backwards — believing that 'elastic demand → price increase → TR increases.' Understanding the logic removes the need to memorise: with elastic demand, a price rise causes consumers to reduce purchases sharply, so the 'lost quantity effect' outweighs the 'gained price effect,' and TR falls. With inelastic demand, a price rise causes only a small fall in quantity, so the 'gained price effect' wins and TR rises. Always approach this by asking: 'which effect is larger?'",
          "In IB Paper 3 (HL), when representing TR on a diagram, you must explicitly show the rectangle below the demand curve (P × Q = TR). Comparing the areas of the two rectangles before and after the price change is the most effective visual way to communicate your argument clearly to the examiner.",
        ],
        example:
          "Consider a cigarette company's pricing strategy. Cigarettes have very few substitutes and are highly addictive, making them strongly inelastic (research estimates |PED| ≈ 0.3–0.5). If the company raises its price by 10%, quantity demanded falls by only 3–5%. In TR = P × Q terms: if P rises 10% and Q falls 5%, TR increases by approximately 4.5% (1.10 × 0.95 ≈ 1.045). This is why tobacco companies often voluntarily raise prices. It is also why governments can impose high taxes on cigarettes — taxes on inelastic goods generate substantial revenue even though they reduce consumption only modestly. Note, however, that IB exams require you to also critically evaluate such taxes from the perspectives of efficiency and equity.",
      },
    ],
  },
];
