import type { SatQuestion } from "./types";

/**
 * Practice Test 1 — second batch of original, hand-verified items, merged into
 * the pools in form1.ts. Brings each Reading & Writing module to 17 and each
 * Math module to 15 questions.
 */

export const RW_M1_X2: SatQuestion[] = [
  {
    id: "rw1-11", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "Although the startup's early growth was ______, within two years it had become one of the largest employers in the region.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["modest", "explosive", "reckless", "permanent"], correct: 0,
    explanation: "Answer: A (modest). The word \"Although\" signals a contrast between the two halves of the sentence: the early growth on one side, and the company becoming \"one of the largest employers in the region\" on the other. For the contrast to make sense, the early growth must be the OPPOSITE of large/impressive — that is, small or unremarkable. \"Modest\" means small in size or amount, which fits perfectly. (B) \"explosive\" describes rapid, dramatic growth — that AGREES with later becoming huge, so there's no contrast; it makes \"Although\" illogical. (C) \"reckless\" describes how growth was pursued (carelessly), not its size, so it doesn't set up the size contrast the sentence needs. (D) \"permanent\" means lasting; it says nothing about the contrast with becoming large and is not something \"early growth\" is normally called.",
  },
  {
    id: "rw1-12", section: "rw", domain: "Standard English Conventions", difficulty: "med",
    passage: "The box of old photographs that my aunt found in the attic ______ to my grandmother.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["belong", "belongs", "belonging", "have belonged"], correct: 1,
    explanation: "Answer: B (belongs). This tests subject-verb agreement. The grammatical subject is \"The box\" — singular. The words \"of old photographs that my aunt found in the attic\" form a prepositional phrase plus a relative clause that describe the box; they are NOT the subject. A singular subject takes a singular verb, and in the present tense a singular third-person verb adds -s: \"box belongs.\" (A) \"belong\" is the plural/base form; it would agree with \"photographs,\" but \"photographs\" is inside a modifying phrase, not the subject — this is the classic trap of matching the verb to the nearest noun. (C) \"belonging\" is a participle, not a finite verb, so it cannot serve as the sentence's main verb. (D) \"have belonged\" is plural (it would need \"boxes\") and also shifts to present-perfect tense without reason.",
  },
  {
    id: "rw1-13", section: "rw", domain: "Information and Ideas", difficulty: "med",
    passage: "The Sahara was not always a desert. Cave paintings across the region depict herds of cattle and people swimming — evidence that the area was once green and well watered.",
    prompt: "Which statement is best supported by the text?",
    type: "mcq", choices: [
      "The Sahara had a much wetter climate at some point in the past.",
      "The Sahara has always been a desert.",
      "The cave paintings were made very recently.",
      "No people ever lived in the Sahara region.",
    ], correct: 0,
    explanation: "Answer: A. The text states the Sahara \"was not always a desert\" and offers cave paintings of cattle herds and people swimming as \"evidence that the area was once green and well watered.\" A wetter climate in the past is exactly what \"green and well watered\" describes, so (A) is directly supported by the textual evidence. (B) directly contradicts the first sentence (\"was not always a desert\"). (C) makes a claim about WHEN the paintings were made; the text says nothing about their age, so this is unsupported. (D) is contradicted by the text, which explicitly mentions \"people swimming\" — people clearly lived there.",
  },
  {
    id: "rw1-14", section: "rw", domain: "Expression of Ideas", difficulty: "med",
    passage: "Electric cars produce no tailpipe emissions. ______, the electricity that charges them may still be generated by burning fossil fuels.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["Therefore", "However", "Likewise", "For example"], correct: 1,
    explanation: "Answer: B (However). The first sentence is positive about electric cars (\"no tailpipe emissions\"). The second sentence introduces a downside (the electricity \"may still be generated by burning fossil fuels\"), which qualifies and undercuts that positive point. Moving from a benefit to an offsetting drawback is a contrast, which \"However\" precisely signals. (A) \"Therefore\" signals a cause-and-effect conclusion, but the fossil-fuel point is not a result of having no tailpipe emissions. (C) \"Likewise\" signals similarity/addition of a like idea, but the second sentence is opposite in tone, not similar. (D) \"For example\" introduces an illustration of the prior claim, but the second sentence is a counterpoint, not an example of zero emissions.",
  },
  {
    id: "rw1-15", section: "rw", domain: "Standard English Conventions", difficulty: "med",
    passage: "The ______ uniforms were collected and washed after the match.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["players", "player's", "players'", "players's"], correct: 2,
    explanation: "Answer: C (players'). The uniforms belong to the players, so a possessive is required, and there are multiple players, so it must be a PLURAL possessive. Rule: to form the possessive of a regular plural noun that already ends in -s, add only an apostrophe after the -s: players + ' = \"players'.\" (A) \"players\" is the plain plural with no apostrophe, so it shows no possession at all. (B) \"player's\" is the SINGULAR possessive (one player), which wrongly implies the uniforms belong to a single player. (D) \"players's\" is not standard; you do not add an apostrophe-plus-s to a regular plural that already ends in -s.",
  },
  {
    id: "rw1-16", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "Rather than define \"courage\" outright, the author lets the idea emerge through a series of brief stories about ordinary people making hard choices.",
    prompt: "Which choice best describes the function of the brief stories?",
    type: "mcq", choices: [
      "They illustrate the concept of courage instead of stating a definition.",
      "They argue that courage does not really exist.",
      "They provide dictionary definitions of courage.",
      "They bring the essay to an abrupt close.",
    ], correct: 0,
    explanation: "Answer: A. The passage says the author, \"Rather than define 'courage' outright,\" lets the idea \"emerge through a series of brief stories about ordinary people making hard choices.\" So the stories' function is to show/illustrate the concept in place of a flat definition. (A) captures exactly this: illustrate the concept instead of stating a definition. (B) is wrong because nothing suggests the author denies courage exists; the stories are evidence OF courage, not against it. (C) is the opposite of the text — the author specifically AVOIDS \"dictionary definitions\" (\"Rather than define ... outright\"). (D) is unsupported; the passage describes a technique, not an abrupt ending, and \"brief\" describes the stories, not the essay's closing.",
  },
  {
    id: "rw1-17", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "The negotiations proved ______: after months of meetings, neither side had budged from its original position.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["fruitless", "productive", "brief", "cordial"], correct: 0,
    explanation: "Answer: A (fruitless). The colon means the second part explains the blank: \"after months of meetings, neither side had budged from its original position.\" Nothing changed despite extended effort, so the negotiations produced no results. \"Fruitless\" means producing no useful result, which matches exactly. (B) \"productive\" means yielding results — the direct opposite of what happened, since neither side budged. (C) \"brief\" means short, but the negotiations lasted \"months,\" so this contradicts the text. (D) \"cordial\" means friendly; the passage describes the OUTCOME (no progress), not the mood, so \"cordial\" isn't supported by the explanatory clause.",
  },
];

export const RW_M2_EASY_X2: SatQuestion[] = [
  {
    id: "rw2e-11", section: "rw", domain: "Craft and Structure", difficulty: "easy",
    passage: "The library is a very ______ place, so please do not talk loudly.",
    prompt: "Which choice completes the text with the most logical word?",
    type: "mcq", choices: ["quiet", "loud", "bright", "cold"], correct: 0,
    explanation: "Answer: A (quiet). The instruction \"so please do not talk loudly\" is the result of the kind of place the library is, so the blank must name a quality that explains why loud talking is discouraged. A \"quiet\" place is exactly where people are asked not to be loud. (B) \"loud\" is self-contradictory — you would not ask people to be silent because a place is already loud. (C) \"bright\" describes lighting, which has nothing to do with talking loudly. (D) \"cold\" describes temperature, also unrelated to the request for quiet.",
  },
  {
    id: "rw2e-12", section: "rw", domain: "Standard English Conventions", difficulty: "easy",
    passage: "She adopted ______ energetic puppy from the local shelter.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["a", "an", "the", "some"], correct: 1,
    explanation: "Answer: B (an). Rule for indefinite articles: use \"an\" before a word that begins with a VOWEL SOUND and \"a\" before a consonant sound. \"Energetic\" begins with the vowel sound /e/, so \"an energetic puppy\" is correct. (A) \"a\" is used before consonant sounds, so \"a energetic\" is wrong and awkward to say. (C) \"the\" is the definite article, used for a specific, already-known puppy, but the sentence introduces a new, unspecified puppy adopted from a shelter. (D) \"some\" implies an unspecified quantity/plural and clashes with the singular \"puppy.\"",
  },
  {
    id: "rw2e-13", section: "rw", domain: "Information and Ideas", difficulty: "easy",
    passage: "Camels can survive for days without drinking. Their humps store fat, which their bodies break down for energy when food and water are scarce.",
    prompt: "Which choice best states the main idea of the text?",
    type: "mcq", choices: [
      "Camels are well adapted to survive with little water.",
      "Camels store water inside their humps.",
      "Camels cannot live in dry places.",
      "Camels must drink water every hour.",
    ], correct: 0,
    explanation: "Answer: A. The text says camels \"can survive for days without drinking\" and that their humps store fat their bodies break down for energy \"when food and water are scarce.\" The main idea is that camels are well adapted to survive with little water — (A) captures both the survival ability and the adaptation. (B) is a common misconception and is contradicted by the text: humps store FAT, not water. (C) is the opposite of the passage, which emphasizes that camels CAN survive in dry conditions. (D) is contradicted by \"survive for days without drinking\" — they do not need water every hour.",
  },
  {
    id: "rw2e-14", section: "rw", domain: "Expression of Ideas", difficulty: "easy",
    passage: "The recipe was very simple. ______, even a beginner could follow it.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["For example", "However", "Therefore", "Instead"], correct: 2,
    explanation: "Answer: C (Therefore). The recipe being \"very simple\" is the CAUSE, and \"even a beginner could follow it\" is the logical EFFECT/result. \"Therefore\" is the transition that signals a conclusion drawn from a cause. (A) \"For example\" would introduce a specific instance of the first idea, but the second sentence is a consequence, not an example. (B) \"However\" signals contrast, yet there is no contrast — both sentences agree the recipe is easy. (D) \"Instead\" signals replacement of one idea with another, which doesn't fit a smooth cause-and-effect link.",
  },
  {
    id: "rw2e-15", section: "rw", domain: "Standard English Conventions", difficulty: "easy",
    passage: "Yesterday she ______ all of her homework before dinner.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["finish", "finishes", "finished", "finishing"], correct: 2,
    explanation: "Answer: C (finished). The time marker \"Yesterday\" places the action firmly in the past, so the verb must be in the simple past tense: \"finished.\" (A) \"finish\" is present tense (base form) and clashes with \"Yesterday\"; it also wouldn't agree with the singular \"she.\" (B) \"finishes\" is present tense, used for habitual/current action, not a completed past one. (D) \"finishing\" is a present participle and cannot stand alone as the main verb without a helping verb like \"was.\"",
  },
  {
    id: "rw2e-16", section: "rw", domain: "Craft and Structure", difficulty: "easy",
    passage: "After running the entire marathon, he felt completely ______ and just wanted to rest.",
    prompt: "Which choice completes the text with the most logical word?",
    type: "mcq", choices: ["exhausted", "energetic", "curious", "cheerful"], correct: 0,
    explanation: "Answer: A (exhausted). After \"running the entire marathon\" he \"just wanted to rest,\" which signals extreme tiredness. \"Exhausted\" means completely worn out — a perfect match. (B) \"energetic\" is the opposite of wanting to rest, so it contradicts the second half of the sentence. (C) \"curious\" describes a desire to learn or explore, which has no connection to running a marathon and resting. (D) \"cheerful\" describes a happy mood, but the cue \"just wanted to rest\" points to fatigue, not happiness.",
  },
  {
    id: "rw2e-17", section: "rw", domain: "Information and Ideas", difficulty: "easy",
    passage: "Recycling paper saves trees. It also uses less water and energy than making paper from new materials.",
    prompt: "Which choice best states the main idea of the text?",
    type: "mcq", choices: [
      "Recycling paper has several environmental benefits.",
      "Recycling paper harms forests.",
      "Making new paper is always the better choice.",
      "Paper cannot be recycled.",
    ], correct: 0,
    explanation: "Answer: A. The text lists multiple upsides of recycling paper: it \"saves trees\" and \"uses less water and energy than making paper from new materials.\" These are all environmental benefits, so (A) — recycling paper has several environmental benefits — is the broad main idea that covers every detail. (B) is contradicted: recycling SAVES trees, it does not harm forests. (C) is contradicted: the text says recycling uses less water and energy, implying making new paper is NOT always better. (D) is flatly contradicted, since the whole passage is about recycling paper, which means paper can be recycled.",
  },
];

export const RW_M2_HARD_X2: SatQuestion[] = [
  {
    id: "rw2h-11", section: "rw", domain: "Craft and Structure", difficulty: "hard",
    passage: "The professor's lectures, though ______, rewarded close attention: each digression eventually circled back to illuminate the central argument.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["meandering", "concise", "tedious", "rehearsed"], correct: 0,
    explanation: "Answer: A (meandering). The clue is \"each digression eventually circled back\": the lectures wander off on tangents before returning to the main point. \"Meandering\" means wandering or following a winding course — exactly that. The structure \"though ______, rewarded close attention\" also implies the blank names a trait that might seem like a drawback but pays off, and wandering fits. (B) \"concise\" means brief and to the point — the opposite of full of digressions. (C) \"tedious\" means boring; but the sentence says the lectures \"rewarded close attention,\" so a purely negative word clashes with the payoff. (D) \"rehearsed\" means practiced/polished, which says nothing about the digressions that \"circle back,\" the key detail.",
  },
  {
    id: "rw2h-12", section: "rw", domain: "Information and Ideas", difficulty: "hard",
    passage: "The article first presents the conventional explanation for the empire's collapse — military overreach — before marshaling climate data that complicates, though does not entirely overturn, that account.",
    prompt: "Which choice best describes the main purpose of the text?",
    type: "mcq", choices: [
      "To complicate a conventional explanation by adding new evidence.",
      "To completely reject the idea of military overreach.",
      "To prove that climate played no role in the collapse.",
      "To give a detailed summary of military tactics.",
    ], correct: 0,
    explanation: "Answer: A. The text says the article presents the conventional explanation (military overreach) and then brings in climate data that \"complicates, though does not entirely overturn, that account.\" The purpose is therefore to add new evidence that complicates — not destroy — the standard view. (A) states exactly this. (B) overstates: \"does not entirely overturn\" means the explanation is NOT completely rejected. (C) is contradicted because the climate data is offered as meaningful, so climate clearly DID play some role. (D) is wrong because the focus is on the climate-vs-overreach debate, not a detailed summary of military tactics.",
  },
  {
    id: "rw2h-13", section: "rw", domain: "Information and Ideas", difficulty: "hard",
    passage: "An app study found that users who got daily reminders completed 68% of their goals, those who got weekly reminders completed 51%, and those who got none completed 40%.",
    prompt: "Which statement is best supported by the data?",
    type: "mcq", choices: [
      "More frequent reminders were associated with higher goal completion.",
      "Reminders had no measurable effect on completion.",
      "Weekly reminders produced the highest completion.",
      "Users who got no reminders completed the most goals.",
    ], correct: 0,
    explanation: "Answer: A. Line up the three groups by reminder frequency and read off the completion rates: daily = 68%, weekly = 51%, none = 40%. As the reminders become MORE frequent (none → weekly → daily), the completion rate steadily RISES (40% → 51% → 68%). So more frequent reminders are associated with higher goal completion — (A). (B) is contradicted: the rates differ by nearly 30 points, so reminders clearly had a measurable effect. (C) is wrong because weekly (51%) is in the middle, not the highest; daily (68%) is highest. (D) is the opposite of the data — the no-reminder group had the LOWEST rate (40%).",
  },
  {
    id: "rw2h-14", section: "rw", domain: "Expression of Ideas", difficulty: "hard",
    passage: "The author concedes that the proposed program is expensive. ______, she argues, the cost of doing nothing would be far greater.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["Furthermore", "Still", "Thus", "For example"], correct: 1,
    explanation: "Answer: B (Still). The author first CONCEDES a negative point (the program \"is expensive\"), then pivots to argue the opposite is worth it (\"the cost of doing nothing would be far greater\"). \"Still\" is a concessive transition meaning \"nevertheless / in spite of that,\" perfect for pushing past a concession to the main argument. (A) \"Furthermore\" adds a similar/supporting point, but here the author reverses direction rather than piling on. (C) \"Thus\" signals a conclusion that follows logically from the cost, but expensiveness does not lead to \"doing nothing is worse\" as a conclusion — it's a counterpoint. (D) \"For example\" introduces an illustration, but the second sentence is a rebuttal, not an example of the program being expensive.",
  },
  {
    id: "rw2h-15", section: "rw", domain: "Standard English Conventions", difficulty: "hard",
    passage: "Neither the manager nor the employees ______ aware that the schedule had changed.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["was", "were", "is", "has been"], correct: 1,
    explanation: "Answer: B (were). Rule for \"neither ... nor\" (and \"either ... or\"): the verb agrees with the subject CLOSER to it. Here the nearer subject is \"the employees,\" which is plural, so the verb must be plural: \"were.\" The sentence also describes a past situation (\"the schedule had changed\"), confirming past tense. (A) \"was\" is singular and would agree with \"manager,\" but \"employees\" is the nearer subject, so singular is wrong. (C) \"is\" is singular AND present tense — wrong on both number and time. (D) \"has been\" is singular present-perfect, which mismatches the plural nearer subject and the past time frame.",
  },
  {
    id: "rw2h-16", section: "rw", domain: "Craft and Structure", difficulty: "hard",
    passage: "Her prose is admirably ______, conveying complex ideas in plain, unadorned sentences.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["spare", "ornate", "verbose", "ambiguous"], correct: 0,
    explanation: "Answer: A (spare). The blank is defined by the phrase after the comma: she conveys \"complex ideas in plain, unadorned sentences.\" In a writing context, \"spare\" means stripped-down, lean, without excess — a synonym for \"plain, unadorned.\" (B) \"ornate\" means elaborately decorated, the opposite of plain. (C) \"verbose\" means using too many words, again the opposite of unadorned/economical. (D) \"ambiguous\" means unclear or open to multiple meanings, but the sentence praises the prose for clearly conveying complex ideas, so this contradicts the cue.",
  },
  {
    id: "rw2h-17", section: "rw", domain: "Expression of Ideas", difficulty: "hard",
    passage: "The first half of the speech is relentlessly grim, cataloguing failures and losses. ______, its closing turns unexpectedly hopeful, urging listeners toward concrete action.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["In contrast", "Consequently", "Indeed", "Likewise"], correct: 0,
    explanation: "Answer: A (In contrast). The first half is \"relentlessly grim,\" while the closing \"turns unexpectedly hopeful.\" Grim versus hopeful is an opposition, and the word \"unexpectedly\" reinforces the reversal, so a contrast transition is needed: \"In contrast.\" (B) \"Consequently\" signals a result, but a hopeful ending is not a logical consequence of cataloguing failures. (C) \"Indeed\" intensifies or confirms the previous point, yet the closing reverses tone rather than reinforcing the grimness. (D) \"Likewise\" signals similarity, but the two halves are opposite in tone, not alike.",
  },
];

export const MATH_M1_X2: SatQuestion[] = [
  {
    id: "m1-10", section: "math", domain: "Algebra", difficulty: "med",
    prompt: "If (x / 3) + 4 = 10, what is the value of x?",
    type: "grid", gridAnswers: ["18"],
    explanation: "Goal: solve (x/3) + 4 = 10 for x.\nStep 1 — isolate the x-term by subtracting 4 from both sides: (x/3) + 4 − 4 = 10 − 4, which gives x/3 = 6.\nStep 2 — undo the division by multiplying both sides by 3: 3 · (x/3) = 6 · 3, so x = 18.\nCheck: (18/3) + 4 = 6 + 4 = 10. ✓ Correct, so the grid-in answer is 18.\nTrap: a careless student multiplies by 3 BEFORE subtracting 4, getting x + 4 = 30 → x = 26. You must remove the +4 first, then clear the fraction.",
  },
  {
    id: "m1-11", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med",
    prompt: "A shirt costs $20. With an 8% sales tax added, what is the total cost?",
    type: "mcq", choices: ["$21.60", "$28.00", "$20.80", "$22.00"], correct: 0,
    explanation: "Goal: find the total cost after adding 8% sales tax to a $20 shirt.\nStep 1 — compute the tax: 8% of 20 = 0.08 × 20 = $1.60.\nStep 2 — add the tax to the price: 20 + 1.60 = $21.60. (Equivalently, multiply by 1.08: 20 × 1.08 = 21.60.)\nAnswer: A, $21.60.\n(B) $28.00 wrongly adds 8 dollars instead of 8 percent (20 + 8). (C) $20.80 uses 4% (or misplaces a decimal: 0.008 × 20 = 0.16 added). (D) $22.00 adds 10% rather than 8%.",
  },
  {
    id: "m1-12", section: "math", domain: "Algebra", difficulty: "med",
    prompt: "A line passes through the points (1, 2) and (3, 8). What is the slope of the line?",
    type: "mcq", choices: ["3", "2", "4", "1/3"], correct: 0,
    explanation: "Goal: find the slope of the line through (1, 2) and (3, 8).\nSlope formula: m = (y2 − y1) / (x2 − x1).\nLet (x1, y1) = (1, 2) and (x2, y2) = (3, 8).\nStep 1 — change in y: 8 − 2 = 6.\nStep 2 — change in x: 3 − 1 = 2.\nStep 3 — divide: m = 6 / 2 = 3.\nAnswer: A, 3.\n(B) 2 mixes up the order, e.g. using (3 − 1)/(8 − 2) inverted partway, or just the run. (C) 4 comes from (8 − 2)/(... ) with a wrong run. (D) 1/3 is the reciprocal — the result of putting Δx over Δy by mistake. Always put the y-difference on TOP.",
  },
  {
    id: "m1-13", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med",
    prompt: "The average (arithmetic mean) of 5 numbers is 12. What is the sum of the 5 numbers?",
    type: "grid", gridAnswers: ["60"],
    explanation: "Goal: find the sum of 5 numbers whose average is 12.\nKey relationship: average = sum ÷ count, which rearranges to sum = average × count.\nStep 1 — substitute: sum = 12 × 5.\nStep 2 — multiply: 12 × 5 = 60.\nCheck: a sum of 60 over 5 numbers gives 60 ÷ 5 = 12, the stated average. ✓ Grid-in answer: 60.\nTrap: dividing (12 ÷ 5 = 2.4) instead of multiplying. The total is larger than the average, not smaller, so multiply by the count.",
  },
  {
    id: "m1-14", section: "math", domain: "Geometry and Trigonometry", difficulty: "med",
    prompt: "Two angles of a triangle measure 50° and 60°. What is the measure, in degrees, of the third angle?",
    type: "mcq", choices: ["70", "80", "90", "110"], correct: 0,
    explanation: "Goal: find the third angle of a triangle whose other two angles are 50° and 60°.\nRule: the interior angles of any triangle sum to 180°.\nStep 1 — add the known angles: 50 + 60 = 110.\nStep 2 — subtract from 180: 180 − 110 = 70°.\nAnswer: A, 70.\n(D) 110 is the SUM of the two given angles — the value you subtract, not the answer. (B) 80 and (C) 90 are arithmetic slips; double-check that all three add to 180: 50 + 60 + 70 = 180. ✓",
  },
  {
    id: "m1-15", section: "math", domain: "Algebra", difficulty: "med",
    prompt: "If 7x + 2 = 5x + 14, what is the value of x?",
    type: "grid", gridAnswers: ["6"],
    explanation: "Goal: solve 7x + 2 = 5x + 14 for x.\nStep 1 — get the x-terms on one side by subtracting 5x from both sides: 7x − 5x + 2 = 14, so 2x + 2 = 14.\nStep 2 — subtract 2 from both sides: 2x = 12.\nStep 3 — divide both sides by 2: x = 6.\nCheck: left side 7(6) + 2 = 44; right side 5(6) + 14 = 44. Both equal 44. ✓ Grid-in answer: 6.\nTrap: subtracting 7x instead of 5x leaves a negative coefficient (−2x = 12 → x = −6); move the SMALLER x-term to keep the coefficient positive.",
  },
];

export const MATH_M2_EASY_X2: SatQuestion[] = [
  {
    id: "m2e-10", section: "math", domain: "Algebra", difficulty: "easy",
    prompt: "If x − 4 = 9, what is the value of x?",
    type: "grid", gridAnswers: ["13"],
    explanation: "Goal: solve x − 4 = 9 for x.\nStep 1 — undo the subtraction by adding 4 to both sides: x − 4 + 4 = 9 + 4, so x = 13.\nCheck: 13 − 4 = 9. ✓ Grid-in answer: 13.\nTrap: subtracting 4 (getting 5) instead of adding. To isolate x, do the OPPOSITE of the operation attached to it — here, add.",
  },
  {
    id: "m2e-11", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy",
    prompt: "What is 20% of 60?",
    type: "mcq", choices: ["12", "30", "20", "6"], correct: 0,
    explanation: "Goal: compute 20% of 60.\n\"Percent\" means per hundred, so 20% = 20/100 = 0.20, and \"of\" means multiply.\nStep 1 — convert: 20% = 0.20.\nStep 2 — multiply: 0.20 × 60 = 12.\nAnswer: A, 12.\n(B) 30 is 50% of 60 (half). (C) 20 just copies the percent number. (D) 6 is 10% of 60 — half of the correct percent. A quick gut check: 20% is one-fifth, and 60 ÷ 5 = 12. ✓",
  },
  {
    id: "m2e-12", section: "math", domain: "Geometry and Trigonometry", difficulty: "easy",
    prompt: "A rectangle has a length of 10 and a width of 3. What is its area?",
    type: "grid", gridAnswers: ["30"],
    explanation: "Goal: find the area of a rectangle with length 10 and width 3.\nFormula: Area = length × width.\nStep 1 — substitute: Area = 10 × 3.\nStep 2 — multiply: 10 × 3 = 30.\nGrid-in answer: 30 (square units).\nTrap: computing the PERIMETER instead, 2(10 + 3) = 26. Area multiplies the two dimensions; perimeter adds them around.",
  },
  {
    id: "m2e-13", section: "math", domain: "Algebra", difficulty: "easy",
    prompt: "If 6 + x = 15, what is the value of x?",
    type: "mcq", choices: ["9", "21", "6", "10"], correct: 0,
    explanation: "Goal: solve 6 + x = 15 for x.\nStep 1 — undo the +6 by subtracting 6 from both sides: 6 + x − 6 = 15 − 6, so x = 9.\nCheck: 6 + 9 = 15. ✓ Answer: A, 9.\n(B) 21 comes from adding (15 + 6) instead of subtracting. (C) 6 just repeats the constant. (D) 10 is an arithmetic slip; 15 − 6 = 9, not 10.",
  },
  {
    id: "m2e-14", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy",
    prompt: "A shelter has 4 cats and 8 dogs. What is the ratio of cats to dogs in simplest form?",
    type: "mcq", choices: ["1 : 2", "2 : 1", "1 : 4", "4 : 1"], correct: 0,
    explanation: "Goal: write the ratio of cats to dogs in simplest form.\nStep 1 — set up the ratio in the order asked (cats : dogs): 4 : 8.\nStep 2 — divide both parts by their greatest common factor, 4: (4÷4) : (8÷4) = 1 : 2.\nAnswer: A, 1 : 2.\n(B) 2 : 1 reverses the order (that's dogs to cats). (C) 1 : 4 incorrectly divides only one side or uses the wrong factor. (D) 4 : 1 both reverses and fails to simplify. Order matters: \"cats to dogs\" puts cats first.",
  },
  {
    id: "m2e-15", section: "math", domain: "Advanced Math", difficulty: "easy",
    prompt: "What is the value of 5² − 4?",
    type: "grid", gridAnswers: ["21"],
    explanation: "Goal: evaluate 5² − 4.\nOrder of operations (PEMDAS): handle the exponent before the subtraction.\nStep 1 — exponent: 5² = 5 × 5 = 25.\nStep 2 — subtract: 25 − 4 = 21.\nGrid-in answer: 21.\nTrap: subtracting first (5 − 4 = 1) then squaring (1² = 1), or multiplying 5 × 2 = 10 for the exponent. 5² means 5 times itself, and exponents come before subtraction.",
  },
];

export const MATH_M2_HARD_X2: SatQuestion[] = [
  {
    id: "m2h-10", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If x² = 49 and x < 0, what is the value of x?",
    type: "grid", gridAnswers: ["-7"],
    explanation: "Goal: solve x² = 49 given the constraint x < 0.\nStep 1 — take the square root of both sides. A squared variable yields TWO roots: x = ±√49 = ±7. So x = 7 or x = −7.\nStep 2 — apply the constraint x < 0: of the two roots, only −7 is negative.\nTherefore x = −7.\nCheck: (−7)² = 49 ✓ and −7 < 0 ✓. Grid-in answer: −7.\nTrap: forgetting the negative root and answering 7; the condition x < 0 exists precisely to select the negative solution.",
  },
  {
    id: "m2h-11", section: "math", domain: "Algebra", difficulty: "hard",
    prompt: "If 3x + 4y = 18 and x = 2, what is the value of y?",
    type: "mcq", choices: ["3", "2", "4", "6"], correct: 0,
    explanation: "Goal: find y given 3x + 4y = 18 and x = 2.\nStep 1 — substitute x = 2: 3(2) + 4y = 18.\nStep 2 — simplify: 6 + 4y = 18.\nStep 3 — subtract 6 from both sides: 4y = 12.\nStep 4 — divide by 4: y = 3.\nCheck: 3(2) + 4(3) = 6 + 12 = 18. ✓ Answer: A, 3.\n(D) 6 forgets to divide by 4 (stops at 4y = 12 and reads y = 12/... wrong, or copies the constant). (B) 2 just echoes x. (C) 4 divides 16/4 from a subtraction slip. Always finish by dividing off the coefficient of y.",
  },
  {
    id: "m2h-12", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If 3^x = 81, what is the value of x?",
    type: "grid", gridAnswers: ["4"],
    explanation: "Goal: solve 3^x = 81 for x.\nStrategy: rewrite 81 as a power of 3 so both sides share the same base.\nStep 1 — express 81 in base 3: 3¹=3, 3²=9, 3³=27, 3⁴=81. So 81 = 3⁴.\nStep 2 — the equation becomes 3^x = 3⁴; with equal bases, the exponents must be equal, so x = 4.\nCheck: 3⁴ = 81. ✓ Grid-in answer: 4.\nTrap: dividing 81 ÷ 3 = 27 and answering 27, or guessing 3; the exponent is the answer, not the base or the quotient.",
  },
  {
    id: "m2h-13", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "hard",
    prompt: "The price of a stock rises from $40 to $50. What is the percent increase?",
    type: "mcq", choices: ["25%", "20%", "10%", "50%"], correct: 0,
    explanation: "Goal: find the percent increase from $40 to $50.\nFormula: percent change = (new − original) / original × 100%, using the ORIGINAL value as the base.\nStep 1 — change in price: 50 − 40 = 10.\nStep 2 — divide by the original price (40): 10 / 40 = 0.25.\nStep 3 — convert to percent: 0.25 × 100% = 25%.\nAnswer: A, 25%.\n(B) 20% wrongly divides by the NEW value (10/50). (C) 10% confuses the dollar change with the percent. (D) 50% comes from dividing 10 by 20 or doubling. The denominator must be the starting value, 40.",
  },
  {
    id: "m2h-14", section: "math", domain: "Geometry and Trigonometry", difficulty: "hard",
    prompt: "The area of a circle is given by A = πr². If r = 5, the area equals kπ. What is the value of k?",
    type: "grid", gridAnswers: ["25"],
    explanation: "Goal: with A = πr² and r = 5, the area is kπ; find k.\nStep 1 — substitute r = 5: A = π(5²).\nStep 2 — square the radius: 5² = 25, so A = 25π.\nStep 3 — match to the form kπ: 25π = kπ, therefore k = 25.\nGrid-in answer: 25.\nTrap: multiplying 2 × 5 = 10 for the square (giving k = 10), or including π in the answer. The blank k is just the numerical coefficient, 25.",
  },
  {
    id: "m2h-15", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If f(x) = x² − 1, what is the value of f(5) − f(3)?",
    type: "mcq", choices: ["16", "8", "14", "24"], correct: 0,
    explanation: "Goal: with f(x) = x² − 1, compute f(5) − f(3).\nStep 1 — evaluate f(5): 5² − 1 = 25 − 1 = 24.\nStep 2 — evaluate f(3): 3² − 1 = 9 − 1 = 8.\nStep 3 — subtract: f(5) − f(3) = 24 − 8 = 16.\nAnswer: A, 16.\n(D) 24 is just f(5) alone — you must subtract f(3). (B) 8 is f(3) alone. (C) 14 comes from forgetting the −1 on one term (e.g., 25 − 1 − ... slip). Compute each output fully, then subtract.",
  },
];
