import type { SatForm, SatQuestion } from "./types";

/**
 * Practice Test 6 — an additional adaptive form (original, hand-verified
 * items). Each module is a focused set (R&W 8, Math 6) with the full adaptive
 * structure. Topics are distinct from Practice Tests 1–5.
 */

// ─────────────────────────── PRACTICE TEST 6 ───────────────────────────
const T6_RW_M1: SatQuestion[] = [
  { id: "t6rw1-1", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "The glassblower's technique was remarkably ______: every vase she produced was nearly identical to the last.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["consistent", "haphazard", "experimental", "fragile"], correct: 0, explanation: "Producing nearly identical results each time shows the technique was \"consistent.\"" },
  { id: "t6rw1-2", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "The flock of geese ______ across the lake at dawn each morning.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["glide", "gliding", "glides", "to glide"], correct: 2, explanation: "The singular subject \"flock\" takes the singular verb \"glides.\"" },
  { id: "t6rw1-3", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "Mangrove forests grow where rivers meet the sea, and their tangled roots trap sediment, protecting nearby coastlines from erosion during storms.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Mangrove roots shield coastlines by trapping sediment.", "Mangroves can grow only in deep ocean water.", "Mangroves accelerate coastal erosion.", "Mangroves have no roots."], correct: 0, explanation: "The text says the roots trap sediment and protect coastlines from erosion (choice A)." },
  { id: "t6rw1-4", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "The prototype passed every laboratory test. ______, engineers chose to delay its release until field trials were complete.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Therefore", "Nevertheless", "Likewise", "Consequently"], correct: 1, explanation: "Delaying despite passing tests is a contrast — \"Nevertheless.\"" },
  { id: "t6rw1-5", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "The chef relied on three staples in every dish ______ garlic, olive oil, and fresh basil.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["dish, garlic", "dish: garlic", "dish; garlic", "dish garlic"], correct: 1, explanation: "A colon introduces the list that specifies the \"three staples.\"" },
  { id: "t6rw1-6", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "Her memoir was praised for its ______ honesty, refusing to soften even her own worst decisions.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["unflinching", "reluctant", "selective", "guarded"], correct: 0, explanation: "Refusing to soften anything is \"unflinching\" honesty." },
  { id: "t6rw1-7", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "The grant funds research only at institutions founded before 1900; newer institutions are ineligible.", prompt: "Which statement is best supported by the text?", type: "mcq", choices: ["A university founded in 1880 is eligible for the grant.", "Every institution qualifies for the grant.", "A university founded in 1950 is eligible.", "No institution can receive the grant."], correct: 0, explanation: "Only institutions founded before 1900 qualify, so one from 1880 is eligible (choice A)." },
  { id: "t6rw1-8", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "The museum digitized its entire archive. ______, scholars on other continents can now study the collection.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["However", "As a result", "Otherwise", "In contrast"], correct: 1, explanation: "Digitizing the archive enables remote study — cause/effect \"As a result.\"" },
];
const T6_RW_M2E: SatQuestion[] = [
  { id: "t6rw2e-1", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The soup was too ______, so I added some cold water to cool it down.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["hot", "sweet", "empty", "blue"], correct: 0, explanation: "Adding cold water to cool it means the soup was \"hot.\"" },
  { id: "t6rw2e-2", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "The two cats ______ sleeping on the windowsill.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["is", "are", "was", "am"], correct: 1, explanation: "\"Two cats\" is plural, so \"are\" is correct." },
  { id: "t6rw2e-3", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Owls hunt at night, and their large eyes help them see well in very dim light.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Owls' large eyes help them see at night.", "Owls hunt only during the day.", "Owls cannot see in the dark.", "Owls have very small eyes."], correct: 0, explanation: "The text links their large eyes to seeing in dim light (choice A)." },
  { id: "t6rw2e-4", section: "rw", domain: "Expression of Ideas", difficulty: "easy", passage: "The bus was late this morning. ______, I still arrived at school on time.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["For example", "Therefore", "However", "Because"], correct: 2, explanation: "Arriving on time despite the late bus is a contrast — \"However.\"" },
  { id: "t6rw2e-5", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "Last weekend we ______ a movie at the new theater downtown.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["watch", "watches", "watched", "watching"], correct: 2, explanation: "\"Last weekend\" requires the past tense \"watched.\"" },
  { id: "t6rw2e-6", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The lake was perfectly ______, with no waves at all on the calm morning.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["still", "stormy", "loud", "crowded"], correct: 0, explanation: "No waves on a calm morning means the lake was \"still.\"" },
  { id: "t6rw2e-7", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Recycling saves energy, reduces landfill waste, and conserves natural resources.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Recycling provides several environmental benefits.", "Recycling wastes energy.", "Recycling only fills landfills.", "Recycling harms natural resources."], correct: 0, explanation: "Three benefits are listed — choice A." },
  { id: "t6rw2e-8", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "She gave ______ honest answer to every question on the form.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["a", "an", "the only", "some"], correct: 1, explanation: "\"Honest\" begins with a silent h (a vowel sound), so \"an.\"" },
];
const T6_RW_M2H: SatQuestion[] = [
  { id: "t6rw2h-1", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "The diplomat's remarks were studiously ______, offering reassurance to both sides without endorsing either position.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["noncommittal", "inflammatory", "candid", "decisive"], correct: 0, explanation: "Reassuring both sides without endorsing either is \"noncommittal.\"" },
  { id: "t6rw2h-2", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "The essay opens with a vivid anecdote about a single fisherman before broadening into a claim about an entire industry's decline.", prompt: "Which choice best describes the function of the opening anecdote?", type: "mcq", choices: ["To introduce a concrete example that sets up a broader argument.", "To state the essay's final conclusion outright.", "To provide statistical evidence for the claim.", "To contradict the rest of the essay."], correct: 0, explanation: "The single anecdote leads into a broader claim about the industry (choice A)." },
  { id: "t6rw2h-3", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "A reservoir's water level fell 2 cm in the first dry week, 9 cm in the second, and 10 cm in the third.", prompt: "Which statement is best supported by the data?", type: "mcq", choices: ["The rate of decline rose sharply after the first week.", "The water level rose over the three weeks.", "The decline was fastest in the first week.", "The level did not change at all."], correct: 0, explanation: "2 cm to 9 cm is a sharp jump in the rate of decline after week one (choice A)." },
  { id: "t6rw2h-4", section: "rw", domain: "Expression of Ideas", difficulty: "hard", passage: "The treaty was hailed as a diplomatic triumph. ______, several of its key provisions were never enforced.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Accordingly", "In practice", "Similarly", "Therefore"], correct: 1, explanation: "Praise versus what actually happened is signaled by \"In practice.\"" },
  { id: "t6rw2h-5", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "The internship trains participants to gather data carefully, to interpret results rigorously, and ______ findings clearly.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["to present", "presenting", "presents", "presented"], correct: 0, explanation: "Parallel with \"to gather\" and \"to interpret\" requires \"to present.\"" },
  { id: "t6rw2h-6", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "The biography is exhaustively ______, documenting even the subject's grocery lists and weather diaries.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["thorough", "cursory", "selective", "vague"], correct: 0, explanation: "Documenting even trivial details makes the work \"thorough.\"" },
  { id: "t6rw2h-7", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "Where earlier biographers portrayed the composer as a lone genius, this study stresses the network of collaborators who shaped his work.", prompt: "Which choice best describes the main purpose of the text?", type: "mcq", choices: ["To revise a lone-genius portrait by emphasizing collaborators.", "To confirm that the composer worked entirely alone.", "To summarize earlier biographies approvingly.", "To deny that the composer wrote any music."], correct: 0, explanation: "It contrasts the lone-genius view with one emphasizing collaborators (choice A)." },
  { id: "t6rw2h-8", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "The morning session ran far over schedule ______ the afternoon panels had to be cut entirely.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["schedule, the", "schedule; the", "schedule the", "schedule: the"], correct: 1, explanation: "Two independent clauses are joined by a semicolon." },
];
const T6_M_M1: SatQuestion[] = [
  { id: "t6m1-1", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 7x − 4 = 31, what is the value of x?", type: "grid", gridAnswers: ["5"], explanation: "7x = 35, so x = 5." },
  { id: "t6m1-2", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "A recipe makes 36 cookies and serves 9 people equally. How many cookies does each person get?", type: "mcq", choices: ["4", "5", "6", "9"], correct: 0, explanation: "36 ÷ 9 = 4 cookies per person." },
  { id: "t6m1-3", section: "math", domain: "Advanced Math", difficulty: "med", prompt: "If f(x) = x² + 2x, what is the value of f(5)?", type: "mcq", choices: ["35", "27", "30", "25"], correct: 0, explanation: "f(5) = 25 + 10 = 35." },
  { id: "t6m1-4", section: "math", domain: "Geometry and Trigonometry", difficulty: "med", prompt: "A circle has a radius of 7. What is its diameter?", type: "grid", gridAnswers: ["14"], explanation: "Diameter = 2 × radius = 2 × 7 = 14." },
  { id: "t6m1-5", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 4(x + 2) = 28, what is the value of x?", type: "grid", gridAnswers: ["5"], explanation: "x + 2 = 7, so x = 5." },
  { id: "t6m1-6", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "A train travels 150 miles in 3 hours. What is its average speed in miles per hour?", type: "mcq", choices: ["50", "45", "30", "75"], correct: 0, explanation: "150 ÷ 3 = 50 mph." },
];
const T6_M_M2E: SatQuestion[] = [
  { id: "t6m2e-1", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If x + 6 = 15, what is the value of x?", type: "grid", gridAnswers: ["9"], explanation: "x = 15 − 6 = 9." },
  { id: "t6m2e-2", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "What is 20% of 60?", type: "mcq", choices: ["12", "10", "30", "6"], correct: 0, explanation: "0.20 × 60 = 12." },
  { id: "t6m2e-3", section: "math", domain: "Geometry and Trigonometry", difficulty: "easy", prompt: "A rectangle has a length of 7 and a width of 4. What is its area?", type: "grid", gridAnswers: ["28"], explanation: "7 × 4 = 28." },
  { id: "t6m2e-4", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If 6x = 42, what is the value of x?", type: "mcq", choices: ["7", "6", "8", "36"], correct: 0, explanation: "x = 42 ÷ 6 = 7." },
  { id: "t6m2e-5", section: "math", domain: "Advanced Math", difficulty: "easy", prompt: "What is the value of 4² − 1?", type: "grid", gridAnswers: ["15"], explanation: "4² = 16; 16 − 1 = 15." },
  { id: "t6m2e-6", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "A jar has 3 red marbles and 9 blue marbles. What fraction of the marbles are red?", type: "mcq", choices: ["1/4", "1/3", "3/9", "1/9"], correct: 0, explanation: "3 red out of 12 total = 3/12 = 1/4." },
];
const T6_M_M2H: SatQuestion[] = [
  { id: "t6m2h-1", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If x² − 49 = 0 and x > 0, what is the value of x?", type: "grid", gridAnswers: ["7"], explanation: "x² = 49, so x = 7 (taking the positive root)." },
  { id: "t6m2h-2", section: "math", domain: "Algebra", difficulty: "hard", prompt: "If x + y = 15 and x − y = 3, what is the value of y?", type: "mcq", choices: ["6", "9", "5", "12"], correct: 0, explanation: "Subtract the equations: 2y = 12, so y = 6." },
  { id: "t6m2h-3", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If 3^x = 81, what is the value of x?", type: "grid", gridAnswers: ["4"], explanation: "81 = 3⁴, so x = 4." },
  { id: "t6m2h-4", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "hard", prompt: "An $80 jacket is discounted by 25%. What is the sale price?", type: "mcq", choices: ["$60", "$55", "$65", "$20"], correct: 0, explanation: "25% of 80 = 20; 80 − 20 = $60." },
  { id: "t6m2h-5", section: "math", domain: "Geometry and Trigonometry", difficulty: "hard", prompt: "A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?", type: "grid", gridAnswers: ["13"], explanation: "√(25 + 144) = √169 = 13." },
  { id: "t6m2h-6", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If g(x) = 4x − 1, what is the value of g(g(2))?", type: "mcq", choices: ["27", "7", "23", "15"], correct: 0, explanation: "g(2) = 7; g(7) = 4(7) − 1 = 27." },
];

export const SAT_FORM_6: SatForm = {
  id: "practice-6",
  title: "InHero SAT Practice Test 6",
  rw: { m1: T6_RW_M1, m2easy: T6_RW_M2E, m2hard: T6_RW_M2H, timeSec: 1080 },
  math: { m1: T6_M_M1, m2easy: T6_M_M2E, m2hard: T6_M_M2H, timeSec: 1080 },
};
