import type { SatQuestion } from "./types";

/**
 * Practice Test 1 — second batch of original, hand-verified items, merged into
 * the pools in form1.ts. Brings each Reading & Writing module to 17 and each
 * Math module to 15 questions.
 */

export const RW_M1_X2: SatQuestion[] = [
  {
    id: "rw1-11", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "Although the startup's early growth was ______, within two years it had become one of the largest employers in the region.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["modest", "explosive", "reckless", "permanent"], correct: 0,
    explanation: "\"Although … ______, within two years it had become one of the largest\" sets up a contrast, so early growth was small — \"modest.\"",
  },
  {
    id: "rw1-12", section: "rw", domain: "Standard English Conventions", difficulty: "med",
    passage: "The box of old photographs that my aunt found in the attic ______ to my grandmother.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["belong", "belongs", "belonging", "have belonged"], correct: 1,
    explanation: "The subject is the singular \"box\" (not \"photographs\"), so the singular verb \"belongs\" is correct.",
  },
  {
    id: "rw1-13", section: "rw", domain: "Information and Ideas", difficulty: "med",
    passage: "The Sahara was not always a desert. Cave paintings across the region depict herds of cattle and people swimming — evidence that the area was once green and well watered.",
    prompt: "Which statement is best supported by the text?",
    type: "mcq", choices: [
      "The Sahara had a much wetter climate at some point in the past.",
      "The Sahara has always been a desert.",
      "The cave paintings were made very recently.",
      "No people ever lived in the Sahara region.",
    ], correct: 0,
    explanation: "Paintings of cattle and swimming are offered as evidence the Sahara was \"once green and well watered\" (choice A).",
  },
  {
    id: "rw1-14", section: "rw", domain: "Expression of Ideas", difficulty: "med",
    passage: "Electric cars produce no tailpipe emissions. ______, the electricity that charges them may still be generated by burning fossil fuels.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["Therefore", "However", "Likewise", "For example"], correct: 1,
    explanation: "The second sentence qualifies the first's optimism, a contrast signaled by \"However.\"",
  },
  {
    id: "rw1-15", section: "rw", domain: "Standard English Conventions", difficulty: "med",
    passage: "The ______ uniforms were collected and washed after the match.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["players", "player's", "players'", "players's"], correct: 2,
    explanation: "Uniforms belonging to multiple players takes the plural possessive \"players'.\"",
  },
  {
    id: "rw1-16", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "Rather than define \"courage\" outright, the author lets the idea emerge through a series of brief stories about ordinary people making hard choices.",
    prompt: "Which choice best describes the function of the brief stories?",
    type: "mcq", choices: [
      "They illustrate the concept of courage instead of stating a definition.",
      "They argue that courage does not really exist.",
      "They provide dictionary definitions of courage.",
      "They bring the essay to an abrupt close.",
    ], correct: 0,
    explanation: "The author uses the stories *instead of* a definition to let the idea emerge — they illustrate it (choice A).",
  },
  {
    id: "rw1-17", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "The negotiations proved ______: after months of meetings, neither side had budged from its original position.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["fruitless", "productive", "brief", "cordial"], correct: 0,
    explanation: "Months of talks with no movement means nothing was accomplished — \"fruitless.\"",
  },
];

export const RW_M2_EASY_X2: SatQuestion[] = [
  {
    id: "rw2e-11", section: "rw", domain: "Craft and Structure", difficulty: "easy",
    passage: "The library is a very ______ place, so please do not talk loudly.",
    prompt: "Which choice completes the text with the most logical word?",
    type: "mcq", choices: ["quiet", "loud", "bright", "cold"], correct: 0,
    explanation: "\"Do not talk loudly\" tells us the library is \"quiet.\"",
  },
  {
    id: "rw2e-12", section: "rw", domain: "Standard English Conventions", difficulty: "easy",
    passage: "She adopted ______ energetic puppy from the local shelter.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["a", "an", "the", "some"], correct: 1,
    explanation: "\"Energetic\" begins with a vowel sound, so \"an\" is correct.",
  },
  {
    id: "rw2e-13", section: "rw", domain: "Information and Ideas", difficulty: "easy",
    passage: "Camels can survive for days without drinking. Their humps store fat, which their bodies break down for energy when food and water are scarce.",
    prompt: "Which choice best states the main idea of the text?",
    type: "mcq", choices: [
      "Camels are well adapted to survive with little water.",
      "Camels store water inside their humps.",
      "Camels cannot live in dry places.",
      "Camels must drink water every hour.",
    ], correct: 0,
    explanation: "The text says humps store *fat* (not water) and camels last days without drinking — they're adapted to scarcity (choice A).",
  },
  {
    id: "rw2e-14", section: "rw", domain: "Expression of Ideas", difficulty: "easy",
    passage: "The recipe was very simple. ______, even a beginner could follow it.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["For example", "However", "Therefore", "Instead"], correct: 2,
    explanation: "Being simple is the reason a beginner could follow it — cause/effect \"Therefore.\"",
  },
  {
    id: "rw2e-15", section: "rw", domain: "Standard English Conventions", difficulty: "easy",
    passage: "Yesterday she ______ all of her homework before dinner.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["finish", "finishes", "finished", "finishing"], correct: 2,
    explanation: "\"Yesterday\" requires the past tense \"finished.\"",
  },
  {
    id: "rw2e-16", section: "rw", domain: "Craft and Structure", difficulty: "easy",
    passage: "After running the entire marathon, he felt completely ______ and just wanted to rest.",
    prompt: "Which choice completes the text with the most logical word?",
    type: "mcq", choices: ["exhausted", "energetic", "curious", "cheerful"], correct: 0,
    explanation: "Wanting only to rest after a marathon means he was \"exhausted.\"",
  },
  {
    id: "rw2e-17", section: "rw", domain: "Information and Ideas", difficulty: "easy",
    passage: "Recycling paper saves trees. It also uses less water and energy than making paper from new materials.",
    prompt: "Which choice best states the main idea of the text?",
    type: "mcq", choices: [
      "Recycling paper has several environmental benefits.",
      "Recycling paper harms forests.",
      "Making new paper is always the better choice.",
      "Paper cannot be recycled.",
    ], correct: 0,
    explanation: "The text lists benefits (saves trees, water, energy) — choice A.",
  },
];

export const RW_M2_HARD_X2: SatQuestion[] = [
  {
    id: "rw2h-11", section: "rw", domain: "Craft and Structure", difficulty: "hard",
    passage: "The professor's lectures, though ______, rewarded close attention: each digression eventually circled back to illuminate the central argument.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["meandering", "concise", "tedious", "rehearsed"], correct: 0,
    explanation: "Digressions that wander but \"circle back\" describe a \"meandering\" style; the payoff rules out the purely negative options.",
  },
  {
    id: "rw2h-12", section: "rw", domain: "Information and Ideas", difficulty: "hard",
    passage: "The article first presents the conventional explanation for the empire's collapse — military overreach — before marshaling climate data that complicates, though does not entirely overturn, that account.",
    prompt: "Which choice best describes the main purpose of the text?",
    type: "mcq", choices: [
      "To complicate a conventional explanation by adding new evidence.",
      "To completely reject the idea of military overreach.",
      "To prove that climate played no role in the collapse.",
      "To give a detailed summary of military tactics.",
    ], correct: 0,
    explanation: "The climate data \"complicates, though does not entirely overturn\" the standard account — it complicates it (choice A).",
  },
  {
    id: "rw2h-13", section: "rw", domain: "Information and Ideas", difficulty: "hard",
    passage: "An app study found that users who got daily reminders completed 68% of their goals, those who got weekly reminders completed 51%, and those who got none completed 40%.",
    prompt: "Which statement is best supported by the data?",
    type: "mcq", choices: [
      "More frequent reminders were associated with higher goal completion.",
      "Reminders had no measurable effect on completion.",
      "Weekly reminders produced the highest completion.",
      "Users who got no reminders completed the most goals.",
    ], correct: 0,
    explanation: "68% (daily) > 51% (weekly) > 40% (none): completion rises with reminder frequency (choice A).",
  },
  {
    id: "rw2h-14", section: "rw", domain: "Expression of Ideas", difficulty: "hard",
    passage: "The author concedes that the proposed program is expensive. ______, she argues, the cost of doing nothing would be far greater.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["Furthermore", "Still", "Thus", "For example"], correct: 1,
    explanation: "After conceding a point, the author pivots to her counterargument — the concessive \"Still.\"",
  },
  {
    id: "rw2h-15", section: "rw", domain: "Standard English Conventions", difficulty: "hard",
    passage: "Neither the manager nor the employees ______ aware that the schedule had changed.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["was", "were", "is", "has been"], correct: 1,
    explanation: "With \"neither … nor,\" the verb agrees with the nearer subject — the plural \"employees\" — so \"were.\"",
  },
  {
    id: "rw2h-16", section: "rw", domain: "Craft and Structure", difficulty: "hard",
    passage: "Her prose is admirably ______, conveying complex ideas in plain, unadorned sentences.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["spare", "ornate", "verbose", "ambiguous"], correct: 0,
    explanation: "\"Plain, unadorned\" matches \"spare\"; the other options mean wordy or unclear.",
  },
  {
    id: "rw2h-17", section: "rw", domain: "Expression of Ideas", difficulty: "hard",
    passage: "The first half of the speech is relentlessly grim, cataloguing failures and losses. ______, its closing turns unexpectedly hopeful, urging listeners toward concrete action.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["In contrast", "Consequently", "Indeed", "Likewise"], correct: 0,
    explanation: "Grim first half vs. hopeful close is a contrast — \"In contrast.\"",
  },
];

export const MATH_M1_X2: SatQuestion[] = [
  {
    id: "m1-10", section: "math", domain: "Algebra", difficulty: "med",
    prompt: "If (x / 3) + 4 = 10, what is the value of x?",
    type: "grid", gridAnswers: ["18"],
    explanation: "x/3 = 6, so x = 18.",
  },
  {
    id: "m1-11", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med",
    prompt: "A shirt costs $20. With an 8% sales tax added, what is the total cost?",
    type: "mcq", choices: ["$21.60", "$28.00", "$20.80", "$22.00"], correct: 0,
    explanation: "Tax = 8% of 20 = $1.60; total = 20 + 1.60 = $21.60.",
  },
  {
    id: "m1-12", section: "math", domain: "Algebra", difficulty: "med",
    prompt: "A line passes through the points (1, 2) and (3, 8). What is the slope of the line?",
    type: "mcq", choices: ["3", "2", "4", "1/3"], correct: 0,
    explanation: "Slope = (8 − 2) / (3 − 1) = 6 / 2 = 3.",
  },
  {
    id: "m1-13", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med",
    prompt: "The average (arithmetic mean) of 5 numbers is 12. What is the sum of the 5 numbers?",
    type: "grid", gridAnswers: ["60"],
    explanation: "Sum = average × count = 12 × 5 = 60.",
  },
  {
    id: "m1-14", section: "math", domain: "Geometry and Trigonometry", difficulty: "med",
    prompt: "Two angles of a triangle measure 50° and 60°. What is the measure, in degrees, of the third angle?",
    type: "mcq", choices: ["70", "80", "90", "110"], correct: 0,
    explanation: "Angles sum to 180°: 180 − 50 − 60 = 70°.",
  },
  {
    id: "m1-15", section: "math", domain: "Algebra", difficulty: "med",
    prompt: "If 7x + 2 = 5x + 14, what is the value of x?",
    type: "grid", gridAnswers: ["6"],
    explanation: "7x − 5x = 14 − 2 → 2x = 12 → x = 6.",
  },
];

export const MATH_M2_EASY_X2: SatQuestion[] = [
  {
    id: "m2e-10", section: "math", domain: "Algebra", difficulty: "easy",
    prompt: "If x − 4 = 9, what is the value of x?",
    type: "grid", gridAnswers: ["13"],
    explanation: "x = 9 + 4 = 13.",
  },
  {
    id: "m2e-11", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy",
    prompt: "What is 20% of 60?",
    type: "mcq", choices: ["12", "30", "20", "6"], correct: 0,
    explanation: "0.20 × 60 = 12.",
  },
  {
    id: "m2e-12", section: "math", domain: "Geometry and Trigonometry", difficulty: "easy",
    prompt: "A rectangle has a length of 10 and a width of 3. What is its area?",
    type: "grid", gridAnswers: ["30"],
    explanation: "Area = length × width = 10 × 3 = 30.",
  },
  {
    id: "m2e-13", section: "math", domain: "Algebra", difficulty: "easy",
    prompt: "If 6 + x = 15, what is the value of x?",
    type: "mcq", choices: ["9", "21", "6", "10"], correct: 0,
    explanation: "x = 15 − 6 = 9.",
  },
  {
    id: "m2e-14", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy",
    prompt: "A shelter has 4 cats and 8 dogs. What is the ratio of cats to dogs in simplest form?",
    type: "mcq", choices: ["1 : 2", "2 : 1", "1 : 4", "4 : 1"], correct: 0,
    explanation: "4 : 8 simplifies (divide by 4) to 1 : 2.",
  },
  {
    id: "m2e-15", section: "math", domain: "Advanced Math", difficulty: "easy",
    prompt: "What is the value of 5² − 4?",
    type: "grid", gridAnswers: ["21"],
    explanation: "5² = 25; 25 − 4 = 21.",
  },
];

export const MATH_M2_HARD_X2: SatQuestion[] = [
  {
    id: "m2h-10", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If x² = 49 and x < 0, what is the value of x?",
    type: "grid", gridAnswers: ["-7"],
    explanation: "x = ±7; since x < 0, x = −7.",
  },
  {
    id: "m2h-11", section: "math", domain: "Algebra", difficulty: "hard",
    prompt: "If 3x + 4y = 18 and x = 2, what is the value of y?",
    type: "mcq", choices: ["3", "2", "4", "6"], correct: 0,
    explanation: "3(2) + 4y = 18 → 6 + 4y = 18 → 4y = 12 → y = 3.",
  },
  {
    id: "m2h-12", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If 3^x = 81, what is the value of x?",
    type: "grid", gridAnswers: ["4"],
    explanation: "81 = 3⁴, so x = 4.",
  },
  {
    id: "m2h-13", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "hard",
    prompt: "The price of a stock rises from $40 to $50. What is the percent increase?",
    type: "mcq", choices: ["25%", "20%", "10%", "50%"], correct: 0,
    explanation: "Increase = 10; 10 / 40 = 0.25 = 25%.",
  },
  {
    id: "m2h-14", section: "math", domain: "Geometry and Trigonometry", difficulty: "hard",
    prompt: "The area of a circle is given by A = πr². If r = 5, the area equals kπ. What is the value of k?",
    type: "grid", gridAnswers: ["25"],
    explanation: "A = π(5²) = 25π, so k = 25.",
  },
  {
    id: "m2h-15", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If f(x) = x² − 1, what is the value of f(5) − f(3)?",
    type: "mcq", choices: ["16", "8", "14", "24"], correct: 0,
    explanation: "f(5) = 24, f(3) = 8; 24 − 8 = 16.",
  },
];
