import type { SatForm, SatQuestion } from "./types";

/**
 * Practice Test 5 — an additional adaptive form (original, hand-verified
 * items). Each module is a focused set (R&W 8, Math 6) with the full adaptive
 * structure. Topics and passages are distinct from Practice Tests 1–4.
 */

// ─────────────────────────── PRACTICE TEST 5 ───────────────────────────
const T5_RW_M1: SatQuestion[] = [
  { id: "t5rw1-1", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "Lacking any formal training, the self-taught engineer relied on a remarkably ______ understanding of mechanics, grasping principles she had never been taught.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["intuitive", "borrowed", "reluctant", "outdated"], correct: 0, explanation: "Grasping untaught principles points to an \"intuitive\" understanding." },
  { id: "t5rw1-2", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "The orchestra, along with its conductor, ______ traveling to Vienna for the festival.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["are", "is", "were", "have been"], correct: 1, explanation: "The subject \"orchestra\" is singular; \"along with\" does not change number, so \"is.\"" },
  { id: "t5rw1-3", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "Mangrove forests anchor coastlines: their dense, tangled roots trap sediment, blunt the force of incoming waves, and shelter young fish.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Mangrove roots protect and stabilize coastal ecosystems.", "Mangroves grow only far inland.", "Mangroves erode coastlines over time.", "Mangroves provide no habitat for fish."], correct: 0, explanation: "Trapping sediment, blunting waves, and sheltering fish all describe coastal protection and stabilization (choice A)." },
  { id: "t5rw1-4", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "The recipe called for fresh basil. ______, the cook substituted a spoonful of dried basil instead.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Lacking it", "In addition", "By comparison", "As a result"], correct: 0, explanation: "The substitution is made because the fresh basil is absent — \"Lacking it.\"" },
  { id: "t5rw1-5", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "The museum acquired three paintings last spring ______ a Monet, a Degas, and a small Cézanne sketch.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["spring, a", "spring: a", "spring; a", "spring a"], correct: 1, explanation: "A colon introduces the list that specifies the \"three paintings.\"" },
  { id: "t5rw1-6", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "Far from settling the debate, the new evidence only ______ it, raising questions no one had thought to ask.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["complicated", "resolved", "ignored", "shortened"], correct: 0, explanation: "Raising new questions \"complicated\" the debate rather than settling it." },
  { id: "t5rw1-7", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "The grant funds research only at institutions located outside the capital region; institutions within it must seek other support.", prompt: "Which statement is best supported by the text?", type: "mcq", choices: ["A university in a rural province may apply for the grant.", "Every institution in the country qualifies for the grant.", "Only capital-region institutions can receive the grant.", "The grant funds no research at all."], correct: 0, explanation: "Institutions outside the capital region are eligible, so a rural-province university may apply (choice A)." },
  { id: "t5rw1-8", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "The bridge passed every load test. ______, inspectors recommended it be opened to traffic ahead of schedule.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Nevertheless", "Consequently", "In contrast", "Otherwise"], correct: 1, explanation: "Passing the tests leads to the recommendation — cause/effect \"Consequently.\"" },
];
const T5_RW_M2E: SatQuestion[] = [
  { id: "t5rw2e-1", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The soup was too ______, so she added a little water to cool it down.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["hot", "cold", "empty", "sweet"], correct: 0, explanation: "Cooling it down means the soup was \"hot.\"" },
  { id: "t5rw2e-2", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "The two dogs ______ barking at the mail carrier.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["is", "are", "was", "am"], correct: 1, explanation: "\"Two dogs\" is plural, so \"are.\"" },
  { id: "t5rw2e-3", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Owls hunt at night, using their excellent hearing and night vision to find small animals in the dark.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Owls are well suited to hunting in the dark.", "Owls can only hunt during the day.", "Owls have very poor hearing.", "Owls do not hunt at all."], correct: 0, explanation: "Hearing and night vision let owls hunt in the dark (choice A)." },
  { id: "t5rw2e-4", section: "rw", domain: "Expression of Ideas", difficulty: "easy", passage: "The bus was late this morning. ______, I still arrived at school on time.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["For example", "However", "Therefore", "Meanwhile"], correct: 1, explanation: "Arriving on time despite the late bus is a contrast — \"However.\"" },
  { id: "t5rw2e-5", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "Last week we ______ a new movie at the theater downtown.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["see", "sees", "saw", "seeing"], correct: 2, explanation: "\"Last week\" requires the past tense \"saw.\"" },
  { id: "t5rw2e-6", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The room was very ______, so we turned on more lights to see.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["dark", "bright", "loud", "warm"], correct: 0, explanation: "Needing more lights means the room was \"dark.\"" },
  { id: "t5rw2e-7", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Reading every day can build your vocabulary, improve your focus, and spark your imagination.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Reading daily offers several benefits.", "Reading is bad for the mind.", "Reading only helps with focus.", "Reading shrinks your vocabulary."], correct: 0, explanation: "Three benefits are listed — choice A." },
  { id: "t5rw2e-8", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "She waited for ______ hour before the train finally arrived.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["a", "an", "the only", "some"], correct: 1, explanation: "\"Hour\" begins with a silent h (a vowel sound), so \"an.\"" },
];
const T5_RW_M2H: SatQuestion[] = [
  { id: "t5rw2h-1", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "The memoir is admirably ______: the author refuses to soften her own failures or flatter her allies.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["unsparing", "sentimental", "evasive", "flattering"], correct: 0, explanation: "Refusing to soften failures or flatter allies makes the memoir \"unsparing.\"" },
  { id: "t5rw2h-2", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "The essay devotes its first half to a vivid anecdote, which the author then dissects to introduce the abstract principle the rest of the piece defends.", prompt: "Which choice best describes the function of the opening anecdote?", type: "mcq", choices: ["To supply a concrete case from which the essay's broader principle is drawn.", "To state the essay's counterargument.", "To list the essay's sources.", "To conclude the essay's argument."], correct: 0, explanation: "The anecdote is a concrete case the author dissects to introduce the principle (choice A)." },
  { id: "t5rw2h-3", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "A survey found that 82% of remote workers reported high job satisfaction, compared with 61% of in-office workers and 64% of hybrid workers.", prompt: "Which statement is best supported by the data?", type: "mcq", choices: ["Remote workers reported the highest satisfaction of the three groups.", "In-office workers were the most satisfied.", "Hybrid workers reported the lowest satisfaction.", "All three groups reported identical satisfaction."], correct: 0, explanation: "82% (remote) exceeds 64% (hybrid) and 61% (in-office), so remote workers reported the highest (choice A)." },
  { id: "t5rw2h-4", section: "rw", domain: "Expression of Ideas", difficulty: "hard", passage: "The treaty was signed with great ceremony. ______, neither side took any steps to honor its terms in the months that followed.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Accordingly", "In practice", "Likewise", "Therefore"], correct: 1, explanation: "A gap between the formal signing and the actual conduct calls for \"In practice.\"" },
  { id: "t5rw2h-5", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "The internship trained her to gather data carefully, to interpret it rigorously, and ______ it clearly to a general audience.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["to present", "presenting", "present", "presented"], correct: 0, explanation: "Parallel with \"to gather\" and \"to interpret\" requires \"to present.\"" },
  { id: "t5rw2h-6", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "Where his early poems were ornate and crowded with imagery, his later work grew almost ______, stripped to a handful of plain words.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["austere", "lavish", "florid", "chaotic"], correct: 0, explanation: "Work stripped to plain words is \"austere,\" the opposite of the early ornate style." },
  { id: "t5rw2h-7", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "Whereas previous biographers cast the composer as a solitary genius, this study locates him within a busy network of collaborators and rivals.", prompt: "Which choice best describes the main purpose of the text?", type: "mcq", choices: ["To revise the lone-genius portrayal by situating the composer among his peers.", "To confirm that the composer worked entirely alone.", "To rank the composer above his rivals.", "To deny that the composer had any talent."], correct: 0, explanation: "\"Whereas previous biographers …\" signals a revision: the study replaces the solitary image with a networked one (choice A)." },
  { id: "t5rw2h-8", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "The drought lasted nearly two years ______ the reservoir never fully emptied, thanks to careful rationing.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["years, the", "years; the", "years the", "years: the"], correct: 1, explanation: "Two independent clauses are joined by a semicolon." },
];
const T5_M_M1: SatQuestion[] = [
  { id: "t5m1-1", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 7x − 4 = 31, what is the value of x?", type: "grid", gridAnswers: ["5"], explanation: "7x = 35, so x = 5." },
  { id: "t5m1-2", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "A recipe uses 3 cups of flour to make 12 muffins. How many cups of flour are needed to make 20 muffins?", type: "mcq", choices: ["5", "4", "6", "8"], correct: 0, explanation: "Flour per muffin is 3/12 = 0.25 cup; 0.25 × 20 = 5 cups." },
  { id: "t5m1-3", section: "math", domain: "Advanced Math", difficulty: "med", prompt: "If f(x) = x² − 3x + 2, what is the value of f(5)?", type: "mcq", choices: ["12", "10", "7", "17"], correct: 0, explanation: "f(5) = 25 − 15 + 2 = 12." },
  { id: "t5m1-4", section: "math", domain: "Geometry and Trigonometry", difficulty: "med", prompt: "A circle has a radius of 5. What is its diameter?", type: "grid", gridAnswers: ["10"], explanation: "Diameter = 2 × radius = 2 × 5 = 10." },
  { id: "t5m1-5", section: "math", domain: "Algebra", difficulty: "med", prompt: "The line y = 2x + b passes through the point (3, 10). What is the value of b?", type: "grid", gridAnswers: ["4"], explanation: "10 = 2(3) + b = 6 + b, so b = 4." },
  { id: "t5m1-6", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "The average of 4 numbers is 15. What is their sum?", type: "mcq", choices: ["60", "30", "45", "19"], correct: 0, explanation: "Sum = average × count = 15 × 4 = 60." },
];
const T5_M_M2E: SatQuestion[] = [
  { id: "t5m2e-1", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If x + 7 = 16, what is the value of x?", type: "grid", gridAnswers: ["9"], explanation: "x = 16 − 7 = 9." },
  { id: "t5m2e-2", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "What is 10% of 90?", type: "mcq", choices: ["9", "10", "18", "80"], correct: 0, explanation: "0.10 × 90 = 9." },
  { id: "t5m2e-3", section: "math", domain: "Geometry and Trigonometry", difficulty: "easy", prompt: "A rectangle has a length of 7 and a width of 4. What is its perimeter?", type: "grid", gridAnswers: ["22"], explanation: "Perimeter = 2(7 + 4) = 2 × 11 = 22." },
  { id: "t5m2e-4", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If 6x = 42, what is the value of x?", type: "mcq", choices: ["7", "6", "36", "8"], correct: 0, explanation: "x = 42 ÷ 6 = 7." },
  { id: "t5m2e-5", section: "math", domain: "Advanced Math", difficulty: "easy", prompt: "What is the value of 2³?", type: "grid", gridAnswers: ["8"], explanation: "2³ = 2 × 2 × 2 = 8." },
  { id: "t5m2e-6", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "There are 8 red marbles and 12 blue marbles in a jar. What fraction of the marbles are red?", type: "mcq", choices: ["2/5", "1/2", "8/12", "3/5"], correct: 0, explanation: "8 red out of 20 total = 8/20 = 2/5." },
];
const T5_M_M2H: SatQuestion[] = [
  { id: "t5m2h-1", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If x² − 49 = 0 and x > 0, what is the value of x?", type: "grid", gridAnswers: ["7"], explanation: "x² = 49, so x = 7 (taking the positive root)." },
  { id: "t5m2h-2", section: "math", domain: "Algebra", difficulty: "hard", prompt: "If 3x + 2y = 18 and y = 3, what is the value of x?", type: "mcq", choices: ["4", "6", "5", "8"], correct: 0, explanation: "3x + 2(3) = 18 → 3x + 6 = 18 → 3x = 12 → x = 4." },
  { id: "t5m2h-3", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If 3^x = 81, what is the value of x?", type: "grid", gridAnswers: ["4"], explanation: "81 = 3⁴, so x = 4." },
  { id: "t5m2h-4", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "hard", prompt: "A population grows from 250 to 300. What is the percent increase?", type: "mcq", choices: ["20%", "25%", "50%", "16%"], correct: 0, explanation: "Increase = 50; 50 ÷ 250 = 0.20 = 20%." },
  { id: "t5m2h-5", section: "math", domain: "Geometry and Trigonometry", difficulty: "hard", prompt: "A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?", type: "grid", gridAnswers: ["13"], explanation: "√(25 + 144) = √169 = 13." },
  { id: "t5m2h-6", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If k(x) = 4x − 1, what is the value of k(k(2))?", type: "mcq", choices: ["27", "7", "11", "23"], correct: 0, explanation: "k(2) = 4(2) − 1 = 7; k(7) = 4(7) − 1 = 27." },
];

export const SAT_FORM_5: SatForm = {
  id: "practice-5",
  title: "InHero SAT Practice Test 5",
  rw: { m1: T5_RW_M1, m2easy: T5_RW_M2E, m2hard: T5_RW_M2H, timeSec: 1080 },
  math: { m1: T5_M_M1, m2easy: T5_M_M2E, m2hard: T5_M_M2H, timeSec: 1080 },
};
