import type { SatQuestion } from "./types";

/** Practice Tests 2 & 3 — third expansion batch (original, hand-verified).
 *  Brings each module to R&W 16 / Math 14. */

// ── Test 2 ──
export const T2_RW_M1_C: SatQuestion[] = [
  { id: "t2rw1-12", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "The mayor's plan was widely seen as ______, addressing problems that no one else had dared to tackle.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["bold", "timid", "conventional", "minor"], correct: 0, explanation: "Tackling what others avoided is \"bold.\"" },
  { id: "t2rw1-13", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "Each of the proposals ______ at least some merit.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["has", "have", "were", "are"], correct: 0, explanation: "\"Each\" is singular, so \"has.\"" },
  { id: "t2rw1-14", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "The festival runs only on weekends in July; weekday visitors will find the grounds closed.", prompt: "Which statement is best supported by the text?", type: "mcq", choices: ["The festival is closed on a Tuesday in July.", "The festival runs every day in July.", "The festival is open throughout August.", "Weekend visitors are turned away."], correct: 0, explanation: "Weekdays are closed, and Tuesday is a weekday (choice A)." },
  { id: "t2rw1-15", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "The software update fixed the crash that users had reported. ______, it introduced a new minor bug.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Therefore", "However", "Moreover", "Hence"], correct: 1, explanation: "A fix followed by a new problem is a contrast — \"However.\"" },
  { id: "t2rw1-16", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "Her handwriting was so ______ that the pharmacist could not read the prescription.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["illegible", "elegant", "bold", "large"], correct: 0, explanation: "Unreadable handwriting is \"illegible.\"" },
];
export const T2_RW_M2E_C: SatQuestion[] = [
  { id: "t2rw2e-12", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The lemon was very ______, so she made a funny face after biting it.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["sour", "sweet", "soft", "warm"], correct: 0, explanation: "Lemons taste \"sour.\"" },
  { id: "t2rw2e-13", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "The keys ______ on the kitchen counter.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["is", "are", "was", "am"], correct: 1, explanation: "\"Keys\" is plural, so \"are.\"" },
  { id: "t2rw2e-14", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Owls hunt at night. Their large eyes and sharp hearing help them find prey in the dark.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Owls are well suited to hunting at night.", "Owls hunt only in the daytime.", "Owls cannot hear very well.", "Owls have very small eyes."], correct: 0, explanation: "Big eyes and good hearing make owls night hunters (choice A)." },
  { id: "t2rw2e-15", section: "rw", domain: "Expression of Ideas", difficulty: "easy", passage: "The fire alarm rang loudly. ______, everyone left the building.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["However", "So", "For example", "Meanwhile"], correct: 1, explanation: "The alarm caused everyone to leave — \"So.\"" },
  { id: "t2rw2e-16", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "Yesterday he ______ his bike all the way to school.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["ride", "rides", "rode", "riding"], correct: 2, explanation: "\"Yesterday\" requires the past tense \"rode.\"" },
];
export const T2_RW_M2H_C: SatQuestion[] = [
  { id: "t2rw2h-12", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "The essay's central claims are ______, supported at every step by carefully chosen evidence.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["well-founded", "dubious", "unsupported", "reckless"], correct: 0, explanation: "Claims backed by evidence are \"well-founded.\"" },
  { id: "t2rw2h-13", section: "rw", domain: "Expression of Ideas", difficulty: "hard", passage: "The two theories agree on the basic facts. ______, they draw opposite conclusions from them.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Therefore", "Yet", "Likewise", "Thus"], correct: 1, explanation: "Agreement on facts but opposite conclusions is a contrast — \"Yet.\"" },
  { id: "t2rw2h-14", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "A city's recycling rate was 22% in 2010, 41% in 2015, and 47% in 2020.", prompt: "Which statement is best supported by the data?", type: "mcq", choices: ["The recycling rate rose most sharply between 2010 and 2015.", "The recycling rate fell over the decade.", "The rate was highest in 2010.", "The rate stayed the same throughout."], correct: 0, explanation: "22 to 41 is +19; 41 to 47 is +6 — the sharper rise is 2010 to 2015 (choice A)." },
  { id: "t2rw2h-15", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "Good design means removing clutter, clarifying choices, and ______ the user's attention.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["to guide", "guiding", "guide", "guided"], correct: 1, explanation: "Parallel with \"removing\" and \"clarifying\" requires \"guiding.\"" },
  { id: "t2rw2h-16", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "His ______ remarks, though brief, conveyed more than a long speech could have.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["pithy", "verbose", "rambling", "evasive"], correct: 0, explanation: "Brief but meaningful is \"pithy.\"" },
];
export const T2_M_M1_C: SatQuestion[] = [
  { id: "t2m1-10", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 9x = 72, what is the value of x?", type: "grid", gridAnswers: ["8"], explanation: "x = 72 ÷ 9 = 8." },
  { id: "t2m1-11", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "A team won 18 of its 24 games. What percent of its games did it win?", type: "mcq", choices: ["75%", "60%", "80%", "70%"], correct: 0, explanation: "18 ÷ 24 = 0.75 = 75%." },
  { id: "t2m1-12", section: "math", domain: "Advanced Math", difficulty: "med", prompt: "If f(x) = x² − 4, what is the value of f(5)?", type: "mcq", choices: ["21", "6", "16", "9"], correct: 0, explanation: "f(5) = 25 − 4 = 21." },
  { id: "t2m1-13", section: "math", domain: "Geometry and Trigonometry", difficulty: "med", prompt: "A rectangle has an area of 48 and a width of 6. What is its length?", type: "grid", gridAnswers: ["8"], explanation: "Length = area ÷ width = 48 ÷ 6 = 8." },
  { id: "t2m1-14", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 5x + 4 = 3x + 14, what is the value of x?", type: "grid", gridAnswers: ["5"], explanation: "2x = 10, so x = 5." },
];
export const T2_M_M2E_C: SatQuestion[] = [
  { id: "t2m2e-10", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If x + 11 = 20, what is the value of x?", type: "grid", gridAnswers: ["9"], explanation: "x = 20 − 11 = 9." },
  { id: "t2m2e-11", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "What is 40% of 25?", type: "mcq", choices: ["10", "15", "40", "5"], correct: 0, explanation: "0.40 × 25 = 10." },
  { id: "t2m2e-12", section: "math", domain: "Geometry and Trigonometry", difficulty: "easy", prompt: "A square has a side length of 9. What is its area?", type: "grid", gridAnswers: ["81"], explanation: "9² = 81." },
  { id: "t2m2e-13", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If 7x = 49, what is the value of x?", type: "mcq", choices: ["7", "42", "56", "6"], correct: 0, explanation: "x = 49 ÷ 7 = 7." },
  { id: "t2m2e-14", section: "math", domain: "Advanced Math", difficulty: "easy", prompt: "What is the value of 5²?", type: "grid", gridAnswers: ["25"], explanation: "5 × 5 = 25." },
];
export const T2_M_M2H_C: SatQuestion[] = [
  { id: "t2m2h-10", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If 3^x = 27, what is the value of x?", type: "grid", gridAnswers: ["3"], explanation: "27 = 3³, so x = 3." },
  { id: "t2m2h-11", section: "math", domain: "Algebra", difficulty: "hard", prompt: "If x + y = 10 and y = 2x + 1, what is the value of x?", type: "mcq", choices: ["3", "4", "2", "7"], correct: 0, explanation: "x + (2x + 1) = 10 → 3x = 9 → x = 3." },
  { id: "t2m2h-12", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "hard", prompt: "A $120 item is discounted by 15%. What is the sale price?", type: "mcq", choices: ["$102", "$105", "$108", "$100"], correct: 0, explanation: "15% of 120 = 18; 120 − 18 = $102." },
  { id: "t2m2h-13", section: "math", domain: "Geometry and Trigonometry", difficulty: "hard", prompt: "A circle has a radius of 6. Its area equals kπ. What is the value of k?", type: "grid", gridAnswers: ["36"], explanation: "Area = π(6²) = 36π, so k = 36." },
  { id: "t2m2h-14", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If x² − 10x + 21 = 0 and x > 4, what is the value of x?", type: "grid", gridAnswers: ["7"], explanation: "(x − 3)(x − 7) = 0 → x = 3 or 7; since x > 4, x = 7." },
];

// ── Test 3 ──
export const T3_RW_M1_C: SatQuestion[] = [
  { id: "t3rw1-12", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "The coach's praise was ______, offered only when it was genuinely earned.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["sparing", "constant", "empty", "excessive"], correct: 0, explanation: "Given only when earned means praise was \"sparing.\"" },
  { id: "t3rw1-13", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "The team celebrated ______ hard-won championship victory.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["its", "it's", "their", "they're"], correct: 0, explanation: "Singular \"team\" takes \"its.\"" },
  { id: "t3rw1-14", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "The discount applies only to purchases over $50; smaller orders pay full price.", prompt: "Which statement is best supported by the text?", type: "mcq", choices: ["A $40 order does not receive the discount.", "Every order receives the discount.", "A $60 order pays full price.", "No order can receive the discount."], correct: 0, explanation: "Under $50 pays full price, so a $40 order gets no discount (choice A)." },
  { id: "t3rw1-15", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "The proposal was popular with local residents. ______, the council voted to reject it.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Therefore", "Nevertheless", "Moreover", "Likewise"], correct: 1, explanation: "Popular yet rejected is a contrast — \"Nevertheless.\"" },
  { id: "t3rw1-16", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "The courtroom fell ______ as the judge entered and everyone stopped talking.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["silent", "loud", "bright", "warm"], correct: 0, explanation: "Everyone stopping talking makes the room \"silent.\"" },
];
export const T3_RW_M2E_C: SatQuestion[] = [
  { id: "t3rw2e-12", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The ice cream was very ______, so we ate it quickly before it melted.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["cold", "hot", "spicy", "dry"], correct: 0, explanation: "Ice cream that can melt is \"cold.\"" },
  { id: "t3rw2e-13", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "The students ______ ready for the big test.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["is", "are", "was", "am"], correct: 1, explanation: "\"Students\" is plural, so \"are.\"" },
  { id: "t3rw2e-14", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Trees give off oxygen and provide homes for many kinds of animals.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Trees are helpful to the environment and to animals.", "Trees are harmful to the environment.", "Trees give off only carbon dioxide.", "No animals live in trees."], correct: 0, explanation: "Oxygen plus animal homes = helpful (choice A)." },
  { id: "t3rw2e-15", section: "rw", domain: "Expression of Ideas", difficulty: "easy", passage: "He saved his allowance for months. ______, he bought the bicycle he wanted.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["However", "Finally", "For example", "Instead"], correct: 1, explanation: "After a long wait, he reaches the goal — \"Finally.\"" },
  { id: "t3rw2e-16", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "She read ______ interesting book over the weekend.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["a", "an", "the only", "some"], correct: 1, explanation: "\"Interesting\" begins with a vowel sound, so \"an.\"" },
];
export const T3_RW_M2H_C: SatQuestion[] = [
  { id: "t3rw2h-12", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "The film's plot is ______, weaving three separate timelines into a single coherent story.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["intricate", "simplistic", "predictable", "dull"], correct: 0, explanation: "Three interwoven timelines make it \"intricate.\"" },
  { id: "t3rw2h-13", section: "rw", domain: "Expression of Ideas", difficulty: "hard", passage: "The data are striking. ______, they come from a single small study and should be treated with caution.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Therefore", "However", "Similarly", "Thus"], correct: 1, explanation: "Impressive data undercut by a caveat is a contrast — \"However.\"" },
  { id: "t3rw2h-14", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "Participants' average daily steps were 4,200 before a fitness program, 7,800 during it, and 6,500 one year later.", prompt: "Which statement is best supported by the data?", type: "mcq", choices: ["Step counts rose during the program and then fell partway back afterward.", "Step counts fell during the program.", "Step counts were highest a year later.", "The program had no effect on step counts."], correct: 0, explanation: "4,200 to 7,800 (rise), then to 6,500 (partial drop, still above baseline) — choice A." },
  { id: "t3rw2h-15", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "The role calls for managing budgets, leading teams, and ______ with senior executives.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["to communicate", "communicating", "communicate", "communicated"], correct: 1, explanation: "Parallel with \"managing\" and \"leading\" requires \"communicating.\"" },
  { id: "t3rw2h-16", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "Her tone was ______, betraying neither excitement nor disappointment at the news.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["measured", "frantic", "gleeful", "bitter"], correct: 0, explanation: "Showing no strong emotion either way is a \"measured\" tone." },
];
export const T3_M_M1_C: SatQuestion[] = [
  { id: "t3m1-10", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 7x − 5 = 30, what is the value of x?", type: "grid", gridAnswers: ["5"], explanation: "7x = 35, so x = 5." },
  { id: "t3m1-11", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "A store sells 5 pens for $2.00. At that rate, how much do 20 pens cost?", type: "mcq", choices: ["$8.00", "$10.00", "$6.00", "$40.00"], correct: 0, explanation: "Each pen is 2 ÷ 5 = $0.40; 20 × 0.40 = $8.00." },
  { id: "t3m1-12", section: "math", domain: "Advanced Math", difficulty: "med", prompt: "If g(x) = 2x² + 1, what is the value of g(3)?", type: "mcq", choices: ["19", "13", "37", "7"], correct: 0, explanation: "g(3) = 2(9) + 1 = 19." },
  { id: "t3m1-13", section: "math", domain: "Geometry and Trigonometry", difficulty: "med", prompt: "A triangle has two angles measuring 30° and 70°. What is the third angle, in degrees?", type: "grid", gridAnswers: ["80"], explanation: "180 − 30 − 70 = 80°." },
  { id: "t3m1-14", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 6x + 2 = 2x + 18, what is the value of x?", type: "grid", gridAnswers: ["4"], explanation: "4x = 16, so x = 4." },
];
export const T3_M_M2E_C: SatQuestion[] = [
  { id: "t3m2e-10", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If x − 7 = 2, what is the value of x?", type: "grid", gridAnswers: ["9"], explanation: "x = 2 + 7 = 9." },
  { id: "t3m2e-11", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "What is 60% of 20?", type: "mcq", choices: ["12", "8", "60", "14"], correct: 0, explanation: "0.60 × 20 = 12." },
  { id: "t3m2e-12", section: "math", domain: "Geometry and Trigonometry", difficulty: "easy", prompt: "A square has a side length of 5. What is its area?", type: "grid", gridAnswers: ["25"], explanation: "5² = 25." },
  { id: "t3m2e-13", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If 3x = 24, what is the value of x?", type: "mcq", choices: ["8", "21", "27", "6"], correct: 0, explanation: "x = 24 ÷ 3 = 8." },
  { id: "t3m2e-14", section: "math", domain: "Advanced Math", difficulty: "easy", prompt: "What is the value of 4³?", type: "grid", gridAnswers: ["64"], explanation: "4 × 4 × 4 = 64." },
];
export const T3_M_M2H_C: SatQuestion[] = [
  { id: "t3m2h-10", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If 2^x = 16, what is the value of x?", type: "grid", gridAnswers: ["4"], explanation: "16 = 2⁴, so x = 4." },
  { id: "t3m2h-11", section: "math", domain: "Algebra", difficulty: "hard", prompt: "If 2x − y = 5 and x = 4, what is the value of y?", type: "mcq", choices: ["3", "5", "13", "2"], correct: 0, explanation: "2(4) − y = 5 → 8 − y = 5 → y = 3." },
  { id: "t3m2h-12", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "hard", prompt: "A population grows from 200 to 250. What is the percent increase?", type: "mcq", choices: ["25%", "20%", "50%", "30%"], correct: 0, explanation: "Increase = 50; 50 ÷ 200 = 0.25 = 25%." },
  { id: "t3m2h-13", section: "math", domain: "Geometry and Trigonometry", difficulty: "hard", prompt: "A right triangle has legs of length 7 and 24. What is the length of the hypotenuse?", type: "grid", gridAnswers: ["25"], explanation: "√(49 + 576) = √625 = 25." },
  { id: "t3m2h-14", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If x² − 6x + 8 = 0 and x > 3, what is the value of x?", type: "grid", gridAnswers: ["4"], explanation: "(x − 2)(x − 4) = 0 → x = 2 or 4; since x > 3, x = 4." },
];
