import type { SatQuestion } from "./types";

/**
 * Practice Test 1 — third batch of original, hand-verified items. Brings each
 * Reading & Writing module to 27 and each Math module to 22 questions — the
 * real Digital SAT module counts.
 */

export const RW_M1_X3: SatQuestion[] = [
  { id: "rw1-18", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "The critic's review was surprisingly ______, praising nearly every aspect of a film that other reviewers had panned.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["favorable", "scathing", "indifferent", "brief"], correct: 0,
    explanation: "Praising nearly everything makes the review \"favorable\"; \"scathing\" is its opposite." },
  { id: "rw1-19", section: "rw", domain: "Standard English Conventions", difficulty: "med",
    passage: "All of the students must submit ______ projects by Friday afternoon.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["their", "there", "they're", "its"], correct: 0,
    explanation: "The plural \"students\" takes the plural possessive \"their.\"" },
  { id: "rw1-20", section: "rw", domain: "Information and Ideas", difficulty: "med",
    passage: "Coral reefs cover less than 1% of the ocean floor, yet they shelter roughly a quarter of all known marine species.",
    prompt: "Which choice best states the main idea of the text?",
    type: "mcq", choices: [
      "Coral reefs support a share of marine life that is large relative to their size.",
      "Coral reefs cover most of the ocean floor.",
      "Very few species live in coral reefs.",
      "Coral reefs are unimportant to the ocean.",
    ], correct: 0,
    explanation: "Tiny area (<1%) but a quarter of species — a disproportionately large role (choice A)." },
  { id: "rw1-21", section: "rw", domain: "Expression of Ideas", difficulty: "med",
    passage: "The new bridge was completed ahead of schedule. ______, it came in well under budget.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["However", "Moreover", "Nevertheless", "Otherwise"], correct: 1,
    explanation: "A second piece of good news is added — \"Moreover.\"" },
  { id: "rw1-22", section: "rw", domain: "Standard English Conventions", difficulty: "med",
    passage: "The experiment failed the first time ______ the team refined the procedure and ran it again.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["time, the", "time; the", "time the", "time: the"], correct: 1,
    explanation: "Two independent clauses are joined with a semicolon; a comma alone would be a splice." },
  { id: "rw1-23", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "Once a ______ village, the town has become a bustling commuter hub since the new rail line opened.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["sleepy", "crowded", "modern", "dangerous"], correct: 0,
    explanation: "\"Once a ______ village … has become bustling\" sets up a contrast — it used to be \"sleepy.\"" },
  { id: "rw1-24", section: "rw", domain: "Information and Ideas", difficulty: "med",
    passage: "Unlike most birds, the kiwi has nostrils at the very tip of its long beak, which it uses to sniff out insects hidden underground.",
    prompt: "Which statement is best supported by the text?",
    type: "mcq", choices: [
      "The kiwi locates food using its sense of smell.",
      "The kiwi has no sense of smell.",
      "The kiwi hunts only by sight during the day.",
      "All birds have nostrils at the tips of their beaks.",
    ], correct: 0,
    explanation: "It \"sniff[s] out insects\" with tip-of-beak nostrils — it finds food by smell (choice A)." },
  { id: "rw1-25", section: "rw", domain: "Standard English Conventions", difficulty: "med",
    passage: "The list of approved vendors ______ posted on the company website each quarter.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["is", "are", "were", "have been"], correct: 0,
    explanation: "The subject is the singular \"list\" (not \"vendors\"), so \"is\" is correct." },
  { id: "rw1-26", section: "rw", domain: "Expression of Ideas", difficulty: "med",
    passage: "Solar power is clean and increasingly inexpensive. ______, it cannot generate electricity at night without some form of storage.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["Therefore", "Still", "Likewise", "Thus"], correct: 1,
    explanation: "A limitation is set against the advantages — the concessive \"Still.\"" },
  { id: "rw1-27", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "The novel's narrator frequently interrupts the action to address the reader directly, breaking the illusion that the story is unfolding on its own.",
    prompt: "Which choice best describes the effect of the narrator's direct address?",
    type: "mcq", choices: [
      "It reminds readers that they are reading a deliberately constructed story.",
      "It makes the events feel completely realistic.",
      "It conceals the narrator's presence entirely.",
      "It signals that the novel has ended.",
    ], correct: 0,
    explanation: "\"Breaking the illusion\" foregrounds the story's constructedness (choice A)." },
];

export const RW_M2_EASY_X3: SatQuestion[] = [
  { id: "rw2e-18", section: "rw", domain: "Craft and Structure", difficulty: "easy",
    passage: "The cake was so ______ that everyone asked for a second slice.",
    prompt: "Which choice completes the text with the most logical word?",
    type: "mcq", choices: ["delicious", "stale", "dry", "plain"], correct: 0,
    explanation: "Asking for seconds means it tasted \"delicious.\"" },
  { id: "rw2e-19", section: "rw", domain: "Standard English Conventions", difficulty: "easy",
    passage: "There ______ three books lying on the table.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["is", "are", "was", "am"], correct: 1,
    explanation: "\"Three books\" is plural, so \"are\" is correct." },
  { id: "rw2e-20", section: "rw", domain: "Information and Ideas", difficulty: "easy",
    passage: "Bats are the only mammals that can truly fly. Their wings are made of thin skin stretched between long finger bones.",
    prompt: "Which choice best states the main idea of the text?",
    type: "mcq", choices: [
      "Bats are mammals that fly using skin-covered wings.",
      "Bats are a kind of bird.",
      "Bats are unable to fly.",
      "Bats have feathered wings.",
    ], correct: 0,
    explanation: "The text says bats are flying mammals with skin wings (choice A)." },
  { id: "rw2e-21", section: "rw", domain: "Expression of Ideas", difficulty: "easy",
    passage: "He studied hard every night that week. ______, he passed the exam easily.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["However", "As a result", "For example", "Instead"], correct: 1,
    explanation: "Studying caused the easy pass — \"As a result.\"" },
  { id: "rw2e-22", section: "rw", domain: "Standard English Conventions", difficulty: "easy",
    passage: "We spotted ______ owl perched in the tree at dusk.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["a", "an", "the only", "some"], correct: 1,
    explanation: "\"Owl\" starts with a vowel sound, so \"an\" is correct." },
  { id: "rw2e-23", section: "rw", domain: "Craft and Structure", difficulty: "easy",
    passage: "The basement was so ______ that we had to turn on every light to see.",
    prompt: "Which choice completes the text with the most logical word?",
    type: "mcq", choices: ["dark", "bright", "loud", "warm"], correct: 0,
    explanation: "Needing all the lights means it was \"dark.\"" },
  { id: "rw2e-24", section: "rw", domain: "Information and Ideas", difficulty: "easy",
    passage: "Plants make their own food from sunlight, water, and carbon dioxide in a process called photosynthesis.",
    prompt: "Which choice best states the main idea of the text?",
    type: "mcq", choices: [
      "Plants use sunlight to make their own food.",
      "Plants get food by eating animals.",
      "Plants do not need any water.",
      "Plants cannot make their own food.",
    ], correct: 0,
    explanation: "Photosynthesis is plants making food from sunlight (choice A)." },
  { id: "rw2e-25", section: "rw", domain: "Standard English Conventions", difficulty: "easy",
    passage: "Last night the whole family ______ a movie together at the theater.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["watch", "watches", "watched", "watching"], correct: 2,
    explanation: "\"Last night\" requires the past tense \"watched.\"" },
  { id: "rw2e-26", section: "rw", domain: "Expression of Ideas", difficulty: "easy",
    passage: "The store was already closed when we arrived. ______, we drove back home.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["For example", "Therefore", "However", "Meanwhile"], correct: 1,
    explanation: "The closed store is the reason they went home — \"Therefore.\"" },
  { id: "rw2e-27", section: "rw", domain: "Craft and Structure", difficulty: "easy",
    passage: "She felt very ______ when she won first place in the science fair.",
    prompt: "Which choice completes the text with the most logical word?",
    type: "mcq", choices: ["proud", "sad", "bored", "angry"], correct: 0,
    explanation: "Winning first place would make her feel \"proud.\"" },
];

export const RW_M2_HARD_X3: SatQuestion[] = [
  { id: "rw2h-18", section: "rw", domain: "Craft and Structure", difficulty: "hard",
    passage: "The memoir is refreshingly ______, refusing to flatter its author or to soften her past mistakes.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["candid", "evasive", "grandiose", "sentimental"], correct: 0,
    explanation: "Refusing to flatter or soften = honest and frank — \"candid.\"" },
  { id: "rw2h-19", section: "rw", domain: "Information and Ideas", difficulty: "hard",
    passage: "The paper devotes its opening sections to dismantling a rival theory, clearing the ground before it advances a model of its own.",
    prompt: "Which choice best describes the function of the opening sections?",
    type: "mcq", choices: [
      "They refute a competing theory to prepare for the author's alternative.",
      "They demonstrate that the rival theory is correct.",
      "They summarize the author's own model in detail.",
      "They serve as the paper's conclusion.",
    ], correct: 0,
    explanation: "\"Clearing the ground\" before advancing its own model means refuting the rival first (choice A)." },
  { id: "rw2h-20", section: "rw", domain: "Information and Ideas", difficulty: "hard",
    passage: "Across three cities, average commute times were 22 minutes where bike lanes were extensive, 31 minutes where they were moderate, and 39 minutes where they were minimal.",
    prompt: "Which statement is best supported by the data?",
    type: "mcq", choices: [
      "More extensive bike lanes were associated with shorter average commutes.",
      "Bike lanes lengthened average commutes.",
      "Commute time was unrelated to bike-lane coverage.",
      "Minimal bike lanes produced the shortest commutes.",
    ], correct: 0,
    explanation: "22 < 31 < 39 as coverage drops, so more lanes go with shorter commutes (choice A)." },
  { id: "rw2h-21", section: "rw", domain: "Expression of Ideas", difficulty: "hard",
    passage: "The theory elegantly accounts for nearly all of the observed data. ______, it rests on an assumption that has never been experimentally tested.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["Therefore", "Yet", "Likewise", "Thus"], correct: 1,
    explanation: "A strength followed by a serious caveat is a contrast — \"Yet.\"" },
  { id: "rw2h-22", section: "rw", domain: "Standard English Conventions", difficulty: "hard",
    passage: "The position requires analyzing reports, drafting proposals, and ______ regularly with clients.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["to meet", "meeting", "meet", "met"], correct: 1,
    explanation: "Parallel structure with \"analyzing\" and \"drafting\" requires the gerund \"meeting.\"" },
  { id: "rw2h-23", section: "rw", domain: "Craft and Structure", difficulty: "hard",
    passage: "His ______ tone — neither warm nor hostile — made it impossible to tell whether he approved of the plan.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["neutral", "effusive", "caustic", "jubilant"], correct: 0,
    explanation: "\"Neither warm nor hostile\" defines a \"neutral\" tone." },
  { id: "rw2h-24", section: "rw", domain: "Information and Ideas", difficulty: "hard",
    passage: "Whereas earlier biographers treated the inventor's failures as embarrassing detours, this study treats them as essential rehearsals for his later breakthroughs.",
    prompt: "Which choice best describes the main purpose of the text?",
    type: "mcq", choices: [
      "To contrast a new interpretation of the inventor's failures with earlier ones.",
      "To list each of the inventor's successful inventions.",
      "To argue that the inventor never actually failed.",
      "To dismiss the new study as unconvincing.",
    ], correct: 0,
    explanation: "\"Whereas earlier biographers … this study …\" frames a contrast of interpretations (choice A)." },
  { id: "rw2h-25", section: "rw", domain: "Standard English Conventions", difficulty: "hard",
    passage: "Not only the students but also the teacher ______ surprised by the announcement.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["was", "were", "have been", "are"], correct: 0,
    explanation: "With \"not only … but also,\" the verb agrees with the nearer subject — singular \"teacher\" — so \"was.\"" },
  { id: "rw2h-26", section: "rw", domain: "Expression of Ideas", difficulty: "hard",
    passage: "Most analysts predicted that the currency would weaken sharply. ______, it gained value steadily over the following year.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["Accordingly", "Instead", "Therefore", "Moreover"], correct: 1,
    explanation: "The outcome contradicts the prediction — \"Instead.\"" },
  { id: "rw2h-27", section: "rw", domain: "Craft and Structure", difficulty: "hard",
    passage: "The essay's argument is ______, building each new claim carefully on the one that comes before it.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["cumulative", "haphazard", "circular", "vague"], correct: 0,
    explanation: "Each claim builds on the last — a \"cumulative\" structure." },
];

export const MATH_M1_X3: SatQuestion[] = [
  { id: "m1-16", section: "math", domain: "Algebra", difficulty: "med",
    prompt: "If 2(x + 3) = 16, what is the value of x?",
    type: "grid", gridAnswers: ["5"], explanation: "x + 3 = 8, so x = 5." },
  { id: "m1-17", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med",
    prompt: "If 5 notebooks cost $12.50, how much do 8 notebooks cost at the same price per notebook?",
    type: "mcq", choices: ["$20.00", "$18.00", "$25.00", "$16.00"], correct: 0,
    explanation: "Each costs 12.50 ÷ 5 = $2.50; 8 × 2.50 = $20.00." },
  { id: "m1-18", section: "math", domain: "Advanced Math", difficulty: "med",
    prompt: "If h(x) = 3x² − x, what is the value of h(2)?",
    type: "mcq", choices: ["10", "11", "14", "6"], correct: 0,
    explanation: "h(2) = 3(4) − 2 = 12 − 2 = 10." },
  { id: "m1-19", section: "math", domain: "Geometry and Trigonometry", difficulty: "med",
    prompt: "A circle has a diameter of 14. What is its radius?",
    type: "grid", gridAnswers: ["7"], explanation: "Radius = diameter ÷ 2 = 14 ÷ 2 = 7." },
  { id: "m1-20", section: "math", domain: "Algebra", difficulty: "med",
    prompt: "If (2x − 1) / 3 = 5, what is the value of x?",
    type: "grid", gridAnswers: ["8"], explanation: "2x − 1 = 15 → 2x = 16 → x = 8." },
  { id: "m1-21", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med",
    prompt: "30 is what percent of 120?",
    type: "mcq", choices: ["25%", "30%", "40%", "20%"], correct: 0,
    explanation: "30 ÷ 120 = 0.25 = 25%." },
  { id: "m1-22", section: "math", domain: "Geometry and Trigonometry", difficulty: "med",
    prompt: "A triangle has a base of 10 and a height of 6. What is its area?",
    type: "mcq", choices: ["30", "60", "16", "18"], correct: 0,
    explanation: "Area = ½ × 10 × 6 = 30." },
];

export const MATH_M2_EASY_X3: SatQuestion[] = [
  { id: "m2e-16", section: "math", domain: "Algebra", difficulty: "easy",
    prompt: "If 3x = 21, what is the value of x?",
    type: "grid", gridAnswers: ["7"], explanation: "x = 21 ÷ 3 = 7." },
  { id: "m2e-17", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy",
    prompt: "What is 50% of 80?",
    type: "mcq", choices: ["40", "30", "50", "160"], correct: 0,
    explanation: "50% of 80 = 0.5 × 80 = 40." },
  { id: "m2e-18", section: "math", domain: "Geometry and Trigonometry", difficulty: "easy",
    prompt: "A square has a perimeter of 20. What is the length of one side?",
    type: "grid", gridAnswers: ["5"], explanation: "A square has 4 equal sides: 20 ÷ 4 = 5." },
  { id: "m2e-19", section: "math", domain: "Algebra", difficulty: "easy",
    prompt: "If x + 7 = 10, what is the value of x?",
    type: "mcq", choices: ["3", "17", "7", "4"], correct: 0, explanation: "x = 10 − 7 = 3." },
  { id: "m2e-20", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy",
    prompt: "A bag holds 10 marbles, and 4 of them are red. How many marbles are not red?",
    type: "grid", gridAnswers: ["6"], explanation: "10 − 4 = 6." },
  { id: "m2e-21", section: "math", domain: "Advanced Math", difficulty: "easy",
    prompt: "What is the value of 4²?",
    type: "mcq", choices: ["16", "8", "12", "4"], correct: 0, explanation: "4² = 4 × 4 = 16." },
  { id: "m2e-22", section: "math", domain: "Algebra", difficulty: "easy",
    prompt: "If 10 − x = 6, what is the value of x?",
    type: "grid", gridAnswers: ["4"], explanation: "x = 10 − 6 = 4." },
];

export const MATH_M2_HARD_X3: SatQuestion[] = [
  { id: "m2h-16", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If x² − 7x + 12 = 0 and x > 3, what is the value of x?",
    type: "grid", gridAnswers: ["4"], explanation: "(x − 3)(x − 4) = 0 → x = 3 or 4; since x > 3, x = 4." },
  { id: "m2h-17", section: "math", domain: "Algebra", difficulty: "hard",
    prompt: "If 2x + 3y = 16 and x = y + 3, what is the value of y?",
    type: "mcq", choices: ["2", "3", "4", "5"], correct: 0,
    explanation: "2(y + 3) + 3y = 16 → 5y + 6 = 16 → 5y = 10 → y = 2." },
  { id: "m2h-18", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "hard",
    prompt: "A price falls from $80 to $60. What is the percent decrease?",
    type: "mcq", choices: ["25%", "20%", "30%", "33%"], correct: 0,
    explanation: "Decrease = 20; 20 ÷ 80 = 0.25 = 25%." },
  { id: "m2h-19", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If 4^x = 64, what is the value of x?",
    type: "grid", gridAnswers: ["3"], explanation: "64 = 4³, so x = 3." },
  { id: "m2h-20", section: "math", domain: "Geometry and Trigonometry", difficulty: "hard",
    prompt: "A right triangle has legs of length 8 and 15. What is the length of the hypotenuse?",
    type: "grid", gridAnswers: ["17"], explanation: "√(8² + 15²) = √(64 + 225) = √289 = 17." },
  { id: "m2h-21", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If f(x) = 2x − 1 and g(x) = x², what is the value of f(g(3))?",
    type: "mcq", choices: ["17", "11", "8", "5"], correct: 0,
    explanation: "g(3) = 9; f(9) = 2(9) − 1 = 17." },
  { id: "m2h-22", section: "math", domain: "Algebra", difficulty: "hard",
    prompt: "Three consecutive integers have a sum of 48. What is the largest of the three?",
    type: "grid", gridAnswers: ["17"], explanation: "Middle = 48 ÷ 3 = 16, so the integers are 15, 16, 17; the largest is 17." },
];
