import type { SatForm, SatQuestion } from "./types";

/**
 * Practice Test 4 — an additional adaptive form (original, hand-verified
 * items). Each module is a focused set (R&W 8, Math 6) with the full adaptive
 * structure. Topics and passages are distinct from Practice Tests 1–3.
 */

// ─────────────────────────── PRACTICE TEST 4 ───────────────────────────
const T4_RW_M1: SatQuestion[] = [
  { id: "t4rw1-1", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "The diplomat's ______ remarks managed to calm both delegations without committing her government to anything.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["conciliatory", "inflammatory", "indifferent", "boastful"], correct: 0, explanation: "Calming both sides points to \"conciliatory.\"" },
  { id: "t4rw1-2", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "Each of the volunteers ______ assigned a different neighborhood to canvass.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["were", "was", "are", "have been"], correct: 1, explanation: "\"Each\" is singular, so the singular verb \"was\" is correct." },
  { id: "t4rw1-3", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "Octopuses can change both the color and the texture of their skin within seconds, blending into coral, sand, or rock to avoid predators.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Octopuses rapidly alter their skin to camouflage themselves.", "Octopuses are unable to hide from predators.", "Octopuses can change only their color, never their texture.", "Octopuses prefer to live far from coral and rock."], correct: 0, explanation: "Changing color and texture to blend in is camouflage (choice A)." },
  { id: "t4rw1-4", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "The original engine ran on coal. ______, modern versions of the locomotive use electricity drawn from overhead wires.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["For instance", "By contrast", "As a result", "In addition"], correct: 1, explanation: "Coal then versus electricity now is a contrast — \"By contrast.\"" },
  { id: "t4rw1-5", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "The expedition reached three landmarks ______ a frozen lake, a hidden valley, and an ancient bridge.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["landmarks, a", "landmarks: a", "landmarks; a", "landmarks a"], correct: 1, explanation: "A colon introduces the list that specifies the \"three landmarks.\"" },
  { id: "t4rw1-6", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "Far from being ______, the proposal borrowed heavily from ideas the committee had already rejected.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["novel", "expensive", "lengthy", "popular"], correct: 0, explanation: "Borrowing from old, rejected ideas means it was not \"novel\" (new)." },
  { id: "t4rw1-7", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "The grant is available only to researchers who have already published at least one peer-reviewed paper; first-time authors are not eligible.", prompt: "Which statement is best supported by the text?", type: "mcq", choices: ["A researcher with no published papers cannot receive the grant.", "Any researcher may apply regardless of publications.", "First-time authors are given priority for the grant.", "The grant requires at least ten published papers."], correct: 0, explanation: "First-time authors are not eligible, so someone unpublished cannot receive it (choice A)." },
  { id: "t4rw1-8", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "The bridge passed every safety inspection. ______, engineers recommended reinforcing it before the next decade of heavy traffic.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Therefore", "Even so", "For example", "Likewise"], correct: 1, explanation: "Passing inspection yet still recommending reinforcement is a concession — \"Even so.\"" },
];
const T4_RW_M2E: SatQuestion[] = [
  { id: "t4rw2e-1", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The soup was too ______, so I added some cold water to cool it down.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["hot", "sweet", "empty", "quiet"], correct: 0, explanation: "Adding cold water to cool it means the soup was \"hot.\"" },
  { id: "t4rw2e-2", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "The two dogs ______ barking at the mail carrier.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["is", "are", "was", "am"], correct: 1, explanation: "\"Two dogs\" is plural, so \"are.\"" },
  { id: "t4rw2e-3", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Penguins are birds, but instead of flying they use their wings as flippers to swim quickly through the water.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Penguins use their wings to swim rather than fly.", "Penguins can fly long distances.", "Penguins do not have wings.", "Penguins cannot move in water."], correct: 0, explanation: "Their wings act as flippers for swimming (choice A)." },
  { id: "t4rw2e-4", section: "rw", domain: "Expression of Ideas", difficulty: "easy", passage: "The library was closing soon. ______, I returned my books and left.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["For example", "So", "However", "Meanwhile"], correct: 1, explanation: "The closing is the reason for leaving — \"So.\"" },
  { id: "t4rw2e-5", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "Last weekend we ______ a movie at the new theater downtown.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["watch", "watches", "watched", "watching"], correct: 2, explanation: "\"Last weekend\" requires the past tense \"watched.\"" },
  { id: "t4rw2e-6", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The bread was ______ and crunchy because it had been baked too long.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["hard", "soft", "wet", "cold"], correct: 0, explanation: "Baked too long and crunchy means it was \"hard.\"" },
  { id: "t4rw2e-7", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Recycling saves energy, reduces waste, and protects natural resources for the future.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Recycling provides several environmental benefits.", "Recycling wastes more energy than it saves.", "Recycling has only one purpose.", "Recycling harms natural resources."], correct: 0, explanation: "Three benefits are listed — choice A." },
  { id: "t4rw2e-8", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "We waited for nearly ______ hour before the train finally arrived.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["a", "an", "the only", "some"], correct: 1, explanation: "\"Hour\" begins with a silent h (a vowel sound), so \"an.\"" },
];
const T4_RW_M2H: SatQuestion[] = [
  { id: "t4rw2h-1", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "The memoir is ______ to a fault: the author dwells on minor grievances long after the reader has grasped the point.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["self-indulgent", "concise", "impartial", "reticent"], correct: 0, explanation: "Dwelling at length on personal grievances is \"self-indulgent.\"" },
  { id: "t4rw2h-2", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "The essay opens with a vivid anecdote about a single farmer, then widens its lens to a continent-spanning analysis of agricultural policy.", prompt: "Which choice best describes the function of the opening anecdote?", type: "mcq", choices: ["To ground a broad policy discussion in a concrete human example.", "To state the essay's statistical conclusion.", "To list the essay's sources.", "To refute the policy analysis that follows."], correct: 0, explanation: "The anecdote grounds the later broad analysis in a specific case (choice A)." },
  { id: "t4rw2h-3", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "A factory's defect rate was 9.0% before automation, 3.2% one year after, and 2.9% two years after.", prompt: "Which statement is best supported by the data?", type: "mcq", choices: ["Most of the reduction in defects occurred within the first year of automation.", "The defect rate rose after automation.", "Automation eliminated all defects.", "The defect rate was unchanged by automation."], correct: 0, explanation: "9.0% to 3.2% is a large drop; 3.2% to 2.9% is small — most reduction is in year one (choice A)." },
  { id: "t4rw2h-4", section: "rw", domain: "Expression of Ideas", difficulty: "hard", passage: "The theory elegantly explains the planet's orbit. ______, it fails to account for the small wobble astronomers have repeatedly measured.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Consequently", "Nonetheless", "Similarly", "Accordingly"], correct: 1, explanation: "A strength followed by an unexplained flaw is a contrast — \"Nonetheless.\"" },
  { id: "t4rw2h-5", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "The training program asks recruits to follow orders precisely, to adapt quickly, and ______ independently when no order is given.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["to act", "acting", "act", "acted"], correct: 0, explanation: "Parallel with \"to follow\" and \"to adapt\" requires \"to act.\"" },
  { id: "t4rw2h-6", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "The witness's account was so ______ that even the defense attorney could find no contradiction to exploit.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["consistent", "garbled", "tentative", "contradictory"], correct: 0, explanation: "No contradiction to exploit means the account was \"consistent.\"" },
  { id: "t4rw2h-7", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "Where the older guidebooks praised the region's ruins as untouched, this new survey documents the extensive restoration that has quietly reshaped them.", prompt: "Which choice best describes the main purpose of the text?", type: "mcq", choices: ["To correct the impression that the ruins are untouched by noting their restoration.", "To recommend the older guidebooks as accurate.", "To argue the ruins should never be visited.", "To deny that any restoration has occurred."], correct: 0, explanation: "It contrasts the \"untouched\" claim with documented restoration (choice A)." },
  { id: "t4rw2h-8", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "The morning shipment arrived damaged ______ the afternoon shipment was flawless.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["damaged, the", "damaged; the", "damaged the", "damaged: the"], correct: 1, explanation: "Two independent clauses are joined by a semicolon." },
];
const T4_M_M1: SatQuestion[] = [
  { id: "t4m1-1", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 7x − 4 = 31, what is the value of x?", type: "grid", gridAnswers: ["5"], explanation: "7x = 35, so x = 5." },
  { id: "t4m1-2", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "A recipe requires 3 cups of flour for every 12 cookies. How many cups of flour are needed for 20 cookies?", type: "mcq", choices: ["5", "4", "6", "8"], correct: 0, explanation: "3 cups ÷ 12 = 0.25 cup per cookie; 0.25 × 20 = 5 cups." },
  { id: "t4m1-3", section: "math", domain: "Advanced Math", difficulty: "med", prompt: "If f(x) = 2x² − x, what is the value of f(3)?", type: "mcq", choices: ["15", "12", "17", "9"], correct: 0, explanation: "f(3) = 2(9) − 3 = 18 − 3 = 15." },
  { id: "t4m1-4", section: "math", domain: "Geometry and Trigonometry", difficulty: "med", prompt: "A circle has a radius of 7. What is its circumference in terms of π? (Enter the coefficient of π.)", type: "grid", gridAnswers: ["14"], explanation: "Circumference = 2πr = 2π(7) = 14π, so the coefficient is 14." },
  { id: "t4m1-5", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 4(x + 2) = 28, what is the value of x?", type: "grid", gridAnswers: ["5"], explanation: "x + 2 = 7, so x = 5." },
  { id: "t4m1-6", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "The mean of the four numbers 8, 10, 14, and x is 12. What is the value of x?", type: "mcq", choices: ["16", "12", "14", "18"], correct: 0, explanation: "Sum must be 4 × 12 = 48; 8 + 10 + 14 = 32, so x = 48 − 32 = 16." },
];
const T4_M_M2E: SatQuestion[] = [
  { id: "t4m2e-1", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If x + 6 = 15, what is the value of x?", type: "grid", gridAnswers: ["9"], explanation: "x = 15 − 6 = 9." },
  { id: "t4m2e-2", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "What is 10% of 90?", type: "mcq", choices: ["9", "10", "18", "90"], correct: 0, explanation: "0.10 × 90 = 9." },
  { id: "t4m2e-3", section: "math", domain: "Geometry and Trigonometry", difficulty: "easy", prompt: "A rectangle has a length of 7 and a width of 3. What is its perimeter?", type: "grid", gridAnswers: ["20"], explanation: "Perimeter = 2(7 + 3) = 20." },
  { id: "t4m2e-4", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If 6x = 42, what is the value of x?", type: "mcq", choices: ["7", "6", "8", "36"], correct: 0, explanation: "x = 42 ÷ 6 = 7." },
  { id: "t4m2e-5", section: "math", domain: "Advanced Math", difficulty: "easy", prompt: "What is the value of 4² − 1?", type: "grid", gridAnswers: ["15"], explanation: "4² = 16; 16 − 1 = 15." },
  { id: "t4m2e-6", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "A jar holds 8 red marbles and 12 blue marbles. What fraction of the marbles are red?", type: "mcq", choices: ["2/5", "1/2", "3/5", "8/12"], correct: 0, explanation: "8 red out of 20 total = 8/20 = 2/5." },
];
const T4_M_M2H: SatQuestion[] = [
  { id: "t4m2h-1", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If x² − 49 = 0 and x > 0, what is the value of x?", type: "grid", gridAnswers: ["7"], explanation: "x² = 49, so x = 7 (positive root)." },
  { id: "t4m2h-2", section: "math", domain: "Algebra", difficulty: "hard", prompt: "If 3x + 2y = 19 and y = 5, what is the value of x?", type: "mcq", choices: ["3", "4", "5", "2"], correct: 0, explanation: "3x + 10 = 19 → 3x = 9 → x = 3." },
  { id: "t4m2h-3", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If 3^x = 81, what is the value of x?", type: "grid", gridAnswers: ["4"], explanation: "81 = 3⁴, so x = 4." },
  { id: "t4m2h-4", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "hard", prompt: "A shirt originally priced at $40 is marked up by 15%. What is the new price?", type: "mcq", choices: ["$46", "$55", "$34", "$48"], correct: 0, explanation: "15% of 40 = 6; 40 + 6 = $46." },
  { id: "t4m2h-5", section: "math", domain: "Geometry and Trigonometry", difficulty: "hard", prompt: "A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?", type: "grid", gridAnswers: ["13"], explanation: "√(25 + 144) = √169 = 13." },
  { id: "t4m2h-6", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If p(x) = 4x − 1, what is the value of p(p(2))?", type: "mcq", choices: ["27", "13", "7", "23"], correct: 0, explanation: "p(2) = 7; p(7) = 4(7) − 1 = 27." },
];

export const SAT_FORM_4: SatForm = {
  id: "practice-4",
  title: "InHero SAT Practice Test 4",
  rw: { m1: T4_RW_M1, m2easy: T4_RW_M2E, m2hard: T4_RW_M2H, timeSec: 1080 },
  math: { m1: T4_M_M1, m2easy: T4_M_M2E, m2hard: T4_M_M2H, timeSec: 1080 },
};
