import type { SatQuestion } from "./types";

/**
 * Practice Test 1 — third batch of original, hand-verified items. Brings each
 * Reading & Writing module to 27 and each Math module to 22 questions — the
 * real Digital SAT module counts.
 */

export const RW_M1_X3: SatQuestion[] = [
  { id: "rw1-18", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "The critic's review was surprisingly ______, praising nearly every aspect of a film that other reviewers had panned.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["favorable", "scathing", "indifferent", "brief"], correct: 0,
    explanation: "Answer: A (favorable). The blank is defined by what follows: the review was \"praising nearly every aspect\" of the film. A review full of praise is a positive, approving one — \"favorable.\" The detail that other reviewers \"panned\" it (and that this is \"surprisingly\" so) sets up the contrast, confirming this critic liked it. (B) \"scathing\" means harshly critical — the exact opposite of praising everything. (C) \"indifferent\" means showing no strong opinion, but praising nearly every aspect is a strong positive opinion. (D) \"brief\" refers to length, not attitude, and nothing in the sentence concerns how short the review was." },
  { id: "rw1-19", section: "rw", domain: "Standard English Conventions", difficulty: "med",
    passage: "All of the students must submit ______ projects by Friday afternoon.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["their", "there", "they're", "its"], correct: 0,
    explanation: "Answer: A (their). The projects belong to the students, so a plural possessive pronoun is needed, and \"their\" is the possessive form. Test the homophones: (B) \"there\" indicates a place (\"over there\"), not possession. (C) \"they're\" is the contraction of \"they are\" — substituting it gives \"submit they are projects,\" which is ungrammatical. (D) \"its\" is the possessive of \"it,\" a SINGULAR thing, so it can't refer back to the plural \"students.\" Only \"their\" correctly shows plural possession." },
  { id: "rw1-20", section: "rw", domain: "Information and Ideas", difficulty: "med",
    passage: "Coral reefs cover less than 1% of the ocean floor, yet they shelter roughly a quarter of all known marine species.",
    prompt: "Which choice best states the main idea of the text?",
    type: "mcq", choices: [
      "Coral reefs support a share of marine life that is large relative to their size.",
      "Coral reefs cover most of the ocean floor.",
      "Very few species live in coral reefs.",
      "Coral reefs are unimportant to the ocean.",
    ], correct: 0,
    explanation: "Answer: A. The text pairs a small figure with a large one: reefs cover \"less than 1% of the ocean floor, yet they shelter roughly a quarter of all known marine species.\" The word \"yet\" highlights that the share of life they support is large RELATIVE to their tiny area — exactly (A). (B) is contradicted: reefs cover less than 1%, not most, of the floor. (C) is contradicted: a quarter of species is many, not \"very few.\" (D) is contradicted by the whole point — sheltering a quarter of marine species makes reefs very important." },
  { id: "rw1-21", section: "rw", domain: "Expression of Ideas", difficulty: "med",
    passage: "The new bridge was completed ahead of schedule. ______, it came in well under budget.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["However", "Moreover", "Nevertheless", "Otherwise"], correct: 1,
    explanation: "Answer: B (Moreover). The first sentence gives one positive (finished \"ahead of schedule\"); the second adds another positive (\"under budget\"). Stacking a second supporting good point calls for an additive transition: \"Moreover\" (meaning \"in addition / furthermore\"). (A) \"However\" and (C) \"Nevertheless\" both signal contrast, but the two facts agree — both are good news — so there's nothing to contrast. (D) \"Otherwise\" means \"if not / in other circumstances,\" introducing an alternative scenario, which doesn't fit two facts that are simply both true." },
  { id: "rw1-22", section: "rw", domain: "Standard English Conventions", difficulty: "med",
    passage: "The experiment failed the first time ______ the team refined the procedure and ran it again.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["time, the", "time; the", "time the", "time: the"], correct: 1,
    explanation: "Answer: B (time; the). Both sides are complete independent clauses: \"The experiment failed the first time\" and \"the team refined the procedure and ran it again.\" Two independent clauses with no coordinating conjunction (and, but, so...) can be joined by a SEMICOLON. (A) \"time, the\" uses a comma alone between two independent clauses — a comma splice, which is an error. (C) \"time the\" runs the two clauses together with no punctuation — a run-on (fused) sentence. (D) \"time: the\" uses a colon, but a colon should follow a complete clause that INTRODUCES a list, explanation, or elaboration; here the second clause is just a related event, not an explanation of the first, so a colon is inappropriate." },
  { id: "rw1-23", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "Once a ______ village, the town has become a bustling commuter hub since the new rail line opened.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["sleepy", "crowded", "modern", "dangerous"], correct: 0,
    explanation: "Answer: A (sleepy). The sentence contrasts the town's past with its present: \"Once a ______ village, the town has become a bustling commuter hub.\" \"Bustling\" means busy and lively, so the village USED to be the opposite — quiet and inactive. \"Sleepy,\" describing a quiet, slow place, is the precise contrast. (B) \"crowded\" agrees with \"bustling\" rather than contrasting it, so the \"once ... has become\" reversal breaks down. (C) \"modern\" doesn't pair as an opposite of busy and ignores the time contrast. (D) \"dangerous\" introduces a safety idea the sentence never raises; the contrast is about activity level, not danger." },
  { id: "rw1-24", section: "rw", domain: "Information and Ideas", difficulty: "med",
    passage: "Unlike most birds, the kiwi has nostrils at the very tip of its long beak, which it uses to sniff out insects hidden underground.",
    prompt: "Which statement is best supported by the text?",
    type: "mcq", choices: [
      "The kiwi locates food using its sense of smell.",
      "The kiwi has no sense of smell.",
      "The kiwi hunts only by sight during the day.",
      "All birds have nostrils at the tips of their beaks.",
    ], correct: 0,
    explanation: "Answer: A. The text says the kiwi has nostrils at the tip of its beak \"which it uses to sniff out insects hidden underground.\" Sniffing out food is locating it by smell — directly supporting (A). (B) is contradicted: the kiwi clearly HAS a sense of smell, since it sniffs. (C) is unsupported and contradicted: it finds hidden, underground insects by smell, not by daytime sight. (D) overgeneralizes: the text says the kiwi is \"unlike most birds\" in having tip-of-beak nostrils, so it's the exception, not the rule for all birds." },
  { id: "rw1-25", section: "rw", domain: "Standard English Conventions", difficulty: "med",
    passage: "The list of approved vendors ______ posted on the company website each quarter.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["is", "are", "were", "have been"], correct: 0,
    explanation: "Answer: A (is). Subject-verb agreement. The true subject is \"The list\" — singular. \"of approved vendors\" is a prepositional phrase describing the list, not the subject. A singular subject takes the singular verb \"is.\" The phrase \"each quarter\" indicates a habitual, present action, confirming present tense. (B) \"are\" and (D) \"have been\" are plural; they wrongly agree with \"vendors\" inside the modifying phrase (the nearest-noun trap). (C) \"were\" is plural AND past tense, mismatching both the singular subject and the habitual present time frame." },
  { id: "rw1-26", section: "rw", domain: "Expression of Ideas", difficulty: "med",
    passage: "Solar power is clean and increasingly inexpensive. ______, it cannot generate electricity at night without some form of storage.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["Therefore", "Still", "Likewise", "Thus"], correct: 1,
    explanation: "Answer: B (Still). The first sentence praises solar power (\"clean and increasingly inexpensive\"); the second names a real limitation (it \"cannot generate electricity at night without ... storage\"). Going from advantages to a drawback is a contrast, and \"Still\" works as a concessive transition meaning \"nevertheless.\" (A) \"Therefore\" and (D) \"Thus\" both signal a conclusion/result, but the nighttime limitation is not caused by solar being clean and cheap. (C) \"Likewise\" signals similarity, yet the second sentence opposes the first's praise rather than echoing it." },
  { id: "rw1-27", section: "rw", domain: "Craft and Structure", difficulty: "med",
    passage: "The novel's narrator frequently interrupts the action to address the reader directly, breaking the illusion that the story is unfolding on its own.",
    prompt: "Which choice best describes the effect of the narrator's direct address?",
    type: "mcq", choices: [
      "It reminds readers that they are reading a deliberately constructed story.",
      "It makes the events feel completely realistic.",
      "It conceals the narrator's presence entirely.",
      "It signals that the novel has ended.",
    ], correct: 0,
    explanation: "Answer: A. The narrator \"interrupts the action to address the reader directly, breaking the illusion that the story is unfolding on its own.\" By shattering that illusion, the device makes readers aware they're experiencing a crafted, authored story — exactly (A). (B) is the opposite: breaking the illusion makes events feel LESS realistic, not \"completely realistic.\" (C) is contradicted: addressing the reader directly FOREGROUNDS the narrator rather than concealing the narrator's presence. (D) is unsupported; direct address is a recurring technique throughout, not a signal that the novel has ended." },
];

export const RW_M2_EASY_X3: SatQuestion[] = [
  { id: "rw2e-18", section: "rw", domain: "Craft and Structure", difficulty: "easy",
    passage: "The cake was so ______ that everyone asked for a second slice.",
    prompt: "Which choice completes the text with the most logical word?",
    type: "mcq", choices: ["delicious", "stale", "dry", "plain"], correct: 0,
    explanation: "Answer: A (delicious). The structure \"so ______ that everyone asked for a second slice\" means the blank is a quality strong enough to make people want more. Wanting seconds means the cake tasted great — \"delicious.\" (B) \"stale,\" (C) \"dry,\" and (D) \"plain\" are all unappealing qualities; nobody would ask for a second slice of a stale, dry, or plain cake, so each contradicts the result clause." },
  { id: "rw2e-19", section: "rw", domain: "Standard English Conventions", difficulty: "easy",
    passage: "There ______ three books lying on the table.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["is", "are", "was", "am"], correct: 1,
    explanation: "Answer: B (are). In a \"There ___\" sentence, the verb agrees with what FOLLOWS it: here \"three books,\" which is plural. The plural present-tense verb is \"are.\" The present tense fits because the books are presently \"lying on the table.\" (A) \"is\" and (C) \"was\" are singular; (C) is also past tense. (D) \"am\" is used only with the subject \"I,\" so it can never go with \"three books.\"" },
  { id: "rw2e-20", section: "rw", domain: "Information and Ideas", difficulty: "easy",
    passage: "Bats are the only mammals that can truly fly. Their wings are made of thin skin stretched between long finger bones.",
    prompt: "Which choice best states the main idea of the text?",
    type: "mcq", choices: [
      "Bats are mammals that fly using skin-covered wings.",
      "Bats are a kind of bird.",
      "Bats are unable to fly.",
      "Bats have feathered wings.",
    ], correct: 0,
    explanation: "Answer: A. The text states bats are \"the only mammals that can truly fly\" and their wings are \"thin skin stretched between long finger bones.\" The main idea combines both facts: bats are mammals that fly using skin-covered wings — (A). (B) is contradicted: bats are mammals, not birds. (C) is contradicted: the text says bats CAN truly fly. (D) is contradicted: their wings are skin, not feathers — that's a key detail of the passage." },
  { id: "rw2e-21", section: "rw", domain: "Expression of Ideas", difficulty: "easy",
    passage: "He studied hard every night that week. ______, he passed the exam easily.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["However", "As a result", "For example", "Instead"], correct: 1,
    explanation: "Answer: B (As a result). Studying hard every night is the CAUSE; passing the exam easily is the EFFECT. \"As a result\" signals that consequence. (A) \"However\" signals contrast, but passing after studying agrees with the first sentence rather than opposing it. (C) \"For example\" introduces an illustration, yet passing is an outcome, not an example of studying. (D) \"Instead\" signals a replacement/alternative, which doesn't fit a straightforward cause-and-effect link." },
  { id: "rw2e-22", section: "rw", domain: "Standard English Conventions", difficulty: "easy",
    passage: "We spotted ______ owl perched in the tree at dusk.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["a", "an", "the only", "some"], correct: 1,
    explanation: "Answer: B (an). Use \"an\" before a word beginning with a VOWEL SOUND. \"Owl\" begins with the vowel sound /au/, so \"an owl\" is correct. (A) \"a\" precedes consonant sounds, so \"a owl\" is wrong and hard to pronounce. (C) \"the only\" wrongly implies this is the single owl in existence — far more specific than the sentence supports (they simply spotted one owl). (D) \"some\" suggests an unspecified quantity/plural, clashing with the singular \"owl perched in the tree.\"" },
  { id: "rw2e-23", section: "rw", domain: "Craft and Structure", difficulty: "easy",
    passage: "The basement was so ______ that we had to turn on every light to see.",
    prompt: "Which choice completes the text with the most logical word?",
    type: "mcq", choices: ["dark", "bright", "loud", "warm"], correct: 0,
    explanation: "Answer: A (dark). The result clause — \"we had to turn on every light to see\" — tells us why: there wasn't enough light, so the basement was \"dark.\" (B) \"bright\" is the opposite; you wouldn't need every light in an already-bright room. (C) \"loud\" describes sound, unrelated to needing lights to see. (D) \"warm\" describes temperature, also unrelated to visibility." },
  { id: "rw2e-24", section: "rw", domain: "Information and Ideas", difficulty: "easy",
    passage: "Plants make their own food from sunlight, water, and carbon dioxide in a process called photosynthesis.",
    prompt: "Which choice best states the main idea of the text?",
    type: "mcq", choices: [
      "Plants use sunlight to make their own food.",
      "Plants get food by eating animals.",
      "Plants do not need any water.",
      "Plants cannot make their own food.",
    ], correct: 0,
    explanation: "Answer: A. The text says plants \"make their own food from sunlight, water, and carbon dioxide\" in photosynthesis. The main idea is that plants use sunlight to make their own food — (A). (B) is contradicted: plants make food themselves, they don't eat animals. (C) is contradicted: water is explicitly one of the ingredients. (D) is the opposite of the passage, which says plants DO make their own food." },
  { id: "rw2e-25", section: "rw", domain: "Standard English Conventions", difficulty: "easy",
    passage: "Last night the whole family ______ a movie together at the theater.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["watch", "watches", "watched", "watching"], correct: 2,
    explanation: "Answer: C (watched). The time marker \"Last night\" places the action in the past, so the verb must be simple past: \"watched.\" (A) \"watch\" is present/base tense and also wouldn't agree with the singular \"family.\" (B) \"watches\" is present tense, for habitual or current action, not a completed past event. (D) \"watching\" is a participle and cannot be the main verb without a helping verb like \"was.\"" },
  { id: "rw2e-26", section: "rw", domain: "Expression of Ideas", difficulty: "easy",
    passage: "The store was already closed when we arrived. ______, we drove back home.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["For example", "Therefore", "However", "Meanwhile"], correct: 1,
    explanation: "Answer: B (Therefore). The store being \"already closed\" is the CAUSE, and driving home is the logical EFFECT. \"Therefore\" signals that result. (A) \"For example\" would introduce an illustration of the first sentence, but driving home is a consequence, not an example. (C) \"However\" signals contrast, yet there's no opposition — going home naturally follows a closed store. (D) \"Meanwhile\" signals two things happening at the same time, but these are sequential cause and effect, not simultaneous events." },
  { id: "rw2e-27", section: "rw", domain: "Craft and Structure", difficulty: "easy",
    passage: "She felt very ______ when she won first place in the science fair.",
    prompt: "Which choice completes the text with the most logical word?",
    type: "mcq", choices: ["proud", "sad", "bored", "angry"], correct: 0,
    explanation: "Answer: A (proud). Winning first place is a positive achievement, so the natural feeling is \"proud.\" The three wrong choices are all negative emotions that don't fit a victory: (B) \"sad,\" (C) \"bored,\" and (D) \"angry\" would each contradict the happy occasion of winning the science fair." },
];

export const RW_M2_HARD_X3: SatQuestion[] = [
  { id: "rw2h-18", section: "rw", domain: "Craft and Structure", difficulty: "hard",
    passage: "The memoir is refreshingly ______, refusing to flatter its author or to soften her past mistakes.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["candid", "evasive", "grandiose", "sentimental"], correct: 0,
    explanation: "Answer: A (candid). The blank is defined by what follows: the memoir refuses \"to flatter its author or to soften her past mistakes.\" Telling the unflattering truth is being honest and frank — \"candid.\" (B) \"evasive\" means avoiding the truth — the opposite of refusing to soften mistakes. (C) \"grandiose\" means pompous or exaggerated, which clashes with not flattering oneself. (D) \"sentimental\" means overly emotional/nostalgic, but the memoir resists softening, so it isn't indulging sentimentality." },
  { id: "rw2h-19", section: "rw", domain: "Information and Ideas", difficulty: "hard",
    passage: "The paper devotes its opening sections to dismantling a rival theory, clearing the ground before it advances a model of its own.",
    prompt: "Which choice best describes the function of the opening sections?",
    type: "mcq", choices: [
      "They refute a competing theory to prepare for the author's alternative.",
      "They demonstrate that the rival theory is correct.",
      "They summarize the author's own model in detail.",
      "They serve as the paper's conclusion.",
    ], correct: 0,
    explanation: "Answer: A. The paper spends its opening \"dismantling a rival theory, clearing the ground before it advances a model of its own.\" Dismantling = refuting; clearing the ground = preparing for the author's alternative. So the opening sections refute a competing theory to prepare for the author's model — (A). (B) is the opposite: dismantling the rival theory shows it is NOT correct. (C) is wrong on timing: the author's own model comes AFTER, not in the opening sections, which attack the rival. (D) is wrong because attacking the rival is the SETUP, not the conclusion." },
  { id: "rw2h-20", section: "rw", domain: "Information and Ideas", difficulty: "hard",
    passage: "Across three cities, average commute times were 22 minutes where bike lanes were extensive, 31 minutes where they were moderate, and 39 minutes where they were minimal.",
    prompt: "Which statement is best supported by the data?",
    type: "mcq", choices: [
      "More extensive bike lanes were associated with shorter average commutes.",
      "Bike lanes lengthened average commutes.",
      "Commute time was unrelated to bike-lane coverage.",
      "Minimal bike lanes produced the shortest commutes.",
    ], correct: 0,
    explanation: "Answer: A. Pair each bike-lane level with its commute time: extensive = 22 min, moderate = 31 min, minimal = 39 min. As coverage decreases (extensive → moderate → minimal), commute time INCREASES (22 → 31 → 39). Equivalently, more extensive lanes go with SHORTER commutes — (A). (B) is the opposite: more lanes correspond to shorter, not longer, commutes. (C) is contradicted: the times vary systematically with coverage, so they're related. (D) is contradicted: minimal lanes had the LONGEST commute (39 min), not the shortest." },
  { id: "rw2h-21", section: "rw", domain: "Expression of Ideas", difficulty: "hard",
    passage: "The theory elegantly accounts for nearly all of the observed data. ______, it rests on an assumption that has never been experimentally tested.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["Therefore", "Yet", "Likewise", "Thus"], correct: 1,
    explanation: "Answer: B (Yet). The first sentence is a strength (the theory \"elegantly accounts for nearly all of the observed data\"); the second is a serious weakness (it \"rests on an assumption that has never been experimentally tested\"). Moving from a virtue to a flaw is a contrast, signaled by \"Yet.\" (A) \"Therefore\" and (D) \"Thus\" both mark a conclusion/result, but the untested assumption is not a consequence of the theory's elegance. (C) \"Likewise\" marks similarity, yet the two sentences are opposed in evaluation, not alike." },
  { id: "rw2h-22", section: "rw", domain: "Standard English Conventions", difficulty: "hard",
    passage: "The position requires analyzing reports, drafting proposals, and ______ regularly with clients.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["to meet", "meeting", "meet", "met"], correct: 1,
    explanation: "Answer: B (meeting). This tests PARALLEL STRUCTURE. The sentence lists three duties joined by \"and\": \"analyzing reports, drafting proposals, and ______ regularly with clients.\" The first two items are gerunds (-ing forms), so the third must match: \"meeting.\" (A) \"to meet\" is an infinitive, breaking the -ing pattern. (C) \"meet\" is a base verb, also not parallel. (D) \"met\" is past tense, neither parallel nor grammatical in this list. Items in a series must share the same grammatical form." },
  { id: "rw2h-23", section: "rw", domain: "Craft and Structure", difficulty: "hard",
    passage: "His ______ tone — neither warm nor hostile — made it impossible to tell whether he approved of the plan.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["neutral", "effusive", "caustic", "jubilant"], correct: 0,
    explanation: "Answer: A (neutral). The dashes define the blank directly: a tone \"neither warm nor hostile.\" Something between warmth and hostility, leaning to neither side, is \"neutral,\" which is also why it was \"impossible to tell\" his opinion. (B) \"effusive\" means gushingly enthusiastic — that's very warm, contradicting \"neither warm.\" (C) \"caustic\" means bitingly sarcastic — that's hostile, contradicting \"nor hostile.\" (D) \"jubilant\" means joyful — again far from neutral, and it would reveal his feelings rather than hide them." },
  { id: "rw2h-24", section: "rw", domain: "Information and Ideas", difficulty: "hard",
    passage: "Whereas earlier biographers treated the inventor's failures as embarrassing detours, this study treats them as essential rehearsals for his later breakthroughs.",
    prompt: "Which choice best describes the main purpose of the text?",
    type: "mcq", choices: [
      "To contrast a new interpretation of the inventor's failures with earlier ones.",
      "To list each of the inventor's successful inventions.",
      "To argue that the inventor never actually failed.",
      "To dismiss the new study as unconvincing.",
    ], correct: 0,
    explanation: "Answer: A. The sentence is built on \"Whereas earlier biographers treated the failures as embarrassing detours, this study treats them as essential rehearsals.\" \"Whereas\" frames a contrast between an OLD interpretation and a NEW one of the same failures — exactly (A). (B) is wrong: the focus is on how the failures are interpreted, not a list of successful inventions. (C) overstates: the study reinterprets the failures as useful, but never claims he \"never failed.\" (D) is wrong: the text presents the new study approvingly, not dismissively." },
  { id: "rw2h-25", section: "rw", domain: "Standard English Conventions", difficulty: "hard",
    passage: "Not only the students but also the teacher ______ surprised by the announcement.",
    prompt: "Which choice conforms to the conventions of Standard English?",
    type: "mcq", choices: ["was", "were", "have been", "are"], correct: 0,
    explanation: "Answer: A (was). Rule for \"not only ... but also\" (a correlative conjunction joining two subjects): the verb agrees with the subject NEARER to it. The nearer subject is \"the teacher,\" which is singular, so the verb is singular: \"was.\" The past context (\"surprised by the announcement\") also calls for past tense. (B) \"were\" and (D) \"are\" are plural, agreeing with \"students,\" but \"teacher\" is the closer subject. (C) \"have been\" is present-perfect plural, wrong on both number and tense for this completed past reaction." },
  { id: "rw2h-26", section: "rw", domain: "Expression of Ideas", difficulty: "hard",
    passage: "Most analysts predicted that the currency would weaken sharply. ______, it gained value steadily over the following year.",
    prompt: "Which choice completes the text with the most logical transition?",
    type: "mcq", choices: ["Accordingly", "Instead", "Therefore", "Moreover"], correct: 1,
    explanation: "Answer: B (Instead). Analysts predicted the currency \"would weaken sharply,\" but it \"gained value steadily\" — the reality REPLACED the expected outcome with its opposite. \"Instead\" precisely marks that a different thing happened than was predicted. (A) \"Accordingly\" and (C) \"Therefore\" both signal a result that follows logically from the prediction, but gaining value contradicts the forecast rather than following from it. (D) \"Moreover\" adds a similar point, yet the second sentence opposes the first rather than reinforcing it." },
  { id: "rw2h-27", section: "rw", domain: "Craft and Structure", difficulty: "hard",
    passage: "The essay's argument is ______, building each new claim carefully on the one that comes before it.",
    prompt: "Which choice completes the text with the most logical and precise word?",
    type: "mcq", choices: ["cumulative", "haphazard", "circular", "vague"], correct: 0,
    explanation: "Answer: A (cumulative). The blank is defined by \"building each new claim carefully on the one that comes before it.\" An argument where each step rests on the prior one and adds up is \"cumulative.\" (B) \"haphazard\" means random and disorganized — the opposite of carefully building in order. (C) \"circular\" means the reasoning loops back on itself (begs the question), not that it progresses forward. (D) \"vague\" means unclear, but the sentence describes a careful, orderly structure, not a fuzzy one." },
];

export const MATH_M1_X3: SatQuestion[] = [
  { id: "m1-16", section: "math", domain: "Algebra", difficulty: "med",
    prompt: "If 2(x + 3) = 16, what is the value of x?",
    type: "grid", gridAnswers: ["5"], explanation: "Goal: solve 2(x + 3) = 16 for x.\nStep 1 — divide both sides by 2 to undo the multiplication: (x + 3) = 8. (You could instead distribute: 2x + 6 = 16; both routes work.)\nStep 2 — subtract 3 from both sides: x = 5.\nCheck: 2(5 + 3) = 2(8) = 16. ✓ Grid-in answer: 5.\nTrap: distributing incorrectly as 2x + 3 = 16 (forgetting to multiply the 3 by 2), which gives x = 6.5. Multiply BOTH terms inside the parentheses by 2." },
  { id: "m1-17", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med",
    prompt: "If 5 notebooks cost $12.50, how much do 8 notebooks cost at the same price per notebook?",
    type: "mcq", choices: ["$20.00", "$18.00", "$25.00", "$16.00"], correct: 0,
    explanation: "Goal: find the cost of 8 notebooks if 5 cost $12.50, at the same unit price.\nStep 1 — unit price: 12.50 ÷ 5 = $2.50 per notebook.\nStep 2 — cost of 8: 8 × 2.50 = $20.00.\nAnswer: A, $20.00. (Proportion check: 5/12.50 = 8/x → x = 8 × 12.50/5 = 100/5 = 20. ✓)\n(C) $25.00 mistakenly multiplies by 10 or adds wrong. (B) $18.00 and (D) $16.00 come from arithmetic slips in the unit price. Find the per-unit cost first, then scale up." },
  { id: "m1-18", section: "math", domain: "Advanced Math", difficulty: "med",
    prompt: "If h(x) = 3x² − x, what is the value of h(2)?",
    type: "mcq", choices: ["10", "11", "14", "6"], correct: 0,
    explanation: "Goal: with h(x) = 3x² − x, find h(2). Substitute x = 2.\nStep 1 — square first (order of operations): 2² = 4.\nStep 2 — multiply by 3: 3 × 4 = 12.\nStep 3 — subtract x (= 2): 12 − 2 = 10.\nAnswer: A, 10.\nTrap: computing (3·2)² = 6² = 36 by squaring AFTER multiplying — the exponent applies only to x, so square the 2 first. (C) 14 comes from 3(4) + 2 (sign error on −x); (B) 11 and (D) 6 are other arithmetic slips." },
  { id: "m1-19", section: "math", domain: "Geometry and Trigonometry", difficulty: "med",
    prompt: "A circle has a diameter of 14. What is its radius?",
    type: "grid", gridAnswers: ["7"], explanation: "Goal: find the radius of a circle whose diameter is 14.\nRelationship: the radius is half the diameter (diameter = 2 × radius).\nStep — divide the diameter by 2: 14 ÷ 2 = 7.\nGrid-in answer: 7.\nTrap: multiplying by 2 (getting 28) — that would go from radius to diameter, the wrong direction. The radius is the SMALLER value, half the diameter." },
  { id: "m1-20", section: "math", domain: "Algebra", difficulty: "med",
    prompt: "If (2x − 1) / 3 = 5, what is the value of x?",
    type: "grid", gridAnswers: ["8"], explanation: "Goal: solve (2x − 1)/3 = 5 for x.\nStep 1 — clear the fraction by multiplying both sides by 3: 2x − 1 = 15.\nStep 2 — add 1 to both sides: 2x = 16.\nStep 3 — divide by 2: x = 8.\nCheck: (2·8 − 1)/3 = (16 − 1)/3 = 15/3 = 5. ✓ Grid-in answer: 8.\nTrap: adding 1 before multiplying by 3, or distributing the 3 incorrectly. Multiply away the denominator first, then isolate x." },
  { id: "m1-21", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med",
    prompt: "30 is what percent of 120?",
    type: "mcq", choices: ["25%", "30%", "40%", "20%"], correct: 0,
    explanation: "Goal: 30 is what percent of 120?\nSet up: part / whole × 100% = percent, with 30 as the part and 120 as the whole.\nStep 1 — divide: 30 ÷ 120 = 0.25.\nStep 2 — convert to percent: 0.25 × 100% = 25%.\nAnswer: A, 25%.\n(B) 30% just reuses the number 30. (C) 40% comes from dividing by 75 or another wrong base. (D) 20% comes from 30/150 or a slip. The whole (120) goes in the denominator; gut check: 30 is a quarter of 120, and a quarter is 25%. ✓" },
  { id: "m1-22", section: "math", domain: "Geometry and Trigonometry", difficulty: "med",
    prompt: "A triangle has a base of 10 and a height of 6. What is its area?",
    type: "mcq", choices: ["30", "60", "16", "18"], correct: 0,
    explanation: "Goal: find the area of a triangle with base 10 and height 6.\nFormula: Area = ½ × base × height.\nStep 1 — multiply base and height: 10 × 6 = 60.\nStep 2 — take half: ½ × 60 = 30.\nAnswer: A, 30.\n(B) 60 forgets the ½ factor (that's base × height, a rectangle's area, not a triangle's). (C) 16 and (D) 18 come from adding (10 + 6 = 16) or other slips. The triangle's ½ is essential." },
];

export const MATH_M2_EASY_X3: SatQuestion[] = [
  { id: "m2e-16", section: "math", domain: "Algebra", difficulty: "easy",
    prompt: "If 3x = 21, what is the value of x?",
    type: "grid", gridAnswers: ["7"], explanation: "Goal: solve 3x = 21 for x.\nStep — undo the multiplication by dividing both sides by 3: x = 21 ÷ 3 = 7.\nCheck: 3 × 7 = 21. ✓ Grid-in answer: 7.\nTrap: subtracting 3 (getting 18) instead of dividing. When a number multiplies x, divide by it to isolate x." },
  { id: "m2e-17", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy",
    prompt: "What is 50% of 80?",
    type: "mcq", choices: ["40", "30", "50", "160"], correct: 0,
    explanation: "Goal: compute 50% of 80.\n50% means one half (50/100 = 0.5), and \"of\" means multiply.\nStep — multiply: 0.5 × 80 = 40 (equivalently, 80 ÷ 2 = 40).\nAnswer: A, 40.\n(B) 30 and (C) 50 are unrelated values. (D) 160 comes from multiplying by 2 instead of taking half. Half of 80 is 40. ✓" },
  { id: "m2e-18", section: "math", domain: "Geometry and Trigonometry", difficulty: "easy",
    prompt: "A square has a perimeter of 20. What is the length of one side?",
    type: "grid", gridAnswers: ["5"], explanation: "Goal: find one side of a square whose perimeter is 20.\nA square has 4 equal sides, so perimeter = 4 × side, which rearranges to side = perimeter ÷ 4.\nStep — divide: 20 ÷ 4 = 5.\nCheck: 4 × 5 = 20. ✓ Grid-in answer: 5.\nTrap: dividing by 2 (getting 10) as if it were a rectangle's length + width. A square has four equal sides, so divide by 4." },
  { id: "m2e-19", section: "math", domain: "Algebra", difficulty: "easy",
    prompt: "If x + 7 = 10, what is the value of x?",
    type: "mcq", choices: ["3", "17", "7", "4"], correct: 0, explanation: "Goal: solve x + 7 = 10 for x.\nStep — undo the +7 by subtracting 7 from both sides: x = 10 − 7 = 3.\nCheck: 3 + 7 = 10. ✓ Answer: A, 3.\n(B) 17 adds (10 + 7) instead of subtracting. (C) 7 just repeats the constant. (D) 4 is an arithmetic slip; 10 − 7 = 3." },
  { id: "m2e-20", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy",
    prompt: "A bag holds 10 marbles, and 4 of them are red. How many marbles are not red?",
    type: "grid", gridAnswers: ["6"], explanation: "Goal: of 10 marbles, 4 are red; find how many are NOT red.\nThe non-red marbles are the total minus the red ones.\nStep — subtract: 10 − 4 = 6.\nGrid-in answer: 6.\nCheck: 6 not-red + 4 red = 10 total. ✓ Trap: answering 4 (the red count) instead of the non-red count the question asks for." },
  { id: "m2e-21", section: "math", domain: "Advanced Math", difficulty: "easy",
    prompt: "What is the value of 4²?",
    type: "mcq", choices: ["16", "8", "12", "4"], correct: 0, explanation: "Goal: evaluate 4².\nAn exponent of 2 means multiply the base by itself: 4² = 4 × 4.\nStep — multiply: 4 × 4 = 16.\nAnswer: A, 16.\nTrap: (B) 8 multiplies 4 × 2 (treating the exponent as a factor); (C) 12 and (D) 4 are other slips. \"Squared\" means the number times itself, not the number times the exponent." },
  { id: "m2e-22", section: "math", domain: "Algebra", difficulty: "easy",
    prompt: "If 10 − x = 6, what is the value of x?",
    type: "grid", gridAnswers: ["4"], explanation: "Goal: solve 10 − x = 6 for x.\nStep 1 — add x to both sides: 10 = 6 + x.\nStep 2 — subtract 6 from both sides: 10 − 6 = x, so x = 4.\nCheck: 10 − 4 = 6. ✓ Grid-in answer: 4.\nTrap: answering 16 by adding (10 + 6); since x is subtracted, isolate it by moving it across, then subtract 6 from 10." },
];

export const MATH_M2_HARD_X3: SatQuestion[] = [
  { id: "m2h-16", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If x² − 7x + 12 = 0 and x > 3, what is the value of x?",
    type: "grid", gridAnswers: ["4"], explanation: "Goal: solve x² − 7x + 12 = 0 with the constraint x > 3.\nStep 1 — factor: find two numbers that multiply to +12 and add to −7. Those are −3 and −4. So x² − 7x + 12 = (x − 3)(x − 4) = 0.\nStep 2 — zero-product property: x − 3 = 0 or x − 4 = 0, giving x = 3 or x = 4.\nStep 3 — apply x > 3: only 4 is strictly greater than 3 (3 is not > 3).\nTherefore x = 4. Check: 4² − 7(4) + 12 = 16 − 28 + 12 = 0 ✓ and 4 > 3 ✓. Grid-in answer: 4.\nTrap: choosing x = 3, which is a root but fails the strict inequality x > 3." },
  { id: "m2h-17", section: "math", domain: "Algebra", difficulty: "hard",
    prompt: "If 2x + 3y = 16 and x = y + 3, what is the value of y?",
    type: "mcq", choices: ["2", "3", "4", "5"], correct: 0,
    explanation: "Goal: find y given 2x + 3y = 16 and x = y + 3 (substitution).\nStep 1 — substitute x = y + 3 into the first equation: 2(y + 3) + 3y = 16.\nStep 2 — distribute: 2y + 6 + 3y = 16.\nStep 3 — combine like terms: 5y + 6 = 16.\nStep 4 — subtract 6: 5y = 10.\nStep 5 — divide by 5: y = 2.\nCheck: x = y + 3 = 5; then 2(5) + 3(2) = 10 + 6 = 16. ✓ Answer: A, 2.\nTrap: forgetting to distribute the 2 across both terms (writing 2y + 3 + 3y). Multiply the 2 by BOTH y and 3." },
  { id: "m2h-18", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "hard",
    prompt: "A price falls from $80 to $60. What is the percent decrease?",
    type: "mcq", choices: ["25%", "20%", "30%", "33%"], correct: 0,
    explanation: "Goal: find the percent decrease from $80 to $60.\nFormula: percent decrease = (original − new) / original × 100%, using the ORIGINAL as the base.\nStep 1 — amount of decrease: 80 − 60 = 20.\nStep 2 — divide by the original (80): 20 / 80 = 0.25.\nStep 3 — convert: 0.25 × 100% = 25%.\nAnswer: A, 25%.\n(B) 20% wrongly divides by the NEW price (20/... ) or uses 100 as the base. (D) 33% comes from dividing by the new value 60 (20/60 ≈ 33%). The base must be the starting price, 80. Gut check: 20 is a quarter of 80, i.e. 25%. ✓" },
  { id: "m2h-19", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If 4^x = 64, what is the value of x?",
    type: "grid", gridAnswers: ["3"], explanation: "Goal: solve 4^x = 64 for x.\nStrategy: rewrite 64 as a power of 4 so both sides share base 4.\nStep 1 — powers of 4: 4¹ = 4, 4² = 16, 4³ = 64. So 64 = 4³.\nStep 2 — the equation becomes 4^x = 4³; equal bases force equal exponents, so x = 3.\nCheck: 4³ = 64. ✓ Grid-in answer: 3.\nTrap: answering 16 (64 ÷ 4) or guessing 4; the exponent is what's asked, not the quotient or base." },
  { id: "m2h-20", section: "math", domain: "Geometry and Trigonometry", difficulty: "hard",
    prompt: "A right triangle has legs of length 8 and 15. What is the length of the hypotenuse?",
    type: "grid", gridAnswers: ["17"], explanation: "Goal: find the hypotenuse of a right triangle with legs 8 and 15.\nUse the Pythagorean theorem: c² = a² + b², where a and b are the legs and c is the hypotenuse.\nStep 1 — square the legs: 8² = 64 and 15² = 225.\nStep 2 — add: 64 + 225 = 289.\nStep 3 — take the square root: c = √289 = 17.\nGrid-in answer: 17. (This is the 8-15-17 Pythagorean triple.)\nTrap: adding the legs (8 + 15 = 23) or forgetting to take the square root (leaving 289). The hypotenuse is √(sum of the squared legs)." },
  { id: "m2h-21", section: "math", domain: "Advanced Math", difficulty: "hard",
    prompt: "If f(x) = 2x − 1 and g(x) = x², what is the value of f(g(3))?",
    type: "mcq", choices: ["17", "11", "8", "5"], correct: 0,
    explanation: "Goal: with f(x) = 2x − 1 and g(x) = x², find f(g(3)) — a composition, so work from the INSIDE out.\nStep 1 — inner function: g(3) = 3² = 9.\nStep 2 — feed that into f: f(9) = 2(9) − 1 = 18 − 1 = 17.\nAnswer: A, 17.\n(D) 5 evaluates f(3) first by mistake (2·3 − 1 = 5), i.e. wrong order. (B) 11 and (C) 8 come from other order/arithmetic errors. In f(g(3)), evaluate g(3) first, then apply f." },
  { id: "m2h-22", section: "math", domain: "Algebra", difficulty: "hard",
    prompt: "Three consecutive integers have a sum of 48. What is the largest of the three?",
    type: "grid", gridAnswers: ["17"], explanation: "Goal: three consecutive integers sum to 48; find the largest.\nStep 1 — let the integers be n, n+1, n+2. Their sum: n + (n+1) + (n+2) = 3n + 3 = 48.\nStep 2 — subtract 3: 3n = 45.\nStep 3 — divide by 3: n = 15. So the integers are 15, 16, 17.\nStep 4 — the largest is 17.\nCheck: 15 + 16 + 17 = 48. ✓ Grid-in answer: 17.\n(Shortcut: for three consecutive integers, the MIDDLE one is the average, 48 ÷ 3 = 16, so the largest is 16 + 1 = 17.)\nTrap: answering 16 (the middle/average) or 15 (the smallest) instead of the largest the question asks for." },
];
