import type { SatForm, SatQuestion } from "./types";
import {
  T2_RW_M1_B, T2_RW_M2E_B, T2_RW_M2H_B, T2_M_M1_B, T2_M_M2E_B, T2_M_M2H_B,
  T3_RW_M1_B, T3_RW_M2E_B, T3_RW_M2H_B, T3_M_M1_B, T3_M_M2E_B, T3_M_M2H_B,
} from "./forms-extra-b";
import {
  T2_RW_M1_C, T2_RW_M2E_C, T2_RW_M2H_C, T2_M_M1_C, T2_M_M2E_C, T2_M_M2H_C,
  T3_RW_M1_C, T3_RW_M2E_C, T3_RW_M2H_C, T3_M_M1_C, T3_M_M2E_C, T3_M_M2H_C,
} from "./forms-extra-c";

/**
 * Practice Tests 2 and 3 — additional adaptive forms (original, hand-verified
 * items). Each module is a focused set (R&W 8, Math 6) with the full adaptive
 * structure; they can be expanded toward full length like Test 1.
 */

// ─────────────────────────── PRACTICE TEST 2 ───────────────────────────
const T2_RW_M1: SatQuestion[] = [
  { id: "t2rw1-1", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "The scientist's findings were so ______ that they overturned decades of accepted theory.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["groundbreaking", "trivial", "predictable", "tentative"], correct: 0, explanation: "Overturning decades of theory makes the findings \"groundbreaking.\"" },
  { id: "t2rw1-2", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "The collection of rare coins ______ displayed in the main hall of the museum.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["is", "are", "were", "have"], correct: 0, explanation: "The subject is singular \"collection,\" so \"is\" is correct." },
  { id: "t2rw1-3", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "Tardigrades, tiny aquatic animals, can survive extreme cold, intense radiation, and even the vacuum of space by entering a dormant state.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Tardigrades survive extreme conditions by becoming dormant.", "Tardigrades can live only in outer space.", "Tardigrades cannot tolerate cold.", "Tardigrades are unusually large animals."], correct: 0, explanation: "The text lists extremes they survive \"by entering a dormant state\" (choice A)." },
  { id: "t2rw1-4", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "The first design was rejected for being too costly. ______, the team produced a cheaper alternative.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["However", "Accordingly", "Nevertheless", "Meanwhile"], correct: 1, explanation: "The cheaper design is a response to the rejection — \"Accordingly.\"" },
  { id: "t2rw1-5", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "The kit contained three tools ______ a hammer, a wrench, and a screwdriver.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["tools, a", "tools: a", "tools; a", "tools a"], correct: 1, explanation: "A colon introduces the list that explains \"three tools.\"" },
  { id: "t2rw1-6", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "Her explanation was admirably ______, clearing up the confusion in a single sentence.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["lucid", "convoluted", "lengthy", "vague"], correct: 0, explanation: "Clearing confusion in one sentence is \"lucid\" (clear)." },
  { id: "t2rw1-7", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "The new emissions policy applies only to vehicles registered after January 2020; older vehicles are exempt.", prompt: "Which statement is best supported by the text?", type: "mcq", choices: ["A vehicle registered in 2018 is exempt from the policy.", "Every vehicle must comply with the policy.", "Vehicles registered in 2021 are exempt.", "The policy applies to no vehicles at all."], correct: 0, explanation: "Older (pre-2020) vehicles are exempt, so a 2018 vehicle is exempt (choice A)." },
  { id: "t2rw1-8", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "Sales rose every quarter. ______, the company expanded into three new countries.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["However", "Moreover", "Otherwise", "Instead"], correct: 1, explanation: "A second positive development is added — \"Moreover.\"" },
];
const T2_RW_M2E: SatQuestion[] = [
  { id: "t2rw2e-1", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The movie was so ______ that I fell asleep halfway through it.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["boring", "exciting", "scary", "funny"], correct: 0, explanation: "Falling asleep means it was \"boring.\"" },
  { id: "t2rw2e-2", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "The children ______ playing happily in the park.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["is", "are", "was", "am"], correct: 1, explanation: "\"Children\" is plural, so \"are\" is correct." },
  { id: "t2rw2e-3", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Whales are mammals, so they breathe air with lungs and must come to the surface regularly.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Whales breathe air and surface to do so.", "Whales breathe underwater using gills.", "Whales are a kind of fish.", "Whales never come to the surface."], correct: 0, explanation: "As air-breathing mammals, they must surface (choice A)." },
  { id: "t2rw2e-4", section: "rw", domain: "Expression of Ideas", difficulty: "easy", passage: "It was raining hard outside. ______, we decided to stay indoors.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["For example", "Therefore", "However", "Meanwhile"], correct: 1, explanation: "The rain is the reason they stayed in — \"Therefore.\"" },
  { id: "t2rw2e-5", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "She ______ to the store about an hour ago.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["go", "goes", "went", "going"], correct: 2, explanation: "\"An hour ago\" requires the past tense \"went.\"" },
  { id: "t2rw2e-6", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The puppy was ______ and ran around the yard chasing its tail.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["playful", "lazy", "sad", "silent"], correct: 0, explanation: "Running and chasing its tail shows it was \"playful.\"" },
  { id: "t2rw2e-7", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Regular exercise strengthens muscles, improves mood, and helps people sleep better.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Exercise has several health benefits.", "Exercise is harmful to health.", "Exercise only helps with sleep.", "Exercise weakens the muscles."], correct: 0, explanation: "Three benefits are listed — choice A." },
  { id: "t2rw2e-8", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "He ate ______ apple and a banana for breakfast.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["a", "an", "the only", "some"], correct: 1, explanation: "\"Apple\" begins with a vowel sound, so \"an.\"" },
];
const T2_RW_M2H: SatQuestion[] = [
  { id: "t2rw2h-1", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "The committee's response was deliberately ______, committing to nothing while appearing fully cooperative.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["evasive", "forthright", "decisive", "blunt"], correct: 0, explanation: "Committing to nothing while seeming cooperative is \"evasive.\"" },
  { id: "t2rw2h-2", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "The lecture begins with a striking paradox, then spends the remainder of the hour patiently working to resolve it.", prompt: "Which choice best describes the function of the opening paradox?", type: "mcq", choices: ["To pose a puzzle that the rest of the lecture sets out to resolve.", "To state the lecture's final conclusion.", "To provide a list of definitions.", "To bring the lecture to a close."], correct: 0, explanation: "The paradox sets up the problem the lecture then resolves (choice A)." },
  { id: "t2rw2h-3", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "Crop yields were 5.0 t/ha with no fertilizer, 6.8 t/ha with low fertilizer, and 7.1 t/ha with high fertilizer.", prompt: "Which statement is best supported by the data?", type: "mcq", choices: ["Most of the yield gain came from the first addition of fertilizer.", "Yield decreased as fertilizer increased.", "High fertilizer cut the yield in half.", "Fertilizer had no effect on yield."], correct: 0, explanation: "5.0 to 6.8 is a large jump; 6.8 to 7.1 is small — most gain is from the first addition (choice A)." },
  { id: "t2rw2h-4", section: "rw", domain: "Expression of Ideas", difficulty: "hard", passage: "The plan is ambitious and generously funded. ______, its success depends on a level of cooperation that has so far proved elusive.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Therefore", "Yet", "Likewise", "Hence"], correct: 1, explanation: "Strengths followed by a serious caveat is a contrast — \"Yet.\"" },
  { id: "t2rw2h-5", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "The course teaches students to write clearly, to think critically, and ______ persuasively.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["to argue", "arguing", "argue", "argued"], correct: 0, explanation: "Parallel with \"to write\" and \"to think\" requires \"to argue.\"" },
  { id: "t2rw2h-6", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "His ______ for detail made him an excellent editor, though a famously slow one.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["meticulousness", "indifference", "haste", "carelessness"], correct: 0, explanation: "Being a great but slow editor points to \"meticulousness.\"" },
  { id: "t2rw2h-7", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "Whereas the first study relied on participants' self-reports, the second used direct measurements, and its results differed sharply from the first.", prompt: "Which choice best describes the main purpose of the text?", type: "mcq", choices: ["To contrast two studies' methods and note their differing results.", "To argue that self-reports are the best method.", "To summarize only the first study.", "To dismiss both studies as flawed."], correct: 0, explanation: "\"Whereas … the second …\" contrasts methods and notes differing results (choice A)." },
  { id: "t2rw2h-8", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "Neither the report nor the slides ______ ready in time for the morning meeting.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["was", "were", "is", "has been"], correct: 1, explanation: "With \"neither … nor,\" the verb agrees with the nearer subject — plural \"slides\" — so \"were.\"" },
];
const T2_M_M1: SatQuestion[] = [
  { id: "t2m1-1", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 5x − 3 = 22, what is the value of x?", type: "grid", gridAnswers: ["5"], explanation: "5x = 25, so x = 5." },
  { id: "t2m1-2", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "A bag of 24 apples is shared equally among 6 people. How many apples does each person get?", type: "mcq", choices: ["4", "6", "18", "12"], correct: 0, explanation: "24 ÷ 6 = 4." },
  { id: "t2m1-3", section: "math", domain: "Advanced Math", difficulty: "med", prompt: "If f(x) = x² + 1, what is the value of f(3)?", type: "mcq", choices: ["10", "7", "9", "6"], correct: 0, explanation: "f(3) = 9 + 1 = 10." },
  { id: "t2m1-4", section: "math", domain: "Geometry and Trigonometry", difficulty: "med", prompt: "A square has an area of 36. What is the length of one side?", type: "grid", gridAnswers: ["6"], explanation: "√36 = 6." },
  { id: "t2m1-5", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 3(x − 1) = 12, what is the value of x?", type: "grid", gridAnswers: ["5"], explanation: "x − 1 = 4, so x = 5." },
  { id: "t2m1-6", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "A car uses 4 gallons of gas to travel 120 miles. How many miles per gallon is that?", type: "mcq", choices: ["30", "40", "24", "20"], correct: 0, explanation: "120 ÷ 4 = 30 mpg." },
];
const T2_M_M2E: SatQuestion[] = [
  { id: "t2m2e-1", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If x + 8 = 20, what is the value of x?", type: "grid", gridAnswers: ["12"], explanation: "x = 20 − 8 = 12." },
  { id: "t2m2e-2", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "What is 25% of 40?", type: "mcq", choices: ["10", "15", "20", "4"], correct: 0, explanation: "0.25 × 40 = 10." },
  { id: "t2m2e-3", section: "math", domain: "Geometry and Trigonometry", difficulty: "easy", prompt: "A rectangle has a length of 9 and a width of 2. What is its area?", type: "grid", gridAnswers: ["18"], explanation: "9 × 2 = 18." },
  { id: "t2m2e-4", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If 4x = 20, what is the value of x?", type: "mcq", choices: ["5", "16", "24", "4"], correct: 0, explanation: "x = 20 ÷ 4 = 5." },
  { id: "t2m2e-5", section: "math", domain: "Advanced Math", difficulty: "easy", prompt: "What is the value of 3² + 1?", type: "grid", gridAnswers: ["10"], explanation: "3² = 9; 9 + 1 = 10." },
  { id: "t2m2e-6", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "A class has 5 boys and 5 girls. What fraction of the class are boys?", type: "mcq", choices: ["1/2", "1/5", "5/5", "2/5"], correct: 0, explanation: "5 boys out of 10 students = 1/2." },
];
const T2_M_M2H: SatQuestion[] = [
  { id: "t2m2h-1", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If x² − 9 = 0 and x > 0, what is the value of x?", type: "grid", gridAnswers: ["3"], explanation: "x² = 9, so x = 3 (taking the positive root)." },
  { id: "t2m2h-2", section: "math", domain: "Algebra", difficulty: "hard", prompt: "If x + y = 12 and x − y = 4, what is the value of x?", type: "mcq", choices: ["8", "6", "4", "10"], correct: 0, explanation: "Add the equations: 2x = 16, so x = 8." },
  { id: "t2m2h-3", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If 5^x = 125, what is the value of x?", type: "grid", gridAnswers: ["3"], explanation: "125 = 5³, so x = 3." },
  { id: "t2m2h-4", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "hard", prompt: "A $50 item is discounted by 30%. What is the sale price?", type: "mcq", choices: ["$35", "$30", "$20", "$45"], correct: 0, explanation: "30% of 50 = 15; 50 − 15 = $35." },
  { id: "t2m2h-5", section: "math", domain: "Geometry and Trigonometry", difficulty: "hard", prompt: "A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?", type: "grid", gridAnswers: ["10"], explanation: "√(36 + 64) = √100 = 10." },
  { id: "t2m2h-6", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If g(x) = 2x + 3, what is the value of g(g(1))?", type: "mcq", choices: ["13", "7", "11", "5"], correct: 0, explanation: "g(1) = 5; g(5) = 2(5) + 3 = 13." },
];

export const SAT_FORM_2: SatForm = {
  id: "practice-2",
  title: "InHero SAT Practice Test 2",
  rw: { m1: [...T2_RW_M1, ...T2_RW_M1_B, ...T2_RW_M1_C], m2easy: [...T2_RW_M2E, ...T2_RW_M2E_B, ...T2_RW_M2E_C], m2hard: [...T2_RW_M2H, ...T2_RW_M2H_B, ...T2_RW_M2H_C], timeSec: 1080 },
  math: { m1: [...T2_M_M1, ...T2_M_M1_B, ...T2_M_M1_C], m2easy: [...T2_M_M2E, ...T2_M_M2E_B, ...T2_M_M2E_C], m2hard: [...T2_M_M2H, ...T2_M_M2H_B, ...T2_M_M2H_C], timeSec: 960 },
};

// ─────────────────────────── PRACTICE TEST 3 ───────────────────────────
const T3_RW_M1: SatQuestion[] = [
  { id: "t3rw1-1", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "The audience grew ______ as the speaker continued well past the scheduled time.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["restless", "delighted", "silent", "curious"], correct: 0, explanation: "An audience kept too long grows \"restless.\"" },
  { id: "t3rw1-2", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "The company announced ______ new product line at the conference yesterday.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["its", "it's", "their", "they're"], correct: 0, explanation: "Singular \"company\" takes the singular possessive \"its.\"" },
  { id: "t3rw1-3", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "Fireflies produce light through a chemical reaction in their abdomens — a process called bioluminescence that gives off almost no heat.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Fireflies create nearly heatless light through a chemical reaction.", "Fireflies are hot to the touch when they glow.", "Fireflies are unable to produce light.", "Fireflies glow by using electricity."], correct: 0, explanation: "Bioluminescence produces light with \"almost no heat\" (choice A)." },
  { id: "t3rw1-4", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "The trail was steep and rocky. ______, the hikers reached the summit by noon.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Therefore", "Nonetheless", "Moreover", "Likewise"], correct: 1, explanation: "Reaching the top despite a hard trail is a contrast — \"Nonetheless.\"" },
  { id: "t3rw1-5", section: "rw", domain: "Standard English Conventions", difficulty: "med", passage: "After the meeting finally ended ______ the team went out to celebrate.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["ended the", "ended, the", "ended; the", "ended: the"], correct: 1, explanation: "An introductory clause is followed by a comma before the main clause." },
  { id: "t3rw1-6", section: "rw", domain: "Craft and Structure", difficulty: "med", passage: "The instructions were so ______ that many users were unsure what to do.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["ambiguous", "clear", "concise", "detailed"], correct: 0, explanation: "Leaving users unsure means the instructions were \"ambiguous.\"" },
  { id: "t3rw1-7", section: "rw", domain: "Information and Ideas", difficulty: "med", passage: "Admission to the exhibit is free for children under 12; all other visitors pay $15.", prompt: "Which statement is best supported by the text?", type: "mcq", choices: ["A 10-year-old can enter without paying.", "Every visitor must pay $15.", "Adults are admitted for free.", "Children under 12 pay $15."], correct: 0, explanation: "Children under 12 are free, so a 10-year-old enters free (choice A)." },
  { id: "t3rw1-8", section: "rw", domain: "Expression of Ideas", difficulty: "med", passage: "The city council approved the budget. ______, construction on the new library can begin next month.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["However", "As a result", "Otherwise", "Instead"], correct: 1, explanation: "Approval enables construction — cause/effect \"As a result.\"" },
];
const T3_RW_M2E: SatQuestion[] = [
  { id: "t3rw2e-1", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The sun was very ______, so everyone put on sunglasses.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["bright", "dark", "cold", "quiet"], correct: 0, explanation: "Needing sunglasses means the sun was \"bright.\"" },
  { id: "t3rw2e-2", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "My friends ______ coming over to my house tonight.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["is", "are", "was", "am"], correct: 1, explanation: "\"Friends\" is plural, so \"are.\"" },
  { id: "t3rw2e-3", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Bees help plants by carrying pollen from flower to flower, which allows the plants to make seeds.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Bees help plants reproduce by moving pollen.", "Bees harm flowers when they visit.", "Plants do not need bees at all.", "Bees eat the seeds of plants."], correct: 0, explanation: "Moving pollen lets plants make seeds — bees aid reproduction (choice A)." },
  { id: "t3rw2e-4", section: "rw", domain: "Expression of Ideas", difficulty: "easy", passage: "I was very hungry after practice. ______, I made myself a sandwich.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["For example", "So", "However", "Meanwhile"], correct: 1, explanation: "Being hungry leads to making food — \"So.\"" },
  { id: "t3rw2e-5", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "They ______ soccer after school yesterday afternoon.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["play", "plays", "played", "playing"], correct: 2, explanation: "\"Yesterday\" requires the past tense \"played.\"" },
  { id: "t3rw2e-6", section: "rw", domain: "Craft and Structure", difficulty: "easy", passage: "The blanket was soft and ______, perfect for a cold winter night.", prompt: "Which choice completes the text with the most logical word?", type: "mcq", choices: ["warm", "icy", "rough", "wet"], correct: 0, explanation: "Good for a cold night means it was \"warm.\"" },
  { id: "t3rw2e-7", section: "rw", domain: "Information and Ideas", difficulty: "easy", passage: "Drinking enough water helps your body stay cool, carry nutrients, and remove waste.", prompt: "Which choice best states the main idea of the text?", type: "mcq", choices: ["Water performs several important jobs in the body.", "Water is harmful to the body.", "Water only cools the body.", "The body does not need water."], correct: 0, explanation: "Three roles are listed — choice A." },
  { id: "t3rw2e-8", section: "rw", domain: "Standard English Conventions", difficulty: "easy", passage: "We took ______ honest approach and admitted our mistake.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["a", "an", "the only", "some"], correct: 1, explanation: "\"Honest\" begins with a silent h (a vowel sound), so \"an.\"" },
];
const T3_RW_M2H: SatQuestion[] = [
  { id: "t3rw2h-1", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "The novel's pacing is ______: tense action gives way abruptly to long, quiet passages and then back again.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["uneven", "consistent", "rapid", "predictable"], correct: 0, explanation: "Abrupt shifts between action and quiet make the pacing \"uneven.\"" },
  { id: "t3rw2h-2", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "The author opens by conceding her opponents' strongest point, only to argue that it ultimately supports her own position.", prompt: "Which choice best describes the function of the concession?", type: "mcq", choices: ["To grant a rival point before turning it to her own advantage.", "To abandon her argument entirely.", "To summarize the opponents' full case.", "To bring the essay to a close."], correct: 0, explanation: "She concedes the point, then repurposes it for her side (choice A)." },
  { id: "t3rw2h-3", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "Students' average test scores were 78 after 6 hours of sleep, 84 after 7 hours, and 85 after 8 hours.", prompt: "Which statement is best supported by the data?", type: "mcq", choices: ["The largest score gain came from increasing sleep from 6 to 7 hours.", "Scores decreased as sleep increased.", "Six hours of sleep produced the highest scores.", "Sleep had no effect on scores."], correct: 0, explanation: "78 to 84 is +6; 84 to 85 is +1 — the biggest gain is 6 to 7 hours (choice A)." },
  { id: "t3rw2h-4", section: "rw", domain: "Expression of Ideas", difficulty: "hard", passage: "The medication relieves symptoms within minutes. ______, it does nothing to address the underlying cause of the illness.", prompt: "Which choice completes the text with the most logical transition?", type: "mcq", choices: ["Therefore", "However", "Similarly", "Thus"], correct: 1, explanation: "Quick relief vs. not treating the cause is a contrast — \"However.\"" },
  { id: "t3rw2h-5", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "A good leader listens carefully, decides fairly, and ______ responsibility for the outcomes.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["taking", "takes", "to take", "taken"], correct: 1, explanation: "Parallel with \"listens\" and \"decides\" requires \"takes.\"" },
  { id: "t3rw2h-6", section: "rw", domain: "Craft and Structure", difficulty: "hard", passage: "Critics found the film's symbolism too ______, spelling out its meaning at every turn rather than trusting the audience.", prompt: "Which choice completes the text with the most logical and precise word?", type: "mcq", choices: ["heavy-handed", "subtle", "restrained", "elusive"], correct: 0, explanation: "Spelling everything out is \"heavy-handed.\"" },
  { id: "t3rw2h-7", section: "rw", domain: "Information and Ideas", difficulty: "hard", passage: "Unlike earlier accounts that blamed a single cause, this history insists the crisis arose from many overlapping factors.", prompt: "Which choice best describes the main purpose of the text?", type: "mcq", choices: ["To argue the crisis had multiple causes, against earlier single-cause accounts.", "To identify the one true cause of the crisis.", "To summarize earlier accounts with approval.", "To deny that the crisis had any causes."], correct: 0, explanation: "It contrasts a multi-cause view with single-cause accounts (choice A)." },
  { id: "t3rw2h-8", section: "rw", domain: "Standard English Conventions", difficulty: "hard", passage: "The first prototype overheated within minutes ______ the second ran flawlessly for hours.", prompt: "Which choice conforms to the conventions of Standard English?", type: "mcq", choices: ["overheated, the", "overheated; the", "overheated the", "overheated: the"], correct: 1, explanation: "Two independent clauses are joined by a semicolon." },
];
const T3_M_M1: SatQuestion[] = [
  { id: "t3m1-1", section: "math", domain: "Algebra", difficulty: "med", prompt: "If 6x + 5 = 29, what is the value of x?", type: "grid", gridAnswers: ["4"], explanation: "6x = 24, so x = 4." },
  { id: "t3m1-2", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "A pizza is cut into 8 equal slices and 3 are eaten. What fraction of the pizza remains?", type: "mcq", choices: ["5/8", "3/8", "1/8", "5/3"], correct: 0, explanation: "8 − 3 = 5 slices remain out of 8: 5/8." },
  { id: "t3m1-3", section: "math", domain: "Advanced Math", difficulty: "med", prompt: "If f(x) = x² − 2x, what is the value of f(4)?", type: "mcq", choices: ["8", "6", "12", "4"], correct: 0, explanation: "f(4) = 16 − 8 = 8." },
  { id: "t3m1-4", section: "math", domain: "Geometry and Trigonometry", difficulty: "med", prompt: "A triangle has angles measuring 90° and 45°. What is the measure, in degrees, of the third angle?", type: "grid", gridAnswers: ["45"], explanation: "180 − 90 − 45 = 45°." },
  { id: "t3m1-5", section: "math", domain: "Algebra", difficulty: "med", prompt: "If (2x) / 5 = 4, what is the value of x?", type: "grid", gridAnswers: ["10"], explanation: "2x = 20, so x = 10." },
  { id: "t3m1-6", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "med", prompt: "12 is what percent of 48?", type: "mcq", choices: ["25%", "12%", "30%", "20%"], correct: 0, explanation: "12 ÷ 48 = 0.25 = 25%." },
];
const T3_M_M2E: SatQuestion[] = [
  { id: "t3m2e-1", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If x − 5 = 5, what is the value of x?", type: "grid", gridAnswers: ["10"], explanation: "x = 5 + 5 = 10." },
  { id: "t3m2e-2", section: "math", domain: "Advanced Math", difficulty: "easy", prompt: "What is the value of 10 × 10?", type: "mcq", choices: ["100", "20", "110", "1000"], correct: 0, explanation: "10 × 10 = 100." },
  { id: "t3m2e-3", section: "math", domain: "Geometry and Trigonometry", difficulty: "easy", prompt: "A square has a side length of 8. What is its perimeter?", type: "grid", gridAnswers: ["32"], explanation: "4 × 8 = 32." },
  { id: "t3m2e-4", section: "math", domain: "Algebra", difficulty: "easy", prompt: "If x + 2 = 9, what is the value of x?", type: "mcq", choices: ["7", "11", "5", "9"], correct: 0, explanation: "x = 9 − 2 = 7." },
  { id: "t3m2e-5", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "What is half of 50?", type: "grid", gridAnswers: ["25"], explanation: "50 ÷ 2 = 25." },
  { id: "t3m2e-6", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "easy", prompt: "A class has 12 boys and 18 girls. How many students are there in total?", type: "mcq", choices: ["30", "6", "216", "24"], correct: 0, explanation: "12 + 18 = 30." },
];
const T3_M_M2H: SatQuestion[] = [
  { id: "t3m2h-1", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If x² − 16 = 0 and x > 0, what is the value of x?", type: "grid", gridAnswers: ["4"], explanation: "x² = 16, so x = 4 (positive root)." },
  { id: "t3m2h-2", section: "math", domain: "Algebra", difficulty: "hard", prompt: "If 2x + y = 11 and y = 3, what is the value of x?", type: "mcq", choices: ["4", "5", "3", "8"], correct: 0, explanation: "2x + 3 = 11 → 2x = 8 → x = 4." },
  { id: "t3m2h-3", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If 2^x = 64, what is the value of x?", type: "grid", gridAnswers: ["6"], explanation: "64 = 2⁶, so x = 6." },
  { id: "t3m2h-4", section: "math", domain: "Problem-Solving and Data Analysis", difficulty: "hard", prompt: "A price increases from $20 to $26. What is the percent increase?", type: "mcq", choices: ["30%", "6%", "26%", "20%"], correct: 0, explanation: "Increase = 6; 6 ÷ 20 = 0.30 = 30%." },
  { id: "t3m2h-5", section: "math", domain: "Geometry and Trigonometry", difficulty: "hard", prompt: "A right triangle has legs of length 9 and 12. What is the length of the hypotenuse?", type: "grid", gridAnswers: ["15"], explanation: "√(81 + 144) = √225 = 15." },
  { id: "t3m2h-6", section: "math", domain: "Advanced Math", difficulty: "hard", prompt: "If h(x) = 3x − 2, what is the value of h(h(2))?", type: "mcq", choices: ["10", "4", "7", "12"], correct: 0, explanation: "h(2) = 4; h(4) = 3(4) − 2 = 10." },
];

export const SAT_FORM_3: SatForm = {
  id: "practice-3",
  title: "InHero SAT Practice Test 3",
  rw: { m1: [...T3_RW_M1, ...T3_RW_M1_B, ...T3_RW_M1_C], m2easy: [...T3_RW_M2E, ...T3_RW_M2E_B, ...T3_RW_M2E_C], m2hard: [...T3_RW_M2H, ...T3_RW_M2H_B, ...T3_RW_M2H_C], timeSec: 1080 },
  math: { m1: [...T3_M_M1, ...T3_M_M1_B, ...T3_M_M1_C], m2easy: [...T3_M_M2E, ...T3_M_M2E_B, ...T3_M_M2E_C], m2hard: [...T3_M_M2H, ...T3_M_M2H_B, ...T3_M_M2H_C], timeSec: 1080 },
};
