/**
 * US college analysis database for the parent hub (/parents/colleges).
 *
 * The fields Korean parents ask 유학원s about, in one place: what kind of
 * student each school actually wants (인재상), location/setting, admissions
 * data, early plans, international financial aid, signature programs,
 * internship & career pipelines, and essay/supplement angles.
 *
 * Kept factual and conservative. Acceptance rates / SAT bands / costs are
 * recent approximations and drift every cycle — the UI frames everything as
 * "약(approx.)" with a check-the-official-site disclaimer. Test policies have
 * been especially volatile since 2024; treat them as "최근 기준".
 */

export type CollegeCategory =
  | "아이비리그"
  | "최상위 사립"
  | "최상위 주립"
  | "리버럴 아츠 칼리지";

export interface College {
  name: string;          // official English name
  nameKo: string;        // Korean name
  emoji: string;
  category: CollegeCategory;
  location: string;      // city, state + Korean context
  setting: "대도시" | "도시" | "근교" | "소도시·칼리지타운";
  type: "사립" | "공립";
  undergrads: string;    // approx undergrad enrollment
  acceptRate: string;    // recent approximate
  satRange: string;      // middle 50% approx
  testPolicy: string;    // recent policy (volatile — disclaimed in UI)
  earlyPlan: string;     // ED/EA/REA structure
  aidIntl: string;       // financial aid for internationals
  costBand: string;      // approx annual total cost of attendance
  personaTitle: string;  // 인재상 one-liner
  persona: string;       // 인재상 detail
  admitPoints: string[]; // what actually moves the needle
  programs: string[];    // signature majors/programs
  internships: string;   // internship & career pipeline
  essayNote: string;     // supplement/essay angle
  koreanNote: string;    // Korean/international applicant note
}

export const COLLEGES: College[] = [
  // ───────────────────────── 아이비리그 ─────────────────────────
  {
    name: "Harvard University", nameKo: "하버드 대학교", emoji: "🏛️",
    category: "아이비리그", location: "Cambridge, MA — 보스턴 바로 옆 대학 도시",
    setting: "도시", type: "사립", undergrads: "약 7,200명",
    acceptRate: "약 3–4%", satRange: "약 1500–1580", testPolicy: "SAT/ACT 필수 (2024년 재도입)",
    earlyPlan: "REA (제한적 얼리액션) — 타교 ED/EA 동시 지원 불가",
    aidIntl: "유학생 니드블라인드 + 재정 필요 100% 충족 (최상급)",
    costBand: "연 총비용 약 $87,000 (보조금 전 기준)",
    personaTitle: "분야를 가리지 않는 '리더가 될 사람'",
    persona: "하버드는 특정 스펙보다 '이 학생이 자기 분야와 커뮤니티를 이끌 사람인가'를 봅니다. 학업 최상위는 전제 조건이고, 그 위에 한 분야를 깊게 판 탁월함(distinction)과 타인에게 영향을 주는 성품·리더십을 찾습니다. 전 분야에서 고르게 잘하는 학생보다, 무언가 하나로 '전국·국제급'인 학생이 유리합니다.",
    admitPoints: [
      "한 분야의 전국·국제급 탁월함 (올림피아드, 연구, 창작, 사회활동 등)",
      "추천서에서 드러나는 인성·지적 호기심 — 하버드는 추천서 비중이 큰 학교",
      "리더십의 '결과' — 직함이 아니라 무엇을 바꿨는지",
    ],
    programs: ["경제학", "정부학(Government)", "컴퓨터과학", "생명과학·Pre-med", "응용수학"],
    internships: "보스턴·뉴욕 금융, 컨설팅, 빅테크로 이어지는 미국 최강 수준의 동문 네트워크. 교내 리서치(학부생 연구 펀딩), 하버드 비즈니스 스쿨·의대·로스쿨 연계 기회와 여름 공공 서비스 펀딩(서머 펀딩)이 풍부합니다.",
    essayNote: "2023년부터 짧은 서플 5개 — '당신이 커뮤니티에 무엇을 가져올 사람인가'를 일관되게 보여줘야 합니다.",
    koreanNote: "유학생 니드블라인드라 소득과 무관하게 공정 심사. 한국 지원자 풀이 매우 강해 '한국에서 또 한 명의 수학 잘하는 학생'으로 보이지 않는 차별화가 핵심입니다.",
  },
  {
    name: "Yale University", nameKo: "예일 대학교", emoji: "🎭",
    category: "아이비리그", location: "New Haven, CT — 뉴욕에서 기차 1.5시간",
    setting: "도시", type: "사립", undergrads: "약 6,600명",
    acceptRate: "약 3.7%", satRange: "약 1500–1580", testPolicy: "시험 점수 필수·유연형 (SAT/ACT/AP/IB 중 택1 제출)",
    earlyPlan: "SCEA (싱글초이스 얼리액션)",
    aidIntl: "유학생 니드블라인드 + 100% 충족 (최상급)",
    costBand: "연 총비용 약 $90,000",
    personaTitle: "커뮤니티를 만드는 인문 정신의 리더",
    persona: "예일은 '캠퍼스에 무엇을 기여할 사람인가'를 가장 노골적으로 묻는 학교입니다. 14개 기숙 칼리지 중심의 공동체 문화가 강해, 혼자 잘난 학생보다 주변을 끌어올리는 학생을 선호합니다. 인문·예술 전통이 깊지만 최근 공학·CS 투자도 큽니다.",
    admitPoints: [
      "공동체 기여의 구체적 증거 — 동아리·학교·지역을 실제로 바꾼 경험",
      "지적 즐거움(intellectual vitality)이 드러나는 글쓰기",
      "인문·예술 + STEM을 잇는 융합형 프로필에 호의적",
    ],
    programs: ["경제학", "정치학·역사", "심리학", "분자생물학", "연극·예술(드라마스쿨 전통)"],
    internships: "뉴욕 금융·로펌·미디어와 워싱턴 정계로 이어지는 파이프라인이 강력. 학부생 여름 펠로우십(국제 경험 펀딩 ISA 등)과 기숙 칼리지 단위의 멘토링이 특징입니다.",
    essayNote: "짧은 에세이가 많고 '왜 예일인가'를 진짜 구체적으로 — 기숙 칼리지·세미나 문화에 대한 이해가 보여야 합니다.",
    koreanNote: "니드블라인드 + 전액 지원 가능. 에세이·추천서 등 '글로 드러나는 사람됨' 비중이 커서 점수만 좋은 지원자는 걸러집니다.",
  },
  {
    name: "Princeton University", nameKo: "프린스턴 대학교", emoji: "🐯",
    category: "아이비리그", location: "Princeton, NJ — 뉴욕·필라델피아 사이 조용한 타운",
    setting: "근교", type: "사립", undergrads: "약 5,600명 (아이비 중 가장 작은 학부 중심)",
    acceptRate: "약 4%", satRange: "약 1510–1580", testPolicy: "SAT/ACT 필수 (2025년 재도입 발표)",
    earlyPlan: "SCEA (싱글초이스 얼리액션)",
    aidIntl: "유학생 니드블라인드 + 100% 충족 · 전액 그랜트(대출 없음)",
    costBand: "연 총비용 약 $86,000",
    personaTitle: "학부 교육에 모든 것을 건 '학자형' 학생",
    persona: "프린스턴은 대학원보다 학부에 자원을 집중하는 학교로, 전원이 졸업 논문(Senior Thesis)을 씁니다. 깊게 파고드는 학구적 성향, 교수와 1:1로 연구할 준비가 된 학생을 원합니다. '국가와 인류에 대한 봉사(In the Nation's Service)' 모토처럼 공적 기여 의식도 중요합니다.",
    admitPoints: [
      "지적 깊이 — 한 주제를 스스로 끝까지 파본 경험 (독립 연구·심화 프로젝트)",
      "수학·과학 경시 실적은 공대·수학과에서 특히 강한 신호",
      "봉사·공공 기여의 진정성 (모토와 연결)",
    ],
    programs: ["수학 (세계 최정상)", "물리학", "경제·금융(ORFE)", "공공정책(SPIA)", "컴퓨터과학"],
    internships: "뉴욕 금융권(특히 퀀트·IB) 진출이 매우 강함. 학부생 전원 논문 제도 덕에 대학원·연구직 진학 경쟁력 최상위. International Internship Program으로 해외 인턴 펀딩도 제공.",
    essayNote: "활동보다 '생각'을 묻는 서플이 많습니다. 자기 목소리로 사유한 흔적이 없으면 어렵습니다.",
    koreanNote: "장학금이 전액 그랜트(갚을 필요 없음)라 재정 부담 면에서 유학생에게 최고 수준. 학부 중심이라 한국 부모가 기대하는 '교수 케어'가 실제로 존재하는 학교입니다.",
  },
  {
    name: "Columbia University", nameKo: "컬럼비아 대학교", emoji: "🗽",
    category: "아이비리그", location: "New York, NY — 맨해튼 한복판",
    setting: "대도시", type: "사립", undergrads: "약 8,900명 (컬럼비아칼리지+공대)",
    acceptRate: "약 4%", satRange: "약 1500–1570", testPolicy: "테스트 옵셔널 (아이비 중 드물게 유지)",
    earlyPlan: "ED (얼리디시전 — 합격 시 등록 의무)",
    aidIntl: "유학생은 니드어웨어이나, 합격 시 필요액 100% 충족",
    costBand: "연 총비용 약 $93,000 (뉴욕 물가 포함 최고가권)",
    personaTitle: "고전을 읽고 도시를 무대로 쓰는 지성",
    persona: "전교생이 듣는 Core Curriculum(고전 중심 교양 필수)이 정체성입니다. 플라톤부터 현대 사상까지 토론할 지적 체력, 그리고 뉴욕이라는 도시를 적극 활용할 에너지를 가진 학생을 찾습니다. 도시형 자기주도 학생에게 최적입니다.",
    admitPoints: [
      "독서·글쓰기 깊이 — 서플에 '좋아하는 책·매체' 목록을 직접 묻는 학교",
      "도시 자원을 활용해 본 경험 (인턴, 현장 활동, 저널리즘 등)",
      "Core Curriculum에 대한 진심 어린 이해를 '왜 컬럼비아' 에세이에",
    ],
    programs: ["경제학", "정치학·국제관계(SIPA 연계)", "저널리즘 전통", "컴퓨터과학·공학(SEAS)", "영문·비교문학"],
    internships: "위치가 곧 스펙 — 월스트리트 금융, 미디어, UN, 스타트업 인턴을 학기 중에도 병행 가능. 금융·컨설팅·미디어 취업 파이프라인은 미국 최상위권입니다.",
    essayNote: "리스트형 서플(읽은 것·들은 것)이 독특 — 평소의 지적 식단이 그대로 드러나니 미리 쌓아야 합니다.",
    koreanNote: "한국 학생·동문 커뮤니티가 매우 큼. 유학생은 니드어웨어라 지원 요청 금액이 합격에 영향을 줄 수 있다는 점은 알고 지원해야 합니다.",
  },
  {
    name: "University of Pennsylvania", nameKo: "유펜 (펜실베이니아 대학교)", emoji: "🐍",
    category: "아이비리그", location: "Philadelphia, PA — 필라델피아 대학가",
    setting: "대도시", type: "사립", undergrads: "약 10,000명",
    acceptRate: "약 5%", satRange: "약 1500–1570", testPolicy: "최근 시험 점수 필수로 회귀 발표 — 공식 확인 필요",
    earlyPlan: "ED — 얼리 합격 비중이 매우 큰 학교",
    aidIntl: "유학생 니드어웨어 · 합격 시 100% 충족 (전액 그랜트)",
    costBand: "연 총비용 약 $92,000",
    personaTitle: "이론과 실전을 잇는 실용주의 리더",
    persona: "벤저민 프랭클린의 실용주의 정신을 내세우는 학교로, '아는 것'보다 '아는 것으로 무엇을 하는가'를 봅니다. Wharton(경영), 간호, 공학 등 프리프로페셔널 색이 가장 강한 아이비입니다. 복수 학위(M&T, LSM 등) 프로그램에 야심 있는 학생이 모입니다.",
    admitPoints: [
      "지원 단과대학(Wharton/공대/칼리지/간호)별로 인재상이 사실상 다름 — 단과대 맞춤 지원 필수",
      "창업·실전 프로젝트·인턴 등 '실행' 경험",
      "Wharton은 리더십+계량 능력, M&T·LSM 등 듀얼디그리는 최상위 변별",
    ],
    programs: ["Wharton 경영 (학부 경영 세계 1위급)", "M&T (경영+공학)", "간호", "경제학", "생명공학·LSM"],
    internships: "Wharton발 금융·컨설팅 리크루팅은 미국 전체 최강 수준. 1학년부터 인턴·창업 문화가 일반적이고, 필라델피아+뉴욕(기차 1.5시간) 양쪽 시장을 씁니다.",
    essayNote: "'왜 펜, 왜 이 단과대'가 핵심 — 학교 전체가 아니라 지원 스쿨의 구체 자원을 짚어야 합니다.",
    koreanNote: "한국 학생 선호도 최상위권 학교. ED 합격률이 RD의 2~3배 수준이라, 유펜이 1지망이면 ED 활용 가치가 큽니다.",
  },
  {
    name: "Brown University", nameKo: "브라운 대학교", emoji: "🎨",
    category: "아이비리그", location: "Providence, RI — 보스턴에서 1시간",
    setting: "도시", type: "사립", undergrads: "약 7,200명",
    acceptRate: "약 5%", satRange: "약 1500–1570", testPolicy: "SAT/ACT 필수 (2024년 재도입)",
    earlyPlan: "ED",
    aidIntl: "유학생 니드블라인드 전환 발표 (최근) + 100% 충족",
    costBand: "연 총비용 약 $92,000",
    personaTitle: "스스로 커리큘럼을 설계하는 자기주도 탐험가",
    persona: "필수 교양이 없는 Open Curriculum이 브라운의 전부입니다. '무엇을 배울지 스스로 결정할 수 있는 학생'을 뽑기 때문에, 자유가 주어졌을 때 방황하지 않고 자기 길을 설계해 온 증거를 원합니다. 성적도 선택적 Pass/Fail이 가능할 만큼 자율적입니다.",
    admitPoints: [
      "스스로 만든 학습 경험 — 독학, 자기 설계 프로젝트, 비정형 활동",
      "분야를 가로지르는 호기심 (이중 관심사를 잇는 스토리)",
      "'Open Curriculum으로 무엇을 할 것인가'에 대한 구체적 답",
    ],
    programs: ["컴퓨터과학", "국제관계", "인지과학·뇌과학", "PLME (8년 의대 직통)", "문예창작·미디어"],
    internships: "PLME(학부+의대 직통)는 미국 최고 인기 프로그램 중 하나. 자유 전공 문화 덕에 테크·미디어·창업 쪽 진출이 활발하고, BrownConnect로 동문 연계 인턴 펀딩을 제공합니다.",
    essayNote: "Open Curriculum을 '편해서'가 아니라 '이렇게 쓰겠다'로 답해야 — 자유를 다룰 계획이 보여야 합니다.",
    koreanNote: "유학생 니드블라인드 전환으로 재정 문턱이 낮아짐. 자기주도 서사가 약한 '관리형 스펙' 학생에게는 가장 어울리지 않는 아이비입니다.",
  },
  {
    name: "Dartmouth College", nameKo: "다트머스 대학", emoji: "🌲",
    category: "아이비리그", location: "Hanover, NH — 뉴햄프셔 산속 칼리지타운",
    setting: "소도시·칼리지타운", type: "사립", undergrads: "약 4,500명 (아이비 최소 규모)",
    acceptRate: "약 5%", satRange: "약 1490–1570", testPolicy: "SAT/ACT 필수 (2024년 가장 먼저 재도입)",
    earlyPlan: "ED",
    aidIntl: "유학생 니드블라인드 (2022년 전환) + 100% 충족",
    costBand: "연 총비용 약 $91,000",
    personaTitle: "야외와 공동체를 사랑하는 끈끈한 제너럴리스트",
    persona: "아이비 중 가장 작고 가장 공동체적인 학교. 학부 교육 집중도와 동문 결속력(Dartmouth Mafia)이 유명합니다. 자연·아웃도어 문화(전교생 오리엔테이션 하이킹)가 정체성이라, 도시형보다 공동체·모험형 학생이 맞습니다. D-Plan(쿼터제)으로 학기 중 인턴이 자유롭습니다.",
    admitPoints: [
      "공동체 적합성 — 작은 학교에서 4년을 함께할 사람인지",
      "아웃도어·스포츠·모험 경험이 실제 플러스가 되는 드문 학교",
      "D-Plan을 활용할 계획 (학기 분산 인턴·연구)",
    ],
    programs: ["경제학", "정부학", "컴퓨터과학", "공학(Thayer)", "지구과학·환경"],
    internships: "졸업생 1인당 금융·컨설팅 진출률이 아이비 최상위권 — 작은 규모 대비 월스트리트 영향력이 큽니다. D-Plan 덕분에 남들이 학기 중일 때 오프시즌 인턴을 잡는 전략이 가능합니다.",
    essayNote: "공동체·장소에 대한 애정이 드러나야 — 다트머스는 '왜 우리 산골까지 오고 싶은가'를 진지하게 봅니다.",
    koreanNote: "유학생 니드블라인드. 한국 학생 수가 적은 편이라 오히려 차별화가 쉽고, 동문 네트워크의 밀도는 졸업 후 큰 자산이 됩니다.",
  },
  {
    name: "Cornell University", nameKo: "코넬 대학교", emoji: "🍎",
    category: "아이비리그", location: "Ithaca, NY — 뉴욕주 북부 협곡의 칼리지타운",
    setting: "소도시·칼리지타운", type: "사립", undergrads: "약 16,000명 (아이비 최대)",
    acceptRate: "약 8% (단과대별 차이 큼)", satRange: "약 1470–1560", testPolicy: "SAT/ACT 필수 회귀 (2026 가을 입학부터) — 단과대별 확인",
    earlyPlan: "ED",
    aidIntl: "유학생 니드어웨어 · 합격 시 100% 충족",
    costBand: "연 총비용 약 $92,000",
    personaTitle: "'어떤 분야든 최고'를 찾아온 실전형 전문가 지망생",
    persona: "\"any person, any study\" — 호텔경영부터 노사관계, 농생명, 공학까지 전공 스펙트럼이 아이비 중 가장 넓습니다. 8개 학부 칼리지가 각자 따로 뽑기 때문에 '코넬 합격'이 아니라 '코넬 ○○칼리지 합격' 전략을 짜야 합니다. 전공 적합성(fit to major)을 가장 깐깐하게 보는 아이비입니다.",
    admitPoints: [
      "지원 칼리지·전공과 활동의 정합성 — 코넬은 '전공 갈아타기' 서사에 박합니다",
      "공대·CS는 사실상 최상위 변별, 호텔·ILR·농생명은 스토리 적합성이 핵심",
      "ED 활용 가치 큼 (특히 1지망 칼리지가 명확할 때)",
    ],
    programs: ["공학·CS (아이비 최강급)", "호텔경영(SHA, 세계 1위)", "ILR(노사관계)", "농생명(CALS)", "건축(AAP, 학부 최상위)"],
    internships: "공학·CS는 빅테크, 호텔스쿨은 글로벌 호스피탈리티 업계 직통, Dyson 경영은 금융권으로 — 칼리지별 산업 파이프라인이 뚜렷합니다. 뉴욕시에 Cornell Tech 캠퍼스도 보유.",
    essayNote: "서플 전체가 '왜 이 칼리지, 왜 이 전공' — 학교 일반론을 쓰면 바로 탈락하는 유형입니다.",
    koreanNote: "한국 학생이 가장 많이 지원하는 아이비 중 하나. 단과대 선택이 합격률을 좌우하므로 '간판'보다 적합성으로 칼리지를 골라야 합니다.",
  },

  // ───────────────────────── 최상위 사립 ─────────────────────────
  {
    name: "MIT", nameKo: "매사추세츠 공과대학", emoji: "⚙️",
    category: "최상위 사립", location: "Cambridge, MA — 하버드 옆, 보스턴 강변",
    setting: "도시", type: "사립", undergrads: "약 4,600명",
    acceptRate: "약 4–5%", satRange: "약 1530–1580 (수학 만점대 일반적)", testPolicy: "SAT/ACT 필수 (2022년 최초 재도입)",
    earlyPlan: "EA (비제한 얼리액션) · ED 없음",
    aidIntl: "유학생 니드블라인드 + 100% 충족 (최상급)",
    costBand: "연 총비용 약 $85,000",
    personaTitle: "손으로 만들며 세상을 고치는 메이커",
    persona: "MIT는 '시험 잘 보는 학생'이 아니라 '만드는 사람(maker)'을 뽑습니다. 손을 더럽히며 무언가를 직접 만들고, 실패하고, 다시 만든 경험 — 그리고 그것을 즐기는 태도(mens et manus, 머리와 손)를 봅니다. 협업 문화가 강해 독불장군형 천재보다 잘 어울려 일하는 천재를 선호합니다.",
    admitPoints: [
      "수학·과학 경시(AMC/AIME, 올림피아드)는 사실상 공통 언어",
      "직접 만든 것 — 코드, 로봇, 연구, 장치 — 의 포트폴리오",
      "MIT 지원서는 공통원서가 아닌 자체 양식 — '즐거움으로 하는 일'을 묻는 문항이 핵심",
    ],
    programs: ["컴퓨터과학(Course 6)", "전기·기계공학", "수학", "물리학", "경영(Sloan 학부)·경제"],
    internships: "UROP(학부생 연구 프로그램)로 1학년부터 교수 연구실 참여가 제도화 — 미국 학부 연구 시스템의 원조. 빅테크·퀀트·딥테크 스타트업 채용에서 최상위 브랜드이며 창업 생태계(The Engine 등)도 강력합니다.",
    essayNote: "잘 쓴 글보다 진짜 목소리 — MIT 에세이는 꾸민 글을 가장 빨리 알아채는 것으로 유명합니다.",
    koreanNote: "유학생 니드블라인드. 한국 경시권 학생들의 1지망이 몰리는 곳이라 수상 실적 '위'에 자기만의 만들기 서사가 있어야 합니다.",
  },
  {
    name: "Stanford University", nameKo: "스탠퍼드 대학교", emoji: "🌲",
    category: "최상위 사립", location: "Stanford, CA — 실리콘밸리 한가운데",
    setting: "근교", type: "사립", undergrads: "약 7,800명",
    acceptRate: "약 4%", satRange: "약 1500–1580", testPolicy: "SAT/ACT 필수 회귀 발표 (2026 가을 입학부터)",
    earlyPlan: "REA (제한적 얼리액션)",
    aidIntl: "유학생 니드어웨어 · 합격 시 100% 충족",
    costBand: "연 총비용 약 $92,000",
    personaTitle: "지적 활력(intellectual vitality)과 창업가 정신",
    persona: "스탠퍼드가 공식적으로 쓰는 단어가 'intellectual vitality' — 배움 자체에서 뿜어져 나오는 에너지입니다. 실리콘밸리 DNA답게 아이디어를 실행으로 옮긴 경험, 기존 방식에 도전한 경험을 높게 봅니다. 학업+활동 모두에서 '스케일'을 만든 학생이 강합니다.",
    admitPoints: [
      "무언가를 0→1로 만든 경험 (창업, 단체 설립, 연구, 제품)",
      "에세이에서 터져 나오는 host of ideas — 짧은 서플 다수에 개성이 실려야",
      "지원자 풀이 세계 최강 — '전부 잘함'보다 '하나가 무서움'이 통함",
    ],
    programs: ["컴퓨터과학 (세계 최정상)", "공학 전반", "경제학", "Symbolic Systems (CS+인지)", "생명과학·Pre-med"],
    internships: "실리콘밸리가 곧 캠퍼스 — 재학 중 빅테크·스타트업 인턴이 일상이고, 교수·동문이 투자자인 창업 생태계는 세계 유일급입니다. CS 졸업생 초봉·취업률 모두 최상위.",
    essayNote: "유명한 '룸메이트에게 보내는 편지' 서플 — 격식을 벗고 진짜 자기다움을 보여줘야 하는 문항입니다.",
    koreanNote: "니드어웨어이므로 재정지원 요청이 변수일 수 있음. 합격자 프로필이 '활동의 스케일' 면에서 아이비보다도 화려한 경향이 있습니다.",
  },
  {
    name: "Caltech", nameKo: "캘리포니아 공과대학", emoji: "🔭",
    category: "최상위 사립", location: "Pasadena, CA — LA 근교",
    setting: "근교", type: "사립", undergrads: "약 1,000명 (초소형)",
    acceptRate: "약 3%", satRange: "약 1530–1580 (사실상 수학 만점)", testPolicy: "SAT/ACT 필수 (2025년 재도입)",
    earlyPlan: "REA",
    aidIntl: "유학생 니드어웨어 · 합격 시 100% 충족",
    costBand: "연 총비용 약 $86,000",
    personaTitle: "순수 과학에 미친 초소수 정예",
    persona: "학부생 1,000명, 교수 대 학생 비율 3:1의 초밀도 연구 기관입니다. 전교생이 듣는 살인적인 Core(물리·수학 필수 시퀀스)를 버틸 수학적 체력과, 과학 그 자체를 향한 순수한 집착을 가진 학생만 찾습니다. 명예 규율(Honor Code)로 시험을 집에서 볼 만큼 신뢰 문화가 강합니다.",
    admitPoints: [
      "수학·물리 실력의 증거 — 올림피아드, 대학 수준 선행, 연구",
      "STEM '열정'이 아니라 STEM '집착'의 구체적 흔적",
      "협업 증거 — Core를 함께 버티는 문화라 팀워크도 봅니다",
    ],
    programs: ["물리학 (세계 최정상)", "수학", "천문·행성과학(JPL 연계)", "화학", "컴퓨터과학"],
    internships: "NASA JPL(제트추진연구소)을 직접 운영하는 학교 — 학부생 SURF 연구 프로그램으로 거의 전원이 연구를 경험합니다. 졸업생 다수가 최상위 대학원·연구소로, 학계 진출 비율이 미국 최고 수준.",
    essayNote: "서플이 전부 STEM 경험 깊이를 파고듭니다 — 일반 입시용 다재다능 서사는 통하지 않습니다.",
    koreanNote: "규모가 작아 한국 학생 수도 극소수 — 그만큼 합격 시 희소가치가 큽니다. 의대 진학용 학교가 아니라 연구자의 학교라는 점을 분명히 알고 지원해야 합니다.",
  },
  {
    name: "University of Chicago", nameKo: "시카고 대학교", emoji: "📖",
    category: "최상위 사립", location: "Chicago, IL — 시카고 하이드파크",
    setting: "대도시", type: "사립", undergrads: "약 7,500명",
    acceptRate: "약 5%", satRange: "약 1510–1580", testPolicy: "테스트 옵셔널 (가장 먼저 도입, 유지 중)",
    earlyPlan: "EA + ED1 + ED2 — 얼리 옵션이 가장 많은 학교",
    aidIntl: "유학생 니드어웨어 · 합격 시 100% 충족",
    costBand: "연 총비용 약 $93,000 (최고가권)",
    personaTitle: "괴짜 같은 질문을 사랑하는 순수 지성",
    persona: "\"재미가 죽으러 오는 곳(where fun comes to die)\"이라는 자조적 별명이 자부심인 학교. 악명 높은 괴짜 에세이 프롬프트(예: '치즈가 사라진 세상을 논하라')로 지적 유연성을 시험합니다. 토론과 이론, 사상 자체를 즐기는 학생 — 경제학·수학·인문학의 학풍이 미국에서 가장 학구적입니다.",
    admitPoints: [
      "괴짜 서플 에세이가 사실상 당락 결정 — 글로 노는 능력",
      "이론적 깊이 (경제·수학·철학 성향 학생에게 최적)",
      "ED2 존재 — 아이비 얼리 탈락 후 전략적 카드로 활용 가능",
    ],
    programs: ["경제학 (노벨상 사관학교)", "수학", "정치학·사회사상", "물리학", "생물학·Pre-med"],
    internships: "시카고 금융(옵션·트레이딩의 도시)과 컨설팅 진출이 강하고, 경제학과는 연준·IMF·학계로 이어집니다. Metcalf 인턴십 프로그램으로 학부생에게 유급 인턴을 학교가 직접 매칭해 줍니다.",
    essayNote: "Uncommon Essay에 시간을 가장 많이 써야 하는 학교 — 안전하게 쓰면 떨어지고, 위험하게 잘 쓰면 붙습니다.",
    koreanNote: "테스트 옵셔널 유지 + ED1/ED2/EA 등 지원 경로가 많아 전략적 선택지가 풍부. 학업 강도가 미국 최상위라 '학구파' 자녀에게 잘 맞습니다.",
  },
  {
    name: "Duke University", nameKo: "듀크 대학교", emoji: "😈",
    category: "최상위 사립", location: "Durham, NC — 노스캐롤라이나 리서치트라이앵글",
    setting: "도시", type: "사립", undergrads: "약 6,500명",
    acceptRate: "약 5%", satRange: "약 1500–1570", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "ED",
    aidIntl: "유학생 니드어웨어 · 합격 시 100% 충족",
    costBand: "연 총비용 약 $92,000",
    personaTitle: "학업과 열정(스포츠·리더십)을 모두 불태우는 올라운더",
    persona: "아이비급 학업 + 전국구 스포츠 문화(농구) + 남부의 따뜻한 공동체가 듀크의 조합입니다. 공부만 하는 학생보다 캠퍼스 라이프에 온몸으로 뛰어들 에너지형 리더를 선호합니다. 의대·공대·공공정책 모두 강한 균형형 명문입니다.",
    admitPoints: [
      "에너지와 열정이 보이는 프로필 — 듀크는 '캠퍼스에 활기를 더할 사람'을 명시적으로 찾음",
      "리서치트라이앵글 연계 연구·의학 관심 학생에게 강한 어필 포인트",
      "ED 합격률이 RD 대비 크게 높은 대표적 학교",
    ],
    programs: ["공공정책(Sanford)", "생명과학·Pre-med (듀크병원)", "공학(Pratt)", "경제학", "컴퓨터과학"],
    internships: "듀크대학병원 중심의 의학 연구 기회가 학부생에게 열려 있고, DukeEngage(여름 사회혁신 활동 전액 지원)가 시그니처. 금융·컨설팅·테크 리크루팅도 남부 최강입니다.",
    essayNote: "공동체 기여와 정체성에 관한 선택 서플 — 자기 배경을 편안하게 이야기할 수 있으면 유리합니다.",
    koreanNote: "한국 인지도 대비 지원 난도가 합리적인 편이었으나 최근 급상승. 의대 진학(Pre-med) 트랙으로 한국 학생 선호가 높습니다.",
  },
  {
    name: "Northwestern University", nameKo: "노스웨스턴 대학교", emoji: "💜",
    category: "최상위 사립", location: "Evanston, IL — 시카고 북쪽 호숫가",
    setting: "근교", type: "사립", undergrads: "약 8,800명",
    acceptRate: "약 7%", satRange: "약 1500–1570", testPolicy: "시험 점수 필수 회귀 발표 (최근) — 확인 필요",
    earlyPlan: "ED — 신입생 절반 이상을 ED로 선발",
    aidIntl: "유학생 니드어웨어 · 합격 시 100% 충족",
    costBand: "연 총비용 약 $93,000",
    personaTitle: "여러 재능을 동시에 굴리는 'AND'형 인재",
    persona: "노스웨스턴의 공식 키워드가 'AND'입니다 — 저널리즘 AND CS, 연극 AND 경제처럼 복수의 정체성을 가진 학생. 쿼터제라 수강 폭이 넓고, 저널리즘(Medill)·연극(Communication)·음악 등 프로페셔널 스쿨이 학부에 있는 게 특징입니다.",
    admitPoints: [
      "두 개 이상의 분야를 진짜로 결합한 프로필",
      "Medill(저널리즘)·연극·음악 지망은 포트폴리오·실적이 직접 변별",
      "ED 비중이 매우 커서 1지망이면 ED가 사실상 정석",
    ],
    programs: ["저널리즘(Medill, 미국 최고)", "연극·커뮤니케이션", "경제학", "공학(McCormick)", "음악(Bienen)"],
    internships: "Medill은 학기제 인턴(Journalism Residency)이 커리큘럼에 내장 — 주요 언론사로 직행합니다. 시카고 금융·컨설팅 접근성과 엔터테인먼트(동문이 할리우드에 두터움) 양쪽 파이프라인 보유.",
    essayNote: "'왜 노스웨스턴' 하나에 집중되는 구조 — 학교의 AND 문화와 자기 조합을 정확히 연결해야 합니다.",
    koreanNote: "ED로 절반을 뽑는 구조라 RD는 체감 난도가 훨씬 높습니다. 문·이과 융합형 한국 학생에게 잘 맞는 학풍입니다.",
  },
  {
    name: "Johns Hopkins University", nameKo: "존스홉킨스 대학교", emoji: "🩺",
    category: "최상위 사립", location: "Baltimore, MD — 워싱턴 D.C.에서 1시간",
    setting: "도시", type: "사립", undergrads: "약 6,000명",
    acceptRate: "약 6%", satRange: "약 1530–1570", testPolicy: "SAT/ACT 필수 회귀 발표 (2026 가을 입학부터)",
    earlyPlan: "ED1 + ED2",
    aidIntl: "유학생 니드어웨어 · 합격 시 100% 충족",
    costBand: "연 총비용 약 $92,000",
    personaTitle: "연구로 인류 문제를 풀겠다는 집요한 탐구자",
    persona: "미국 최초의 연구 중심 대학이자 의학·공중보건·국제관계의 세계적 본산입니다. '연구 경험이 있는 학생'이 아니라 '연구가 삶인 학생'을 찾습니다. 학부생 3분의 2 이상이 연구에 참여하며, 협업적 무한 탐구(collaboration + impact)가 공식 인재상입니다.",
    admitPoints: [
      "연구 경험의 깊이 — 단순 랩 견학이 아닌 기여의 증거",
      "의·생명 지망생의 전국 격전지 — BME(의공학)는 세계 1위라 별도 최상위 변별",
      "에세이에서 '협업'을 보여줘야 — 홉킨스가 공식적으로 강조하는 단어",
    ],
    programs: ["의공학(BME, 세계 1위)", "공중보건", "신경과학", "국제관계(SAIS 연계)", "분자생물학·Pre-med"],
    internships: "존스홉킨스병원·블룸버그 공중보건대학원·APL(응용물리연구소)이라는 세계 최고 연구 인프라를 학부생이 씁니다. NIH(국립보건원)와 D.C.가 가까워 바이오·정책 인턴 접근성이 탁월합니다.",
    essayNote: "합격 에세이를 매년 공개하는 'Essays That Worked' 페이지가 있을 만큼 에세이를 중시 — 반드시 읽고 톤을 파악하세요.",
    koreanNote: "Pre-med 지망 한국 학생의 성지이지만, 그만큼 '의대 가고 싶어요'만으로는 차별화 불가 — 구체적 연구 질문이 있어야 합니다.",
  },
  {
    name: "Vanderbilt University", nameKo: "밴더빌트 대학교", emoji: "🎸",
    category: "최상위 사립", location: "Nashville, TN — 음악의 도시 내슈빌",
    setting: "도시", type: "사립", undergrads: "약 7,100명",
    acceptRate: "약 5–6%", satRange: "약 1510–1570", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "ED1 + ED2",
    aidIntl: "유학생 니드어웨어 · 합격자 필요액 충족 (Opportunity Vanderbilt)",
    costBand: "연 총비용 약 $90,000",
    personaTitle: "공부 잘하면서 행복할 줄 아는 균형형 인재",
    persona: "'미국에서 가장 행복한 명문대'로 불리는 학교 — 학업 최상위권이면서 학생 만족도·공동체 분위기가 좋기로 유명합니다. 성적 경쟁만 하는 학생보다 협력적이고 사회성 좋은 고성취자를 선호합니다. 교육학(Peabody)과 음악(Blair)이 학부에 있는 것도 특징.",
    admitPoints: [
      "성취 + 따뜻함의 조합 — 추천서에서 인성이 중요하게 작동",
      "ED1/ED2를 합쳐 절반 이상 선발 — 얼리 전략 필수",
      "리더십을 '함께'의 언어로 서술하면 잘 맞음",
    ],
    programs: ["교육학(Peabody, 미국 최상위)", "의·생명과학", "경제학", "공학", "음악(Blair)"],
    internships: "내슈빌은 헬스케어 산업의 수도(HCA 등 본사 밀집) — 의료 경영·바이오 인턴이 풍부합니다. 음악 산업 연계도 독특한 자산. 남부 금융·컨설팅 리크루팅 강세.",
    essayNote: "서플이 짧고 단순한 편 — 그만큼 커먼앱 메인 에세이와 추천서의 비중이 상대적으로 큽니다.",
    koreanNote: "장학 정책(Opportunity Vanderbilt)이 후하기로 유명. 학업 강도 대비 삶의 질을 중시하는 가정에 인기가 높아졌습니다.",
  },
  {
    name: "Rice University", nameKo: "라이스 대학교", emoji: "🦉",
    category: "최상위 사립", location: "Houston, TX — 휴스턴 메디컬센터 옆",
    setting: "대도시", type: "사립", undergrads: "약 4,500명",
    acceptRate: "약 7%", satRange: "약 1500–1570", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "ED1 + ED2",
    aidIntl: "유학생 니드어웨어 · 합격 시 100% 충족",
    costBand: "연 총비용 약 $80,000 (최상위 사립 중 저렴한 편)",
    personaTitle: "겸손하고 협력적인 STEM 강자",
    persona: "'남부의 아이비'로 불리는 소수정예 연구 대학. 전교생이 11개 기숙 칼리지에 무작위 배정되는 공동체 문화가 핵심이라, 잘난 척 없는(unpretentious) 협력형 인재를 명시적으로 찾습니다. 세계 최대 의료단지(TMC)가 길 건너에 있어 의·생명 기회가 독보적입니다.",
    admitPoints: [
      "협업·공동체 기여의 증거 — Rice의 공식 문화 키워드",
      "TMC 연계를 노리는 Pre-med·BME 지망생에게 최적의 스토리 연결",
      "'The Box' — 자신을 보여주는 이미지 한 장을 내는 독특한 전형",
    ],
    programs: ["생명공학·BME", "컴퓨터과학", "기계·전기공학", "음악(Shepherd)", "건축"],
    internships: "Texas Medical Center(세계 최대 병원 단지)가 도보 거리 — 학부생 임상·연구 섀도잉 기회가 미국 최고 수준입니다. 휴스턴 에너지 산업(엔지니어링 채용)과 NASA 존슨우주센터도 가깝습니다.",
    essayNote: "전통의 'Box' 문항(이미지 제출)이 상징 — 한 장으로 자기다움을 전하는 센스가 필요합니다.",
    koreanNote: "학비가 동급 사립 대비 저렴하고 규모 대비 기회 밀도가 높아 '가성비 명문'으로 한국 부모 선호 급상승 중입니다.",
  },
  {
    name: "University of Notre Dame", nameKo: "노트르담 대학교", emoji: "☘️",
    category: "최상위 사립", location: "Notre Dame, IN — 시카고에서 2시간",
    setting: "소도시·칼리지타운", type: "사립", undergrads: "약 8,900명",
    acceptRate: "약 11%", satRange: "약 1470–1550", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "REA",
    aidIntl: "유학생 니드어웨어 · 합격 시 필요액 충족",
    costBand: "연 총비용 약 $86,000",
    personaTitle: "신념과 봉사 정신을 가진 공동체형 리더",
    persona: "가톨릭 전통의 명문으로, 신앙 자체보다 '가치관과 봉사 정신이 분명한 학생'을 찾습니다. 동문 충성도가 미국 대학 중 최고 수준(Notre Dame family)이라 공동체 적합성이 합격의 큰 부분입니다. 풋볼로 상징되는 전통·소속감 문화가 강합니다.",
    admitPoints: [
      "봉사·윤리적 리더십의 일관된 기록",
      "공동체 전통에 대한 진정성 있는 공감 (종교 무관)",
      "경영(Mendoza)은 학부 최상위권으로 별도 변별",
    ],
    programs: ["경영(Mendoza)", "정치학", "신학·철학", "공학", "건축(고전 건축 전통)"],
    internships: "'Domer 네트워크'로 불리는 동문 채용 문화가 강력 — 시카고·뉴욕 금융, 컨설팅, 회계 빅4 진출이 두텁습니다. 봉사 연계 프로그램(ACE 등)도 시그니처.",
    essayNote: "가치관을 묻는 서플 — 자신이 믿는 것과 그렇게 살아온 증거를 정직하게 쓰는 게 정답입니다.",
    koreanNote: "한국 인지도 대비 실제 위상(특히 경영·취업 네트워크)이 높은 학교. 종교가 없어도 가치 지향이 맞으면 전혀 문제없습니다.",
  },
  {
    name: "Georgetown University", nameKo: "조지타운 대학교", emoji: "🏛️",
    category: "최상위 사립", location: "Washington, D.C. — 백악관에서 3km",
    setting: "대도시", type: "사립", undergrads: "약 7,900명",
    acceptRate: "약 12%", satRange: "약 1450–1550", testPolicy: "SAT/ACT 사실상 필수 (옵셔널 도입한 적 없음)",
    earlyPlan: "EA (제한형 — 타교 ED와 병행 불가)",
    aidIntl: "유학생 니드어웨어 · 지원 제한적",
    costBand: "연 총비용 약 $90,000",
    personaTitle: "세계 무대를 꿈꾸는 미래 외교관·정책가",
    persona: "국제관계(SFS)는 세계 최고로 꼽히며, 워싱턴 D.C.라는 위치가 곧 커리큘럼입니다. 국제 문제에 대한 진짜 관심 — 시사 이슈를 자기 언어로 분석할 수 있는 수준 — 을 가진 학생을 찾습니다. 예수회 전통의 'people for others' 봉사 정신도 봅니다.",
    admitPoints: [
      "국제 이슈 관련 활동 (모의유엔, 토론, 정책 리서치, 어학)",
      "자체 지원서 + 인터뷰(동문) 전통 — 말로 자신을 설명할 준비",
      "SFS·경영(McDonough)·칼리지 등 스쿨별 지원",
    ],
    programs: ["국제관계(SFS, 세계 최고)", "정치학", "경영(McDonough)", "경제학", "외국어·지역학"],
    internships: "학기 중 국무부·싱크탱크·의회·국제기구 인턴이 일상 — D.C. 위치는 정책·외교 지망생에게 대체 불가입니다. 외교관·국제기구 진출 동문 네트워크 세계 최강급.",
    essayNote: "자체 원서라 커먼앱 재활용 불가 — 에세이를 따로 준비해야 하며 시사 인터뷰 대비도 필요합니다.",
    koreanNote: "외교·국제기구 지망 한국 학생의 1순위. 유학생 재정지원이 약한 편이라 비용 계획을 미리 세워야 합니다.",
  },
  {
    name: "Carnegie Mellon University", nameKo: "카네기멜런 대학교", emoji: "🤖",
    category: "최상위 사립", location: "Pittsburgh, PA — 피츠버그 대학가",
    setting: "도시", type: "사립", undergrads: "약 7,800명",
    acceptRate: "약 11% (CS는 약 4–7%)", satRange: "약 1500–1570 (CS는 상단)", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "ED1 + ED2",
    aidIntl: "유학생 재정지원 거의 없음 — 사실상 전액 자비 각오",
    costBand: "연 총비용 약 $90,000",
    personaTitle: "한 분야를 끝까지 파는 스페셜리스트",
    persona: "CS는 MIT·스탠퍼드와 어깨를 나란히 하는 세계 최정상, 드라마·미술 등 예술도 미국 최상위 — '골고루'가 아니라 '한 우물'의 학교입니다. 단과대별로 사실상 별개 입시를 치르며, 지원 전공에 대한 깊이가 전부입니다.",
    admitPoints: [
      "School of CS는 미국 전체에서 가장 치열한 단일 프로그램 중 하나 — 경시·프로젝트 최상위 필요",
      "예술 계열은 오디션·포트폴리오가 당락의 핵심",
      "전공 적합성 — '왜 이 분야'에 대한 수년간의 증거",
    ],
    programs: ["컴퓨터과학(SCS, 세계 1위급)", "로보틱스·AI", "드라마(뮤지컬 명문)", "미술·디자인", "전기컴퓨터공학·정보시스템"],
    internships: "빅테크·AI 기업 채용에서 'CMU CS' 브랜드는 사실상 보증수표 — 실리콘밸리와 시애틀로의 파이프라인이 압도적입니다. 피츠버그 자체도 로보틱스·자율주행 허브(다수 연구소 소재).",
    essayNote: "지원 전공 외길 서사가 유리 — CMU는 '탐색 중'인 학생보다 '결심한' 학생을 원합니다.",
    koreanNote: "유학생 재정지원이 거의 없다는 점이 최대 변수. CS 지망이면 한국 정보올림피아드·USACO 급 실적이 사실상 출발선입니다.",
  },
  {
    name: "University of Southern California", nameKo: "USC (서던캘리포니아 대학교)", emoji: "🌴",
    category: "최상위 사립", location: "Los Angeles, CA — LA 다운타운 남쪽",
    setting: "대도시", type: "사립", undergrads: "약 21,000명 (사립 중 대형)",
    acceptRate: "약 9–10%", satRange: "약 1450–1540", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "EA (일부 전공) · ED 없음 — 장학금은 조기 지원 마감 주의",
    aidIntl: "유학생 니드 지원 없음 · 성적 장학금(메릿)은 가능",
    costBand: "연 총비용 약 $95,000 (최고가권)",
    personaTitle: "엔터·미디어·테크를 넘나드는 네트워커",
    persona: "영화(SC Cinematic Arts)는 세계 1위, 게임·커뮤니케이션·음악 산업과의 연결이 미국에서 가장 실전적인 학교입니다. 'Trojan Family'로 불리는 동문 네트워크 문화가 강해, 사교성과 야망을 함께 가진 학생이 잘 맞습니다.",
    admitPoints: [
      "영화·게임·음악 등 크리에이티브 지망은 포트폴리오가 당락 결정",
      "복수 전공·스쿨 간 융합 프로그램 활용 계획",
      "메릿 장학금(반액·전액)은 12월 초 조기 마감 — 일정 관리 필수",
    ],
    programs: ["영화·영상(세계 1위)", "게임 디자인", "커뮤니케이션(Annenberg)", "경영(Marshall)", "컴퓨터과학·공학(Viterbi)"],
    internships: "할리우드 스튜디오·게임사·미디어 기업 인턴이 학기 중 일상 — 엔터테인먼트 산업 취업은 USC 동문망이 지배적입니다. LA 테크(실리콘비치) 채용도 활발합니다.",
    essayNote: "짧은 문답형 서플(좋아하는 것 리스트 등)에 개성이 드러나야 — 형식적 답변은 바로 묻힙니다.",
    koreanNote: "한국 동문 네트워크가 미국 사립대 중 최대급 — 한인 사회 연결이 강점. 유학생은 니드 지원이 없어 비용 부담이 크지만 메릿 장학 기회는 열려 있습니다.",
  },
  {
    name: "New York University", nameKo: "뉴욕 대학교 (NYU)", emoji: "🍎",
    category: "최상위 사립", location: "New York, NY — 맨해튼 그리니치빌리지 (캠퍼스 없는 도시 그 자체)",
    setting: "대도시", type: "사립", undergrads: "약 29,000명 (초대형)",
    acceptRate: "약 8–9%", satRange: "약 1470–1560", testPolicy: "테스트 옵셔널 (유연한 제출 정책)",
    earlyPlan: "ED1 + ED2",
    aidIntl: "유학생 재정지원 제한적 — 비용 계획 필수",
    costBand: "연 총비용 약 $95,000+ (뉴욕 생활비 포함 미국 최고가권)",
    personaTitle: "도시를 캠퍼스 삼는 독립적인 야심가",
    persona: "담장 없는 캠퍼스, 뉴욕 그 자체가 학교입니다. 보호받는 대학 생활보다 도시에서 스스로 길을 만드는 독립성이 필수입니다. 경영(Stern), 예술(Tisch), 그리고 아부다비·상하이 글로벌 캠퍼스까지 — 세계화 지향이 가장 강한 미국 대학입니다.",
    admitPoints: [
      "Stern(경영)·Tisch(영화·공연)는 사실상 별도 최상위 입시",
      "도시·글로벌 경험에 대한 갈증을 구체적으로",
      "ED 활용도가 높고, 스쿨 선택이 합격률을 크게 좌우",
    ],
    programs: ["경영(Stern)", "영화·공연예술(Tisch)", "경제학", "컴퓨터과학(Courant)", "글로벌 리버럴 스터디스"],
    internships: "월스트리트·미디어·패션·스타트업 — 학기 중 인턴 병행이 NYU 문화의 표준입니다. Stern은 IB(투자은행) 타깃스쿨이며 Tisch는 영화·방송 업계 직통입니다.",
    essayNote: "'왜 NYU' 하나로 압축된 서플 — 어느 스쿨, 어느 캠퍼스, 왜 뉴욕인지 삼단 구체화가 필요합니다.",
    koreanNote: "한국 학생 수 미국 최상위권 — 커뮤니티는 풍부하지만 그만큼 차별화 필요. 기숙사·생활비 포함 총비용이 가장 비싼 축이니 4년 예산을 현실적으로 잡아야 합니다.",
  },
  {
    name: "Emory University", nameKo: "에모리 대학교", emoji: "🦅",
    category: "최상위 사립", location: "Atlanta, GA — 애틀랜타 근교",
    setting: "근교", type: "사립", undergrads: "약 7,100명",
    acceptRate: "약 10–11%", satRange: "약 1460–1550", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "ED1 + ED2",
    aidIntl: "유학생 니드어웨어 · 지원 제한적, 메릿 장학(Emory Scholars) 있음",
    costBand: "연 총비용 약 $88,000",
    personaTitle: "보건·의학·사회 문제에 진심인 따뜻한 성취가",
    persona: "CDC(미국 질병통제예방센터)가 캠퍼스 옆에 있는 공중보건·의학 명문입니다. 옥스퍼드 칼리지(2년제 소규모 캠퍼스 트랙)라는 독특한 진입 경로도 있습니다. 성취 지향적이면서도 사회적 책임감이 강한 학생을 선호합니다.",
    admitPoints: [
      "보건·의학·생명윤리 관심의 일관성 (CDC·에모리병원 스토리 연결)",
      "Oxford College 트랙 — 소규모 교육 선호 학생에게 별도의 문",
      "ED1/ED2 활용 가치 큼",
    ],
    programs: ["공중보건", "생물학·Pre-med", "경영(Goizueta)", "심리학·신경과학", "철학·윤리"],
    internships: "CDC·에모리대학병원·카터센터가 모두 인접 — 공중보건·글로벌 헬스 인턴 기회는 미국 최고 수준입니다. 애틀랜타는 코카콜라·델타 등 대기업 본사 도시라 경영 쪽 채용도 강합니다.",
    essayNote: "지적 관심을 묻는 짧은 서플 — Pre-med 클리셰가 가장 많이 몰리는 학교라 구체성으로 승부해야 합니다.",
    koreanNote: "의·보건 계열 한국 지원자에게 인지도 이상의 실속(병원·CDC 인프라)이 있는 학교. 한인 커뮤니티(애틀랜타 한인타운)도 가까워 생활 적응이 쉽습니다.",
  },

  // ───────────────────────── 최상위 주립 ─────────────────────────
  {
    name: "UC Berkeley", nameKo: "UC 버클리", emoji: "🐻",
    category: "최상위 주립", location: "Berkeley, CA — 샌프란시스코 만 건너",
    setting: "도시", type: "공립", undergrads: "약 33,000명",
    acceptRate: "약 11% (CS·EECS는 한 자릿수 초반)", satRange: "시험 미반영 (Test-Free)", testPolicy: "UC 전체 Test-Free — SAT 제출해도 반영 안 함",
    earlyPlan: "얼리 없음 — 11월 30일 단일 마감 (UC 공통원서)",
    aidIntl: "유학생 재정지원 없음 + 비거주자 추가 등록금",
    costBand: "유학생 연 총비용 약 $80,000",
    personaTitle: "치열한 환경에서 스스로 기회를 쟁취하는 강자",
    persona: "공립 1위를 다투는 연구 거인 — 노벨상, 스타트업, 사회운동의 산실입니다. 학생을 살뜰히 챙겨주는 학교가 아니라, 거대한 자원 속에서 스스로 길을 찾는 헝그리한 학생이 성공합니다. UC 지원서는 에세이(PIQ 4편)와 성적 중심이며 추천서를 받지 않습니다.",
    admitPoints: [
      "내신(GPA)과 수강 강도가 절대적 — UC는 학업 기록 비중이 가장 큼",
      "PIQ 4편 — 커먼앱과 완전히 다른 실용적 문체 필요",
      "CS·EECS 직접 지원은 최고 난도 — 전공 우회 전략은 막히는 추세",
    ],
    programs: ["EECS·컴퓨터과학 (세계 최정상)", "경영(Haas)", "경제학", "화학·화학공학", "데이터사이언스"],
    internships: "실리콘밸리까지 1시간 — 빅테크·스타트업 채용에서 스탠퍼드와 함께 양대 공급원입니다. 학내 창업 생태계(SkyDeck 액셀러레이터)와 연구실 규모도 공립 최대급.",
    essayNote: "PIQ는 문학적 에세이가 아니라 '증거 진술서' — 한 일과 결과를 구체적·직설적으로 쓰는 게 정답입니다.",
    koreanNote: "유학생 재정지원이 없어 4년 약 $32만의 자비 부담을 전제해야 합니다. 추천서·인터뷰가 없어 성적·에세이만으로 승부하는 구조가 한국 학생에게 유불리 양면이 있습니다.",
  },
  {
    name: "UCLA", nameKo: "UCLA (캘리포니아 대학교 LA)", emoji: "🐻‍❄️",
    category: "최상위 주립", location: "Los Angeles, CA — LA 웨스트우드",
    setting: "대도시", type: "공립", undergrads: "약 33,000명",
    acceptRate: "약 9% (미국 지원자 수 1위 대학)", satRange: "시험 미반영 (Test-Free)", testPolicy: "UC 전체 Test-Free",
    earlyPlan: "얼리 없음 — 11월 30일 단일 마감",
    aidIntl: "유학생 재정지원 없음 + 비거주자 추가 등록금",
    costBand: "유학생 연 총비용 약 $80,000",
    personaTitle: "다재다능 + 도시 에너지의 균형형 올라운더",
    persona: "매년 미국에서 가장 많은 지원서를 받는 대학입니다. 학업·연구는 버클리급이면서 날씨·캠퍼스·스포츠·엔터 산업 접근성까지 갖춰 '균형'을 원하는 최상위권 학생이 몰립니다. 의대·병원(UCLA Health) 인프라도 학부생에게 큰 자산입니다.",
    admitPoints: [
      "GPA·수강 강도 최상위 + PIQ에서의 구체적 임팩트 증명",
      "지원자 풀이 거대해 '특별한 한 가지'가 더 중요",
      "영화·연기 등 예술 전공은 별도 포트폴리오 전형",
    ],
    programs: ["경제·경영경제", "심리학", "컴퓨터과학", "영화·연극(TFT)", "생명과학·Pre-med"],
    internships: "할리우드·실리콘비치(LA 테크)·UCLA 메디컬센터가 모두 시내 — 엔터·테크·의학 인턴이 풍부합니다. 동문 규모가 거대해 캘리포니아 전역 채용에서 강력합니다.",
    essayNote: "PIQ에서 '균형 잡힌 모범생'이 아니라 '하나가 뾰족한 사람'으로 보여야 거대 지원 풀에서 살아남습니다.",
    koreanNote: "LA 한인 커뮤니티 인프라(음식·생활)가 미국 최고라 적응이 가장 쉬운 명문 — 다만 유학생 학비 전액 자비는 버클리와 동일합니다.",
  },
  {
    name: "University of Michigan", nameKo: "미시간 대학교 (앤아버)", emoji: "〽️",
    category: "최상위 주립", location: "Ann Arbor, MI — 미국 최고의 칼리지타운 중 하나",
    setting: "소도시·칼리지타운", type: "공립", undergrads: "약 33,000명",
    acceptRate: "약 18% (주외·유학생은 더 낮음)", satRange: "약 1400–1540", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "EA (11월 1일) — 사실상 필수로 통용",
    aidIntl: "유학생 니드 지원 거의 없음",
    costBand: "유학생 연 총비용 약 $85,000",
    personaTitle: "거대한 무대에서 리더십을 발휘하는 'Leaders and Best'",
    persona: "공립 명문 중 가장 '사립 같은' 학교 — 공학·경영(Ross)·음악·스포츠까지 전부 미국 최상위입니다. 학교 슬로건 'Leaders and Best'처럼 큰 조직에서 주도해 본 경험을 좋아합니다. 동문 네트워크(전 세계 60만+)는 공립 최강입니다.",
    admitPoints: [
      "EA 지원이 사실상 표준 — RD는 자리가 적음",
      "'왜 미시간' 에세이 — 단과대·프로그램 구체성 요구",
      "Ross 경영은 별도 포트폴리오성 지원으로 최상위 변별",
    ],
    programs: ["공학 (전 분야 최상위)", "경영(Ross)", "컴퓨터과학", "정치학·공공정책(Ford)", "음악·퍼포밍아츠"],
    internships: "빅테크·자동차(디트로이트)·금융까지 전 산업 리크루팅이 도는 초대형 채용 시장 — 캠퍼스 커리어페어 규모가 미국 최대급입니다. Ross는 시카고·뉴욕 금융 타깃스쿨.",
    essayNote: "커뮤니티 에세이 + 왜 미시간 — 둘 다 구체적 프로그램명·기회를 짚어야 형식적으로 보이지 않습니다.",
    koreanNote: "한국에서 인지도·동문망이 모두 탄탄한 주립 1순위급. 유학생 합격률은 공표치보다 낮다고 보고 EA로 일찍 넣는 것이 핵심입니다.",
  },
  {
    name: "University of Virginia", nameKo: "버지니아 대학교 (UVA)", emoji: "🏛️",
    category: "최상위 주립", location: "Charlottesville, VA — 워싱턴 D.C.에서 2시간",
    setting: "소도시·칼리지타운", type: "공립", undergrads: "약 17,000명",
    acceptRate: "약 17% (주외는 더 낮음)", satRange: "약 1420–1540", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "ED + EA 모두 운영 (공립에서는 드묾)",
    aidIntl: "유학생 니드 지원 없음",
    costBand: "유학생 연 총비용 약 $80,000",
    personaTitle: "명예와 전통을 존중하는 신사적 리더",
    persona: "토머스 제퍼슨이 설계한 캠퍼스(유네스코 세계유산)와 학생 자치 명예 규율(Honor System)이 정체성입니다. 공립이지만 사립 같은 학부 교육 밀도를 갖췄고, 품격·신뢰·공동체 기여를 중시하는 문화가 강합니다.",
    admitPoints: [
      "ED 운영 공립 — 1지망이면 ED 카드 활용 가능",
      "명예·공동체 가치에 대한 공감이 에세이에 자연스럽게",
      "경영(McIntire)·공공정책(Batten) 등 상위 진입 프로그램 인지",
    ],
    programs: ["경영(McIntire)", "경제학", "정치학·공공정책", "영문학 (전통 명문)", "컴퓨터과학"],
    internships: "D.C. 권역 정책·컨설팅·금융 채용이 강하고, McIntire 경영은 월스트리트 타깃스쿨로 분류됩니다. 동문 결속이 남부 특유로 끈끈합니다.",
    essayNote: "짧고 개성 있는 서플 문항 — 위트와 진정성의 균형이 좋은 답을 만듭니다.",
    koreanNote: "한국 인지도는 실제 위상(공립 Top 5)보다 낮은 편 — 그만큼 노려볼 가치가 있습니다. 유학생 재정지원은 없습니다.",
  },
  {
    name: "Georgia Tech", nameKo: "조지아 공과대학", emoji: "🐝",
    category: "최상위 주립", location: "Atlanta, GA — 애틀랜타 미드타운",
    setting: "대도시", type: "공립", undergrads: "약 19,000명",
    acceptRate: "약 16% (주외·유학생 한 자릿수대)", satRange: "약 1370–1530 (수학 상단)", testPolicy: "SAT/ACT 필수 (조지아 주립 시스템)",
    earlyPlan: "EA1·EA2 (주외는 EA2) — 11월 초 마감",
    aidIntl: "유학생 재정지원 없음 — 단, 절대 비용이 낮음",
    costBand: "유학생 연 총비용 약 $55,000 (명문 공대 중 최저가권)",
    personaTitle: "실전 엔지니어링으로 증명하는 실용주의자",
    persona: "MIT·스탠퍼드·버클리와 함께 미국 공학 빅4로 묶이는 실전형 공대입니다. 이론보다 만들고 적용하는 능력, 코업(Co-op)으로 일하며 배우는 문화가 핵심입니다. '진보와 봉사(Progress and Service)' 모토대로 기술로 문제를 푸는 학생을 찾습니다.",
    admitPoints: [
      "수학 실력의 증거 (SAT 수학 만점대 + 미적분 이상 선행)",
      "만들기·코딩·로봇 등 실행 프로젝트",
      "코업/인턴 의지 — 실용주의 학풍과의 적합성",
    ],
    programs: ["산업공학 (수십 년 연속 미국 1위)", "컴퓨터과학", "항공우주공학", "기계·전기공학", "바이오메디컬공학"],
    internships: "5년 코업 프로그램(학기제 유급 근무)이 시그니처 — 졸업 전 1년+ 경력을 쌓고 나옵니다. 애틀랜타 본사 기업(코카콜라·델타·NCR)과 빅테크 남부 거점 채용이 모두 캠퍼스로 옵니다.",
    essayNote: "서플 부담이 적은 대신 수치 스펙 비중이 큼 — 시험·내신·수학 이력이 사실상 승부처입니다.",
    koreanNote: "명문 공대 중 총비용이 가장 낮은 축 — '가성비 유학'의 대표 카드입니다. 졸업 난도가 높기로 유명하니 입학 후 학업 체력도 준비돼야 합니다.",
  },
  {
    name: "UNC Chapel Hill", nameKo: "노스캐롤라이나 대학교 채플힐", emoji: "💙",
    category: "최상위 주립", location: "Chapel Hill, NC — 리서치트라이앵글",
    setting: "소도시·칼리지타운", type: "공립", undergrads: "약 20,000명",
    acceptRate: "약 19% (주외 쿼터 18%로 주외는 한 자릿수대)", satRange: "약 1400–1530", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "EA (10월 마감 — 빠름)",
    aidIntl: "유학생 니드 지원 없음",
    costBand: "유학생 연 총비용 약 $60,000",
    personaTitle: "따뜻한 남부 공동체의 균형형 리더",
    persona: "미국 최초의 주립대학이자 '공립의 아이비'로 불립니다. 저널리즘·공중보건·경영이 강하고, 농구로 상징되는 캠퍼스 결속 문화가 특징입니다. 주외 입학 쿼터(18%)가 법으로 묶여 있어 주외·유학생에게는 사실상 최상위 난도입니다.",
    admitPoints: [
      "주외 쿼터 — 유학생 체감 합격률은 한 자릿수로 보고 전략 수립",
      "공동체·봉사 중심 서사가 학풍과 부합",
      "저널리즘·공중보건 지망이면 구체적 연결 고리 제시",
    ],
    programs: ["저널리즘·미디어(Hussman)", "공중보건(Gillings)", "경영(Kenan-Flagler)", "생물학·Pre-med", "정치학"],
    internships: "리서치트라이앵글(RTP) — 바이오테크·제약·IT 기업 단지가 인접해 STEM 인턴이 풍부합니다. 듀크·NC State와 함께 묶이는 연구 클러스터의 일원입니다.",
    essayNote: "짧은 서플에서 공동체 기여와 배경 스토리를 자연스럽게 — 과장 없는 따뜻한 톤이 잘 맞습니다.",
    koreanNote: "학비 대비 교육 질이 높은 학교지만 주외 쿼터 탓에 유학생에게는 좁은 문 — '안전권'으로 분류하면 안 됩니다.",
  },
  {
    name: "UIUC", nameKo: "일리노이 대학교 어바나-샴페인", emoji: "🌽",
    category: "최상위 주립", location: "Urbana-Champaign, IL — 시카고에서 2.5시간 평원 칼리지타운",
    setting: "소도시·칼리지타운", type: "공립", undergrads: "약 35,000명",
    acceptRate: "전체 약 44% — 단 CS는 약 7%로 별도 세계", satRange: "약 1340–1520 (CS·공대는 상단)", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "EA (11월 초)",
    aidIntl: "유학생 재정지원 없음",
    costBand: "유학생 연 총비용 약 $60,000",
    personaTitle: "코드와 회로로 말하는 엔지니어",
    persona: "CS는 세계 5위권, 공학 전반이 미국 최상위인 '엔지니어의 학교'입니다. 전체 합격률에 속으면 안 됩니다 — CS 직접 지원은 아이비급 난도이며 전공별 합격률 격차가 미국에서 가장 큰 학교 중 하나입니다. CS+X(융합 전공) 제도가 우회로로 유명합니다.",
    admitPoints: [
      "전공별 지원 — CS 직접 지원 vs CS+X vs 공대 타 전공의 난도 차이를 알고 전략 수립",
      "코딩·수학 실적 (USACO 등)이 CS 지원의 실질 변별",
      "전공 변경(내부 전과)이 매우 어려운 학교 — 첫 지원 전공이 사실상 확정",
    ],
    programs: ["컴퓨터과학 (세계 최상위)", "전기·컴퓨터공학", "기계·토목공학 (전통 최강)", "CS+X 융합전공", "회계·경영(Gies)"],
    internships: "빅테크 채용 타깃스쿨 — 실리콘밸리·시애틀 엔지니어 공급원 상위권입니다. 리서치파크(야후·존디어 등 입주)에서 학기 중 유급 인턴이 가능합니다.",
    essayNote: "에세이 비중이 작고 전공 적합성·성적 중심 — 1·2지망 전공 선택이 에세이보다 중요할 수 있습니다.",
    koreanNote: "한국 유학생(특히 공대)이 전통적으로 많은 학교 — 커뮤니티가 두텁습니다. 'UIUC는 쉽다'는 통념은 CS·공대에는 전혀 적용되지 않습니다.",
  },
  {
    name: "UT Austin", nameKo: "텍사스 대학교 오스틴", emoji: "🤘",
    category: "최상위 주립", location: "Austin, TX — 미국에서 가장 빠르게 크는 테크 도시",
    setting: "대도시", type: "공립", undergrads: "약 42,000명 (초대형)",
    acceptRate: "약 29% — 단 주외 쿼터 10%로 유학생은 한 자릿수", satRange: "약 1230–1500 (CS·경영 상단)", testPolicy: "SAT/ACT 필수 (2024년 재도입)",
    earlyPlan: "Priority 마감 (11월 초) — 사실상 필수",
    aidIntl: "유학생 재정지원 없음",
    costBand: "유학생 연 총비용 약 $60,000",
    personaTitle: "급성장하는 도시와 함께 크는 야심가",
    persona: "테슬라·오라클·삼성(오스틴 팹)이 모여드는 테크 붐 도시의 플래그십 주립입니다. CS는 미국 Top 10, 경영(McCombs)·회계는 최상위권. 주내 자동입학(상위 6%) 제도 때문에 주외·유학생 자리는 10%뿐 — 인기 전공은 사실상 최상위 입시입니다.",
    admitPoints: [
      "주외 쿼터 10% — 유학생 체감 난도는 공표 합격률의 수 배",
      "CS·경영 직접 지원은 별도 최상위 전형으로 준비",
      "전공 에세이(전공 적합성 짧은 에세이) 비중이 큼",
    ],
    programs: ["컴퓨터과학", "경영·회계(McCombs, 회계 미국 1위)", "전기컴퓨터공학", "석유공학 (세계 1위급)", "라디오·TV·영화"],
    internships: "오스틴 자체가 채용 시장 — 테슬라·애플·구글·삼성 오스틴 거점의 인턴·취업 기회가 캠퍼스 옆에 있습니다. 텍사스 에너지·반도체 산업 파이프라인도 강력합니다.",
    essayNote: "전공 선택 이유를 묻는 짧은 에세이가 실질 변별 — 전공 스토리가 약하면 인기 전공은 어렵습니다.",
    koreanNote: "삼성 반도체 공장(테일러) 확장으로 한국 기업 연결 고리가 커지는 중 — 반도체·EE 지망생에게 전략적 가치가 있습니다.",
  },
  {
    name: "Purdue University", nameKo: "퍼듀 대학교", emoji: "🚀",
    category: "최상위 주립", location: "West Lafayette, IN — 시카고에서 2시간",
    setting: "소도시·칼리지타운", type: "공립", undergrads: "약 39,000명",
    acceptRate: "약 50% — 단 CS·공대 직접 지원은 훨씬 낮음", satRange: "약 1300–1500 (공대 상단)", testPolicy: "SAT/ACT 필수 (재도입)",
    earlyPlan: "EA (11월 1일) — 인기 전공은 EA가 사실상 필수",
    aidIntl: "유학생 재정지원 없음 — 단, 등록금 동결 정책으로 저렴",
    costBand: "유학생 연 총비용 약 $45,000 (명문 공대 중 최저)",
    personaTitle: "우주를 향하는 성실한 실전 엔지니어",
    persona: "닐 암스트롱을 비롯해 미국 우주비행사를 가장 많이 배출한 '우주인의 모교'입니다. 10년 넘게 등록금을 동결한 가성비 정책으로 유명하고, 항공우주·기계·CS 등 공학 실무 교육이 견고합니다. 화려함보다 성실한 실력형 학생의 학교입니다.",
    admitPoints: [
      "전공 직접 지원제 — CS·항공우주 등 인기 전공은 전체 합격률과 무관한 난도",
      "수학·물리 이수 이력이 공대 지원의 기본기",
      "EA 지원으로 인기 전공 자리 선점",
    ],
    programs: ["항공우주공학 (미국 최상위)", "컴퓨터과학", "기계공학", "산업공학", "농공학·약학"],
    internships: "보잉·록히드마틴·NASA·SpaceX 등 항공우주 채용의 핵심 공급원입니다. 대형 커리어페어와 산학 코업으로 졸업 전 실무 경력을 쌓는 문화가 표준입니다.",
    essayNote: "에세이 비중이 낮은 성적·이력 중심 전형 — 수치 스펙이 곧 전략입니다.",
    koreanNote: "총비용이 미국 명문 공대 중 가장 낮은 수준 — 공학 유학의 가성비 1순위 카드입니다. 항공우주 지망이면 더욱 그렇습니다.",
  },
  {
    name: "University of Washington", nameKo: "워싱턴 대학교 (시애틀)", emoji: "🌧️",
    category: "최상위 주립", location: "Seattle, WA — 아마존·MS의 도시",
    setting: "대도시", type: "공립", undergrads: "약 36,000명",
    acceptRate: "약 43% — 단 CS 직접 입학은 극히 좁음", satRange: "약 1280–1510", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "얼리 없음 — 11월 15일 단일 마감",
    aidIntl: "유학생 재정지원 없음",
    costBand: "유학생 연 총비용 약 $65,000",
    personaTitle: "테크 시티의 현장에서 크는 실용주의자",
    persona: "아마존 본사와 마이크로소프트(레드먼드)가 옆에 있는 시애틀의 플래그십 주립입니다. CS(Paul G. Allen School)는 미국 Top 10이지만 직접 입학(Direct to Major)이 매우 좁고, 의학·글로벌 헬스 연구도 세계적입니다.",
    admitPoints: [
      "CS는 Direct to Major 합격이 사실상 전부 — 입학 후 전과는 극히 어려움",
      "에세이(자체 문항)에서 성장 환경·기여를 구체적으로",
      "단일 마감(11/15)이라 일정 관리 단순 — 대신 늦으면 끝",
    ],
    programs: ["컴퓨터과학(Allen School)", "의학·글로벌헬스", "정보학(iSchool)", "항공우주공학 (보잉 연계)", "해양·환경과학"],
    internships: "아마존·마이크로소프트·보잉이 사실상 옆 동네 — 학기 중 테크 인턴 접근성이 서부에서 실리콘밸리 다음으로 좋습니다. 시애틀 스타트업·게임(닌텐도 아메리카 등) 생태계도 풍부합니다.",
    essayNote: "UW 자체 에세이는 커뮤니티 기여 중심 — 환경이 자신을 어떻게 만들었는지 솔직하게 쓰는 게 좋습니다.",
    koreanNote: "CS 지망이라면 'UW 합격'과 'UW CS 합격'은 완전히 다른 게임임을 알아야 합니다. 시애틀 한인 커뮤니티도 탄탄한 편입니다.",
  },

  // ───────────────────────── 리버럴 아츠 칼리지 ─────────────────────────
  {
    name: "Williams College", nameKo: "윌리엄스 칼리지", emoji: "⛰️",
    category: "리버럴 아츠 칼리지", location: "Williamstown, MA — 버크셔 산맥 속",
    setting: "소도시·칼리지타운", type: "사립", undergrads: "약 2,100명",
    acceptRate: "약 8%", satRange: "약 1480–1570", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "ED",
    aidIntl: "유학생 니드 100% 충족 (그랜트 중심) — 최상급",
    costBand: "연 총비용 약 $86,000",
    personaTitle: "교수와 1:1 토론을 원하는 순수 학문형",
    persona: "리버럴 아츠 1위를 수십 년 지킨 학교. 옥스퍼드식 튜토리얼(교수 1명 + 학생 2명 수업)이 시그니처로, 대형 강의가 아니라 토론과 글쓰기로 배우려는 학생을 찾습니다. 졸업생의 대학원·전문직 진학 성과는 아이비와 동급 이상입니다.",
    admitPoints: [
      "글쓰기·토론 능력의 증거 — 튜토리얼을 견딜 지적 체력",
      "운동(Div III)·예술 등 작은 공동체에 기여할 구체적 재능",
      "ED 활용 — 작은 정원이라 얼리 비중이 큼",
    ],
    programs: ["경제학", "미술사 (세계적 명성)", "수학·통계", "정치학", "영문학"],
    internships: "규모는 작지만 동문 밀도가 깊어 금융(특히 월스트리트)·로스쿨·박사 진학에서 1인당 성과가 미국 최고 수준입니다. 겨울 학기(Winter Study)에 인턴·필드워크를 넣을 수 있습니다.",
    essayNote: "지적 경험에 대한 에세이 — 책·아이디어와 씨름해 본 진짜 이야기가 필요합니다.",
    koreanNote: "한국 인지도는 낮지만 미국 내 평가와 대학원 진학 성과는 아이비급 — '아는 사람만 아는' 최상위 카드입니다. 유학생 재정지원도 최상급.",
  },
  {
    name: "Amherst College", nameKo: "애머스트 칼리지", emoji: "📜",
    category: "리버럴 아츠 칼리지", location: "Amherst, MA — 5개 대학 컨소시엄 타운",
    setting: "소도시·칼리지타운", type: "사립", undergrads: "약 1,900명",
    acceptRate: "약 9%", satRange: "약 1480–1570", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "ED",
    aidIntl: "유학생 니드블라인드 + 100% 충족 (LAC 중 유일급)",
    costBand: "연 총비용 약 $89,000",
    personaTitle: "자유 커리큘럼으로 스스로 길을 짜는 독립 지성",
    persona: "필수 교양이 없는 오픈 커리큘럼(브라운과 함께 양대)과 유학생 니드블라인드 정책으로 유명합니다. UMass 등 인근 5개 대학(Five College Consortium) 수업을 자유롭게 듣는 구조라, 작은 학교의 밀도와 큰 학교의 폭을 동시에 원하는 학생에게 맞습니다.",
    admitPoints: [
      "자기 설계 학습의 증거 (오픈 커리큘럼 적합성)",
      "다양성·형평에 대한 관심 — 학교가 공식적으로 중시",
      "유학생 니드블라인드 — 재정 부담 없이 정면 승부 가능",
    ],
    programs: ["경제학", "영문학·문예창작", "수학", "법·사상·사회(LJST)", "신경과학"],
    internships: "Five College 네트워크 + 동문 멘토링(Loeb Center)으로 소규모지만 금융·미디어·학계 진출이 견고합니다. 졸업생 박사 진학률 최상위권.",
    essayNote: "제시문 기반 선택 에세이가 독특 — 인용문에 지적으로 반응하는 훈련이 필요합니다.",
    koreanNote: "유학생 니드블라인드 + 전액 지원 가능이라는 점에서 한국 중산층 가정에 가장 열린 최상위권 학교 중 하나입니다.",
  },
  {
    name: "Swarthmore College", nameKo: "스워스모어 칼리지", emoji: "🌳",
    category: "리버럴 아츠 칼리지", location: "Swarthmore, PA — 필라델피아 근교",
    setting: "근교", type: "사립", undergrads: "약 1,600명",
    acceptRate: "약 7%", satRange: "약 1470–1560", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "ED1 + ED2",
    aidIntl: "유학생 니드어웨어 · 합격 시 100% 충족 (전액 그랜트)",
    costBand: "연 총비용 약 $84,000",
    personaTitle: "지적 강도를 즐기는 사회적 양심가",
    persona: "리버럴 아츠 중 학업 강도가 가장 세기로 유명하고(아너스 프로그램은 외부 학자가 구술시험), 퀘이커 전통의 사회 정의 의식이 깊은 학교입니다. 드물게 LAC이면서 공학 학위를 주는 것도 특징입니다. 공부의 깊이와 세상에 대한 책임감을 둘 다 가진 학생을 찾습니다.",
    admitPoints: [
      "지적 치열함을 감당·즐긴 증거 (심화 수업, 독립 연구)",
      "사회 문제에 대한 행동의 기록",
      "공학 지망 LAC 희망자에게 거의 유일한 선택지",
    ],
    programs: ["경제학", "공학 (LAC에서 드묾)", "정치학", "생물학", "철학"],
    internships: "필라델피아 30분 + 트라이칼리지(브린모어·해버포드)와 UPenn 수업 교류 — 작은 학교의 한계를 보완합니다. 졸업생 박사 배출률은 미국 전체 최상위권입니다.",
    essayNote: "'왜 스워스모어'에서 학업 강도를 낭만화하지 말고, 감당해 본 경험으로 증명해야 합니다.",
    koreanNote: "학계·연구자 진로를 그리는 자녀라면 아이비보다 나은 선택일 수 있는 학교 — 교수 추천서의 질과 밀도가 다릅니다.",
  },
  {
    name: "Pomona College", nameKo: "포모나 칼리지", emoji: "☀️",
    category: "리버럴 아츠 칼리지", location: "Claremont, CA — LA에서 1시간, 클레어몬트 5개 대학",
    setting: "근교", type: "사립", undergrads: "약 1,700명",
    acceptRate: "약 7%", satRange: "약 1480–1560", testPolicy: "테스트 옵셔널 (최근 기준 — 확인 필요)",
    earlyPlan: "ED1 + ED2",
    aidIntl: "유학생 니드어웨어 · 합격 시 100% 충족 (전액 그랜트)",
    costBand: "연 총비용 약 $87,000",
    personaTitle: "서부의 햇살 아래 깊게 공부하는 균형형",
    persona: "'서부의 애머스트' — 클레어몬트 5개 대학(Pomona·CMC·하비머드·스크립스·피처) 컨소시엄의 중심으로, 1,700명 학교에 다니면서 8,500명 규모의 수업·시설을 씁니다. 동부 LAC의 강도에 캘리포니아의 개방성과 날씨를 더한 조합입니다.",
    admitPoints: [
      "5개 대학 컨소시엄 활용 계획 (예: 하비머드 CS 수업)",
      "학업 + 삶의 균형 서사 — 치열하지만 여유 있는 문화와의 적합성",
      "ED1/ED2 — 정원이 작아 얼리가 유리",
    ],
    programs: ["경제학", "컴퓨터과학 (하비머드 교류)", "신경과학", "환경분석", "미디어학"],
    internships: "LA 1시간 — 엔터·테크 인턴 접근성이 LAC 중 독보적이고, PCIP(유급 인턴 프로그램)로 학기 중 인턴 비용을 학교가 지원합니다. 실리콘밸리 진출도 활발합니다.",
    essayNote: "공동체와 즐거움에 관한 가벼운 톤의 서플 — 힘 빼고 진짜 자기 얘기를 쓰는 게 잘 맞습니다.",
    koreanNote: "한국 인지도는 매우 낮지만 미국 내 평가는 최상위 — 'LAC + 캘리포니아 + 재정지원'의 조합을 원하면 첫손에 꼽을 카드입니다.",
  },
];
